### ISSUE TITLE
Feat: ng add angularfire2

### ISSUE THREAD

**Issue by danielsogl** [angular/angularfire#1676]
If not already in pipeline it would be great to be able to add the angularfire 2 package by a simple `ng add angularfire2`.

**Comment by codediodeio** [comment]
I've been working with schematics for AF2 and have the following proposals. Please post ideas and feedback so we can get the ball rolling:

---

```
ng add angularfire2/schematics
```

- Updates the NgModule with imports, initializeApp, and credentials 
- Installs anglarfire2 & firebase

---

```
ng generate component --firestore --auth
```
- Generates a component with Firestore and AfAuth injected + some starter code
- Mocks firebase in the component spec

---

```
ng generate module --template <crud|login|forms> 
```

Generates a fully fleshed-out feature module based on a goal like CRUD, user auth, forms, etc. The idea is here is to provide a best practices example to be used as a starting point or just solve common problems. (This will be the most difficult schemtic to build and maintain)

**Comment by sulco** [comment]
Hey, I think it would be great to start even (or: especially) with having `ng add angularfire2` command available that would 
- install the module
- prepare configuration object to be filled
- and setup the module

If you're opened to it, I would gladly help with this one (I've already prepared analogous part on other projects)

**Comment by codediodeio** [comment]
@sulco That would be amazing. I've not had the time recently to move this forward. Just having `ng add` would be a valuable addition.

**Comment by sulco** [comment]
Great, I'm on it then - should have a PR within the next couple of days.

**Comment by sis0k0** [comment]
Heya, @sulco any updates on this? I can help if you have any problems :)

**Comment by williamJmelton** [comment]
@sulco I'm also willing to help out with this if needed.
