### ISSUE TITLE
Feature Request: storage refFromURL

### ISSUE THREAD

**Issue by jwuestef** [angular/angularfire#1687]
AngularFire2 already implements file upload & download from Firebase Storage via the AngularFireStorageModule... (_which works great, thanks for your awesome work on that_) but what about delete functionality? It seems a bit crazy that my app can use AngularFire2 for everything related to Firebase Storage - except removing an item.

At the moment I just use the old Firebase package way for deleting an item from storage:
```
import * as firebase from 'firebase';

firebase.storage().refFromURL(urlToDelete).delete().then( () => {
    // successful deletion
}).catch( err => {
    // handle err
})
```

Don't get me wrong, there's nothing wrong with the Firebase package itself, but it would be awesome to cut out that package all together and run everything through AngularFire2.

**Comment by andipaetzold** [comment]
AngularFire2 already supports deleting items from firebase storage. It is implemented [here](https://github.com/angular/angularfire2/blob/a42a84f5a67a09a8a9855ab17e27bf9411d3ff18/src/storage/ref.ts#L33) but isn't documented, yet.

Your code would look the following using AngularFire2:
```JavaScript
angularFireStorage.ref(urlToDelete).delete().toPromise().then( () => {
    // successful deletion
}).catch( err => {
    // handle err
})
```

**Comment by jwuestef** [comment]
That's awesome, I'm sorry I didn't notice that. Thanks again for the awesome package!

**Comment by jwuestef** [comment]
I'm going to reopen this issue - the `.ref` method expects a path and fails when given a URL. 

I've found a solution, and I feel this functionality needs to be added to the package. Firebase includes a `refFromUrl()` method - I think AngularFire2 should too. I've played around inside the AngularFire2 package and I think I've got it working to accept a URL... here is how:

(_All of this is in the angularfire2 -> storage directory_)

Inside storage.js, right below the existing `AngularFireStorage.prototype.ref` declaration, you need:
```
    AngularFireStorage.prototype.refFromURL = function (url) {
        return createStorageRef(this.storage.refFromURL(url), this.scheduler);
    };
```

Inside storage.d.ts, right below the existing `ref(path: string):` line, you need:
```
    refFromURL(url: string): AngularFireStorageReference;
```

Inside storage.js.map, you will need to do some hunting... include this:
```
    refFromUrl(url: string) {\n    return createStorageRef(this.storage.refFromUrl(url), this.scheduler);\n  }\n\n
```
immediately after `ref(path: string) {\n    return createStorageRef(this.storage.ref(path), this.scheduler);\n  }\n\n` and before the 'upload(path: string, data: any, metada....' really close to the end of the file.


That adds the ability to delete a file in Firebase Storage when given the URL... this is an example of it in use:
```
        this.afStorage.refFromURL(urlToDelete).delete().toPromise().then( () => {
                 // Successfully deleted
        }).catch( err => {
                 // Handle err
        })
```

I'm too inexperienced to know if there are other locations in the code that need updated / tested, and I've never done a pull request before... if this could be included in the next release, that would be amazing.
(_and thanks again for the great package_)

**Comment by MurhafSousli** [comment]
Any update on this! I cannot delete files by the URL!!!

**Comment by gonzalezlrjesus** [comment]
Well I could solve,the URL that returns storage 
is always the same, the only thing that changes is the path of 
your file. what I do is shorten the url to the part of the path
 of the file:

`getDownloadURL.slice(72,81);`

and I pass it as a parameter to the function of Ref

```
angularFireStorage.ref(getDownloadURL.slice(72,81)).delete().toPromise().then( () => {
    // successful deletion
}).catch( err => {
    // handle err
})

```
and it worked

**Comment by L96Github** [comment]
I've done it using 
`let fileRef = angularFireStorage.storage.refFromURL(downloadUrl);`

**Comment by berkelmas** [comment]
as L96 said; you can use refFromURL like this:
constructor(private storage: AngularFireStorage) {}

someFunc(downloadURL) {
   return this.storage.storage.refFromURL(downloadURL).fullpath;
}

**Comment by Ashvin-Pal** [comment]
Yes, This worked for me! Thanks guys 👍 
 this.storage.storage.refFromURL("yourUrl").delete()
