### ISSUE TITLE
database-deprecated and rxjs 6

### ISSUE THREAD

**Issue by rtm** [angular/angularfire#1711]
For various reasons, I have upgraded to firebase 5.0.4 and angularfire2 5.0.0-rc.10. However, I am still using database-deprecated.

My code stopped working:

```
import {AngularFireDatabase} from "angularfire2/database-deprecated";

const var remote$ = afdb.object(key);
return remote$.pipe(...
```

The above code fails complaining that there is no `pipe` property on `remote`. When I examine `remote$`, strangely it has the following type:

```
ƒ observeOnOperatorFunction(source) {
        return source.lift(new ObserveOnOperator(scheduler, delay));
    }
```

In other words, it seems to be a function. This is the result of the following code in `firebase_object_factory.ts`:

```
export function FirebaseObjectFactory (
  ref: DatabaseReference,
  { preserveSnapshot }: FirebaseObjectFactoryOpts = {}): FirebaseObjectObservable<any> {

  const objectObservable = new FirebaseObjectObservable((obs: Observer<any>) => {
    let fn = ref.on('value', (snapshot: DataSnapshot) => {
      obs.next(preserveSnapshot ? snapshot : utils.unwrapMapFn(snapshot))
    }, err => {
      if (err) { obs.error(err); obs.complete(); }
    });

    return () => ref.off('value', fn);
  }, ref);

  // TODO: should be in the subscription zone instead
  return observeOn.call(objectObservable, new FirebaseZoneScheduler(new NgZone({}), {}));
}
```

I would call your attention to the last line. It seems like this operator should return the original observable. TypeScript has no idea what is happening--it types the `observeOn.call` as `any` and merrily assigns it to the declared return type (`FirebaseObjectObservable<any>`). But in actuality it seems to be a function--which obviously does not have a `pipe` method on it.

I'm wondering if this was a result of changes between v5 and v6 of rxjs, and the behavior of pipeable operators? I'm wondering if anyone else is in my position of using the cutting edge versions of firebase/angularfire2 while still stuck back in the dark ages with the deprecated database, and if perhaps the deprecated database stuff was not fully tested? However the specs in `angularfire2/database-deprecated/firebase_object_factory.spec.ts` clearly require that the result of `FirebaseObjectFactory` to pass a test requiring it to be an `instanceof FirebaseObjectObservable`. Were they run and did they pass?

Am I missing something basic, or is something broken?

**Comment by jamesdaniels** [comment]
I'm guessing rxjs 6 changed some stuff, but from what I see the tests are (for the most part) green. 
We only test the database-depreciated tests manually, since they're flaky in CI.

We were advised to change our API by rxjs folks (to not extend Observable) over a year ago, which is why we made the big API change.

I'll double check things on our side, I'm guessing they changed how observeOn / schedulers work.

**Comment by rtm** [comment]
@jamesdaniels Appreciate your response. 

> I'm guessing they changed how observeOn / schedulers work.

A likely culprit.

> which is why we made the big API change.

I love changes for the better, even when they're breaking. All one can say is that with 20-20 hindsight. the original API was sort of weird in the way it overloaded observables with CRUD semantics.

I considered trying to somehow patch database-deprecated, but I ended up re-writing one of the repos which used database-deprecated, which took a couple of days, since unfortunately I based the program design around the database-deprecated design, to the extent of actually writing a parallel system with the same interface for local storage in order to support offline. But it would be great if you could fix this bug, if it is a bug, so I can avoid re-writing a second larger repo.

**Comment by rtm** [comment]
Inevitably, I reached the point where I need to get my old app running, with the latest versions of firebase and angularfire2 (since it uses a library which has since been upgraded), and since I don't want to rewrite all the database logic I need to use `database-deprecated`, but this bug is preventing me from doing that. `afdb.object` returns not a `FirebaseObjectObservable` as it should, but rather a `function observeOnOperatorFunction(source)`. 

In other words, database-deprecated doesn't work at all with angularfire2@5.x and rxjs@6. The specifics of the bug are as already discussed earlier in this thread.

When I ran into this bug with my previous app, I bit the bullet and rewrote it against the new database API, but that app was much smaller.

Can this bug be fixed? Failing that, my alternatives are to (1) rewrite my large app to use the new, improved database API; (2) take the entire app back to angularfire2@4 and rxjs@5 etc., and also create a parallel version of my "shared" library which uses those old libraries, and hope that my app doesn't depend on any bugs fixed in firebase@5; (3) monkey-patch the angularfire2 code somehow.

Any thoughts or other suggested alternatives for how to proceed?

**Comment by rtm** [comment]
FYI, the buggy code in `src/database-deprecated` would most likely need to be rewritten as:

```
  return listObs.pipe(
    observeOn(new FirebaseZoneScheduler(new NgZone({}), {}) as any)
  ) as FirebaseListObservable<any>;
```

and similarly in one other place for objects.

When I forked the repo and tried to run `npm run build_npm`, which is the command shown in `publish.sh`, I was informed that there is no such npm script defined. When I try to publish with `npm publish` after doing an `npm run build`, it complains that it can't find `dist/package.json`. How would I publish my forked version?

**Comment by rtm** [comment]
A version of database-deprecated which seems to be working so far is in https://github.com/rtm/angularfire2.

**Comment by jamesdaniels** [comment]
Feel free to send open a PR, even if it's just a WIP.

**Comment by rtm** [comment]
I love open source, and I love community contributions, but I have no idea why I should be the one to do a PR to fix a bug introduced by the core team, which with all due respect to its great work didn't even bother to do the simplest test for this scenario which is almost certain to exist in many legacy applications, and no, we cannot keep upgrading and rewriting our apps every time there is a change in the API, which I'm not criticizing--just that old code needs to keep working.
