### ISSUE TITLE
Slow Google auth

### ISSUE THREAD

**Issue by sondresorbye0111** [angular/angularfire#1795]
I am signing in to my app using Google like this: 
`signInWithGoogle() {
    return this.afAuth.auth.signInWithRedirect(new auth.GoogleAuthProvider());
  }`

Then I am subscribing to the user observable and redirect if the user is signed in:
`this.sub = this.auth.user$.subscribe((user) => {
      if (user) {
        this.router.navigate(['/']);
      }
    });`
### Actual behavior
It work perfectly fine. However, it is extremely slow. It takes at least 5 seconds before the user is redirected to the index page. 
### Expected behavior
Less time between sign in and redirecting user.

**Comment by davideast** [comment]
Hi @sondresorbye0111! This repo is a wrapper around auth please raise your issue with the official SDK if it still persists. Auth is a time consuming process so it can take 5 seconds on slow connections.

**Comment by sondresorbye0111** [comment]
@davideast, this problem does not occur in vanilla js. The problem is that the user observable emits the user object very late even after the user has been redirected back from Google login page.

**Comment by davideast** [comment]
What version are you on for Angular, AngularFire, RxJS, and Firebase JS? This may be a zones issue.

**Comment by sondresorbye0111** [comment]
"@angular/core": "^6.0.5",
"angularfire2": "^5.0.0-rc.10",
"rxjs": "^6.2.1",
"firebase": "^5.0.4"

**Comment by davideast** [comment]
Can someone create a stackblitz the shows the problem? I haven't ran into it myself

**Comment by aaronhma** [comment]
Why don't you read the official angularfire2 documentation about authentication: https://github.com/angular/angularfire2/blob/master/docs/auth/getting-started.md

**Comment by davideast** [comment]
@patrickmichalina Can you provide a code sample or some context to help troubleshoot? I've been testing and haven't hit this problem.

**Comment by aaronhma** [comment]
Just an idea, guys. You might want to upgrade your RXJS, rxjs-compat(if using), and also angularfire2 for better compatibility.

**Comment by george43g** [comment]
This is still an ongoing issue and I believe the problem is with Firebase SDK itself. Im surprised this has not yet been solved.

**Comment by alexAlchemy** [comment]
I'm still getting this problem myself and have had a few users comment on its slowness.

**Comment by aaronhma** [comment]
It has slow Google authentication because it needs to contact FIrebase's server to retrieve your secret access key, then use that key to authenticate to Google's authentication server. Then, on your browser, it puts out a success or a error response,

**Comment by jamesdaniels** [comment]
Outdated. Not a AF issue.
