### ISSUE TITLE
signInWithPopup breaks out of the NgZone

### ISSUE THREAD

**Issue by madakk** [angular/angularfire#1822]
### Version info

**Angular:** 5.0.0

**Firebase:** 4.5.0

**AngularFire:** 5.0.0-rc3

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

https://angularfire-auth-ngzone.stackblitz.io

**Steps to set up and reproduce**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

### Expected behavior

`NgZone.isInAngularZone` should be true when returning from `signInWithPopup`.

### Actual behavior

`NgZone.isInAngularZone` returns false, which means that components fail to get rechecked and various unexpected behavior can occur.

This was previously reported as issue #1384 but was closed.

**Comment by hiepxanh** [comment]
please, upgrade your `angularfire to 5.0-rc11` and `firebase 5.0.4` `NgZone.isInAngularZone` is not ready on old version

**Comment by willykc** [comment]
Hi, I reproduced this issue and #1384 on `angular 6.1.4`, `angularfire 5.0.0-rc.12` & `firebase 5.4.1`.

**Comment by jamesdaniels** [comment]
We have to run auth outside of angular's zone unfortunately. We're working on a strategy which might help, but in the meantime you can call `zone.run(() => ...)` in your `.then(...)`.

**Comment by jamesdaniels** [comment]
Should be addressed with the Proxy implementation in 6.0 series
