### ISSUE TITLE
firestore : edit a document field via an input

### ISSUE THREAD

**Issue by dunglp** [angular/angularfire#1847]
Hi, 

I was looking at how the sample code of documents showing data. 

`<div>
      {{ (item | async)?.name }}
    </div>`

Is is possible to use an input for editing the item name in the sample above ? 
I haved tried this 
`<input *ngIf="item | async" type="text" [(ngModel)]="item.name" [value]="item.name" />`

but it didn't work.

I can get the data to display by this 

> this.rpDoc = this.db.doc<RowId>(`${id}`);
    this.rpInfo = this.rpDoc.snapshotChanges().pipe(
      map(actions => {
           const data = actions.payload.data() as RowId;
           const id = actions.payload.id;
           console.log("document", id, data, actions);
           return {id, ...data};
      })
    );

Thanks in advance.

**Comment by vixson** [comment]
You have to manually write the data **onInput**

_*.component.html_

`<input *ngIf="itemDoc | async as item" (keydown)="setValue($event.value)" [value]="item.name"/>`
or
`<input *ngIf="itemDoc | async as item" (input)="setValue($event.value)" [value]="item.name"/>`


_*.component.ts_

> ...
> public itemDoc = this.db.doc('path/to/document').valueChanges();
> 
> public setValue(value: string) {
>     itemDoc.update(value);
> }
> ...
