### ISSUE TITLE
Download URL and state not updated for file uploads

### ISSUE THREAD

**Issue by johndavis987342** [angular/angularfire#1852]
### Version info

**Angular:** 6.0.0

**Firebase:** 5.4.2

**AngularFire:** 5.0.0 (@angular/fire)

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

Minimal StackBlitz project to allow reproduction of the issue: https://stackblitz.com/edit/angular-cjpn4m

**Steps to set up and reproduce**

Upload a small file (< 1MB).
Upload a larger file (> 2MB).

### Debug output

**Errors in the JavaScript console**

None

### Expected behavior

Download URL is shown for uploads of any size.

State changes from 'running' to 'success' on successful upload.

### Actual behavior

Download URL is shown for smaller files, but not for larger files.

State never changes from 'running' to 'success' on successful upload. State remains 'running' on completion of upload.

**Comment by drahuks** [comment]
Same behaviour observed in my ionic pwa app. Upload sometimes never reach the finalize function

using angularfire2 5.0.0 & firebase 5.4.2

**Comment by JohnGallego** [comment]
Same on my angular app, anything smaller than 2 MB returns the download url anything larger doesn't.

**Comment by jamesdaniels** [comment]
This should have been addressed after the 6.0 release, it turns out those observables were eager & success was never reporting.
