### ISSUE TITLE
Facebook OAuth authentication not working through AngularFire2

### ISSUE THREAD

**Issue by kmuthukrishnan** [angular/angularfire#1867]
### Version info

Angular CLI: 6.0.8 
angularfire2": "^5.0.0-rc.9
typescript: ~2.7.2

### How to reproduce these conditions

I am using facebook OAuth login through Angular Fire 2 for my website. I have done all the settings as specified including App Domains (basic settings) and Valid OAuth Redirect URIs (facebook login settings). However, I am still getting the error message as specified in the screenshot - namely: Can't Load URL: The domain of this URL isn't included in the App's domains. **To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.**

**Steps to set up and reproduce**

go to www.setyourtest.com and click on facebook login

I have tried implementing a number of different solutions based on issues on StackOverflow, facebook support and this forum. These include:

1. Setting Use Strict Mode for Redirect URIs = Yes and setting the Valid OAuth re-direct Uri's on facebook panel to the URI specified in the firebase panel: https://myaccount.firebaseapp.com/__/auth/ (where myaccount refers to my project id). Referred to link: https://www.janrain.com/blog/social-login-facebook-app-requires-strict-uri-matching, https://developers.facebook.com/blog/post/2017/12/18/strict-uri-matching/

2.  Making sure the Google APIs keys on my cloud account is correctly configured. 
a. GoogleCloud>APis and Services> Credentials> API keys> configured the browser key to "Accept requests from these HTTP referrers (websites)". I added www.setyourtest.com (my website) here.
b. GoogleCloud>APis and Services> Credentials> configured the Web client for Authorised JavaScript origins
For 2a and 2b, I referred to: https://github.com/angular/angularfire2/issues/1444

3. Made the facebook app public. Referred to : https://forum.bubble.is/t/solved-fb-login-domain-problem/3267/31

** Screenshots **
Screen
![facebook login issue](https://user-images.githubusercontent.com/5083070/45292212-246d9400-b512-11e8-97f0-9db535824a4a.PNG)
shot of the error is attached

### Actual behavior: Facebook login is stopping with an error as specified in the screenshot and above

Please help me resolve this issue.

**Comment by hiepxanh** [comment]
you should add redirect url in facebook app config too

**Comment by DorianLovera** [comment]
> you should add redirect url in facebook app config too

In your Facebook DashBoard go to Products --> Facebook Login --> Settings --> Valid OAuth Redirect URIs (That you get from Firebase)
