### ISSUE TITLE
Difference between signInWithPopup and signInWithRedirect

### ISSUE THREAD

**Issue by soyjuanmedina** [angular/angularfire#1873]
I'm sorry because I don't know if this is a bug or is a feature :-)

As you propousse I ask before in Stackoverflow, but I don't be sucessfull:

https://stackoverflow.com/questions/52254374/auth-witnh-angularfire2-difference-between-signinwithpopup-and-signinwithredirec

I use:

```
  oAuthLogin(provider) {
    return this.afAuth.auth.signInWithPopup(provider).then(credential => {
      console.log(credential);
      Promise.resolve((this.user = credential));
    });
  }
```
And works ok in web but not in the apk.

I read is necesary to work in cordova to use signInWithRedirect because signInWithPopup is not compatible with it, but It not works.

I see the code of the pluging and is:

```
signInWithPopup(
      provider: firebase.auth.AuthProvider
    ): Promise<firebase.auth.UserCredential>;
    signInWithRedirect(provider: firebase.auth.AuthProvider): Promise<void>;
```
Then is normal don't works because signInWithPopup return a UserCredential and signInWithRedirect return void...

How can I adapt my code with fewer changes possible?

Thanks a lot

**Comment by jamesdaniels** [comment]
Closing as outdated, both return a credential and we now have a credential observer.
