### ISSUE TITLE
Documentation Request: multi-bucket via StorageBucket injection token

### ISSUE THREAD

**Issue by stot3** [angular/angularfire#1875]
Hey, Google functions are applicable to a whole bucket, thus, AngularFireStorage needs to be able to access multiple buckets within a project. I figure, the syntax should look like, 
storage.bucket({bucketId}).ref().put()
storage.bucket({bucketId}).ref()

ex.
storage.bucket("myCustomId").ref(filepath).delete()
storage.bucket("gs://path").ref(filepath).put() etc.

I have tried switching the environments with the storage bucket as a property in another firebase config, but I have had no success with trying to make it work. I also understand that there is a way to use the Firebase SDK to do so but I'm afraid that importing the entire SDK would increase my bundle size too much. Is there a way to incorporate this into future releases? Is there a way for me to help?

**Comment by jamesdaniels** [comment]
There's an injection token, `StorageBucket` that you can provide. I will leave this issue open for documentation.

**Comment by aravindas4** [comment]
In **app.module.ts** we have code snippet like this: 
```
providers: [
        { provide: StorageBucket, useValue: 'xyz-1' }
]
```
We need to implement dynamic **useValue**. We'll get the value after login happens.
Is there a way to do?

**Comment by jamesdaniels** [comment]
Not work the current API. Will consider this in the future.
