### ISSUE TITLE
i have an issue with firebase $key. When i try to store data on firebase the value in the category field is showing undefined

### ISSUE THREAD

**Issue by Malikhaseebtahir** [angular/angularfire#1881]
1. ### Category-Service.ts

import { AngularFireDatabase } from 'angularfire2/database';
import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class CategoryService {

  constructor(private db: AngularFireDatabase) { }

  getCategories() {
    return this.db.list('/categories', ref => ref.orderByChild('name')).valueChanges();
  }
}

-----------------------------------------------------------------------------------------
### 2. product-form-component.ts

export class ProductsFormComponent {
  categories$;

  constructor(
      private categoriesService: CategoryService,
      private productService: ProductService,
      private router: Router
    ) {
    this.categories$ = categoriesService.getCategories();
   }

   save(product) {
     this.productService.createProduct(product);

     this.router.navigate(['/admin/admin-products']);
  }
}

----------------------------------------------------------------------

3. ### product-form-component.html

          <div class="form-group">
            <label for="category">Category</label>
            <select ngModel name="category" #category="ngModel" id="category" type="text" class="form-control" required>
              <option value=""></option>
              <option *ngFor="let c of categories$ | async" [value]="c.$key">
                {{ c.name }}
              </option>
            </select>
            <div class="alert alert-danger" *ngIf="category.touched && category.invalid">Category is required</div>
          </div>

---------------------------------------------------------------

4. ### Output

![output](https://user-images.githubusercontent.com/40055844/45634914-7b1a2700-ba58-11e8-90db-060f6f77e047.PNG)

**Comment by Max5007** [comment]
this.db.list('/categories', ref => ref.orderByChild('name')).valueChanges()
return an ListObservable which changes the $key value. There is a way to fix it by using snapShotChanges() method instead of valueChanges().

But for now, you can proceed by binding c.key instead of c.$key. Also, to make this work, you have to add an extra node of key with same category on your firebase database. See if this works for you.

**Comment by srivathsanvlb** [comment]
Try the following changes

  getCategories() {
    return this.db.list('/categories', ref => ref.orderByChild('name')).snapshotChanges();
  }

    <select ngModel name="category" id="category" class="form-control">
      <option value=""></option>
      <option *ngFor="let c of categories$ | async" [value]="c.key">
        {{c.payload.val().name}}
      </option>
    </select>

Let me know if it helps

**Comment by ajaykumar1090** [comment]
It's working fine. Thanks...
But why you use "payload.val()".

**Comment by Armen-X** [comment]
I had the Same issue I solve id by changing [value]="c.$key" 
to [value]="c.name" 
and it worked I don't know if it causes other problems but so far seems to work for me

**Comment by aslamsk** [comment]
> It's working fine. Thanks...
> But why you use "payload.val()".

to show categories list in case you use c.name ur list didn't show

**Comment by chunkingz** [comment]
> Try the following changes
> 
> getCategories() {
> return this.db.list('/categories', ref => ref.orderByChild('name')).snapshotChanges();
> }
> 
> ```
> <select ngModel name="category" id="category" class="form-control">
>   <option value=""></option>
>   <option *ngFor="let c of categories$ | async" [value]="c.key">
>     {{c.payload.val().name}}
>   </option>
> </select>
> ```
> 
> Let me know if it helps

Thanks man, this worked 👍

**Comment by srivathsanvlb** [comment]
I am happy that I was able to help somebody. All the best everyone.
