### ISSUE TITLE
Error: could not handle the request when deploy

### ISSUE THREAD

**Issue by docaohuynh** [angular/angularfire#1883]
Hi team!
I'm working to config Server-side rendering follow by this instructions
https://github.com/angular/angularfire2/blob/master/docs/universal/cloud-functions.md
It work at localhost when run `firebase serve `but when I deploy to hosting `firebase deploy
` It just return error message `Error: could not handle the request `
My version
Angular 6.1.7
Firebase: 4.2.1
AngularFire: 5.0.0
Thanks!

**Comment by edycarreyes99** [comment]
i have the same problem too... Exactly like you are discribing it. Someone that can help us please?

**Comment by docaohuynh** [comment]
@edycarreyes99  I have found that you must copy all dependencies on package json to functions/package.json and install it

**Comment by jamesdaniels** [comment]
Closing as outdated.
