### ISSUE TITLE
Running with Angular 6 leads to Firebase crash after first several uses

### ISSUE THREAD

**Issue by DevMerlin** [angular/angularfire#1894]
**Angular:5.2.0
**Firebase: 5.5.1
**AngularFire:5.0.0

** Steps to set up and reproduce **
Install Angular application - latest version
Install Firebase - 5.5.1
Install AngularFire - @angular/fire 5.0.0

Set up basic application that uses Firebase Auth:

  imports: [
    BrowserModule,
    ReactiveFormsModule,
    HttpClientModule,
    RouterModule.forRoot(appRoutes),
    AngularFirestoreModule,
    AngularFireAuthModule,
    AngularFireStorageModule,
    // To initialize AngularFire
    AngularFireModule.initializeApp(firebase)
  ],

import { AngularFireAuth } from '@angular/fire/auth';
import { auth } from 'firebase/app';

  loginWithGoogle()
  {
    return new Promise<any>((resolve, reject) => {
      let provider = new auth.GoogleAuthProvider();
      provider.addScope('openid');
      provider.addScope('profile');
      provider.addScope('email');
      this.fireAuth.auth
      .signInWithPopup(provider)
      .then(res => {
        resolve(res);
      })
    })
  }

  systemRegister(value)
  {
    return new Promise<any>((resolve, reject) => {
      this.fireAuth.auth.createUserWithEmailAndPassword(value.email, value.password).then(res => {
        resolve(res);
      }, err => reject(err))
    });
  }
** Errors in Console **
https://i.gyazo.com/2aa96bd5e55dc040f0975193f9beb81d.png
Error TS2307: Cannot find module 'firebase/app'

Expected Behavior
Confirm registration through Firebase, create new users on site and Firebase Auth
Firebase works for the first few reloads, and then crashes.

Actual Behavior

Works first several times, and then behaves as if it can no longer locate 'firebase/app'. Eventually this leads to an outright crash, producing a 'module not found' and / ERROR in the browser.

**Comment by jamesdaniels** [comment]
Closing as stale, should no longer be an issue
