### ISSUE TITLE
sendEmailVerification() not sending Email

### ISSUE THREAD

**Issue by kim-marcel** [angular/angularfire#1895]
### Version info

Angular: 6.0.8

Firebase: 5.5.1

AngularFire: 5.0.2

### How to reproduce these conditions

When using the code below no verification-Email is being sent to the newly created user, although the new user is visible in the firebase console.

```javascript
  emailSignUp(email: string, password: string) {
    this.afAuth.auth.createUserWithEmailAndPassword(email, password).then(
      () => {
        this.verifyEmail();
      }
    );
  }

  verifyEmail() {
    this.afAuth.authState.subscribe(
      (user) => user.sendEmailVerification().then(
        () => console.log('email sent')));
  }
```

I'm not sure whether this is a bug or I'm doing something wrong, but I've found a couple of examples online that seem to work like this with older versions of angular + angularfire2.

### Debug output

No errors are thrown, 'email sent' is logged to console.

### Expected behavior

A verification-Email should be sent to the user.

### Actual behavior

No Email is being sent.

**Comment by kim-marcel** [comment]
This could also be a problem in the firebase SDK. I've opened an [issue](https://github.com/firebase/firebase-js-sdk/issues/1242) in their repository too.

**Comment by jamesdaniels** [comment]
Closing as it's not likely an AngularFire issue, if it's still a problem.
