### ISSUE TITLE
Firebase missing or insufficient permissions

### ISSUE THREAD

**Issue by Aman-US-Punjabi** [angular/angularfire#1896]
I'm getting error: Firebase missing or insufficient permissions
and error occur only when i log in as a regular user. When i log in as admin, then document get created without any issue with success response.
Code : 

    const demoCollectionRef = this.db.collection('items');
    return demoCollectionRef.add(item);

I think this error is because of .add method of angularfire2.

Firestore Rules:

    function isAuthenticated() {
      return request.auth.uid != null;
    }

    function isAdmin() {
      return request.auth.token.admin == true;
    }

     match /items/{itemId} {
       // allow if user is logged in
       // TO DO validate request data
       allow create: if isAuthenticated();
 
       // allow if user is Admin
       // TO DO validate request data

       allow delete, update: if isAdmin();      // .add method checks update rules 
       // at the place of checking the create rules, which make it send error.
       // But if I change the update rule to: allow update, delete: if isAuthenticated(); it works fine
     }

### Version info

Angular CLI: 6.2.3
Node: 10.6.0
OS: darwin x64
Angular: 6.1.8
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.8.3
@angular-devkit/schematics        0.8.3
@angular/cdk                      6.4.7
@angular/cli                      6.2.3
@angular/fire                     5.0.2
@angular/flex-layout              6.0.0-beta.18
@angular/material                 6.4.7
@angular/pwa                      0.8.3
@ngtools/webpack                  6.0.8
@schematics/angular               0.8.3
@schematics/update                0.8.3
rxjs                              6.3.2
typescript                        2.9.2
webpack                           4.8.3

**Comment by jamesdaniels** [comment]
Closing as outdated.
