### ISSUE TITLE
Permissions error with new @angular/fire

### ISSUE THREAD

**Issue by erperejildo** [angular/angularfire#1902]
First of all I want to point out that **I did not change any rule on my ddbb**. If I change this back to previous version it works
------
I was using `angularfire2/firestore` and `angularfire2/database` with getting data like this:
```
private newspapersdb = this.angularFirestore.collection(
    'newspapers',
    ref => ref.orderBy('name')
  );

getDefaultNewspapers() {
    return this.newspapersdb.snapshotChanges().map(actions => {
      return actions.map(action => ({
        $id: action.payload.doc.id,
        ...action.payload.doc.data()
      }));
    });
  }
```
That was working perfectly but when I moved to the new version (based on this message from NPM https://www.npmjs.com/package/angularfire2) using `@angular/fire/firestore` and `@angular/fire/database` with this code:
`  newspapers: Observable<any[]> = this.afDB.list('newspapers').valueChanges();`

I get this error:

> permission_denied at /newspapers: Client doesn't have permission to access the desired data.

**Comment by jamesdaniels** [comment]
I believe issues such as this should be fully addressed with the latest Firestore. Closing as outdated.
