### ISSUE TITLE
Firebase Database (${JSCORE_VERSION}) INTERNAL ASSERT FAILED: Reference.ts has not been loaded.

### ISSUE THREAD

**Issue by harleenarora** [angular/angularfire#1906]
Hi, 

I am working on angular 6 application. I am use angularfire latest version 5.0.2. Its working fine. But on Error in IE9 and IE10 show error. 

Firebase Database (${JSCORE_VERSION}) INTERNAL ASSERT FAILED: Reference.ts has not been loaded.

Tell me how to solve this error.

**Comment by KourdacheHoussam** [comment]
Hello, i'am facing to the same error, nothing found to resolve this ?

**Comment by avinashrg94** [comment]
Any solution for this?

**Comment by jamesdaniels** [comment]
Outdated.
