### ISSUE TITLE
Subscription with limit bleeds into other subscription

### ISSUE THREAD

**Issue by kurtzmarc** [angular/angularfire#1917]
### Version info

**Angular:** Angular: 6.1.10

**Firebase:** 5.5.4

**AngularFire:** 5.0.2

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

https://stackblitz.com/edit/angularfire2-subscription-with-limit-bleeds?file=src%2Fapp%2Fapp.component.ts

**Description**

It appears that when I have two subscriptions - one with a limit, one without - I get results from the "limit" observable in the "non-limit" subscription. If I have three items ('a', 'b', and 'c') in my document collection and I do:

`    const o = of('1', '2', '3', '4').pipe(delay(1000));
    this.db.collection('items', ref => ref.limit(2)).valueChanges().subscribe(T => { });
    o.pipe(switchMap(T => this.db.collection('items').valueChanges())).subscribe(U => console.log(U));
`

In this instance I will get the console outputting `'a', 'b'` followed immediately by `'a', 'b', 'c'`. If I change the limit to 1 then I get `'a'` followed by `'a', 'b', 'c'`. I would expect to always just get the "non-limit" results of only `'a', 'b', 'c'`.

Is this expected behavior, or did I find a bug?

**Comment by kurtzmarc** [comment]
Perhaps this is what is happening: https://groups.google.com/forum/#!topic/google-cloud-firestore-discuss/wEVPfgvLCFs

**Comment by dalepo** [comment]
I have this very same issue. I use different queries with `snapshotChanges()` depending on user's actions, for example I have 2 use cases:

- User visits a view, I get paginated queries (limit=10,20...n)
- User downloads CSV, I query the whole collection (without limit)

In the 'whole collection subscription', I get the same results as the paginated subscriptions, it's really weird.
If I paginate to 20 elements on the view, I'll get the same 20 documents on the full query.

I tried using `get()` but I have some issues, apparently my view hangs when I try a paginated method :/

**Comment by haleyDesignhouse** [comment]
Did anybody ever figure this out? I am doing a limit of 20 on my query. Tried it with limitToLast() as well and I get all the document results for that query like it's not even limiting the query and then my view crashes and I have to kill my tab in Chrome because it cost me like 150,000+ reads...

**Comment by jamesdaniels** [comment]
Unclear that this is a specific AngularFire issue. Closing.
