### ISSUE TITLE
documentation doesn't include workaround for using FCM with ngsw

### ISSUE THREAD

**Issue by markgoho** [angular/angularfire#1923]
[So there's this: ](https://github.com/angular/angularfire2/blob/master/docs/messaging/messaging.md#angularfiremessaging-is-not-compatible-with-the-angular-service-worker)

> ## AngularFireMessaging is not compatible with the Angular Service Worker
> If you are using the Angular Service Worker, you are not currently able to use AngularFireMessaging. If you'd like this feature please file an issue in either repository. Your alternatives are to use WorkboxJS or just simply use the Firebase Messaging Service Worker, which is detailed below.

This kind of leads folks to believe that there isn't a solution to use FCM with the Angular Service Worker. However, some light searching has revealed a few workarounds to use both.  I'm hoping we could unify around one solution and then add it to the docs to help others that might just give up.

## Concatenate the ngsw and FCM sw files
This one is Jeff Delaney's (@codediodeio) solution [posted on AngularFirebase from April 2018.](https://angularfirebase.com/snippets/how-to-use-a-firebase-fcm-service-worker-with-angular-s-ngsw-service-worker/)

Basically, create a new service worker file and, sometime post-build, concatenate the FCM file and ngsw file together and reference this combined file in the app.module.ts file where the service worker is registered.

## Use a native firebase method `useServiceWorker()` to use the ngsw in place of the FCM sw
This one has popped up in a number of places, most notably [on StackOverflow in a question](https://stackoverflow.com/a/41666784/664747) that Michael Bleigh (@mbleigh) from Firebase answered.

Here, from what I gather (particularly from [this SO answer](https://stackoverflow.com/a/50521835/664747)) you can wait for the ngsw to register and then take that registered worker and pass it into useServiceWorker() and FCM will use that worker.

###
I haven't implemented either solution yet. I'm just trying to put some ideas out here for discussion. I'll follow up with some pros and cons of each as I'm able to try each solution. What do you guys think? Have experience with either one?

**Comment by davideast** [comment]
Hey @markgoho!

You can do that, but I'm not certain it's a good idea. The ngsw is not meant to work with other SW libraries and it also works differently than your typical Service Worker. Trying to munge the two together could result in unpredictable results and that's not really good with something as powerful as a Service Worker.

Before we could recommend it we would need to see if it is a good idea, and at my early research suggests that it is not.

The long term solution is to have the ngsw use Firebase Messaging for push notifications. This is something I've spoken with the Angular team about and they are supportive of doing it. 

In the meantime I recommend using Workboxjs with Firebase Messaging. It's really easy and it's a proven path.

**Comment by markgoho** [comment]
Thank you for this input @davideast!

I'm not sure if your recommendation against the concatenation method includes the second option as well to use `firebase.messaging().useServiceWorker(ngsw)`. Have you tried that at all?

For a current workaround are you suggesting to scrap the ngsw (via `ng add @angular/pwa`) altogether in favor of a pure workbox.js implementation? If that's the case, documentation on how to do that would be great to have.

Finally, I haven't seen an issue filed in the Angular repo for this specific issue (although [this issue](https://github.com/angular/angular/issues/26413) seems very similar). I'm not 100% sure what the actual issue is that prevents us from using FCM. Since you mentioned speaking to the core team about the issue, what do you suggest as far as creating an issue to track this need for a better FCM service worker integration?

I greatly appreciate the guidance here - and I'm more than willing to do the work to create the documentation for whatever solution we gather around. I just want to make sure I'm not spending hours researching a solution that someone already has in production.

**Comment by codediodeio** [comment]
🤯 to my amazement, `firebase.messaging().useServiceWorker(ngsw)` actually works. I never considered doing it this way, but was able to confirm that messages are handled by the `SwPush` service and caching still works as expected. This seems like an ideal solution at first glance, so thanks for putting it out there @markgoho.

This is much better then just concatenating files and also preserves the angular worker - are there issues I'm not aware of?

**Comment by zhangxin511** [comment]
I am able to use the way @codediodeio did to hook up firebase and default angular ngsw-worker by do following. The foreground also receive notifications like @codediodeio point out, haven't test the background app yet. I thought the `SwPush` might caused the alerts on foreground app so commented out and using my own service to do logging, but it looks like not related.

app.module.ts:
```
  imports: [
    ...
    AngularFireModule.initializeApp(environment.firebase),
    AngularFireMessagingModule,
    ...
  ],
```

app.component.ts:
```
import { Component } from '@angular/core';
import { SwPush } from '@angular/service-worker';
import { FirebaseApp } from '@angular/fire';
import { MessagingService } from 'services/firebase';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})

export class AppComponent {
  title = '...';
  constructor(
    private sw: SwPush,
    private firebase: FirebaseApp,
    private messagingSvc: MessagingService
  ) {
    // this.sw.messages.subscribe(console.log);
    const messaging = this.firebase.messaging();
    navigator.serviceWorker.getRegistration().then(registration => {
      if (!!registration && registration.active && registration.active.state && registration.active.state === 'activated') {
        messaging.useServiceWorker(registration);
        this.messagingSvc.requestPermission('');
        this.messagingSvc.receiveMessage();
      } else {
        console.warn('No active service worker found, not able to get firebase messaging');
      }
    });
  }
}
```

messaging.service.ts:
```
  requestPermission(userId: string) {
    this.angularFireMessaging.requestToken.subscribe(
      (token) => {
        console.log(token);
      },
      (err) => {
        console.error('Unable to get permission to notify.', err);
      }
    );
  }
  receiveMessage() {
    this.angularFireMessaging.messages.subscribe(
      (payload) => {
        console.log('new message received: ', payload);
        // We decide not to do anything yet.
      });
  }
```

**Comment by SauceCode84** [comment]
@zhangxin511 
It seems to fail on the line `const messaging = this.firebase.messaging();` with the error that **messaging** is not defined.

Is there something missing perhaps?

**Comment by zhangxin511** [comment]
@SauceCode84 I think it may because you didn't initialize the firebase app properly in your module. Can you show how you initialize it? I think you might miss the messaging module?

For me, I end up not using angular dependency injection since I used dynamic firebase configurations that got from api, this is what the partial code looks like:
The module doing nothing for me now: 
![image](https://user-images.githubusercontent.com/3719246/53751630-b1b6f300-3e7a-11e9-8054-086171385b78.png)

The component using the firebase messaging:
1. import
![image](https://user-images.githubusercontent.com/3719246/53751570-86340880-3e7a-11e9-816e-315f0c1a7db2.png)

2. defining as a class property:
![image](https://user-images.githubusercontent.com/3719246/53751695-e1fe9180-3e7a-11e9-9f29-6cf89f0b1400.png)

3. initialize app and messaging object, note, the configs for the app is dynamic I don't know the proper way to include in module.ts therefore I get ride of the DI system of angular:
![image](https://user-images.githubusercontent.com/3719246/53751772-03f81400-3e7b-11e9-88f3-51f4e1970f88.png)

**Comment by matheo** [comment]
I'm trying to call a Firebase Function and I'm getting this error:
```
An unknown error occurred when fetching the script.
Failed to load resource: net::ERR_FILE_NOT_FOUND
```
searching about this Error Message it seems related to the Service Worker
so I wonder if `AngularFireFunctions` relies on this firebase-messaging-sw
or if it's my function that needs to be deployed properly :-?

BTW, a smooth integration with the `ngsw` would be ideal

**Comment by wooldridgetm** [comment]
This may be a dumb question, but can we use the method described [here](https://blog.angular-university.io/angular-push-notifications/) to implement FCM with the Angular Service Worker?

**Comment by zhangxin511** [comment]
@wooldridgetm That if app active, this thread is mainly talk about notifications working with ngsw, service worker, so the app can get notifications when it is not active or closed.

**Comment by wooldridgetm** [comment]
@zhangxin511 Just so I understand you...you're saying [this method](https://blog.angular-university.io/angular-push-notifications/) doesn't allow notifications when the app is closed or isn't active?

**Comment by zhangxin511** [comment]
@wooldridgetm Sorry I may miss understand your question. If you are asking if we can not use FCM but use the method you mentioned, yes you can.
If you are asking if we can receive notification when app is off-load in any means, no we won't. I barely remember I do tried the method you mentioned for the project I worked on using angular 7, where the service worker doesn't not handle notifications when app offload. I think I also checked angular 8 source one day for this and it was still not supported by then.
The problem is, the following code only works when your app is active loaded by browser:
```
subscribeToNotifications() {

        this.swPush.requestSubscription({
            serverPublicKey: this.VAPID_PUBLIC_KEY
        })
        .then(sub => this.newsletterService.addPushSubscriber(sub).subscribe())
        .catch(err => console.error("Could not subscribe to notifications", err));
    }
```
I end up using some customized logic to overwrites the default angular service worker js file and made the the off-load notification works (not for safari, nor ios, which is another story).

**Comment by wooldridgetm** [comment]
Ah, yes, I understand now. Thanks!

**Comment by zhangxin511** [comment]
@SauceCode84 @wooldridgetm @matheo 

I created [a post](https://medium.com/kabbage-engineering/angular-pwa-app-notification-using-firebase-cloud-messaging-d1b7bd171b98) about this if you are still interested. Along with the demo repo [here](https://github.com/zhangxin511/PushDemo)

**Comment by Splaktar** [comment]
This issue in the Angular repo requested by the documentation appears to have been created here: https://github.com/angular/angular/issues/34352

**Comment by bevbomb** [comment]
@zhangxin511 I have been looking at implementing your method and fired up your demo. it all works except for subscribing to messages and notificationClicks from SwPush. Did you manage to get these two working?

**Comment by zhangxin511** [comment]
@bevbomb I am not sure what exactly you did, but if you follow [the post](https://medium.com/kabbage-engineering/angular-pwa-app-notification-using-firebase-cloud-messaging-d1b7bd171b98), should have worked for subscribing to messages and notificationClicks from SwPush. Did you check your angular versions?

> @zhangxin511 I have been looking at implementing your method and fired up your demo. it all works except for subscribing to messages and notificationClicks from SwPush. Did you manage to get these two working?

**Comment by bevbomb** [comment]
@zhangxin511 i managed to get it working. I declared a local variable of firebase.messaging() to use In place of calling the instance each time and it worked after that. I’m not sure how that would have affected it.

**Comment by jamesdaniels** [comment]
FYI we now support `VAPID_KEY` and `SERVICE_WORKER` DI tokens, the latter where you can inject a factory that looks up a service worker registration. I'm hoping to standardize ngsw compatibility after I do some more testing.
