### ISSUE TITLE
Tutorial feedback

### ISSUE THREAD

**Issue by filipesilva** [angular/angularfire#1956]
Heya, just wanted to give some feedback on the tutorial as I was going through it now. Just things that I noticed weren't very clear or were unexpected.

My background is that I'm very used to Angular and Angular CLI but not very familiar with Firebase. So I decided to get started on firebase using angularfire.

## 1. Installation and Setup [(docs)](https://github.com/angular/angularfire2/blob/master/docs/install-and-setup.md)

On `4. Add Firebase config to environments variable` I was told to use my project configuration but I didn't have any project yet. I created one before proceeding. 

Also wasn't very clear what "click Add Firebase to your web app" referred to since that phrase wasn't anywhere in the page, but I assumed it was the third icon above "Add an app to get started", and that showed the credentials.

On `9. Run your app` I got a runtime error in the browser console below:
```
[2018-11-17T14:11:20.896Z]  @firebase/firestore: Firestore (5.5.0): Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: FirebaseError: [code=failed-precondition]: The Cloud Firestore API is not available for Cloud Datastore projects.
This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
```

I wasn't really sure what it meant and what looked like the main error (`The Cloud Firestore API is not available for Cloud Datastore projects.`) didn't really have any hits on this issue tracker. 

In the [Interacting with your database(s)](https://github.com/angular/angularfire2#interacting-with-your-databases) section of the readme there is a mention of two types of databases though. So I went back to the newly created project, clicked "Database" on the menu, and created a Firestore one. It is marked as beta so that was a bit weird, I expected the tutorial to be for the stable (non-beta) service.

The error went away but nothing showed up on the browser. The tutorial code was iterating over a `items` collection and showing the `name` field. So I went back to the firebase window, added a collection called `items`, and a new item with `name: "first item"`. It showed up on the browser now.

## 2. Documents in AngularFirestore [(docs)](https://github.com/angular/angularfire2/blob/master/docs/firestore/documents.md)

In `Using AngularFirestoreDocument`, I copy paste the code but nothing showed up. I saw that the document was `items/1`. I went to check out my database and saw what I assumed to be the id was `gBmNjdlcgzQbtUgOTfDS` and not `1`. I used this id and saw my item.

Also it was a bit confusing to read `The AngularFirestoreDocument service ` since the only Angular service in the example was `AngularFirestore`. But I got what the text meant.

The rest of it was quite informative as I didn't really know anything about the Firebase document structure.

## 3. Collections in AngularFirestore [(docs)](https://github.com/angular/angularfire2/blob/master/docs/firestore/collections.md)

Mostly informative. Good read. Didn't try the examples that used collections I didn't have because I didn't feel like creating them from scratch. But made a mental note to come back and use them as examples when needed.

## 4. Querying Collections in AngularFirestore [(docs)](https://github.com/angular/angularfire2/blob/master/docs/firestore/querying-collections.md)

Found the example nice to play with on StackBlitz. Was the first example that listed the data that I needed to put in the collection to use it. 

The data was provided as JSON and I assume there must be a way to copy paste the JSON as is to make a collection in the Firebase console, but couldn't find it. It seemed too bothersome to make all the documents field by field so I didn't try it on my project.

## 5. Getting started with Firebase Authentication [(docs)](https://github.com/angular/angularfire2/blob/master/docs/auth/getting-started.md)

Was really impressed with how easy the example to login with Google was. 

Tried it locally and got an error though:
```
code: "auth/operation-not-allowed"
message: "The given sign-in provider is disabled for this Firebase project. Enable it in the Firebase console, under the sign-in method tab of the Auth section."
```

The error message is very clear and it was easy to just go and enable the google auth. After that it worked locally.

## Final comments

I hadn't used Firebase at all so the first step was a bit complicated and required setup that wasn't explained. But after that it was pretty smooth sailing. 

I liked how basic Firebase concepts were explained here even though they must be explained in the official docs anyway. I feel I have a decent starting point to start working now.

Thanks for all the good work!

### Version info

**Angular:** 7.0.4

**Firebase:** 5.5.8

**AngularFire:** 5.1.0

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** Node v10.10.0, Chrome 70, Windows 10

**Comment by hiepxanh** [comment]
thank for your feedback, it very nice and clear, we should update a little bit.
