### ISSUE TITLE
Missing or insufficient permissions using ValueChanges

### ISSUE THREAD

**Issue by erperejildo** [angular/angularfire#1957]
This code is working fine:
```
newspapersdb = this.angularFirestore.collection(
    "newspapers",
    ref => ref.orderBy("name")
    // .limit(15)
  );
.......
const newspapers: Observable<any> = this.newspapersdb
      .snapshotChanges()
      .map(newspapers => {
        return newspapers.map(newspaper => {
          const $id = newspaper.payload.doc.id;
          const data = newspaper.payload.doc.data();
          this.showLoading = false;
          return { $id, ...data };
        });
      });

    return newspapers;
```

But not this one:
```
testRef: AngularFirestoreCollection<NewspaperModel>;
test$: Observable<NewspaperModel[]>;
.......
this.testRef = this.angularFirestore.collection("newspaper");
this.test$ = this.testRef.valueChanges();

```
> Error: Missing or insufficient permissions.

Just moving from `snapshotChanges` to `valueChanges` works but I prefer the last one

**Comment by jereckley** [comment]
Same issue... as soon as I subscribe to snapshot changes I get insufficient permissions. I've been over and over my rules... they are good. Request should work.

**Comment by adzza24** [comment]
Any solution to this? I am getting the exact same error. Rules all pass the simulator in Firebase, but they don't get through from the clientside.

**Comment by adzza24** [comment]
A quick update, this issue is definitely related to AngularFire2. I have setup a small HTML page with just the standard Firebase CDN linked, and everything works. As soon as I run the exact same requests through AngularFire2, they return `Error: Missing or insufficient permissions.`

**Comment by marcosjunqueira** [comment]
The same issue here.
I created a database rule as follows:
```
service cloud.firestore {
  match /databases/{database}/documents {
    
    match /assets/{asset} {
    	function isSignedIn() {
    		return request.auth != null;
      }
      function getRole(rsc) {
        // Read from the "roles" map in the resource (rsc).
        return rsc.data.roles[request.auth.uid];
      }
      function isOneOfRoles(rsc, array) {
        // Determine if the user is one of an array of roles
        return isSignedIn() && (getRole(rsc) in array);
      }
      function isValidNewAsset() {
        // Valid if story does not exist and the new story has the correct owner.
      	return resource == null
          && request.resource.data.roles[request.auth.uid] == 'owner';
      }
      // Owners can read, write, and delete stories
      allow write: if isValidNewAsset() || isOneOfRoles(resource, ['owner']);
      // Any role can read stories.
      allow read: if isOneOfRoles(resource, ['owner', 'writer', 'commenter', 'reader']);
      
      match /transactions/{transaction} {
          // Any role can read comments.
          allow read: if isOneOfRoles(get(/databases/$(database)/documents/assets/$(asset)),
                                      ['owner', 'writer', 'commenter', 'reader']);
        }
		}
  }
}
```
When I validate the rule in the console with user uid the read is allowed, but when I try in the application, it fails with this error: 

> ERROR FirebaseError: Missing or insufficient permissions.

Here is the Angular code
```
(...)
export class AppComponent {
  private assetsCollection: AngularFirestoreCollection<Asset>;
  assets: Observable<Asset[]>;

  constructor(public afAuth: AngularFireAuth, private afs: AngularFirestore) {
    this.assetsCollection = afs.collection<Asset>('assets');
    this.assets = this.assetsCollection.snapshotChanges().pipe(
      map(actions => actions.map(a => {
        const data = a.payload.doc.data() as Asset;
        const id = a.payload.doc.id;
        return { id, ...data };
      }))
    );
  }
  login() {
    this.afAuth.auth.signInWithPopup(new auth.GoogleAuthProvider());
  }
  logout() {
    this.afAuth.auth.signOut();
  }
}
```
After reading the firebase documentation again I realized that [Rules are not filters](https://firebase.google.com/docs/firestore/security/rules-conditions?authuser=0#rules_are_not_filters).

So, I changed my query to fit my rule, and now it works! I hope this helps.

**Comment by sandygit17** [comment]
I log in successfully and then immediately get the data from the database, but the angularfire firestore return the 

**ERROR FirebaseError: Missing or insufficient permissions.** 

When I validate the rule in the console with user uid the read is allowed, but when I try in the application, it fails with this error:

**Comment by akushylun** [comment]
I have the same issue...

**Comment by akushylun** [comment]
I found my mistake. 
In app module I used factory for AngularFirestore and AngularFireAuth because I have multiple firebase projects. 

```
providers: [
// Angular fire dependencies for Project1
 {
      provide: 'firebaseClient',
      deps: [PLATFORM_ID, NgZone],
      useFactory: Project1Firestore,
    },
    {
      provide: 'firebaseClientAuth',
      deps: [PLATFORM_ID, NgZone],
      useFactory: Project1Auth,
    }
// Angular fire dependencies for Project2 ...
]
```

When create an instance of AngularFirestore or AngularFireAuth, there is a second property "name" in constructor. 
It should be the same for each project. In my case I named it 'firebase-client' and all works. I hope this helps.

```
export function Project1Firestore(platformId: object, zone: NgZone) {
  return new AngularFirestore(environment.firebaseClient, 'firebase-client', false, null, platformId, zone, null);
}

export function Project1Auth(platformId: object, zone: NgZone) {
  return new AngularFireAuth(environment.firebaseClient, 'firebase-client', platformId, zone);
}
```
