### ISSUE TITLE
Update doc for offline data and multiple tabs

### ISSUE THREAD

**Issue by peterpeterparker** [angular/angularfire#1968]
**Doc:**

If I'm not mistaken, this library, AngularFire, as Firestore itself, does now support offline data with multiple tabs right? (reference: https://github.com/angular/angularfire2/issues/1907#issuecomment-431977457)

If that's correct, then I think the documentation about offline data (https://github.com/angular/angularfire2/blob/master/docs/firestore/offline-data.md) should be updated as the following is still mentioned:

> If a user opens multiple browser tabs that point to the same Cloud Firestore database, and offline persistence is enabled, Cloud Firestore will work correctly only in the first tab.

**Note**

I'm not 100% sure that's why I opened this doc improvement feature request without PR to remove this phrase. If it's correct and you wish me to provide one, no worries, let me know

**Comment by jamesdaniels** [comment]
We now support use of the `experimentalTabSynchronization` configuration flag. `AngularFirestoreModule.enablePersistence({experimentalTabSynchronization: true})`

I'll leave this open for updating the docs.

**Comment by peterpeterparker** [comment]
@jamesdaniels thx for the feedback. exactly it's what I meant, just the doc "need" to be updated

**Comment by jbgomez21** [comment]
Hi @PeterKassenaar 
I have the same error: 

"Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing. "

But, I am not using multitab, I am on ionic cordova application.
aprox 25% user login fails with that error.

some help?

@angular/fire": "^5.0.2"
"firebase": "^5.0.3"

**Comment by PeterKassenaar** [comment]
@jbgomez21 Maybe you meant @peterpeterparker? I have no part in this discussion and have not used Ionic/Cordova in this context ;-)

**Comment by jbgomez21** [comment]
Yes @PeterKassenaar, sorry, I had hash collision of Peters :)

**Comment by peterpeterparker** [comment]
@jbgomez21 I didn't face or faced the error you are mentioning. @Alphonse99 did but it isn't related to this issue sorry

**Comment by thefliik** [comment]
Per #2092 (closed), experimentalTabSynchronization was made experimental in version 5.2 of this library. Am I correct in thinking that the docs should now be updated to reflect the fact that this is no longer a beta feature?
