### ISSUE TITLE
authstate doesn't broadcast when its logged out 

### ISSUE THREAD

**Issue by acegreen** [angular/angularfire#1971]
### Version info

**Angular: ** 7.1.0

**Firebase:** ^5.5.9

**AngularFire:** ^5.1.0

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** Node: 8.9.0, CLI 7.0.6, darwin x64

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

```
  get isAuthenticated(): Observable<boolean> {
    return this.angularFireAuth.authState.pipe(
      take(1),
      map(authState => {
        var isAuthenticated = !!authState;
        console.log("isAuthenticated", isAuthenticated);
        return isAuthenticated;
      }),
      catchError(error => of(false))
    );
  }
```

**Steps to set up and reproduce**

- check observable after login
- check observable after logout
- Check console.log

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

![screen shot 2018-12-05 at 11 02 56 am](https://user-images.githubusercontent.com/10794609/49526217-5d9d7200-f87d-11e8-8996-597fa97bbcad.png)

### Expected behavior

Expect when calling isAuthenticated to get a result of false when authState is null

### Actual behavior

console.log isAuthenticated doesn't happen, isAuthenticated isn't executed. I have a subscribe() on authstate which does return "Logged out :(" as seen in the logs but I don't want to have to subscribe

**Comment by alberthoekstra** [comment]
Try to remove the take(1) operator from your pipe.

**Comment by acegreen** [comment]
Tried it, it didn’t make a difference

**Comment by jamesdaniels** [comment]
Unable to reproduce, without take(1) things seem to work as expected
