### ISSUE TITLE
Could not reach Cloud Firestore backend with Angular Universal and Firebase Functions

### ISSUE THREAD

**Issue by maciejtreder** [angular/angularfire#1985]
### Version info

**Angular:** ^6.1.10

**Firebase:** 5.7.2

**AngularFire:** 5.1.1

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** NodeJS (Angular Universal)

### How to reproduce these conditions

**Steps to set up and reproduce**

I am trying to perform a simple request to the Firestore on the server-side (runned on Firebase with 'firebase serve'):

```
this.afs.doc<any>('myData').valueChanges().subscribe(resp => console.log(resp));
```

### Debug output

** Errors in the JavaScript console **

```
error: [2019-01-06T12:26:14.371Z]  @firebase/firestore: Firestore (5.5.9): Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds.
This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend. 
```

**Comment by nadhir-falta** [comment]
Getting the same issue when running universal locally too

**Comment by lwolteri** [comment]
On Ionic 4 it works fine. Getting the same issue when running cordova on iOS. Version 8.1.2.

**Comment by hesmondjeet** [comment]
Any updates with regards to this issue? Anyone got it to work?

**Comment by jamesdaniels** [comment]
Outdated.
