### ISSUE TITLE
errors in angular site

### ISSUE THREAD

**Issue by gadekarpreetam** [angular/angularfire#1995]
i am getting this errors .. can someone help me to fix this

ERROR in D:/angularsite/my-app/node_modules/@angular/fire/angularfire2.d.ts (1,10): Module '"D:/angularsite/my-app/node_modules/@angular/core/index"' has no exported member 'InjectionToken'.

ERROR in D:/angularsite/my-app/node_modules/firebase/index.d.ts (176,9): Type expected.

ERROR in D:/angularsite/my-app/node_modules/firebase/index.d.ts (183,9): Type expected.

ERROR in D:/angularsite/my-app/node_modules/firebase/index.d.ts (619,9): Type expected.

ERROR in D:/angularsite/my-app/node_modules/firebase/index.d.ts (1938,5): Type expected.

ERROR in D:/angularsite/my-app/node_modules/@angular/fire/firebase.app.module.d.ts (1,10): Module '"D:/angularsite/my-app/node_modules/@angular/core/index"' has no exported member 'InjectionToken'.

ERROR in D:/angularsite/my-app/node_modules/@angular/fire/firebase.app.module.d.ts (2,42): Module '"D:/angularsite/my-app/node_modules/firebase/index"' has no exported member 'functions'.

####### package.json file #############

{
"name": "my-app",
"version": "0.0.0",
"license": "MIT",
"angular-cli": {},
"scripts": {
"ng": "ng",
"start": "ng serve",
"test": "ng test",
"pree2e": "webdriver-manager update --standalone false --gecko false",
"e2e": "protractor"
},
"private": true,
"dependencies": {
"@angular/common": "^2.3.1",
"@angular/compiler": "^2.3.1",
"@angular/core": "^2.3.1",
"@angular/forms": "^2.3.1",
"@angular/http": "^2.3.1",
"@angular/material": "^6.4.7",
"@angular/platform-browser": "^2.3.1",
"@angular/platform-browser-dynamic": "^2.3.1",
"@angular/router": "^3.3.1",
"angularfire2": "^5.1.1",
"core-js": "^2.4.1",
"firebase": "^4.13.1",
"ngx-clipboard": "^7.0.4",
"npm": "^6.4.1",
"rxjs": "^5.0.1",
"ts-helpers": "^1.1.1",
"zone.js": "^0.7.2"
},
"devDependencies": {
"@angular/compiler-cli": "^2.3.1",
"@types/jasmine": "2.5.38",
"@types/node": "^6.0.42",
"angular-cli": "1.0.0-beta.28.3",
"codelyzer": "~2.0.0-beta.1",
"jasmine-core": "2.5.2",
"jasmine-spec-reporter": "2.5.0",
"karma": "1.2.0",
"karma-chrome-launcher": "^2.0.0",
"karma-cli": "^1.0.1",
"karma-jasmine": "^1.0.2",
"karma-remap-istanbul": "^0.2.1",
"protractor": "~4.0.13",
"ts-node": "1.2.1",
"tslint": "^4.3.0",
"typescript": "~2.0.3"
}
}

**Comment by jamesdaniels** [comment]
Closing as outdated.
