### ISSUE TITLE
Change storage buckets dynamically

### ISSUE THREAD

**Issue by SurendraKumar19** [angular/angularfire#1996]
**Angular: 6.1.2**

**Firebase: 5.5.3**

**AngularFire:5.0.2**

**How to reproduce these conditions**
How can i change the storage buckets dynamically?
Right now i have to set the storage bucket name statically in the app.modules,

import { AngularFireStorageModule, StorageBucket } from '@angular/fire/storage';
@NgModule({
...,
providers: [
        { provide: StorageBucket, useValue: 'bucket-xxx' },
        ...,
    ]
})

by this, i can fetch and upload data's to a single bucket only using AngularFireStorage,

this.storage.upload(filePath, file)

**Expected Behaviour**
Change the storage bucket from component on the run, something like this

var storage = firebase.app().storage("gs://my-custom-bucket");

**Comment by studioTeaTwo** [comment]
if you don't care about original methods which `@angular/fire` provides, you can use raw firebase object.

```typescript
constructor(private afStorage: AngularFireStorage) {
  this.defaultBucket = this.afStorage.storage.app.storage();
  this.otherBucket = this.afStorage.storage.app.storage(BUCKETNAME);
}
```

example to upload.
```typescript
const storageRef = this.otherBucket.ref().child(FILENAME);
storageRef.put(file).then((snapshot) => {
    console.log('Uploaded a blob or file!', snapshot);
}
```

You can individually upload to multiple buckets.

**Comment by ksilz** [comment]
@studioTeaTwo Thank you for your solution! Works like a charm. 😄

**Comment by veslav3** [comment]
@studioTeaTwo how do you watch upload progress on this solution? I can only do it with `.upload()` but then I cannot change the buckets like you explained here.

**Comment by madmacc** [comment]
Is this still an issue?  I would prefer to use AngularFire rather than raw firebase.

**Comment by shahmirn** [comment]
@veslav3 @madmacc This is the solution / work-around that I was able to do:

```TS
export class MyComponent implements OnInit {

    @Input() storageBucket: string;

    constructor(
        private angularFireStorage: AngularFireStorage,
        private db: AngularFirestore,
        private angularFireAuth: AngularFireAuth,
        private changeDetectorRef: ChangeDetectorRef
    ) { }

    ngOnInit() {
        // AngularFireStorage has storage as a readonly property, but we need to override it, which is why there's a cast to any
        (this.angularFireStorage as any).storage = this.angularFireStorage.storage.app.storage(this.storageBucket);
        this.angularFireAuth.authState.pipe(
            first()
        ).subscribe(() => {
            this.startUpload();
            this.changeDetectorRef.markForCheck();
        });
    }

    startUpload() {
        const path = 'some-path-over-here';

        // Reference to storage bucket
        const ref = this.angularFireStorage.ref(path);
        // The main task
        this.task = this.angularFireStorage.upload(path, this.file);
        // ... <truncated>
    }

    // ... <truncated>
}

**Comment by veslav3** [comment]
@shahmirn interesting looks like a way to do it, I might try that out sometime as I found another solution using a different method than `.upload` which is suboptimal for me.

**Comment by jamesdaniels** [comment]
closing as there's a work-around. I'll consider making this easier in a future API.

**Comment by dobromyslov** [comment]
@shahmirn thank you for the workaround.

> I'll consider making this easier in a future API.

@jamesdaniels +1

**Comment by grapevinegizmos** [comment]
Has there been any progress on allowing bucket switching in Angular without all the workaround?
