### ISSUE TITLE
AngularFirestoreCollection add method doesn't all return AngularFirestoreDocument type

### ISSUE THREAD

**Issue by Tiedye** [angular/angularfire#2000]
### Version info

**Angular:**
7.2.3

**Firebase:**
5.8.1

**AngularFire:**
5.1.1

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### Actual behavior

The method `AngularFirestoreCollection.add` is not consistent with `AngularFirestoreCollection.doc` and returns a class of type `Promise<firebase.firestore.DocumentReference>` instead of a `Promise<AngularFirestoreDocument>`.

https://github.com/angular/angularfire2/blob/master/src/firestore/collection/collection.ts#L133-L135

https://github.com/angular/angularfire2/blob/master/src/firestore/collection/collection.ts#L141-L143

### Expected behavior

These two methods should be consistent as they are in the underlying firebase library.

**Comment by jamesdaniels** [comment]
Closing as this is the current API. There's a PR and we may reevaluate in the next major.
