### ISSUE TITLE
Browser hangs with multiple firestore queries

### ISSUE THREAD

**Issue by stefanrusek** [angular/angularfire#2003]
### Version info

**Angular:** 7.2.4

**Firebase:** 5.8.2

**AngularFire:** 5.1.1

### How to reproduce these conditions

When I run the following code,  page load hangs and cpu goes to 100%. If I comment our or remove the `<li>` loop, then it works fine.

**Steps to set up and reproduce**

Component

```
import {Component} from '@angular/core';
import {ActivatedRoute, Router} from '@angular/router';
import {AngularFirestore} from '@angular/fire/firestore';
import {switchMap} from 'rxjs/operators';
import {Goat} from '../../store/goat.service';
import {Observable} from 'rxjs';
import {GoatStaticService, GoatWithId} from '../../store/goat-static.service';

@Component({
  selector: 'app-goat-details',
  templateUrl: './goat-details.component.html',
  styleUrls: ['./goat-details.component.css']
})
export class GoatDetailsComponent {

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private store: AngularFirestore) {
    this.goat$ = this.route.paramMap.pipe(
      switchMap(params =>
        GoatStaticService.valueChangesWithIds(this.store.collection<Goat>('goats').ref.where('name', '==', params.get('name')), this.store)
      )
    );
  }

  goat$: Observable<GoatWithId[]>;

  offspring(parent: GoatWithId): Observable<Goat[]> {
    return this.store.collection<Goat>('goats',
      ref => ref.where(parent.sex === 'f' ? 'dam' : 'sire', '==', parent.id).orderBy('name')).valueChanges();
  }
}
```

Template

```
<ng-template ngFor [ngForOf]="goat$ | async" let-goat>
  <h1>{{goat.name}} - {{goat.fullName}}</h1>

  <div>
    <h2>Offspring</h2>
    <ul>
      <li *ngFor="let child of offspring(goat) | async">{{child.name}}</li>
    </ul>
  </div>

</ng-template>
```

### Expected behavior

It should list the children of the goat

### Actual behavior

browser page load hangs and cpu goes to 100%

**Comment by larssn** [comment]
This is an Angular limitation, your problem is this:
`<li *ngFor="let child of offspring(goat) | async">{{child.name}}</li>`

As a general rule, you can't call functions in templates as it messes up the change detection.
Your infinite loop is Angular constantly rebinding to a new function pointer.

Either use pipes to filter your list, or switch change detection into `OnPush` for the component in question.
