### ISSUE TITLE
How to display ppt and document in angular Like I uploaded presentation in firebase storage and now I am trying to display file using download url, Is that possible

### ISSUE THREAD

**Issue by rkanumetta1** [angular/angularfire#2007]
How to display ppt and document in angular
Like I uploaded presentation in firebase storage and now I am trying to display file using download url, Is that possible

**Comment by hooloom** [comment]
Probably your easiest way is to use storage; and then use a live viewer.  There are other ways as well - however in your case you could just literally create a variable called site-to-ppt, or something similar.  Be careful though storage can get expensive.

<iframe src='https://view.officeapps.live.com/op/embed.aspx?src={urlencode(site-to-ppt)}' width='962px' height='565px' frameborder='0'></iframe>

https://products.office.com/en-GB/office-online/view-office-documents-online?legRedir=true&CorrelationId=b28c7173-79a2-4fb7-a1eb-9e75651fd1a1
