### ISSUE TITLE
Document details ( asnyc + subscribe)

### ISSUE THREAD

**Issue by Karman40** [angular/angularfire#2009]
### Version info

**Angular:** `7.2.0`
**Firebase:** `5.7.2`
**AngularFire:** `5.1.1`

### How to reproduce these conditions

**When there is a documenten subscribe at the ts page and async at the html page, the async pipe is not showing correctly!**

**Example:**
**TS:**
```    
this.kategoria.subscribe(siker => {
      this.loading = false;

      if (siker.folyamatban !== true) {
        this.folyamatban = false;
      } else {
        this.folyamatban = true;
      }

      this.nev = siker.nev;
      this.hatter_szin = siker.hatter_szin;
      this.betu_szin = siker.szoveg_szin;
      this.sorrend = siker.sorrend;
      this.url = 'https://konigs-art.hu/uzlet/' + siker.url;
    });
  }
```
return constantly good value!

**HTML:**
```
<div class="col-7">{{ (kategoria | async)?.folyamatban }}</div>
```
return null when the above code is inserted. If I remove it, it returns the correct good value on the frontend.

**Comment by yonathan06** [comment]
Can you provide the code where you initialize the observable?
From first sight it looks like a bug in `RxJS` or in the `async` pipe in angular

**Comment by Karman40** [comment]
```
constructor( ... ) {
    const kategoriaURL = this.getCategoryUrlFromPath();
    this.getKategoria(kategoriaURL);
}
```
---
```
getCategoryUrlFromPath(): string {
    const currentPath = this.location.path();
    const splittedPath = currentPath.split(/\//g);
    return splittedPath[splittedPath.length - 1];
}
```
---
```
getKategoria(url) {
    this.kategoriaDoc = this._afs.doc('kategoria/' + url);
    this.kategoria = this.kategoriaDoc.valueChanges();
}
```

**Comment by yonathan06** [comment]
Do you get any errors in any of the subscriptions?
When there is an error in the parent subscription, it is unsubscribes automatically, unless you handle catch the error or wraps the subscription in an other subscription.

**Comment by hooloom** [comment]
Try changing this around I don't think its correct:

```
 if (siker.folyamatban !== true) {
        this.folyamatban = false;
      } else {
        this.folyamatban = true;
      }
```
to 
` if (siker.folyamatban) {
        this.folyamatban = false;
      } else {
        this.folyamatban = true;
      }`

your basically saying if this exists and its false, then its false - but you don't need to do that - instead its conditional, if siker.folyamatban exists then its false, otherwise its true.  !==true is setting a false flag twice.
