### ISSUE TITLE
Get data from realtime database based on some array of keys in ionic 3 + firebse

### ISSUE THREAD

**Issue by ravipandit14** [angular/angularfire#2032]
**This is my database structure.** 
![Untitled](https://user-images.githubusercontent.com/33632283/54881256-71a8b780-4e0b-11e9-93d9-c234c7c44bc3.png)

**Detail:**
i have `var arr=["0VggPwMNVKMjlo8AWSY7IUjIpR13","Ktf7Y0XLZQXnUSTSfErtjlkj2aq2",...3 more items]`
These arr items are the users key in databse
**Question**
I want to get data, based on arr variable from my database.

Please help??? Thank you in advance.

**package.json detail:**
I am using ionic 3 framework
`"firebase": "^5.7.0",
 "ionic-angular": "3.9.2",`

**Comment by rhendz** [comment]
I suggest looking at [retrieving nested collections](https://github.com/angular/angularfire2/blob/master/docs/firestore/documents.md#retrieving-nested-collections).

You could loop through your arr array and append each key to the current path "user/[key]" to receive each document.

**Comment by ravipandit14** [comment]
I am using real time database not cloud data base. Please provide me ionic 2, 3 code
