### ISSUE TITLE
disallowed_useragent with Ionic 4 / Cordova 8

### ISSUE THREAD

**Issue by oliviercherrier** [angular/angularfire#2035]
### Version info

**Angular: 7.2.2**

**Firebase: 5.9.1**

**AngularFire: 5.1.2**

**Ionic: 4.11**

**Cordova: 8.0.0**

**Node: 8.11.3**

**Operating system: Android 8.0.0**

### How to reproduce these conditions

```
npm install -g ionic
git clone https://github.com/oliviercherrier/firebase-ionic4-cordova
cd firebase-ionic4-cordova
npm install
```

In file `plugins\cordova-universal-links-plugin\hooks\lib\android\manifestWriter.js`, line 21, replace 

`var pathToManifest = path.join(cordovaContext.opts.projectRoot, 'platforms', 'android', 'AndroidManifest.xml');`

by

```
var pathToManifest = path.join(
    cordovaContext.opts.projectRoot, 
    'platforms', 
    'android', 
    'app', 
    'src', 
    'main', 
    'AndroidManifest.xml');
```

to fix bug "unable to found manifest from cordova-universal-links-plugin

Plug Android smartphone - Galaxy S7 for me and launch

`ionic cordova run android`

**Steps to set up and reproduce**

Click on "Log in with Google"

### Debug output

**Errors in the JavaScript console**

No error in javascript console

**Output from `firebase.database.enableLogging(true);`**

In constructor of home page: "undefined"

**Screenshots**

### Expected behavior

Login to Google, as when I launch it using ionic serve.

### Actual behavior

![Screenshot_20190327-102518_MyApp](https://user-images.githubusercontent.com/20126928/55066573-5e515280-507e-11e9-9b54-886accdf88c0.jpg)

To get this result, I followed the official documentation below:

- https://github.com/angular/angularfire2 and more precisely: 

-- https://github.com/angular/angularfire2/blob/master/docs/install-and-setup.md and
-- https://github.com/angular/angularfire2/blob/master/docs/auth/getting-started.md

And I follow this documentation from Firebase for cordova

- https://firebase.google.com/docs/auth/web/cordova

I add code below in config.xml to fix unhautorized redirect to localhost

```
    <allow-navigation href="http://*" />
    <allow-navigation href="https://*" />
```

This issue was apparently fixed in version 7.0 of cordova but reappears in version 8.0

See #1600 

Below some screenshot of firebase configuration

**Project setup**

![image](https://user-images.githubusercontent.com/20126928/55067866-cacd5100-5080-11e9-8744-375f4ec52d10.png)

![image](https://user-images.githubusercontent.com/20126928/55067889-d6207c80-5080-11e9-9149-4d37259fe56b.png)

**Dynamic Links setup**
![image](https://user-images.githubusercontent.com/20126928/55067735-88a40f80-5080-11e9-8370-231ef3b585dc.png)

![image](https://user-images.githubusercontent.com/20126928/55067770-9bb6df80-5080-11e9-95c1-eb4fda19a952.png)

![image](https://user-images.githubusercontent.com/20126928/55067684-7033f500-5080-11e9-8016-225578d675a9.png)

**Comment by renatoflorencia** [comment]
I face the same problem here!

**Comment by PsiOps** [comment]
Same here. Same setup, exact same problem.

**Comment by PsiOps** [comment]
@oliviercherrier @renatoflorencia I found the solution in [this StackOverflow question](https://stackoverflow.com/questions/40591090/403-error-thats-an-error-error-disallowed-useragent): Just add `<preference name="OverrideUserAgent" value="Mozilla/5.0 Google" />` to your `config.xml`. It worked, I'm amazed and so happy right now.

**Comment by iamrafo** [comment]
> @oliviercherrier @renatoflorencia I found the solution in [this StackOverflow question](https://stackoverflow.com/questions/40591090/403-error-thats-an-error-error-disallowed-useragent): Just add `<preference name="OverrideUserAgent" value="Mozilla/5.0 Google" />` to your `config.xml`. It worked, I'm amazed and so happy right now.

your answer is disturbing other native plugins like platform

**Comment by PsiOps** [comment]
> > @oliviercherrier @renatoflorencia I found the solution in [this StackOverflow question](https://stackoverflow.com/questions/40591090/403-error-thats-an-error-error-disallowed-useragent): Just add `<preference name="OverrideUserAgent" value="Mozilla/5.0 Google" />` to your `config.xml`. It worked, I'm amazed and so happy right now.
> 
> your answer is disturbing other native plugins like platform

Could you elaborate on that? What problems does it cause?

**Comment by nileshordex** [comment]
I am using node JS and I faced same issue so how to fix this issue?

can you please help me any one.

Thank you:)

**Comment by davemake** [comment]
We had to completely abandon Ionic and Cordova

Amazingly, almost overnight, google swallowed Ionic and Cordova, and
destroyed their independance from google

First we tried to use node express and that failed

We ended up using node koa and followed the node koa examples and now we
have everything we want

Through node koa we are able to use
Chartist for charts
Get and post data
Use javascript libraries
Use json and fs as a database

For the mobile part
Linux ternminal on the mobile
Install node koa app as you would on the desktop

Ionic was really, really fun and great!
Now Ionic is just another google feature that doesn't work!
