### ISSUE TITLE
Angular Universal app getting error 'location.protocol'  with Firebase

### ISSUE THREAD

**Issue by totheskyer** [angular/angularfire#2039]
### Version info

**Angular:**
Angular 7.1.4

**Firebase:**
Firebase 6.5.0

**AngularFire:**
angularfire2 5.1.2

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
Browser application and MacOS/Windows

### How to reproduce these conditions

**Steps to set up and reproduce**

I run Angular Universal application. It built with Angular Universal framework successfully.
But when serving application in browser, i got error message.
And it caused by calling a method angularFireAuth.auth.getRedirectResult().

**My authentication code is:**
```
async handleAuthRedirectResult() {
    try {
      console.log('working here');
      const userCredential: UserCredential = await this.afAuth.auth.getRedirectResult();
      console.log('working here too');
      //null means no redirect -> the page was not redirected from Auth
      if (userCredential.user) {
          //do something
      }
      else {
          return Promise.reject(e);
      }
}
```
### Debug output

** Errors in the JavaScript console **
```
{ [Error: This operation is not supported in the environment this application is running on. "location.protocol" must be http, https or chrome-extension and web storage must be enabled.]
  code: 'auth/operation-not-supported-in-this-environment',
  message: 'This operation is not supported in the environment this application is running on. "location.protocol" must be http, https or chrome-extension and web storage must be enabled.' }
ERROR [Error]
ERROR [Error]
```

** Screenshots **

![image](https://user-images.githubusercontent.com/20748784/55567740-f7c7d680-5706-11e9-856f-feeadebe72dc.png)

### Expected behavior

It should work correctly, so need it resolved or any workaround.

**Comment by jamesdaniels** [comment]
Not an AngularFire issue, you need to handle the error. AF .user, .authState, .credential now all listen for .getRedirectResult so you don't have to do this yourself either.
