### ISSUE TITLE
rtdb/lists.md#api-summary missing description

### ISSUE THREAD

**Issue by 4skinSkywalker** [angular/angularfire#2055]
Hi guys,

I'm reading the documentation at [https://github.com/angular/angularfire2/blob/master/docs/rtdb/lists.md#api-summary](rtdb/lists.md#api-summary)

![image](https://user-images.githubusercontent.com/17194393/56847358-f9d21f00-68d9-11e9-9c4d-80c5da89bb26.png)

The description for the _update_ method is missing (as it just says "Firebase").

**Comment by jamesdaniels** [comment]
@jhuleatt think you could address?

**Comment by jamesdaniels** [comment]
Dunno if we fixed but closing as outdated since we're revamping the docs for the new version.
