### ISSUE TITLE
Possible bug: AngularFirePerformance fails on boot

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [angular/angularfire#2098]
Hello,

I seem to have an issue when integration Firebase Performance:

### How to reproduce these conditions
I just added AngularFirePerformanceModule to my base module. I didn't do nothing else.
I haven't yet upgraded to Angular 8 (that's a longer dev path), maybe it's related to that?
If I comment out AngularFirePerformanceModule everything works again.
I import everything AngularFire related in a BaseModule that is imported in AppModule.

### Version info
    "@angular/animations": "^7.2.15",
    "@angular/common": "^7.2.15",
    "@angular/compiler": "^7.2.15",
    "@angular/core": "^7.2.15",
    "@angular/forms": "^7.2.15",
    "@angular/http": "^7.2.15",
    "@angular/platform-browser": "^7.2.15",
    "@angular/platform-browser-dynamic": "^7.2.15",
    "@angular/router": "^7.2.15",
    "@angular/service-worker": "^7.2.15",
    "@angular/cdk": "8.0.0-beta.2",
    "@angular/material": "8.0.0-beta.2",
    "@angular/material-moment-adapter": "8.0.0-beta.2",
    "@angular/cdk-experimental": "8.0.0-beta.2",
    "@angular/material-experimental": "8.0.0-beta.2",
    "firebase": "6.1.0",
    "firebase-tools": "^6.10.0",
    "@firebase/app-types": "^0.4.0",
    "@angular/fire": "^5.2.1",

    "@angular-builders/jest": "^7.4.2",
    "@angular-devkit/build-angular": "~0.13.9",
    "@angular/cli": "^7.3.9",
    "@angular/compiler-cli": "^7.2.15",
    "@angular/language-service": "^7.2.15",
    "@angularclass/hmr": "^2.1.3",

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
Windows, node v10.15.3

### Error
When I boot I get:
ERROR in ./node_modules/@angular/fire/performance/performance.js 83:38
Module parse failed: Unexpected token (83:38)
You may need an appropriate loader to handle this file type.
|             return source$.pipe(tap(function () { return traceSubscription.unsubscribe(); }, function () { }, function () { return traceSubscription.unsubscribe(); })).subscribe(subscriber);
|         }); }; };
>         var requirePerformance = from(import('firebase/performance'));
|         this.performance = requirePerformance.pipe(map(function () { return zone.runOutsideAngular(function () { return app.performance(); }); }), tap(function (performance) {
|             if (instrumentationEnabled == false) {

**Comment by donaldaverill** [comment]
In your tsconfig, are you using commonjs as your module type? I'm getting the same error, but if I use es2015 as my module type, then I can't use dynamic imports which I'm using for lazy loading of routes.

**Comment by LanderBeeuwsaert** [comment]
hey @donaldaverill ,
my commonjs looks like this:
Does that answer your question?

{
  "compileOnSave": false,
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "outDir": "./dist/out-tsc",
    "baseUrl": "src",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ],
    "types": [
    ]
  }
}

**Comment by donaldaverill** [comment]
Yeah, according to the [TypeScript docs](https://www.typescriptlang.org/docs/handbook/compiler-options.html), since the 'module' option is not defined and your target is set to es5, then commonjs is the default setting.

**Comment by joaqcid** [comment]
i just upgraded my app to angular 8 and i started getting this error, the ng update command updated the tsconfig.json `compilerOptions.module` to esnext, so probably the library import 'firebase/performace' should be compatible with esnext

**Comment by jamesdaniels** [comment]
Closing as outdated.
