### ISSUE TITLE
AngularFirestoreDocument#update does not allow nested property updates or FieldValues

### ISSUE THREAD

**Issue by duke9509** [angular/angularfire#2100]
### Version info

**Angular:** 7.2.15

**Firebase:** 6.1.0

**AngularFire:** 5.2.1

**TypeScript:** 3.4

### Issue Description

Currently, `AngularFireDocument#update` takes its parameter as `Partial<T>`. This causes issues when trying to use either:

1. Non-computed nested property updates:
    ```ts
    doc.update({"flags.a": true}) //<-- Excess property error
    ```
2. `FieldValue` update methods:
    ```ts
    doc.update({someArray: FieldValue.arrayUnion("newItem")}) //<-- Type 'FieldValue' is missing the following properties from type 'string[]'...
    ```

https://github.com/angular/angularfire2/issues/2008#issuecomment-464849024 notes that this can be worked around by calling the (essentially untyped) version of the method on the raw reference object, but I'd consider that sub-optimal as I'd consider the main point of the wrapper `update` method to be providing a typed alias around the untyped method.

A solution I'd like to propose would be the addition of a new type for use with the `update` method (instead of `Partial`):

```ts
import * as firebaseRaw from "firebase";

export type FirestoreUpdates<T> =
    & {[K in keyof T]?: T[K] | firebaseRaw.firestore.FieldValue}
    & {[key: string]: unknown};
```

This allows arbitrary excess properties while still constraining that properties present on the original interface should either be their original types or a FieldValue object.

I think that would provide as much type-checking as one could hope for (there's no way to statically check nested property path strings) while allowing the full use of all features of the original `update` method.

Thoughts?

**Comment by jamesdaniels** [comment]
I'm amenable to the change. I agree about `[key: string]: unknown` but we have to support Angular 6 until we release the next major. I'd suggest using `any` and putting a comment `// SEMVER once we can, switch to unknown`.

I'd like to also put `[key: string]: unknown` on the return types:

```afs.doc<Something>('asdfasd').get() => Observable<Something & {[key: string]: unknown}>```

Also FYI you can import the types via firebase/app namespace:

```ts
import { firestore } from 'firebase/app';
...firestore.FieldValue;
```

**Comment by duke9509** [comment]
Might I ask why you want to change the return type of `get`? Does Firestore attach extra properties to the objects it returns?

Also I've noticed that that's how you import everything from Firebase in your code, but the API docs at https://firebase.google.com/docs/reference/js/firebase.app just show the "app" module as exporting a single function and interface, and so that actually confused me a bit. Do you know why that import works?

**Comment by michaeljota** [comment]
Maybe with an helper type? 

```ts
type MaybeFieldValue<T> = {
  [P in keyof T]: T[P] | firebase.firestore.FieldValue;
};
```

```ts
 update(data: Partial<MaybeFieldValue<T>>): Promise<void>;
```

Seems to work properly.

**Comment by jamesdaniels** [comment]
We've done a revamp to the types, should address most the feedback. If there are new issues please open another.
