### ISSUE TITLE
 Google login not working on Production server works fine at Dev Server

### ISSUE THREAD

**Issue by azizijunaid** [angular/angularfire#2102]
**Angular:** 5.2.10

**Firebase:** 4.8.0

**AngularFire:** 5.0.0-rc.4

**Error:** code: "auth/invalid-credential", message: "The supplied auth credential is malformed or has expired."

**Comment by BDominik** [comment]
Any solution?
I have the same problem.

**Comment by azizijunaid** [comment]
apis change
