### ISSUE TITLE
Getting started with AngularFire and Universal needs to be updated

### ISSUE THREAD

**Issue by tariva** [angular/angularfire#2105]
When setting up universal following 
https://github.com/angular/angularfire2/blob/master/docs/universal/getting-started.md

module.exports = {
  entry: {  server: './server.ts' },
  resolve: { extensions: ['.js', '.ts'] },
  mode: 'development',
  target: 'node',
  externals: [
    /* Firebase has some troubles being webpacked when in
       in the Node environment, let's skip it.
       Note: you may need to exclude other dependencies depending
       on your project. */
    /^firebase/
  ],....
...
}
externals: [
    /^firebase/
  ]
Causes an error when running 
 npm run serve:ssr

module.exports = firebase/app;
                 ^
ReferenceError: firebase is not defined

Pls update the doc :)

**Comment by Gbuomprisco** [comment]
I'm getting the same error. @tariva did you manage to work it around?

**Comment by dimoreira** [comment]
Locked on the same problem right now.

**Comment by Gbuomprisco** [comment]
Made it work with the following:

`const regex = /^firebase(\/([\w\d]+))*/;

config.externals.push(function(context, request, callback) {
    if (regex.test(request)) {
        return callback(null, 'commonjs ' + request);
    }
    callback();
});
`

**Comment by mvgadagi** [comment]
> Made it work with the following:
> 
> ```
> const regex = /^firebase(\/([\w\d]+))*/;
> 
> config.externals.push(function(context, request, callback) {
>     if (regex.test(request)) {
>         return callback(null, 'commonjs ' + request);
>     }
>     callback();
> });
> ```

Where did you add this change?

**Comment by Gbuomprisco** [comment]
To the file webpack.server.config.js

**Comment by mvgadagi** [comment]
> To the file webpack.server.config.js

Okay, I tried that and didn't work me

**Comment by jamesdaniels** [comment]
Closing as outdated.
