### ISSUE TITLE
Server side rendering fails in prod

### ISSUE THREAD

**Issue by inorganik** [angular/angularfire#2107]
Hi @jamesdaniels, I followed the docs and successfully set up Universal with Firebase. I could run `firebase serve` and everything worked fine. However, once deployed, I consistently get this error reported by the firebase functions logs:

```
Error: Cannot find module 'firebase/app'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at webpackUniversalModuleDefinition (/user_code/dist/angularfire-test-webpack/server.js:3:28)
    at Object.<anonymous> (/user_code/dist/angularfire-test-webpack/server.js:10:3)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
```
In webpack.server.config.js, firebase is an external. I don't know if that has anything to do with it. 
```
externals: [
    /* Firebase has some troubles being webpacked when in
       in the Node environment, let's skip it.
       Note: you may need to exclude other dependencies depending
       on your project. */
    /^firebase/
  ],
```
I reproduced this issue in the following repo: https://github.com/inorganik/angularfire-test

It is deployed here: https://hometowns-angularfire.firebaseapp.com/

This issue https://github.com/firebase/firebase-js-sdk/issues/1250 suggests installing the `firebase` package in the functions directory. However that results in this issue: https://github.com/firebase/firebase-js-sdk/issues/1696

### Version info

**Angular:** 7.2

**Firebase:** 5.10

**AngularFire:** 5.2.1

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** 
macOS 10.14.5
node: 8.15

### How to reproduce these conditions

https://github.com/inorganik/angularfire-test

**Steps to set up and reproduce**

1. include environment.ts with firebase keys
1. create `public` dir at root
1. `npm i`
1. `npm run build`
1. `firebase serve` ...everything should be fine...
1. `firebase deploy` - Errors serving page. Universal function fails.

**Sample data and security rules**

n/a

### Debug output

See above

### Expected behavior

Page should render fine in prod, as it does with firebase serve.

### Actual behavior

Page fails to render in prod.

**Comment by inorganik** [comment]
One other thing I thought I should mention - in order to get the angularfire universal steps to work I had to run in node 8. I have an .nvmrc file in that repro project that puts node at 8.15. Let me know if changing node versions will help, I don't know what version firebase runs in prod.

**Comment by inorganik** [comment]
I was able to resolve this by installing firebase@5.11.1 in my functions folder. Thank you to @Feiyang1 on [this thread](https://github.com/firebase/firebase-js-sdk/issues/1696) for giving us the solution. 

@jamesdaniels following your steps, they didn't prompt installation of the firebase package in functions, or which version to install (which is important, because some versions result in my error). I suggested a README of compatible versions in the other thread, but you may want to update your instructions.

**Comment by imtosss123** [comment]
hello @IgorMinar, I am also working with Universal and firebase and have problems like you.
I try your solution but still not working. can you share me your `webpack.server.config.js` file.
Thanks for your help.

Here is my version:
angular/cli: `6.0.8`
angular: `6.1.0`
angularfire2: `5.2.1`
firebase: `5.11.1`

**Comment by jamesdaniels** [comment]
Closing as outdated. Modern versions should be working much better & we now include SSR in the deploy schematic, which handles a lot of stuff automatically for you.
