### ISSUE TITLE
pipe() doesn't work when snapshotChanges() on a subcollection

### ISSUE THREAD

**Issue by meness** [angular/angularfire#2111]
### Version info

**Angular:** 8.0.0

**Firebase:** 6.1.1

**AngularFire:** 5.2.1

**Browser:** Google Chrome 75.0.3770.80

### How to reproduce these conditions

```typescript
this._firestore.collection<MODELX>(COLLECTION).doc<MODELX>(DOCUMENT_ID)
      .collection<MODELY>(SUBCOLLECTION_NAME)
      .snapshotChanges();
```

### Expected behavior

`.pipe()` works well on the query.

```typescript
// Should work
theAboveQuery.pipe(
        tap(snapshot => {
          console.log("snapshot", snapshot );
        })
      )
```

### Actual behavior

`.pipe()` doesn't work on the query but when I `.subscribe()` it works!

**Comment by meness** [comment]
The return type of the above query (`Observable<DocumentChangeAction<MODEL>[]>`) is different than `.snapshotChanges()` on a document (`Observable<Action<DocumentSnapshot<MODEL>>>`).

**Comment by nikmartin** [comment]
I have spent the better part of a day on this! In an exasperated state, I stuck subscribe on the end of my pipe, and it worked!. 

Repro:
```
// Firestore collection looks like: users/{userid}/containers/{containerid}/{admin:true}

const usersRef = this.afs.collection('users');
const userRef = usersRef.doc(user.uid);
const qryref = userRef.collection(`containers`, ref => ref.where('admin', '==', true));
qryref.snapshotChanges().pipe(map(cont => {
      console.log(this.constructor.name, cont);
})).subscribe();
```

**Comment by jdgamble555** [comment]
Put " | async" in your template...

**Comment by nikmartin** [comment]
@jdgamble555 there's no template in many cases, in my case this is in a service.
