### ISSUE TITLE
Getting started documentation seems unclear.

### ISSUE THREAD

**Issue by SanderElias** [angular/angularfire#2112]
This got reported to me

> At the [NPM SITE:]( https://www.npmjs.com/package/@angular/fire)  I'm told that AngularFire and AngularFire2 are obsolete, yet, in the 
> Getting started - Installation & Setup I am directed to the obsolete [AngularFire2 instructions on Github](https://github.com/angular/angularfire2/blob/HEAD/docs/install-and-setup.md).
> 
> It did not work and it took a bit to find the correct update instructions that are from 2019 and not 2018.
> 
> The correct setup is in the StackBlitz files [Stackblitz Template - Remember to set your Firebase configuration in app/app.module.ts](https://stackblitz.com/edit/angular-1iment)
> 
> From that point the instruction, which all lead to AgukareFire2 github actually work.  Or, once setup then using the docs AngulareFire2  for the different Firebaseservices work.
> 
> Can you fix the docs so that newbies get it right the first time?

I checked, and this seems unclear indeed.

**Comment by stephangrobler** [comment]
Is this still an issue? I can't find the section where it says AngularFire and AngularFire2 is obsolete on the NPM site.
