### ISSUE TITLE
AngularFire breaking change between 5.1.3 and 5.2.0

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [angular/angularfire#2115]
Hello,

This is an issue regarding a breaking change going from AngularFire 5.1.3 to 5.2.0 that I'm unsure that it is the intention.

See the closed issue here: https://github.com/firebase/firebase-js-sdk/issues/1837 ; closed because of a request to re-open here.

Could of course be that this is intended behaviour but I wouldn't think so.

**Comment by N-Andronopoulos** [comment]
Same issue as me: #2124

**Comment by LanderBeeuwsaert** [comment]
Glad I'm not alone haha

**Comment by N-Andronopoulos** [comment]
Just turn off aot and you're good to go till its resolved.

angular.json
```
{
      "aot": false,
      ...
      "buildOptimizer": false,
}
```

**Comment by LanderBeeuwsaert** [comment]
ok cool. Yeah thanks, but that would affect our production environment too much then. So not an option for us.

**Comment by matheo** [comment]
@jamesdaniels this issue got attention in the firebase-js-sdk repo, but here it remains without a solution :( I've spent most of my day today trying to figure out the build issue and I just got here...

@LanderBeeuwsaert please rename this ticket to "Production Build Fail" or "Blank Screen of Death" so others can reach this easier, and figure that the only solution is to not optimize the bundle and get a ton of additional Mb in our bundle.

**Comment by jburson** [comment]
@jamesdaniels Version 5.2 should be rolled back unless a fix is coming very soon. This AOT bug is catastrophic and makes this version useless.

**Comment by matheo** [comment]
Refs https://github.com/angular/angularfire2/pull/2117
