### ISSUE TITLE
Issue about integrating NGRX + angularFire: Insufficient Permissions & Timestamp not serializable

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [angular/angularfire#2119]
Hello,

I have been looking into setting up AngularFire + NGRX.

Because I couldn't find a best practices or a good example to base myself on (If I'm wrong, please point me to one! I would be most grateful!) I launched this request some time ago:
https://github.com/angular/angularfire2/issues/2078

Next to this, I have run into 2 main problems for the moment that I don't get solved.

1. One about a 'Missing or insufficient permissions' error that is thrown when logging out.
  - https://github.com/angular/angularfire2/issues/1459#issuecomment-388867519
  - The solution proposed by James Daniels doesn't seem to work for me, as also said by larssn in the next comment.
  - The solution proposed by rwmb I couldn't get working for NGRX.

2. One about NGRX not accepting non-serializable data in actions with 'strictStateSerializability' and 'strictActionSerializability' on => thus preventing Timestamp to be used in the Store.
  - Any idea what the best practise is here? Should I convert to Date/Moment the instant I get the Timestamp from firestore. I would prefer to not have to convert back & forth to date/timestamp of course.

So because of a combination of reasons:
	- I cannot expect to ask help if I cannot give a concise example of what my problems are
	- If I don't have an easy time to setup the integration, I think this is probably the case for more people than only me
	- It would be nice to have a starter project/example/showcase everybody can use and build upon.

I decided to build a demonstration application myself:
https://github.com/LanderBeeuwsaert/ngrx-8-angularfire-authentication

It would be great if somebody could take a look and make suggestions about how to overcome the two issues I've listed above.
It would also be great if we could expand this demonstration (or some demonstration like this) so as to showcase a real-world best practices usage of NGRX + angularFire.

Some extra points:
  - For now, it just shows how to login/logout of Firebase authentication + subscribe to and create user data from Firestore.
	I'm thinking about adding:
		○ NGRX data <=> angularFire / firebase.
		○ routing on login/logout (so it looks more like a real application)
		○ Route guards based on authentication (AngularFireGuard)
	
  - The firebase config is included in the project. It's just a temp firebase project that is blocked from read/write except for the /users collection. So I included it for easy use.

Hope you can help & think this would be useful.

**Comment by jamesdaniels** [comment]
Going to close for now. Thanks for all the NGRX feedback, we'll consider revamping guidance and some of our APIs to be more friendly in the future; maybe even include some modules that do a bit of this for you.

**Comment by LanderBeeuwsaert** [comment]
@jamesdaniels 
ok, we sure are still be interested in more insights into how to best handle the integration between the two libraries.
