### ISSUE TITLE
bug: AngularFirePerformanceModule and AngularFireAuthModule both do not allow to expose ApplicationRef.isStable = true

### ISSUE THREAD

**Issue by 0x6368656174** [angular/angularfire#2120]
### Version info

**Angular: 8.0.2**

**Firebase: 6.2.2**

**AngularFire: 5.2.1**

### How to reproduce these conditions

https://stackblitz.com/edit/angular-okjfft (look at console)

**Steps to set up and reproduce**

If you add `AngularFireAuthModule` and `AngularFirePerformanceModule` to the project at the same time, then the `ApplicatorRef.isStable` will never have `true`.

### Expected behavior

After application was init, `ApplicationRef.isStable` must be `true`.

### Actual behavior

`ApplicationRef.isStable` always `false`.

**Comment by jamesdaniels** [comment]
Addressed in recent versions.
