### ISSUE TITLE
Add module import and providers to auth-guard docs

### ISSUE THREAD

**Issue by ribomation** [angular/angularfire#2122]
Append to the code snippet about auth-guard how to import and configure providers of the new AngularFireAuthGuard. Something like

    @NgModule({
      imports: [
        RouterModule.forChild(routes),
        AngularFireAuthModule,
      ],
      providers: [
        AngularFireAuthGuard
      ],
      exports: [RouterModule]
    })
    export class MyRoutingModule {}

**Comment by KingDarBoja** [comment]
Unless I am missing something here, there isn't much to be added besides importing the `AngularFireAuthModule` in some module where the `AngularFireAuthGuard` is required: https://github.com/angular/angularfire/blob/master/docs/auth/router-guards.md

**Comment by jamesdaniels** [comment]
Closing as outdated since we're revamping the docs for the new version.
