### ISSUE TITLE
How to listen to server update only ?

### ISSUE THREAD

**Issue by tolotrasamuel** [angular/angularfire#2131]
### Version info

**Angular:** "@angular/core": "~8.1.1",

**Firebase:**  "firebase": "^6.3.0",

**AngularFire:**"@angular/fire": "^5.2.1",

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

The document says 

> hasPendingWrites
> hasPendingWrites: boolean
> True if the snapshot contains the result of local writes (e.g. set() or update() calls) that have not yet been committed to the backend. If your listener has opted into metadata updates (via SnapshotListenOptions) you will receive another snapshot with hasPendingWrites equal to false once the writes have been committed to the backend.

But I cannot find where to **opt into metadata updates (via SnapshotListenOptions)**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

Hence I do get only 1 update with _**hasPendingWrites**_ set to **true**
### Expected behavior

I want to get 2 events. the second one with hasPendingWrites set to false

### Actual behavior

I do get only 1 update with _**hasPendingWrites**_ set to **true**

**Comment by jamesdaniels** [comment]
metadata is now included on snapshots in the recently released 6.1, you can use an rxjs filter
