### ISSUE TITLE
Gmail data on Firebase don't update

### ISSUE THREAD

**Issue by lemmusm** [angular/angularfire#2133]
Hello everyone !

I update data from my gmail account, for example my name, so when I get firebase auth data from Angular the name don´t update.

Note: I use G Suite for Education.

**Angular:** 8.0.2
**@angular/cli:** 8.0.4
**@angular/fire:** 5.1.1

**Comment by wiedzmin26** [comment]
Did you refresh token?

**Comment by lemmusm** [comment]
> Did you refresh token?

Yes, I show token in console.log(auth.getIdTokenResult()); 

When I close session and access again, I obtain a different token and data don´t update.

**Comment by jamesdaniels** [comment]
Not an AngularFire issue, more Firebase in general, open a support issue.
