### ISSUE TITLE
Multiple OrderBy does not return results when using AngularFirestore

### ISSUE THREAD

**Issue by pain0486** [angular/angularfire#2135]
Note: I know this is not supported for a Real-Time Database but is should be for Cloud.
As shown in the [Firebase docs](https://firebase.google.com/docs/firestore/query-data/order-limit-data)
### Version info

**Angular:** 8.1.2

**Firebase:** 6.3.1

**AngularFire:** 5.2.1

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
**OS** Windows 10
**Browser** Chrome
**Node** 11.0

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

[Stack Blitz example](https://stackblitz.com/edit/employee-resmgmt)

**Steps to set up and reproduce**

Chain two orderBy statements
IE
```
this.db
        .collection<Employee>('employees', ref => ref.orderBy('lastName').orderBy('firstName'))
        .snapshotChanges()
```
Note this works fine when using either of them individually but when combined no results are returned.

**Sample data and security rules**

Provided in stack blitz example

### Debug output

** Errors in the JavaScript console ** 
None

### Expected behavior

Results are returned orderBy lastName then firstName

### Actual behavior

No results are returned

**Comment by hiepxanh** [comment]
this basicly impossible and not support yet official by firebase sir
