### ISSUE TITLE
Realtime data list push not insert element to last position

### ISSUE THREAD

**Issue by testanddeploy** [angular/angularfire#2137]
Hi

I don't know if this is a problem but from unknow version to current version when I do

db.list('items').push(newitem);

From different devices or users the item is insert on the last position of the last item inserted by this user/device

ie:

firstmessageUser1
secondmessageUser1
firstmessageUser2

If I insert new message from user1 the result is this:
firstmessageUser1
secondmessageUser1
thirdmessageUser1
firstmessageUser2

My expected result would be

firstmessageUser1
secondmessageUser1
firstmessageUser2
thirdmessageUser1

Is this normal?

Versions:
cordova: 9.0.0
cordova-android:8.0.0
@angular/fire: 5.2.1
firebase: 6.3.3

**### EDIT:**

With this versions works perfectly:

cordova: 9.0.0
cordova-android:8.0.0
@angular/fire: 5.1.3
firebase: 5.11.1

**Comment by jamesdaniels** [comment]
You may need to sort your data?
