### ISSUE TITLE
ng deploy builder does not work well in CI

### ISSUE THREAD

**Issue by FrozenPandaz** [angular/angularfire#2138]
### Version info

**Angular:** 8.2.0-next.2

**Firebase:** 6.3.4

**AngularFire:**5.2.1

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**CircleCI

### How to reproduce these conditions

Try and deploy via CircleCI.

### Expected behavior

`interactive` and `token` should probably be options for the `ng deploy` option. Otherwise, it is difficult to deploy via CI environments like CircleCI.

### Actual behavior

`interactive` and `token` cannot be passed through the builder.

I tried using the environment variable `$FIREBASE_TOKEN` which I think (not sure) logs me in correctly but prompts for analytics. I guess adding only the `interactive` flag would bypass this but I think `token` is the recommended method of passing the `FIREBASE_TOKEN`.

**Comment by jamesdaniels** [comment]
Good point, thanks for pointing out. I'll try to get this together in a future release.

**Comment by mcarey1590** [comment]
it would be nice to have a way to disable building as well. Our CI builds and creates an artifact to deploy in another stage.

**Comment by jamesdaniels** [comment]
environment variable is respected starting in `6.1.0-rc.1`
