### ISSUE TITLE
collection intermittently working in electron environment

### ISSUE THREAD

**Issue by jerryorta-dev** [angular/angularfire#2139]
I have been using Firestore Collection, and recently it's been failing intermittently more frequently. When I use the firebase sdk natively, I receive the queries consistently.

My package.json
"@angular/fire": "5.2.0",
"firebase": "^6.3.4",
 "electron": "^6.0.0",

query is like
```
this.memberOfProjectsSub = this.afs
      .collection('projects', ref =>
        ref
          .where('memberEmails', 'array-contains', user.auth.email)
          .where('share', '==', true)
      )
      .valueChanges()
...
```

**Comment by jamesdaniels** [comment]
Unclear that this has anything to do with AF, perhaps underlying JS SDK issue. Closing for now.
