### ISSUE TITLE
AngularFireFunctions.httpsCallable not catching the error details

### ISSUE THREAD

**Issue by matheo** [angular/angularfire#2140]
### Version info

**Angular:** 8.2.0

**Firebase:** 6.3.4

**AngularFire:** 5.1.3

### Debug output

The function is returning a `500` response with a corresponding error and it's not being processed

![image](https://user-images.githubusercontent.com/260185/62742185-3518d980-ba03-11e9-9b1d-24ff8f27ce39.png)

not a plain error:
![image](https://user-images.githubusercontent.com/260185/62742213-4cf05d80-ba03-11e9-96af-02d7b925f7e0.png)

nor the complete error from `auth.createUser()`
![image](https://user-images.githubusercontent.com/260185/62742674-23383600-ba05-11e9-8923-94234ee9b2a3.png)

![image](https://user-images.githubusercontent.com/260185/62742253-77dab180-ba03-11e9-984e-992b91c8c5ed.png)

### Actual behavior

    console.log(typeof error);
    console.log(Object.keys(error));
    console.log(error.code, error.details);

![image](https://user-images.githubusercontent.com/260185/62742326-bff9d400-ba03-11e9-88b0-384c807637d9.png)

### Expected behavior

To have the returned error message into `error.details`
Thanks!

**Comment by codeimpact** [comment]
I have the same issue with:

Angular: 7.2.2
Firebase: 5.9.1
AngularFire: 5.1.2

In the cloud function I am using express, but even with returning throwing a functions.https.HttpsError I am not able to receive the error.

Anyone facing the same problem?

**Comment by Ross-Rawlins** [comment]
How did you guys resolve this?

**Comment by bytejan** [comment]
The error message which is sent back should be from type functions.https.HttpsError

**Comment by matheo** [comment]
This is not solved right?

**Comment by neeph** [comment]
any new about this?

**Comment by KingDarBoja** [comment]
This is not related to AngularFire as you are using Firebase Cloud Functions to handle and throw any exception in the server side. Unless you are explicity throwing as follow (even with `try-catch` blocks:

```ts
await firestore()
    .collection('users')
    .get(userId)
    .catch((error) => {
      throw new https.HttpsError('failed-precondition', error.message, {
        code: error.code,
        message: error.message,
        userId: context.auth.uid,
      });
    });
```

You should be able to have the correct error response in your client.
