### ISSUE TITLE
BUG: Redundant function in Storage ref.ts file

### ISSUE THREAD

**Issue by rip222** [angular/angularfire#2145]
### Version info

**Angular:** 8.1.0

**Firebase:** 6.3.1

**AngularFire:** 5.2.1

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** MacOSX HighSierra

Take a look at `updateMetatdata` function. Isn't it redundant? 
```
export interface AngularFireStorageReference {
    getDownloadURL(): Observable<any>;
    getMetadata(): Observable<any>;
    delete(): Observable<any>;
    child(path: string): any;
    updateMetatdata(meta: SettableMetadata): Observable<any>;
    updateMetadata(meta: SettableMetadata): Observable<any>;
    put(data: any, metadata?: UploadMetadata | undefined): AngularFireUploadTask;
    putString(data: string, format?: string | undefined, metadata?: UploadMetadata | undefined): AngularFireUploadTask;
}
```

**Comment by jamesdaniels** [comment]
Hey there, it is indeed redundant as we had a spelling mistake. We've left it in this version though, because we don't want to break the API. We will remove it in the next major. Thanks for the PR.

**Comment by jamesdaniels** [comment]
Dropped in 6.
