### ISSUE TITLE
update instructions for microsoft auth

### ISSUE THREAD

**Issue by hooloom** [angular/angularfire#2148]
simple issue to be resolved in documentation - which would be helpful for Microsoft.  Google Firebase also has the same issue:

When using Microsoft Office365 or Microsoft Azure AD - the provider call must be microsoft.com not microsoft.

`  var provider = new firebase.auth.OAuthProvider('microsoft.com');` the google directions have it as:
 ` var provider = new firebase.auth.OAuthProvider('microsoft');` that won't work.  Hopefully if there are others trying to use the microsoft graph api in conjunction this will save a lot of pain.  When I am finished with this part of our app - I will share a couple of code snipets that could hopefully make there way to the documentation on how to properly integrate microsoft graph/microsoft auth with google firebase.  In the interim - this could be an open and close case but something added to the record.

**Comment by jamesdaniels** [comment]
We haven't done any of the new CICP auth stuff in the AF2 docs yet, would be good to cover. Any interest in helping with the docs?

**Comment by hooloom** [comment]
I wouldn't mind helping out - I use your AngularFire2 fairly heavily.  I've not written docs in the past, but as a whole I would like to give back.  So if there is a template that I should follow - I can most certainly do that.

**Comment by jamesdaniels** [comment]
Closing as stale.
