### ISSUE TITLE
FIRESTORE INTERNAL ASSERTION FAILED: AsyncQueue is already failed

### ISSUE THREAD

**Issue by Ross-Rawlins** [angular/angularfire#2166]
### Version info

**Angular:**
8.2.0
**Firebase:**
6.2.2
**AngularFire:**
5.2.1
**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
4.7.0
### How to reproduce these conditions
Enable offline persistance, let your device do to sleep and then come back. If you try to view any collection it always fails with this issue. Even with new observables
**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**
I have no authentication set up for the DB
<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **
FIRESTORE INTERNAL ASSERTION FAILED: AsyncQueue is already failed
** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

### Expected behavior
The app should carry or at least create a new connection after a timeout.

**Comment by jamesdaniels** [comment]
Unable to reproduce. I suspect this is outdated.
