### ISSUE TITLE
@firebase/firestore: Firestore (5.0.4): INTERNAL UNHANDLED ERROR:  The requested version (3) is less than the existing version (8).

### ISSUE THREAD

**Issue by shalvy** [angular/angularfire#2171]
index.esm.js:77 [2019-09-12T11:50:53.014Z]  @firebase/firestore: Firestore (5.0.4): INTERNAL UNHANDLED ERROR:  The requested version (3) is less than the existing version (8).
defaultLogHandler @ index.esm.js:77
Logger.error @ index.esm.js:167
error @ index.cjs.js:99
(anonymous) @ index.cjs.js:13243
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
(anonymous) @ zone.js:872
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:421
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:188
drainMicroTaskQueue @ zone.js:595
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:500
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
zone.js:665 Unhandled Promise rejection: The requested version (3) is less than the existing version (8). ; Zone: <root> ; Task: Promise.then ; Value: DOMException: The requested version (3) is less than the existing version (8). undefined
api.onUnhandledError @ zone.js:665
handleUnhandledRejection @ zone.js:692
_loop_1 @ zone.js:682
api.microtaskDrainDone @ zone.js:686
drainMicroTaskQueue @ zone.js:602
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:500
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
zone.js:192 Uncaught DOMException: The requested version (3) is less than the existing version [(8).[](url)](url
![errorAngfire](https://user-images.githubusercontent.com/26919655/64795670-c2a99500-d57e-11e9-9101-45b5fa1e9b85.JPG)
)

**Comment by jamesdaniels** [comment]
Unable to reproduce, need more info. Likely outdated too.

**Comment by shalvy** [comment]
I solved it by matching versions for particular Angular version I am using thanks
