### ISSUE TITLE
Loss access to update, add and remove methods after using a switchmap on my AngularFireDatabase.list()

### ISSUE THREAD

**Issue by gerardosabetta** [angular/angularfire#2174]
Hey everyone, I'm doing maintenance on an old project of mine that uses firebase realtime database and it now needs to work the same way but allowing multiple instances, so all I did was use a switchmap to get the correct list, it retrieves information but I loss all of the methods (update, remove, etc)

thiswas my old reference to the list:
```
  countries = this.afd.list('/countries/');
```

now with the switchmap:
```
    this.countries = this.settings.instanceSubject.switchMap(
      instance => this.afd.list(`/countries/${instance}/`)
    );
```

and the methods were like:

```
update(country) {
    return this.countries.update(country, {
      moving:true,
      goingTo:country.location,
      location: 'string',
      time: firebase.database.ServerValue.TIMESTAMP
    })
  }
```

### Version info

**Angular:**
4.1.3
**Firebase:**
4.3.1
**AngularFire:**
4.0.0-rc.1
**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
-N/A
### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **
this.countries.update is not a function
** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

### Expected behavior

I expect it to work the same way as before but being always up to date with the instance property
### Actual behavior
It retrieves data alright always up to date but I have no access to the methods update, remove, add.

**Comment by jamesdaniels** [comment]
No longer supporting 4, closing.
