### ISSUE TITLE
How to restrict Firebase api key to referrers and mobile apps?

### ISSUE THREAD

**Issue by philliao** [angular/angularfire#2175]
In my Ionic/Cordova project, my app.module.ts has this line:

```
@ngModule(
   // stuff
   imports: [
       // stuff
       AngularFireModule.initializeApp(environment.firebaseConfig),
       // stuff
    ],
)
```

The firebase config/options contains an Firebase API Key. Google only lets me restrict the key to one of referrers, android app or iOS app. So I will have to use 3 API Keys, each with different restrictions. I know how to use the Platform module to decide which key to used. 

But how do I configure the AngularFireModule to make this decision? A pointer to an example  or documentation will be greatly appreciated.

I could compile them differently. But I want to avoid it.

**Comment by luispimenta** [comment]
did you manage to solve this? I decided at the time of the build to generate according to the platform. But on android, putting restriction by the package does not work, did it work?

**Comment by luispimenta** [comment]
> In my Ionic/Cordova project, my app.module.ts has this line:
> 
> ```
> @ngModule(
>    // stuff
>    imports: [
>        // stuff
>        AngularFireModule.initializeApp(environment.firebaseConfig),
>        // stuff
>     ],
> )
> ```
> 
> The firebase config/options contains an Firebase API Key. Google only lets me restrict the key to one of referrers, android app or iOS app. So I will have to use 3 API Keys, each with different restrictions. I know how to use the Platform module to decide which key to used.
> 
> But how do I configure the AngularFireModule to make this decision? A pointer to an example or documentation will be greatly appreciated.
> 
> I could compile them differently. But I want to avoid it.

did you manage to solve this? I decided at the time of the build to generate according to the platform. But on android, putting restriction by the package does not work, did it work?

**Comment by philliao** [comment]
It's been a while. IIRC, I did try setting up 3 keys and compile them separately. But Google/Firebase saw them all as web clients, so there was no real way to restrict the access by referrer.

**Comment by jamesdaniels** [comment]
Correct there's no referrer blocking in the web SDKs as of yet. It's something they are exploring though but not sure when/if that will become a feature.
