### ISSUE TITLE
Support for Firebase Remote Config/Analytics (included in v7 of Firebase)

### ISSUE THREAD

**Issue by EdricChan03** [angular/angularfire#2178]
### Version info

**Angular:** `v8.x.x`

**Firebase:** `v6.x.x`

**AngularFire:** `v5.x.x`

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** NIL

### Expected behavior

There should be support for Remote Config/Analytics which is included in v7 of the Firebase SDK for JavaScript: [Release Notes](https://firebase.google.com/support/release-notes/js#version_700_-_september_26_2019)

### Actual behavior

There's currently no support for the Remote Config/Firebase Analytics API included in v7 of the JavaScript SDK.

**Comment by jamesdaniels** [comment]
Hey there @EdricChan03, we're definitely planning to add support in short order here. Thanks for raising!

**Comment by jimmykane** [comment]
In regards to this does the new Analytics (just tracking) not work at all?

For example I updated my environment configs to add the `measurementId` property but nothing happens.

**Comment by dominikstrasser** [comment]
You can get analytics up and running right now by using firebase directly.
you simply have to import the analytics script in your **main.ts**

  ```
  import 'firebase/analytics';
  ```

  and call `firebase.analytics()` somewhere in your code - i did it in **app.component.ts**

  ```
ngOnInit() {
   firebase.analytics()
}
  ```

**Comment by RezaRahmati** [comment]
@dominikstrasser Thanks

I tried, but there is no analytics method in firebase

I am using "firebase": "^6.2.0", "@angular/fire": "^5.2.1",

![image](https://user-images.githubusercontent.com/10086092/65841829-67083700-e2f4-11e9-98ba-a761ddd5c68e.png)

**Comment by dominikstrasser** [comment]
@RezaRahmati 
Firebase Analytics for Web was just released with v7 of Firebase.

https://firebase.google.com/support/release-notes/js

either you install firebase@7.0.0 or wait for the @angular/fire implementation.

**Comment by schankam** [comment]
@RezaRahmati Use --force

**Comment by jamesdaniels** [comment]
I've been testing and it seems there's no obvious incompatibilities with Firebase v7, so force installing firebase 7 should be ok. Let me know if you run into anything. I'll be aiming to get an initial attempt out this week.

**Comment by jamesdaniels** [comment]
WIP #2187

**Comment by jsitu** [comment]
@jimmykane where do you find the `measurementId`? I upgraded my Firebase project to integrate with Google Analytics, but I don't see the `measurementId` in the project settings config though.

**Comment by jimmykane** [comment]
@jsitu  I found it in the project config.

**Comment by jamesdaniels** [comment]
After you upgrade you’ll need to get your settings again, or “create a web app” if you haven’t done that before.

**Comment by pycraft114** [comment]
Does angularfire have official documentation for integrating Google Analytics ?

**Comment by stanislavromanov** [comment]
> Does angularfire have official documentation for integrating Google Analytics ?

Once this ticket is implemented you won't have to do this yourself in theory.

**Comment by danconte72** [comment]
I've been testing Analytics on 5.3.0 and it is working properly! Tks

**Comment by IAM5K** [comment]
> @dominikstrasser Thanks
> 
> I tried, but there is no analytics method in firebase
> 
> I am using "firebase": "^6.6.2", "@angular/fire": "^5.2.1",
> 
> Also not able to install firebase 7 (if it's in that version) because I get below error ` @angular/fire@5.2.0 requires a peer of firebase@>= 5.5.7 <7 but none is installed`
> 
> even with @angular/fire@next I get ` @angular/fire@5.2.0-rc.3 requires a peer of firebase@>= 5.5.7 <7 but none is installed`
> 
> ![image](https://user-images.githubusercontent.com/10086092/65841829-67083700-e2f4-11e9-98ba-a761ddd5c68e.png)

while installing use --force and it will get installed.
