### ISSUE TITLE
Feature Request: AngularFireFunctions HttpsCallable - add options to function call

### ISSUE THREAD

**Issue by dcaruana90** [angular/angularfire#2182]
### Version info
**Angular: 8.1.1

**Firebase: 5.10.1

**AngularFire: 5.1.3

### Feature Request Details
AngularFireFunction provides a hook to the FirebaseFunctions via a variable (functions). However, when using AngularFireFunctions to call an HttpsCallable, we lose out on the optional HttpsCallableOptions that the Firebase api provides. This options field is useful in setting the timeout for the function. 

The feature request is to expose that optional field found in the FirebaseFunctions callable so that AngularFireFunctions provides the same api as Firebase.

API reference:
httpsCallable(name: string, options?: HttpsCallableOptions): HttpsCallable

Document Reference:
https://firebase.google.com/docs/reference/js/firebase.functions.Functions

**Comment by cerealexx** [comment]
+1

**Comment by eyupaltindal** [comment]
it will be useful.

**Comment by pdemilly** [comment]
right the timeout is set at 60s which is not enough for some cloud functions especially since firestore db access is so slow

**Comment by jamesdaniels** [comment]
Addressed as of `6.1.0-rc.2`
