### ISSUE TITLE
Error 404 on put file to storage

### ISSUE THREAD

**Issue by itlpps** [angular/angularfire#2184]
### Version info

**Angular:** 8.x.x

**Firebase:** 7.0.0

**AngularFire:** 5.2.1

My config:
```apiKey: 'AIxxx',
      authDomain: 'xxx.firebaseio.com',
      databaseURL: 'https://xxx.firebaseio.com',
      projectId: 'xxx',
      storageBucket: 'xxx.appspot.com',
      messagingSenderId: 'xxx'
```

### Actual behavior
Apparently it is forming the storage url with config databaseURL instead of storageBucket.

Post url, generated when using putstring:
> https://firebasestorage.googleapis.com/v0/b/https://xxx.firebaseio.com/o?name=images%2Fchat%2F8a6af41a5c3c2f59a801

### Expected behavior
Expected url:
> https://firebasestorage.googleapis.com/v0/b/xxx.appspot.com/o?name=images%2Fchat%2F8a6af41a5c3c2f59a801

**Comment by jamesdaniels** [comment]
Closing as outdated.
