### ISSUE TITLE
Unexpected firing of events for AngularFireList valueChanges

### ISSUE THREAD

**Issue by Barbiero** [angular/angularfire#2188]
### Explaining

When calling `valueChanges()` on an AngularFireList, at first I thought that it would be just a wrapper over `on('value')` from the SDK, but then I got myself in a weird situation where observing a specific child of a list while also observing said list somehow exploded my browser.

For context, "said list" was a pretty big ~3k element list where each element is about 500 characters. That said, the weird behavior only started *after* I started observing a specific element in addition to the entire list; if I observe the `valueChanges` of the list by itself there was no performance impact beyond the obvious "3k elements being looked at at the same time".

Code optimization notwithstanding, I found that very odd. So I decided to experiment a bit with the library and the SDK by stamping a bunch of `tap`s around and seeing what happens. Here's what I observed:

- When the list is being observed by itself, the Observable will emit a value a single time, as expected
- When the list is being observed while a child of itself is /also/ being observed, **multiple events will fire from the list observable**. Specifically, instead of only firing once upon subscription, the list `valueChanges` will fire 20 times exactly.
- This does not happen if we start observing the child *after* the list. This isn't always viable, specially on a single page application like angular where we might be observing different things for different reasons(eg. I was looking at a specific user data object, while navigating into a user data list)

When turning on firebase database logging, I noticed that the AngularFireList also reads its data twice: once for a 'value' event and then again for every 'child_added' event for each corresponding element. I'm assuming it's an optimization for frequently changing lists, but it's data-inefficient when first subscribing to a list; and I don't believe this behavior is mentioned anywhere so I got surprised when our data usage went up in addition to the aforementioned bug.

I also noticed that the extra 19 emissions for the object occur *after* the `child_added` events

### Version info

**Angular:** 8.2.9

**Firebase:** 6.6.2

**AngularFire:** 5.2.1

### How to reproduce these conditions

Sorry I couldn't figure out how to set up plunkr/jsfiddle for this, but I did make a small project that you can use to test out this specific situation:

app.component.html

```html
<button (click)="addItem()">Add item!</button>

<span>Specific todo: {{ specificTodo$ | async | json }}</span>

<ul>
  <li *ngFor="let todo of todos$ | async">{{ todo.message }}</li>
</ul>
```

app.component.ts

```ts
import { Component } from "@angular/core";
import { tap } from "rxjs/operators";
import { TodoService } from "./todo.service";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"]
})
export class AppComponent {
  title = "testing-angular-fire-events";

  constructor(private readonly todoService: TodoService) {}

  readonly todos$ = this.todoService.entityList
    .valueChanges()
    .pipe(tap(val => console.warn(val)));

  readonly safeTodo$ = this.todoService.safeTodos$.pipe(tap(console.warn));

  readonly specificTodo$ = this.todoService
    .getByKey("-LqDVX_QFcqGBk49Ndz4") // use whatever specific key from your db
    .valueChanges();

  addItem() {
    this.todoService.addObject();
  }
}
```

```ts
import { Injectable } from "@angular/core";
import { AngularFireDatabase } from "@angular/fire/database";
import { Observable } from "rxjs";

interface Todo {
  message: string;
  otherdata: number;
}

const PREFIX = "todo";

@Injectable({
  providedIn: "root"
})
export class TodoService {
  readonly entityList = this.afDb.list<Todo>(PREFIX);

  constructor(private afDb: AngularFireDatabase) {}

  addObject() {
    return this.entityList.push({
      message: "Some message" + Math.random(),
      otherdata: Math.random()
    });
  }

  getByKey(key: string) {
    return this.afDb.object<Todo>(`${PREFIX}/${key}`);
  }

  // This example "safeTodo" doesnt emit multiple times
  // I tried to also avoid the extra child_addeds, but I'm sure I'll hit
  // a roadblock when dealing with other event types.
  readonly safeTodos$ = new Observable<Todo[]>(subject => {
    const ref = this.afDb.database.ref(PREFIX);
    // 1. read value
    // 2. take last key
    // 3. read child_added after last key
    let lastKey: string | null;
    const arrayToBuild: Todo[] = [];

    let refToClear: firebase.database.Reference;

    ref
      .orderByKey()
      .once("value")
      .then(snapshot => {
        if (!snapshot.exists()) {
          subject.next([]);
        } else {
          snapshot.forEach(todoSnapshot => {
            lastKey = todoSnapshot.key;
            arrayToBuild.push(todoSnapshot.val());
          });
          subject.next(arrayToBuild);
        }
      })
      .then(() => {
        refToClear = this.afDb.database.ref(PREFIX);

        refToClear
          .orderByKey()
          .startAt(lastKey)
          .on("child_added", snapshot => {
            if (snapshot.key === lastKey) {
              return;
            }

            if (snapshot.exists()) {
              const todo = snapshot.val() as Todo;
              arrayToBuild.push(todo);
              subject.next(arrayToBuild);
            }
          });
      });

    return () => refToClear.off("child_added");
  });
}

```

Also add this somewhere to enable firebase database logging:

```js
import * as firebase from "firebase/app";
import "firebase/database";

firebase.database.enableLogging(true,true);
```

**Steps to set up and reproduce**

Just use a new firebase project with the above code and you should be good to go

**Sample data and security rules**

Some sample todos:

```json
{
  "todo" : {
    "-LqDVX_QFcqGBk49Ndz4" : {
      "message" : "Some message0.5517596337980374",
      "otherdata" : 0.8995511806864426
    },
    "-LqDW00n9J47rIECLedK" : {
      "message" : "Some message0.17716230967065738",
      "otherdata" : 0.16948590436383926
    },
    "-LqDZtdSbDrPF2KWoYTB" : {
      "message" : "Some message0.9005843983800266",
      "otherdata" : 0.013133008591108997
    },
    "-LqDZzO10HMP1qgPpCis" : {
      "message" : "Some message0.2089292989228455",
      "otherdata" : 0.2371640804591405
    },
    "-LqDdduGxph8co_zewfK" : {
      "message" : "Some message0.11372333964421932",
      "otherdata" : 0.592930075855727
    },
    "-LqDdixhyadlNWP8bmjv" : {
      "message" : "Some message0.3273968184408669",
      "otherdata" : 0.74645130465163
    }
  }
}

```

### Debug output

Something along these lines:

![example of console.warn outputs](https://i.imgur.com/kTFaGQH.png)

### Expected behavior

Expected to see just a single `console.warn` here, which is what happens when you remove the `specificTodo$` subscription

### Actual behavior

`todo$` is emitting its array multiple times unecessarily.

**Comment by jamesdaniels** [comment]
Thanks for the repo, I've been hunting bugs like this for a while. I'll investigate if we can do anything smarter in the `scan`.

**Comment by jamesdaniels** [comment]
Closing as stale. If this is still an issue with the latest versions please open another issue.
