### ISSUE TITLE
How we can use FireSQL with it ?

### ISSUE THREAD

**Issue by tankejaures** [angular/angularfire#2222]
Please I want to know how i can use it with fireSQL

### Version info

**Angular: 8.1**

**Firebase: 6.6.2**

**AngularFire: 5.2.2**

**Comment by doczoidberg** [comment]
FireSQL is independent of AngularFire. It works with the native firebase library.

**Comment by jamesdaniels** [comment]
Out of scope, the FireSQL developer if they can support AF.
