### ISSUE TITLE
Firestore data retrieval works after ng-serve, but not after ng-deploy

### ISSUE THREAD

**Issue by PeterL1995** [angular/angularfire#2235]
### Version info

**Angular: "@angular/core": "~8.2.8"** 

**Firebase: 7.2.2**

**AngularFire: "@angular/fire": "^5.2.1"**

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

When navigating to the below link, a short list of products should show below the filter options. After ng-serve, the list displays as expected. After ng-deploy (the below) the list of products does not load.

https://padder-939bc.firebaseapp.com/catalogue (this is a live version after ng-deploy, where the issue occurs)

**Steps to set up and reproduce**

The above link is a live example of the issue.

**Sample data and security rules**

I have no security rules on the firebase data for the attached link.

### Debug output

No errors are output in the console.

Working after ng-serve: https://imgur.com/a/d3k0rzm

Not working after ng-deploy: https://imgur.com/a/JAfj7rt

### Expected behavior

Expected to show a list of products below the filters after deploying to firebase hosting.

### Actual behavior

No products are shown after ng-deploy, however, they are after ng-serve. I therefore understand this as an issue with the data being retrieved from Firestore.

**Comment by jamesdaniels** [comment]
Closing as outdated, if still experiencing with the newer versions open a new issue.
