### ISSUE TITLE
Facebook authentication with Firebase - Error message in popup

### ISSUE THREAD

**Issue by vpageau** [angular/angularfire#2237]
### Version info

**Angular:**
8.2.1
**Firebase:**
6.6.2
**AngularFire:**
5.2.1

### How to reproduce these conditions

Just a basic implementation of a Facebook authentication:

```signInWithFacebook() {
        this.afAuth.auth.signInWithPopup( new auth.FacebookAuthProvider() )
            .then(value => {
                //console.log('signInWithFacebook success: ', value);
                this.event$.next( new AuthenticationEvent(AuthenticationEventType.CONNECTED_WITH_FACEBOOK, value) );
            })
            .catch(err => {
                console.log('signInWithFacebook error: ', err);
                this.event$.next( new AuthenticationEvent(AuthenticationEventType.CONNECTED_WITH_FACEBOOK_FAILED, err) );
            });
    }
```

The following screenshot is from the production build when I try to connect using Facebook.

![image](https://user-images.githubusercontent.com/18009382/68031469-189edd00-fc92-11e9-8bd5-7251c1649031.png)

I haven't found anything on if the display type *page* is supported by angular/fire but this message pops up even in production and there's no workaround.

**Comment by remisture** [comment]
I have this issue as well. Did you solve it?

**Comment by jamesdaniels** [comment]
out of scope for AngularFire, if still experiencing this issue open with the Firebase JS SDK
