### ISSUE TITLE
Warning: 'Using development version of firebase sdk'

### ISSUE THREAD

**Issue by DazSanchez** [angular/angularfire#2238]
### Version info
**Angular:** 8.2.0

**Firebase:** 6.6.2

**AngularFire:** 5.2.1

### How to reproduce these conditions
**Steps to set up and reproduce**
* Create a basic Angular app
* Install @angular/fire and firebase libraries
* Initialize AngularFireModule

### Debug output

** Errors in the JavaScript console **
<pre>
It looks like you're using the development build of the Firebase JS SDK.
When deploying Firebase apps to production, it is advisable to only import
the individual SDK components you intend to use.
</pre>

** Screenshots **
![image](https://user-images.githubusercontent.com/11417060/68078499-64d64400-fd9c-11e9-95c2-e4a60d0c2dce.png)

### Expected behavior
Firebase library should not be showing this warning.

### Actual behavior
The library keeps using the old way of importing the firebase modules, wich is not recommended for production applicacions.
As declared in firebase documentation, the firebase modules should be imported as follow:
<pre>
import * as firebase from 'firebase/app';
import * as auth from 'firebase/auth';
import * as database from 'firebase/database';
</pre>

**Comment by jamesdaniels** [comment]
Those are types being imported, note you're in a `.d.ts`, if something is pulling in the development version of Firebase it's not that line of code.
