### ISSUE TITLE
How i get data of fields from using uid in collection of firebase. 

### ISSUE THREAD

**Issue by Ranindu15** [angular/angularfire#2244]
Version info
Angular:
8.3.14
Firebase:
6.4.2
AngularFire:
5.2.1
````
constructor(private mydb: AngularFirestore, private db: AngularFireDatabase, private afAuth: AngularFireAuth)


  getItemsList() {
    this.values = this.db.object(`signup/${this.userId}`);
    return this.values;
  }
````
 I use this for get all users from database.but now i need to click button and show one by one's details from db.Please help

**Comment by jamesdaniels** [comment]
Stackoverflow or one of the other support channels would be a better place for this type of query.
