### ISSUE TITLE
Build Failed in ionic 3/angular 5.x

### ISSUE THREAD

**Issue by himanshu-itmca** [angular/angularfire#2245]
### I've installed plugin in ionic 3 but after that build fails with these errors

** Output  `[15:39:50]  typescript: node_modules/firebase/index.d.ts, line: 4369 
            ';' expected. 

    L4368:  gtagName?: string;
    L4369:  /** Sets custom name for `dataLayer` array used by gtag. */
    L4370:  dataLayerName?: string;

[15:39:50]  typescript: node_modules/firebase/index.d.ts, line: 4369 
            'EventNameString' only refers to a type, but is being used as a value here. 

    L4368:  gtagName?: string;
    L4369:  /** Sets custom name for `dataLayer` array used by gtag. */
    L4370:  dataLayerName?: string;

[15:39:50]  typescript: node_modules/firebase/index.d.ts, line: 4369 
            'never' only refers to a type, but is being used as a value here. 

    L4368:  gtagName?: string;
    L4369:  /** Sets custom name for `dataLayer` array used by gtag. */     
    L4370:  dataLayerName?: string;

[15:39:50]  typescript: node_modules/firebase/index.d.ts, line: 4369 
            Cannot find name 'T'. 

    L4368:  gtagName?: string;
    L4369:  /** Sets custom name for `dataLayer` array used by gtag. */ 
    L4370:  dataLayerName?: string;

[15:39:50]  ionic-app-script task: "build" 
[15:39:50]  Error: Failed to transpile program 
Error: Failed to transpile program
    at new BuildError (/home/himanshu/development/ionic/testfcm1/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at /home/himanshu/development/ionic/testfcm1/node_modules/@ionic/app-scripts/dist/transpile.js:159:20
    at new Promise (<anonymous>)
    at transpileWorker (/home/himanshu/development/ionic/testfcm1/node_modules/@ionic/app-scripts/dist/transpile.js:107:12)
    at Object.transpile (/home/himanshu/development/ionic/testfcm1/node_modules/@ionic/app-scripts/dist/transpile.js:64:12)
    at /home/himanshu/development/ionic/testfcm1/node_modules/@ionic/app-scripts/dist/build.js:109:82
[ERROR] An error occurred while running subprocess ionic-app-scripts.
        
        ionic-app-scripts build --target cordova --platform android exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.
` **

**Comment by mrahmeddiab** [comment]
npm i typescript@latest

**Comment by jtushar53** [comment]
me too facing same issue.

Tried `npm i typescript@latest` but no luck

@himanshu-itmca did you got any resolution?

**Comment by nomaad95** [comment]
I've got the same issue. Any solutions ?

**Comment by nomaad95** [comment]
I've got the same issue. Still any solutions ?

**Comment by jamesdaniels** [comment]
Not an AngularFire issue, rather looks like the types on the JS SDK.
