### ISSUE TITLE
"Versions mistmatch" error during build

### ISSUE THREAD

**Issue by NothingEverHappens** [angular/angularfire#2253]
It seems like after:
https://github.com/angular/angularfire/commit/8e5a99561fe35ff5705a4223b2b6b7406ec236ad#diff-5d6e0c2e1efc2900cfea0be3d099d676

Version was removed from product-specific package.json files. 

So now when running `yarn build`, the following error gets triggered:

![image](https://user-images.githubusercontent.com/216412/69827376-2722da80-11e5-11ea-8722-4c4519e93aa7.png)

The error gets triggered here:
https://github.com/angular/angularfire/blob/master/tools/build.js#L328

The build seems to continue regardless of this error though.

### How to reproduce these conditions

`yarn build`

**Comment by jamesdaniels** [comment]
This step has been dropped from the build command now.
