### ISSUE TITLE
Angular app crashes after 20 hours with +1 gigabyte of memory allocation

### ISSUE THREAD

**Issue by tolotrasamuel** [angular/angularfire#2255]
### Version info

**Angular:**8.2.14

**Firebase:**7.5.0

**AngularFire:**5.2.3

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

I made a minimum reproducible code on https://stackblitz.com/edit/angular-wmwjz4 

**Steps to set up and reproduce**

Run on chrome and check chrome task manager SHIFT+ESC
Add the Javascript memory column and check it increase by 11kb/s

**Sample data and security rules**
N/A

### Debug output

** Errors in the JavaScript console **
N/A
** Output from `firebase.database().enableLogging(true);` **
N/A
** Screenshots **
![image](https://user-images.githubusercontent.com/29230303/69869118-5f99e580-12c5-11ea-9456-1e6b83ab88a1.png)

### Expected behavior
No memory leak

### Actual behavior
You can check yourself that the code does nothing. It just prints hello world. However, the JavaScript memory used by the Angular App increases by 11 kb/s (Chrome Task Manager CRTL+ESC). After 10 hours leaving the browser open, the memory used reaches approx 800 mb (the memory footprint is around twice 1.6 Gb!)

As a result, the browser runs out of memory and the chrome tab crashes.

Code that causes the memory leak:

I found that using the AngularFireAuthModule module causes the memory leak whether it is injected in a component constructor or in a service.

```
import { Component } from '@angular/core';
import {AngularFireAuth} from '@angular/fire/auth';
import {AngularFirestore} from '@angular/fire/firestore';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'memoryleak';
  constructor(public auth: AngularFireAuth){

  }
}
```

**Comment by karmasakshi** [comment]
Related: #2550

**Comment by jamesdaniels** [comment]
It appears the auth team addressed this.
