### ISSUE TITLE
Angular Universal Error : NullInjectorError: StaticInjectorError

### ISSUE THREAD

**Issue by mvgadagi** [angular/angularfire#2256]
I am getting below error when using AngularFireStore with Angular Universal

 `NullInjectorError: No provider for class{constructor(t,e,n,i,a,s,l){this.scheduler=new b.a(s,a),this.firestore=s.runOutsideAngular(()=>{const n=Object(M.e)(t,s,e).firestore();return n.settings(i||T),n}),this.persistenceEnabled$=n&&!Object(x.isPlatformServer)(a)?s.runOutsideAngular(()=>{try{return Object(r.a)(this.firestore.enablePersistence(l||void 0).then(()=>!0,()=>!1))}catch(t){return Object(o.a)(!1)}}):Object(o.a)(!1)}collection(t,e){let n;n="string"==typeof t?this.firestore.collection(t):t;const{ref:i,query:r}=N(n,e);return new _(i,r,this)}collectionGroup(t,e){if(A<6)throw"collection group queries require Firebase JS SDK >= 6.0";const n=e||(t=>t),i=this.firestore.collectionGroup(t);return new w(n(i),this)}doc(t){let e;return e="string"==typeof t?this.firestore.doc(t):t,new C(e,this)}createId(){return this.firestore.collection("_").doc().id}}!
    at ot.get (main-es2015.f3366865893b4d8a5f79.js:1)
    at main-es2015.f3366865893b4d8a5f79.js:1
    at t (main-es2015.f3366865893b4d8a5f79.js:1)
    at Hl.get (main-es2015.f3366865893b4d8a5f79.js:1)
    at main-es2015.f3366865893b4d8a5f79.js:1
    at t (main-es2015.f3366865893b4d8a5f79.js:1)
    at Hl.get (main-es2015.f3366865893b4d8a5f79.js:1)
    at Sp (main-es2015.f3366865893b4d8a5f79.js:1)
    at main-es2015.f3366865893b4d8a5f79.js:1
    at Op (main-es2015.f3366865893b4d8a5f79.js:1)
    at O (polyfills-es2015.15904ffa5452b1d42d39.js:1)
    at O (polyfills-es2015.15904ffa5452b1d42d39.js:1)
    at polyfills-es2015.15904ffa5452b1d42d39.js:1
    at l.invokeTask (polyfills-es2015.15904ffa5452b1d42d39.js:1)
    at Object.onInvokeTask (main-es2015.f3366865893b4d8a5f79.js:1)
    at l.invokeTask (polyfills-es2015.15904ffa5452b1d42d39.js:1)
    at a.runTask (polyfills-es2015.15904ffa5452b1d42d39.js:1)
    at k (polyfills-es2015.15904ffa5452b1d42d39.js:1)
    at u.invokeTask [as invoke] (polyfills-es2015.15904ffa5452b1d42d39.js:1)
    at k (polyfills-es2015.15904ffa5452b1d42d39.js:1)`

Versions :
"@angular/fire": "^5.2.3"
 "@angular/core": "^8.2.7"

app.module.ts
` imports: [
    AngularFireModule.initializeApp(environment.firebase),
    AngularFirestoreModule,
    AngularFireAuthModule],
 providers: [
    FirebaseService]`

FirebaseService

`export class FirebaseService {
  constructor(private afs: AngularFirestore, public afAuth: AngularFireAuth) {
    this.afAuth.auth.signInWithEmailAndPassword('username', 'password').then(() => {
    });
  }
 `

**Comment by mvgadagi** [comment]
I have found way that this issue doesn't exist when we turn off `buildOptimizer`.

But can you please look into this as turning off this flag will produce the prod bundle with huge size

**Comment by roshanaale9818** [comment]
I have same error please help me how can i solve this ?
main-es2015.c70ec67dabb7aac0baa1.js:1 ERROR Error: Uncaught (in promise): NullInjectorError: StaticInjectorError(wo)[class{constructor(t,e){this.spinnerService=t,this.changeDetector=e,this.spinner=new Lg,this.ngUnsubscribe=new M,this.setDefaultOptions=()=>{this.spinner=new Lg({name:this.name,bdColor:this.bdColor,size:this.size,color:this.color,type:this.type,fullScreen:this.fullScreen,divArray:this.divArray,divCount:this.divCount,show:this.show,zIndex:this.zIndex,template:this.template})},this.bdColor="rgba(51,51,51,0.8)",this.zIndex=99999,this.color="#fff",this.type="ball-scale-multiple",this.size="large",this.fullScreen=!0,this.name="primary",this.template=null,this.divArray=[],this.divCount=0,this.show=!1}ngOnInit(){var t;this.setDefaultOptions(),this.spinnerService.getSpinner(this.name).pipe((t=this.ngUnsubscribe,e=>e.lift(new Ng(t)))).subscribe(t=>{this.setDefaultOptions(),Object.assign(this.spinner,t),t.show&&this.onInputChange(),this.changeDetector.markForCheck()})}ngOnChanges(t){for(const e in t)if(e){const n=t[e];if(n.isFirstChange())return;void 0!==n.currentValue&&n.currentValue!==n.previousValue&&""!==n.currentValue&&(this.spinner[e]=n.currentValue)}}getClass(t,e){this.spinner.divCount=Rg[t],this.spinner.divArray=Array(this.spinner.divCount).fill(0).map((t,e)=>e);let n="";switch(e.toLowerCase()){case"small":n="la-sm";break;case"medium":n="la-2x";break;case"large":n="la-3x"}return"la-"+t+" "+n}onInputChange(){this.spinner.class=this.getClass(this.spinner.type,this.spinner.size)}ngOnDestroy(){this.ngUnsubscribe.next(),this.ngUnsubscribe.complete()}} -> t]: 
  StaticInjectorError(Platform: core)[class{constructor(t,e){this.spinnerService=t,this.changeDetector=e,this.spinner=new Lg,this.ngUnsubscribe=new M,this.setDefaultOptions=()=>{this.spinner=new Lg({name:this.name,bdColor:this.bdColor,size:this.size,color:this.color,type:this.type,fullScreen:this.fullScreen,divArray:this.divArray,divCount:this.divCount,show:this.show,zIndex:this.zIndex,template:this.template})},this.bdColor="rgba(51,51,51,0.8)",this.zIndex=99999,this.color="#fff",this.type="ball-scale-multiple",this.size="large",this.fullScreen=!0,this.name="primary",this.template=null,this.divArray=[],this.divCount=0,this.show=!1}ngOnInit(){var t;this.setDefaultOptions(),this.spinnerService.getSpinner(this.name).pipe((t=this.ngUnsubscribe,e=>e.lift(new Ng(t)))).subscribe(t=>{this.setDefaultOptions(),Object.assign(this.spinner,t),t.show&&this.onInputChange(),this.changeDetector.markForCheck()})}ngOnChanges(t){for(const e in t)if(e){const n=t[e];if(n.isFirstChange())return;void 0!==n.currentValue&&n.currentValue!==n.previousValue&&""!==n.currentValue&&(this.spinner[e]=n.currentValue)}}getClass(t,e){this.spinner.divCount=Rg[t],this.spinner.divArray=Array(this.spinner.divCount).fill(0).map((t,e)=>e);let n="";switch(e.toLowerCase()){case"small":n="la-sm";break;case"medium":n="la-2x";break;case"large":n="la-3x"}return"la-"+t+" "+n}onInputChange(){this.spinner.class=this.getClass(this.spinner.type,this.spinner.size)}ngOnDestroy(){this.ngUnsubscribe.next(),this.ngUnsubscribe.complete()}} -> t]: 
    NullInjectorError: No provider for t!
NullInjectorError: StaticInjectorError(wo)[class{constructor(t,e){this.spinnerService=t,this.changeDetector=e,this.spinner=new Lg,this.ngUnsubscribe=new M,this.setDefaultOptions=()=>{this.spinner=new Lg({name:this.name,bdColor:this.bdColor,size:this.size,color:this.color,type:this.type,fullScreen:this.fullScreen,divArray:this.divArray,divCount:this.divCount,show:this.show,zIndex:this.zIndex,template:this.template})},this.bdColor="rgba(51,51,51,0.8)",this.zIndex=99999,this.color="#fff",this.type="ball-scale-multiple",this.size="large",this.fullScreen=!0,this.name="primary",this.template=null,this.divArray=[],this.divCount=0,this.show=!1}ngOnInit(){var t;this.setDefaultOptions(),this.spinnerService.getSpinner(this.name).pipe((t=this.ngUnsubscribe,e=>e.lift(new Ng(t)))).subscribe(t=>{this.setDefaultOptions(),Object.assign(this.spinner,t),t.show&&this.onInputChange(),this.changeDetector.markForCheck()})}ngOnChanges(t){for(const e in t)if(e){const n=t[e];if(n.isFirstChange())return;void 0!==n.currentValue&&n.currentValue!==n.previousValue&&""!==n.currentValue&&(this.spinner[e]=n.currentValue)}}getClass(t,e){this.spinner.divCount=Rg[t],this.spinner.divArray=Array(this.spinner.divCount).fill(0).map((t,e)=>e);let n="";switch(e.toLowerCase()){case"small":n="la-sm";break;case"medium":n="la-2x";break;case"large":n="la-3x"}return"la-"+t+" "+n}onInputChange(){this.spinner.class=this.getClass(this.spinner.type,this.spinner.size)}ngOnDestroy(){this.ngUnsubscribe.next(),this.ngUnsubscribe.complete()}} -> t]: 
  StaticInjectorError(Platform: core)[class{constructor(t,e){this.spinnerService=t,this.changeDetector=e,this.spinner=new Lg,this.ngUnsubscribe=new M,this.setDefaultOptions=()=>{this.spinner=new Lg({name:this.name,bdColor:this.bdColor,size:this.size,color:this.color,type:this.type,fullScreen:this.fullScreen,divArray:this.divArray,divCount:this.divCount,show:this.show,zIndex:this.zIndex,template:this.template})},this.bdColor="rgba(51,51,51,0.8)",this.zIndex=99999,this.color="#fff",this.type="ball-scale-multiple",this.size="large",this.fullScreen=!0,this.name="primary",this.template=null,this.divArray=[],this.divCount=0,this.show=!1}ngOnInit(){var t;this.setDefaultOptions(),this.spinnerService.getSpinner(this.name).pipe((t=this.ngUnsubscribe,e=>e.lift(new Ng(t)))).subscribe(t=>{this.setDefaultOptions(),Object.assign(this.spinner,t),t.show&&this.onInputChange(),this.changeDetector.markForCheck()})}ngOnChanges(t){for(const e in t)if(e){const n=t[e];if(n.isFirstChange())return;void 0!==n.currentValue&&n.currentValue!==n.previousValue&&""!==n.currentValue&&(this.spinner[e]=n.currentValue)}}getClass(t,e){this.spinner.divCount=Rg[t],this.spinner.divArray=Array(this.spinner.divCount).fill(0).map((t,e)=>e);let n="";switch(e.toLowerCase()){case"small":n="la-sm";break;case"medium":n="la-2x";break;case"large":n="la-3x"}return"la-"+t+" "+n}onInputChange(){this.spinner.class=this.getClass(this.spinner.type,this.spinner.size)}ngOnDestroy(){this.ngUnsubscribe.next(),this.ngUnsubscribe.complete()}} -> t]: 
    NullInjectorError: No provider for t!
    at Rt.get (main-es2015.c70ec67dabb7aac0baa1.js:1)
    at main-es2015.c70ec67dabb7aac0baa1.js:1
    at t (main-es2015.c70ec67dabb7aac0baa1.js:1)
    at Ht.get (main-es2015.c70ec67dabb7aac0baa1.js:1)
    at main-es2015.c70ec67dabb7aac0baa1.js:1
    at t (main-es2015.c70ec67dabb7aac0baa1.js:1)
    at Ht.get (main-es2015.c70ec67dabb7aac0baa1.js:1)
    at Oi (main-es2015.c70ec67dabb7aac0baa1.js:1)
    at Gi.get (main-es2015.c70ec67dabb7aac0baa1.js:1)
    at gr (main-es2015.c70ec67dabb7aac0baa1.js:1)
    at v (polyfills-es2015.883cecaebeaf73f2aa3c.js:1)
    at v (polyfills-es2015.883cecaebeaf73f2aa3c.js:1)
    at polyfills-es2015.883cecaebeaf73f2aa3c.js:1
    at a.invokeTask (polyfills-es2015.883cecaebeaf73f2aa3c.js:1)
    at Object.onInvokeTask (main-es2015.c70ec67dabb7aac0baa1.js:1)
    at a.invokeTask (polyfills-es2015.883cecaebeaf73f2aa3c.js:1)
    at t.runTask (polyfills-es2015.883cecaebeaf73f2aa3c.js:1)
    at _ (polyfills-es2015.883cecaebeaf73f2aa3c.js:1)

**Comment by ImFranQ** [comment]
try adding

```
providers: [
    ...
    AngularFirestore
  ],
```
