### ISSUE TITLE
Push notification not working

### ISSUE THREAD

**Issue by yanlyan** [angular/angularfire#2257]
Angular: 8.2.x
Firebase: 7.5.0
AngularFire: 5.2.3
Chrome :  78.0.3904.108

I've followed the developer's guide.

Notification just showed on the first time I installed Angularfire. After subscribing to the foreground message the notification payload treated as a message instead of chrome notification.

### Request token
`this.afMessaging.requestPermission
      .pipe(mergeMapTo(this.afMessaging.tokenChanges))
      .subscribe(
        token => {
          this.afMessaging.messages.subscribe(console.log);
          console.log("Permission granted! Save to the server!", token);
        },
        error => {
          console.error(error);
        }
      );`

### Browser console
![image](https://user-images.githubusercontent.com/3099180/69935252-e38ee000-1506-11ea-8dff-5ccd855804f5.png)

Notification doesn't showed up

**Comment by rkimaoui** [comment]
Did you find a solution ?
