### ISSUE TITLE
Don't cache ngsw-config.json in firebase hosting

### ISSUE THREAD

**Issue by mgechev** [angular/angularfire#2259]
### Version info

**Angular:**

latest

**Firebase:**

latest

**AngularFire:**

latest

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

For any project run:

```
ng add @angular/fire
```

If the app is a PWA it'll have `ngsw-config.json`, which firebase will cache for an hour.

### Expected behavior

Add the file to the cache ignore list.

Thanks to @abraham for mentioning this today on the Modern Web meetup.

**Comment by jamesdaniels** [comment]
Addressed in the upcoming AngularFire 7.1 release
