### ISSUE TITLE
hyper links donot work with “firebase serve” or “firebase deploy” where as they work perfectly with “ng serve”

### ISSUE THREAD

**Issue by mayurmaed** [angular/angularfire#2260]
I am trying to host a angular application on firebase. Local or web deployment using "firebase serve" or "_firebase deploy_" make the hyperlinks render 404 error i.e. "localhost:5000" works but "_localhost:5000/link_" doesnot work and gives a 404 error.

I have used angular/cli for this application and until recently ng build used to create out-tsc folder and generate the compiled static files(i.e. all the components etc created) and it has stopped doing so. 

I have tried using the tsc modules in node_module/.bin of the project to generate the out-tsc files but to no effect.

When i try to serve the application locally using "_ng serve_" the app works perfectly and all the links work fine i.e. "_localhost:4200/link_" work exactly as intended

angular.json file :

> {
>   "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
>   "version": 1,
>   "newProjectRoot": "projects",
>   "projects": {
>     "consult": {
>       "projectType": "application",
>       "schematics": {},
>       "root": "",
>       "sourceRoot": "src",
>       "prefix": "app",
>       "architect": {
>         "build": {
>           "builder": "@angular-devkit/build-angular:browser",
>           "options": {
>             "outputPath": "dist/consult",
>             "index": "src/index.html",
>             "main": "src/main.ts",
>             "polyfills": "src/polyfills.ts",
>             "tsConfig": "tsconfig.app.json",
>             "aot": false,
>             "assets": [
>               "src/favicon.ico",
>               "src/assets"
>             ],
>             "styles": [
>               "src/styles.css"
>             ],
>             "scripts": []
>           },
>           "configurations": {
>             "production": {
>               "fileReplacements": [
>                 {
>                   "replace": "src/environments/environment.ts",
>                   "with": "src/environments/environment.prod.ts"
>                 }
>               ],
>               "optimization": true,
>               "outputHashing": "all",
>               "sourceMap": false,
>               "extractCss": true,
>               "namedChunks": false,
>               "aot": true,
>               "extractLicenses": true,
>               "vendorChunk": false,
>               "buildOptimizer": true,
>               "budgets": [
>                 {
>                   "type": "initial",
>                   "maximumWarning": "2mb",
>                   "maximumError": "5mb"
>                 },
>                 {
>                   "type": "anyComponentStyle",
>                   "maximumWarning": "6kb",
>                   "maximumError": "10kb"
>                 }
>               ]
>             }
>           }
>         },
>         "serve": {
>           "builder": "@angular-devkit/build-angular:dev-server",
>           "options": {
>             "browserTarget": "consult:build"
>           },
>           "configurations": {
>             "production": {
>               "browserTarget": "consult:build:production"
>             }
>           }
>         },
>         "extract-i18n": {
>           "builder": "@angular-devkit/build-angular:extract-i18n",
>           "options": {
>             "browserTarget": "consult:build"
>           }
>         },
>         "test": {
>           "builder": "@angular-devkit/build-angular:karma",
>           "options": {
>             "main": "src/test.ts",
>             "polyfills": "src/polyfills.ts",
>             "tsConfig": "tsconfig.spec.json",
>             "karmaConfig": "karma.conf.js",
>             "assets": [
>               "src/favicon.ico",
>               "src/assets"
>             ],
>             "styles": [
>               "src/styles.css"
>             ],
>             "scripts": []
>           }
>         },
>         "lint": {
>           "builder": "@angular-devkit/build-angular:tslint",
>           "options": {
>             "tsConfig": [
>               "tsconfig.app.json",
>               "tsconfig.spec.json",
>               "e2e/tsconfig.json"
>             ],
>             "exclude": [
>               "**/node_modules/**"
>             ]
>           }
>         },
>         "e2e": {
>           "builder": "@angular-devkit/build-angular:protractor",
>           "options": {
>             "protractorConfig": "e2e/protractor.conf.js",
>             "devServerTarget": "consult:serve"
>           },
>           "configurations": {
>             "production": {
>               "devServerTarget": "consult:serve:production"
>             }
>           }
>         },
>         "deploy": {
>           "builder": "@angular/fire:deploy",
>           "options": {}
>         }
>       }
>     }
>   },
>   "defaultProject": "consult"
> }

package.json

> {
>   "name": "consult",
>   "version": "0.0.0",
>   "scripts": {
>     "ng": "ng",
>     "start": "ng serve",
>     "build": "ng build",
>     "test": "ng test",
>     "lint": "ng lint",
>     "e2e": "ng e2e"
>   },
>   "private": true,
>   "dependencies": {
>     "@angular/animations": "~8.2.0",
>     "@angular/cdk": "^8.1.4",
>     "@angular/common": "~8.2.0",
>     "@angular/compiler": "~8.2.0",
>     "@angular/core": "~8.2.0",
>     "@angular/fire": "^5.2.3",
>     "@angular/forms": "~8.2.0",
>     "@angular/material": "^8.1.4",
>     "@angular/platform-browser": "~8.2.0",
>     "@angular/platform-browser-dynamic": "~8.2.0",
>     "@angular/router": "~8.2.0",
>     "@material-ui/core": "^4.5.1",
>     "@ng-bootstrap/ng-bootstrap": "^5.1.1",
>     "angular-bootstrap-md": "^8.2.0",
>     "firebase": "^7.5.2",
>     "jquery": "^3.4.1",
>     "ng-material-multilevel-menu": "^4.10.8",
>     "ngx-select-dropdown": "^1.1.0",
>     "rxjs": "~6.4.0",
>     "tslib": "^1.10.0",
>     "zone.js": "~0.9.1"
>   },
>   "devDependencies": {
>     "@angular-devkit/architect": "<0.900 || ^0.900.0-0 || ^9.0.0-0",
>     "@angular-devkit/build-angular": "~0.802.0",
>     "@angular/cli": "^8.3.20",
>     "@angular/compiler-cli": "~8.2.0",
>     "@angular/language-service": "~8.2.0",
>     "@types/jasmine": "~3.3.8",
>     "@types/jasminewd2": "~2.0.3",
>     "@types/node": "~8.9.4",
>     "codelyzer": "^5.0.0",
>     "firebase-tools": "^6.10.0",
>     "fuzzy": "^0.1.3",
>     "inquirer": "^6.2.2",
>     "inquirer-autocomplete-prompt": "^1.0.1",
>     "jasmine-core": "~3.4.0",
>     "jasmine-spec-reporter": "~4.2.1",
>     "karma": "~4.1.0",
>     "karma-chrome-launcher": "~2.2.0",
>     "karma-coverage-istanbul-reporter": "~2.0.1",
>     "karma-jasmine": "~2.0.1",
>     "karma-jasmine-html-reporter": "^1.4.0",
>     "protractor": "~5.4.0",
>     "ts-node": "~7.0.0",
>     "tslint": "~5.15.0",
>     "typescript": "~3.5.3"
>   }
> }

**Comment by jamesdaniels** [comment]
Can't reproduce.
