### ISSUE TITLE
"auth/invalid-api-key", message: "Your API key is invalid, please check you have copied it correctly."

### ISSUE THREAD

**Issue by tanjunior** [angular/angularfire#2261]
### Version info

**Angular:**
    "@angular/core": "~8.1.2",

**Firebase:**
    "firebase": "^7.5.2",

**AngularFire:**
    "angularfire2": "^5.2.3",

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
node v12.13.1
"@ionic/angular": "^4.7.1"
chrome
windows 10 Home

### How to reproduce these conditions
**Steps to set up and reproduce**
firebaseConfig.ts
```
const firebaseConfig = {
    apiKey: "omitted",
    authDomain: "omitted",
    databaseURL: "omitted",
    projectId: "omitted",
    storageBucket: "omitted",
    messagingSenderId: "omitted",
    appId: "omitted",
    measurementId: "omitted"
}

export default firebaseConfig
```
app.module.ts
```
import firebaseConfig from "../firebaseConfig"

@NgModule({
  declarations: [AppComponent],
  entryComponents: [],
  imports: [BrowserModule, IonicModule.forRoot(), AppRoutingModule, AngularFireModule.initializeApp(firebaseConfig), AngularFireAuthModule],
  providers: [
    AuthService,
    Facebook,
    StatusBar,
    SplashScreen,
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy }
  ],
  bootstrap: [AppComponent]
})
export class AppModule {}

```

### Debug output

"auth/invalid-api-key", message: "Your API key is invalid, please check you have copied it correctly."

### Expected behavior

Page load
### Actual behavior
Page load on ionic serve but doesn't not work after `ionic build` and uploading to webhost

**Comment by ankitjainOfficial** [comment]
same for me. anybody else having the same issue?

**Comment by Lacka90** [comment]
Same for me if I build angular in prod mode. In development mode it works fine.
I tested it on plain angular project.
package.json:
   ```
 "@angular/core": "~8.2.13",
 "@angular/fire": "^5.2.3",
 "firebase": ">= 5.5.7 <8",
```

**Comment by IDontKnowAnythng** [comment]
i m having the same issue here

**Comment by jamesdaniels** [comment]
Can't reproduce.

**Comment by madhujamitra** [comment]
same issue
