### ISSUE TITLE
There are multiple modules with names that only differ in casing. This can lead to unexpected behavior when compiling on a filesystem with other c ase-semantic.

### ISSUE THREAD

**Issue by vamshi121** [angular/angularfire#2265]
WARNING in ./node_modules/angularfire2/fireStore/index.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other c
ase-semantic.
Use equal casing. Compare these module identifiers:
* D:\angularCMS\angularCli\node_modules\angularfire2\fireStore\index.js
    Used by 2 module(s), i. e.
    D:\angularCMS\angularCli\node_modules\@ngtools\webpack\src\index.js!D:\angul
arCMS\angularCli\src\app\providers\af.service.ts
* D:\angularCMS\angularCli\node_modules\angularfire2\firestore\index.js
    Used by 2 module(s), i. e.
    D:\angularCMS\angularCli\node_modules\@ngtools\webpack\src\index.js!D:\angul
arCMS\angularCli\src\app\app.module.ts
i ?wdm?: Compiled with warnings.

    ERROR in src/app/providers/af.service.ts(20,37): error TS2339: Property 'swi
tchMap' does not exist on type 'Observable<User>'.
    src/app/providers/af.service.ts(24,29): error TS2339: Property 'of' does not
 exist on type 'typeof Observable'.

**Comment by jamesdaniels** [comment]
This sounds like an issue with an import, can you search your codebase / node modules for "fireStore"? There are no case-sensitive matches for this in the AngularFire codebase.
