### ISSUE TITLE
ng deploy with prerender builder

### ISSUE THREAD

**Issue by wagnermaciel** [angular/angularfire#2266]
## Feature Request

Change our `deploy` implementation to accept a different build target.

https://github.com/angular/angularfire/blob/master/src/schematics/deploy/actions.ts#L29

## Issue

Because the current `deploy` implementation builds before deploying, it will overwrite the prerendered routes.

## Use Case

angular/universal has recently added a builder which prerenders static routes. Our goal is to make it possible for developers to easily deploy their static routes to firebase.

**Comment by alan-agius4** [comment]
Duplicate of https://github.com/angular/angularfire/issues/2063

**Comment by michaeljota** [comment]
I understand that OP is literally requesting a build target, but prerender is a complete new task introduced by Angular Universal. I read the other issue, and the user would likely be able to do something like this if the user have two different scripts to do it, a first script with `ng prerender` (I think is called that, will check) and another with `ng deploy --no-build`.

However, I think this is supoptimal, as I would have to remember the order, or create another script for this.

Maybe you could introduce another configuration property to define the build task, being `build` the default one.

**Comment by alan-agius4** [comment]
@michaeljota, I am not following why one would need to remember anything. It would be simply a single to build and deploy command.

```cmd
ng deploy --build-target project:prerender:prod
```

**Comment by wagnermaciel** [comment]
Closing this issue as it is a duplicate for #2063
