### ISSUE TITLE
signInWithRedirect with facebook returns null as response

### ISSUE THREAD

**Issue by eliavmaman** [angular/angularfire#2275]
BUG report
I'm implementing facebook and google login using **signInWithRedirect** .
Google works well and i get google user as expected, but Facebook returns null all the time.

Here is my code:
```
doFacebookLogin() {
    const provider = new firebase.auth.FacebookAuthProvider();
    provider.addScope('email');
    provider.addScope('user_friends');
    this.afAuth.auth
      .signInWithRedirect(provider);
}
```

and authState
```
this.afAuth.authState.subscribe((firebaseUser: any) => { //firebaseUser return as null every time only for facebook
      this.onUserLogged.next(firebaseUser);
    })
```
my facebook app
![image](https://user-images.githubusercontent.com/6911449/71562938-72eccc00-2a90-11ea-834c-2c4c631b21b1.png)

What to do?  my brain is about to explode :)

**Comment by hiepxanh** [comment]
edit the config in the firebase console page could help you sir, I don't think this is `@angular/fire` problem
