### ISSUE TITLE
in and array-contains-any not assignable

### ISSUE THREAD

**Issue by borjaluor** [angular/angularfire#2278]
I get the next error when I try to use "in" or "array-contains-any" in where clauses

error TS2345: Argument of type '"in"' is not assignable to parameter of type 'WhereFilterOp'

**Comment by JGH153** [comment]
Try upgrading the firebase dependency to the latest version (which is separate from the @angular/fire dependency). WhereFilterOp is defined in the firebase-sdk, not in angularfire. Works for me on `"firebase": "^7.6.1"` and `"@angular/fire": "^5.2.1"`

**Comment by borjaluor** [comment]
I update `"firebase": "^7.6.1"` and `"@angular/fire": "^5.2.3"` but I get the same error,

`import { AngularFirestoreCollection, AngularFirestore, AngularFirestoreDocument, DocumentReference } from '@angular/fire/firestore';`

` constructor(private db: AngularFirestore, private http: HttpClient) { }`

`this.documentosCol = this.db.collection(tipoDoc, ref => {
      return ref.where('pagada', 'in', [true, false]);
    });`

**Comment by borjaluor** [comment]
> Try upgrading the firebase dependency to the latest version (which is separate from the @angular/fire dependency). WhereFilterOp is defined in the firebase-sdk, not in angularfire. Works for me on `"firebase": "^7.6.1"` and `"@angular/fire": "^5.2.1"`

I update `"firebase": "^7.6.1"` and `"@angular/fire": "^5.2.3"` but I get the same error,

`import { AngularFirestoreCollection, AngularFirestore, AngularFirestoreDocument, DocumentReference } from '@angular/fire/firestore';`

` constructor(private db: AngularFirestore, private http: HttpClient) { }`

`this.documentosCol = this.db.collection(tipoDoc, ref => {
      return ref.where('pagada', 'in', [true, false]);
    });`

**Comment by jereckley** [comment]
7.6.1 fixed it for me on 5.2.1
