### ISSUE TITLE
.auth is not a function

### ISSUE THREAD

**Issue by yannickcare** [angular/angularfire#2286]
I am using Angular 8, with the following packages:
    "@angular/core": "~8.2.14",
    "@angular/fire": "^5.3.0",
    "firebase": ">= 5.5.7 <8",

Works really well in development, but when I compile for production, I get the error

TypeError: Object(...)(...).auth is not a function

this is where in your code:

this.auth = zone.runOutsideAngular(() => {
            const app = _firebaseAppFactory(options, zone, nameOrConfig);
            return app.auth();
        });

I've seen this in other posts, but not with these versions which are the latest from this repo.

**Comment by marcosandreao** [comment]
@yannickcare I've put in app.module.ts
```
import "firebase/auth";
import "firebase/firestore";
```
it work for me
