### ISSUE TITLE
feat(storage): add list method

### ISSUE THREAD

**Issue by AmitMY** [angular/angularfire#2288]
### Version info

**Angular:**
~9.0.0-rc.7

**Firebase:**
^7.6.1-0

**AngularFire:**
^5.3.0-rc.4

## Feature

I'm trying to show a files list of a specific user, which I store in firebase storage. Firebase offers a list method:
https://firebase.google.com/docs/reference/js/firebase.storage.Reference#list

But angularfire doesn't have such method.

I am aware I can access `this.storage.storage.ref('my-folder')`, just wanted to ask for a better service-solution

**Comment by KrustyHack** [comment]
Ay,

On my side I'm able to list all files :

```
    this.storage.ref(this.userService.storagePath + '/album/').listAll().subscribe(data => {
      data.items.forEach(element => {
        console.log(element);
      });
    });
```

It's not what you're trying to do ?
