### ISSUE TITLE
Cant get foreground notification, cant get token in chrome 

### ISSUE THREAD

**Issue by all2pie** [angular/angularfire#2293]
I am using AngularFireMessaging and getting some issue, did a lot of research, read official docs but could not solve them.

1st issue is that when i send push notification the foreground notification handler crashes (image below), background notifications are working fine and everything is correctly setup.

![image](https://user-images.githubusercontent.com/34629684/72800448-35332b80-3c69-11ea-8909-bf181bd72195.png)

2nd issue is that i can not get token in chrome, image below:

![image](https://user-images.githubusercontent.com/34629684/72800682-bb4f7200-3c69-11ea-9946-7145ec050483.png)

Kindly help.

### Version info

Angular: 8.2.14

Firebase: 7.7.0

AngularFire: 5.3.0

**Comment by all2pie** [comment]
Notification Service Code: 

`import { Injectable } from '@angular/core';
import { AngularFireMessaging } from '@angular/fire/messaging';

@Injectable()
export class NotificationService {

  constructor(private messaging: AngularFireMessaging, private generalService: GeneralService) { }

  getPermission() {

      this.messaging.requestToken
        .subscribe(
          (token) => {
            console.log('Permission granted! Save to the server!', token);
            this.messaging.messages
              .subscribe((message) => { console.log(message); });
          },
          (error) => { console.error(error); },
        );
  
  }

}`

**Comment by manishAppsimity** [comment]
I am facing the same issue in angular 8.

**Comment by manishAppsimity** [comment]
I am also facing the same issue..

**Comment by bageren** [comment]
I also cannot get any tokens in Chrome. Haven't tried other browser. I'm not getting any errors though.

**Comment by ayyash** [comment]
the only way I got around this is by filling up the firebase service worker file properly, like this
```
importScripts('https://www.gstatic.com/firebasejs/7.6.0/firebase-app.js');
importScripts('https://www.gstatic.com/firebasejs/7.6.0/firebase-messaging.js');
  firebase.initializeApp({
   apiKey: “from firebase config”,
   authDomain: “from firebase config”,
   databaseURL: “from firebase config”,
   projectId: “from firebase config”,
   storageBucket: “from firebase config”,
   messagingSenderId: “from firebase config”,
   appId: “from firebase config”,
   measurementId: “from firebase config”
});
  const messaging = firebase.messaging();
```

**Comment by jamesdaniels** [comment]
Addressed in recent versions of AngularFire / Firebase.
