### ISSUE TITLE
Analytics not working for prod builds

### ISSUE THREAD

**Issue by smarth55** [angular/angularfire#2295]
### Version info
**Angular:** 9.0.0-rc.9
**Firebase:** 7.7.0
**AngularFire:** 5.3.0

### How to reproduce these conditions
Following the documentation, add the `AngularFireAnalyticsModule` to the root module of the application. Run `npm run build -- --prod`. 

**Steps to set up and reproduce**
I updated by running `ng update --all` and then ran locally with `npm run start`. The correct bundles were produced and the analytics console was showing events. I deployed the application for production and checked the analytics console and nothing was being tracked.

### Debug output
** Errors in the JavaScript console ** none

** Screenshots **
It looks like the bundles are being created by webpack, but are never requested. I actually did this two different ways. The first was just like the documentation: add the module and it should fire a page_view event, but I noticed that the analytics bundle was never requested from the server:

(it should be 4.*.js)
<img width="311" alt="Screen Shot 2020-01-22 at 10 56 15 AM" src="https://user-images.githubusercontent.com/4282223/72910677-dc19d500-3d06-11ea-983a-a74b3ebc966a.png">

I next added `{provide: CONFIG, useValue: {send_page_view: false}}` and manually called `this.analytics.logEvent('page_view');` in my root component and now I see the analytics bundle:
<img width="313" alt="Screen Shot 2020-01-22 at 10 48 33 AM" src="https://user-images.githubusercontent.com/4282223/72910644-d1f7d680-3d06-11ea-9de0-8e9b34b57358.png">

I'm not sure if this is an ivy issue or not, but when I build for develop, everything works fine without manually logging the event.

### Expected behavior
If the documentation is correct, I should see a page_view event after adding the module to my imports.

### Actual behavior
No page_view events are being triggered with `--prod`.

**Comment by jamesdaniels** [comment]
Likely an IVY issue, will be cutting AngularFire v6 RC soon with ng 9 support. Keep an eye out for that.

**Comment by jimmykane** [comment]
No issues here with 9 + Ivy.

**Comment by jamesdaniels** [comment]
Should be addressed in `6.0.0-rc.0`, though you might need the work around in #2303 until I drop the next RC. Please reopen if you're still having troubles.
