### ISSUE TITLE
idField not working in valueChanges()

### ISSUE THREAD

**Issue by haleyDesignhouse** [angular/angularfire#2297]
### Version info

**Angular:** 8.2.14

**Firebase:** 7.5.0

**AngularFire:** 5.3.0

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Steps to set up and reproduce**

I am using a query like this:
```js
return this.afs.collection<StoreDetailDto>(this.collectionName).doc(storeId).valueChanges({ idField: 'docId' });
```

### Debug output

** Errors in the JavaScript console **

> ERROR in src/app/stores/store-repo.service.ts(77,95): error TS2554: Expected 0 arguments, but got 1.

It's referring to my method and my editor even has `valueChanges({ idField: 'docId' })` underlined with red (I use PHPStorm).

### Expected behavior

I thought this feature got added in 5.2 so I'm not sure why it's not able to accept that parameter in valueChanges(). Was this removed in 5.3.0 or something?

When I open up the method.. I see these options here:
```js
valueChanges(): Observable<T[]>;
valueChanges({}: {}): Observable<T[]>;
valueChanges<K extends string>(options: {
        idField: K;
}): Observable<(T & {
        [T in K]: string;
})[]>;
```

I'm not understanding why angular cli is throwing an error saying you can't pass any arguments :(

**Comment by haleyDesignhouse** [comment]
Oh now I'm not having this issue all of a sudden. Not sure what resolved it.

**Comment by haleyDesignhouse** [comment]
Ah nevermind! This is an issue when called on .doc(id).valueChanges()... it works when calling on just the collection when retrieving more than one document... Maybe that will help narrow the issue down?

**Comment by cedvdb** [comment]
Imo this should be a lib configuration, we shouldn't have to call `valueChanges({ idField: 'id' })` everytime. And that should be on both doc and col.
