### ISSUE TITLE
[6.0-rc.0] Analytics: global is not defined

### ISSUE THREAD

**Issue by vandres** [angular/angularfire#2303]
### Version info

**Angular:** 9.0.0-rc.12

**Firebase:** 7.8.0

**AngularFire:** 6.0.0-rc.0

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Steps to set up and reproduce**

Just importing the Analytics Module

```
imports: [
        BrowserModule,
        AngularFireModule.initializeApp(environment.firebase),
        AngularFireAnalyticsModule,
        NoopAnimationsModule,
        ComponentsModule
    ],
```

### Debug output

<details>
Unhandled Promise rejection: global is not defined ; Zone: <root> ; Task: Promise.then ; Value: ReferenceError: "global is not defined"
    Angular 28
 AngularFireAnalytics@http://localhost:4200/vendor.js:74047:13
AngularFireAnalytics_Factory@http://localhost:4200/vendor.js:74153:182
hydrate@http://localhost:4200/vendor.js:46638:54
get@http://localhost:4200/vendor.js:46400:33
injectInjectorOnly@http://localhost:4200/vendor.js:32635:33
ɵɵinject@http://localhost:4200/vendor.js:32645:57
AngularFireAnalyticsModule_Factory@http://localhost:4200/vendor.js:74562:246
hydrate@http://localhost:4200/vendor.js:46638:54
get@http://localhost:4200/vendor.js:46400:33
R3Injector/<@http://localhost:4200/vendor.js:46330:25
R3Injector@http://localhost:4200/vendor.js:46326:31
createInjector@http://localhost:4200/vendor.js:46277:12
NgModuleRef$1@http://localhost:4200/vendor.js:63231:47
create@http://localhost:4200/vendor.js:63321:16
bootstrapModuleFactory/<@http://localhost:4200/vendor.js:68500:64
invoke@http://localhost:4200/polyfills.js:378:30
onInvoke@http://localhost:4200/vendor.js:67718:33
invoke@http://localhost:4200/polyfills.js:377:36
run@http://localhost:4200/polyfills.js:137:47
run@http://localhost:4200/vendor.js:67548:91
bootstrapModuleFactory@http://localhost:4200/vendor.js:68493:23
bootstrapModule/<@http://localhost:4200/vendor.js:68569:31
invoke@http://localhost:4200/polyfills.js:378:30
run@http://localhost:4200/polyfills.js:137:47
scheduleResolveOrReject/<@http://localhost:4200/polyfills.js:864:40
invokeTask@http://localhost:4200/polyfills.js:413:35
runTask@http://localhost:4200/polyfills.js:181:51
drainMicroTaskQueue@http://localhost:4200/polyfills.js:583:39
</details>

### Expected behavior

Analytics running

### Actual behavior

Whole app is not running

### Workaround

By adding `(window as any).global = window;` to `polyfill.ts` I can work around the issue for now

**Comment by jamesdaniels** [comment]
Thanks for the heads up, I was planning on moving the caching service to a new `providedIn: 'root'` module so that it's DI too. I'll address shortly.

**Comment by jamesdaniels** [comment]
Fixed in `6.0.0-rc.1`, which is being cut now

**Comment by vandres** [comment]
Thanks, can confirm it works without the polyfill now

**Comment by jamesdaniels** [comment]
Thanks for giving the RC a spin. The feedback is super valuable!
