### ISSUE TITLE
Release notes missing for 5.3.1 and 5.4.0

### ISSUE THREAD

**Issue by swftvsn** [angular/angularfire#2306]
What changed, is it safe to go to production with these changes?

**Comment by sarunint** [comment]
https://github.com/angular/angularfire/releases

**Comment by swftvsn** [comment]
Thanks! I missed that as I thought the changelog.md is the single source of truth.

**Comment by swftvsn** [comment]
Also in case anyone comes looking, the branch is here, and it _does_ contain proper changelog.md https://github.com/angular/angularfire/blob/v5/CHANGELOG.md
