### ISSUE TITLE
`AngularFireAuth.authState` incorrectly uses `onIdTokenChanged`

### ISSUE THREAD

**Issue by sarunint** [angular/angularfire#2307]
### Version info

**Angular:** 8.2.14

**Firebase:** 7.8.0

**AngularFire:** 5.4.0

### How to reproduce these conditions

In #2294, `AngularFireAuth.authState` had been incorrectly refactored to used `auth.onIdTokenChanged`. It should be `auth.onAuthStateChanged`

https://github.com/angular/angularfire/blob/0ae30d8fab06b1457c8492ef0b9dc3cadaad5bbb/src/auth/auth.ts#L50-L52

This only applies to `v5` branch, does not effect `master` branch.

**Comment by jamesdaniels** [comment]
Addressed in `5.4.1`, thanks for the PR!
