### ISSUE TITLE
Blank page renders with AngularFire 5.4.x

### ISSUE THREAD

**Issue by anisabboud** [angular/angularfire#2314]
- `5.3.1` works fine for me with latest Angular 8.3.24 and Firebase 7.8.0.
- When upgrading to `5.4.0` or `5.4.1`, my angular app loads a **blank page**. There are no errors in the terminal/console (and logging auth state and user id is successful), but inspecting the page shows that the `<app-root>` element contains only an empty `<router-outlet>` and no other components were loaded...
- Downgrading back to `5.3.1` works fine again...

Are there any breaking changes in `5.4.0` I should look for? Thanks!

**Comment by jamesdaniels** [comment]
We did a lot of Zone.js work that landed in 5.4, that could be causing trouble. Hmmmm...

**Comment by jamesdaniels** [comment]
I'd say stick with 5.3.1 for now. Are you planning on migrating to ng 9 once it's out? Curious if you'd run into this with AngularFire v6 too, as in theory I rebased all that in...

<img src="https://media2.giphy.com/media/C6JQPEUsZUyVq/source.gif">

If you have an easy repro feel free to share, jamesdaniels@google.com

**Comment by sarunint** [comment]
Might related to #2309

**Comment by jamesdaniels** [comment]
Agreed. I'm taking the problematic share out and running the tests now.

**Comment by jamesdaniels** [comment]
@anisabboud can you check `5.4.2`?

**Comment by anisabboud** [comment]
`5.4.2` works well, thanks @jamesdaniels!

(Yes, I'm planning to upgrade to Angular 9 and AngularFire v6 once it's out.)

**Comment by jamesdaniels** [comment]
Excellent. Don’t hesitate to reach out if you have any trouble with the RC.

**Comment by josejaner** [comment]
what is the latest stable version of firebase and angular that work well with 5.4.2?
- AngularFire: 5.4.2
- Firebase: ?
- Angular: ?

**Comment by jamesdaniels** [comment]
AngularFire 5.4 should work correctly with Angular 8 and any recent Firebase JS SDK version. See peerDependencies in published package.json

**Comment by josejaner** [comment]
latest stable version with angular 8
AngularFire: 5.4.2 Firebase: 7.10.0 Angular: 8.3.25

**but with 9, is any already available?**
