### ISSUE TITLE
[Question] How to build angular 9 universal firebase function

### ISSUE THREAD

**Issue by docaohuynh** [angular/angularfire#2319]
I have follow this guide https://github.com/angular/angularfire/blob/master/docs/universal/getting-started.md but It's not success at all

**Comment by jamesdaniels** [comment]
Those docs haven’t been updated for ng9. We actually have ng deploy capabilities for this coming in with #2305. 

I’d recommend check out that PR while we wrap it up.

**Comment by hiepxanh** [comment]
@docaohuynh  we can try this with old version in here:
[for version 8](https://fireship.io/lessons/angular-universal-firebase/)

can we close this issue?

**Comment by jamesdaniels** [comment]
yeah, gonna close as outdated.
