### ISSUE TITLE
ERROR in node_modules/@angular/fire/angularfire2.d.ts

### ISSUE THREAD

**Issue by Motero69** [angular/angularfire#2321]
Im using Angular 
Angular CLI: 8.3.25
Node: 12.13.1
OS: win32 x64
Angular: 8.2.14

I create i new project and I test it with ng serve, then I install
ng add @angular/fire@next
and implement all imports like is in the documentation. but when I try to run again with ng serve this message came out:
![Nueva imagen de mapa de bits](https://user-images.githubusercontent.com/32316720/74037305-fc46c680-498b-11ea-907a-d7ca368fbc11.jpg)

??

**Comment by Strapazzon** [comment]
I have the same error.😞

**Comment by jamesdaniels** [comment]
Next is meant for angular 9. For angular 8 drop ‘@next’

**Comment by hiepxanh** [comment]
`npm run uninstall @angular/fire -S` then `npm i @angular/fire -S` will work with angular 8. @Motero69 can you try again?

**Comment by fr4nk-dev** [comment]
> `npm run uninstall @angular/fire -S` then `npm i @angular/fire -S` will work with angular 8. @Motero69 can you try again?

Same error, works yout solution but also delete the node_modules folder

**Comment by hiepxanh** [comment]
aww, always have to delete `node_modules` thank you @fr4nk-dev, i forgot that. @Motero69  you should also delete `node_modules` too and delete `package-lock.json` then do `npm i @angular/fire -S`

**Comment by breakingbeats** [comment]
> 

> aww, always have to delete `node_modules` thank you @fr4nk-dev, i forgot that. @Motero69 you should also delete `node_modules` too and delete `package-lock.json` then do `npm i @angular/fire -S`

do everything as you said but have the same error again and again. any other with the same problem?

**Comment by ihorbond** [comment]
@breakingbeats try npm i @angular/fire@5.2.0. Im using Ionic 5 and it ships with angular 8 by default but latest fire v6 package depends on Angular 9 hence the error

**Comment by jamesdaniels** [comment]
closing as outdated, we don't have the capacity to support older versions

**Comment by aleman1997** [comment]
Buenas tengo el mismo error estoy actualizando un proyecto de Angular 10 a Angular 17

![image](https://github.com/angular/angularfire/assets/30096229/1024e0ee-35a5-4003-b5c1-822c224e58e8)
