### ISSUE TITLE
AngularFirestore.createId() is not technically correct.

### ISSUE THREAD

**Issue by magoarcano** [angular/angularfire#2323]
AngularFirestore.createId() generates a new id from a symbolic collection named '_'.  I know that every id will be different, so it won't be a problem to use them in different collections.
But I think is not technically correct to use a generic collection instead of my actual collection. Firebase documentation doesn't propose that idea anywhere. It proposes to use the name of the collection in order to generate the id

Currently code is:
```
/**
   * Returns a generated Firestore Document Id.
   */
  createId() {
    return this.firestore.collection('_').doc().id
  }

```
I propose an optional (or mandatory) parameter 'collectionPath' 
```
/**
   * Returns a generated Firestore Document Id.
   */
  createId(collectionPath='_') {
    return this.firestore.collection(collectionPath).doc().id
  }

```
### Version info

**Angular:** 8.3.20

**Firebase:** 7.7.0

**AngularFire:**
5.3.0

### How to reproduce these conditions

**Steps to set up and reproduce**

this.afs.createId();
returns Id from collection '_'

### Expected behavior
this.afs.createId('collectionPath');

Return a new generated Id related to my real collection.

**Comment by hiepxanh** [comment]
> But I think is not technically correct to use a generic collection instead of my actual collection. Firebase documentation doesn't propose that idea anywhere. It proposes to use the name of the collection in order to generate the id

![image](https://user-images.githubusercontent.com/16970990/74085643-ce59a300-4aad-11ea-9b54-95d80adf6f6d.png)
[firestore/manage-data/add-data](https://firebase.google.com/docs/firestore/manage-data/add-data)
![image](https://user-images.githubusercontent.com/16970990/74085671-1d9fd380-4aae-11ea-9949-d5fad49aa8e9.png)
It's idea behind in this document [best-practices](https://cloud.google.com/firestore/docs/best-practices) 

> Cloud Firestore allocates document IDs using a scatter algorithm.

I belive that it not releav

**Comment by hiepxanh** [comment]
actually, you cannot prove that:
> AngularFirestore.createId() is not technically correct.
because you... :
> But I think is not technically correct to use a generic collection instead of my actual collection.
so they will not change until you prove that you have evident that it performance is effective by `generic collection instead of my actual collection.`

**Comment by magoarcano** [comment]
> Cloud Firestore allocates document IDs using a scatter algorithm.

That algorithm guarantees there are no duplicates, and avoid hotspotting, etc, inside a collection. It's possible the algorithm can be optimized by the path of the collection.
In firebase when you want to generate an id you do it from a document in a real collection, not in a fictitious one.
In Datastore (Firestore predecesor), the path (entity path) was a parameter in order to generate the ids with a similar (or maybe same) algorithm

**Comment by jamesdaniels** [comment]
`AutoId` is not very complex, [as implemented in the JS SDK](https://github.com/firebase/firebase-js-sdk/blob/112e0d78173ded665c5ac2b03c8da564880da6b6/packages/firestore/src/util/misc.ts#L25), see [how it's used when calling `doc()`](https://github.com/firebase/firebase-js-sdk/blob/112e0d78173ded665c5ac2b03c8da564880da6b6/packages/firestore/src/api/database.ts#L2439). It's just a random string and doesn't take the path into consideration at all. Hence using the collection name `_` makes no difference.

If this is a bug, it's either with the documentation or the Firebase JS SDK, so I'll close here. [Can you file an issue on that repo?](https://github.com/firebase/firebase-js-sdk/issues) If they change how ids are calculated I'll consider an API change on AngularFire.

**Comment by JeongJun-Lee** [comment]
AngularFirestore.createId() returns the undefined. AngularFire version is 6.0.0.
