### ISSUE TITLE
functions zone issue

### ISSUE THREAD

**Issue by pgg** [angular/angularfire#2324]
### Version info

**Angular:**
9.0.0
**Firebase:**
7.7.0
**AngularFire:**
5.4.2
**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
node 13.8.0, brave 1.2.43, mac os catalina
### How to reproduce these conditions
call a firebase function with the AngularFireFunctions.httpsCallable and on subscribe navigate to another page with the angular router, console prints that zone is required. Wrapping the navigation call in zone.run works
**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

**Comment by hiepxanh** [comment]
We actually have ng deploy capabilities for this coming in with #2305.

I’d recommend check out that PR while we wrap it up.
