### ISSUE TITLE
getToken also displays the permissions dialog

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angularfire#2328]
### Version info

**Angular:** 9

**Firebase:**7.8.2-0

**AngularFire:**6.0.0-rc.0

### How to reproduce these conditions
As per the docs `this.messaging.getToken` should return the token. As per my understanding it returns current token or if the current token is expired it returns a new token, provided the user has already granted the permissions. This should not automatically display the permissions dialog, and to request the permissions we should use `this.messaging.requestPermission`.

But it seems that `this.messaging.getToken` also displays the permissions dialog if the user has not already granted the permissions.

**Steps to set up and reproduce**

Try calling on a browser where the user has not already enabled the push notification permissions:

```
this.messaging.getToken.subscribe((token) => {

});
```
### Expected behavior

`this.messaging.getToken` should return token if the user has enabled the push notifications and return null if the user has not yet enabled the push notifications. It should not automatically display the permissions dialog.

This would allow us to display our custom UI to ask to permissions before actually displaying the browser permissions dialog.

With previous version (5.x) we first use `this.messaging.getToken` to get token and if it returned `null` we display, our custom permissions dialog box explaining that we would now request permissions and if user selects to enable notifications, we then use `this.messaging.requestPermission` to actually request permissions.

### Actual behavior

`this.messaging.getToken` automatically displays permissions dialog box.

**Comment by naveedahmed1** [comment]
There's also a question about this on StackOverflow but it seems that this is a genuine issue:

Here's the link to Stackoverflow question:

https://stackoverflow.com/questions/59398621/firebase-messaging-can-i-check-if-the-user-already-has-a-token-without-invoking

**Comment by ckeeney** [comment]
I think this issue might need to be raised with firebase.  [`requestPermission` was deprecated](https://firebase.google.com/docs/reference/js/firebase.messaging.Messaging#requestpermission) and I could not find any documentation to get the current token without creating a prompt.

My use case is that I want to show a form of checkboxes for a user to subscribe to topics.  I don't actually need to ask for permission to send notifications until the user has submitted the form with some checkboxes checked.  However it seems that I can't even check if the user has any notifications subscriptions without prompting them for permission.

**Comment by ckeeney** [comment]
I did manage to find my token.  You can find it under the `Application` tab of Chrome dev tools, in the IndexedDB.

I have an IndexedDB store called `firebase-messaging-store` that has a single key.  Stored at this key is, among other things, the token returned from `getToken`.

I'm sure the firebase team prefers you didn't check for the token this way, and the token isn't guaranteed to be valid, but it is there...

**Comment by mateenQureshi** [comment]
Any idea when this is going to be resolved because I just want to receive events & payload and don't want to show desktop notifications. Opening permissions dialogue should be decoupled from `this.angularFireMessaging.requestToken` method.

Angular fire: 6.0.3
Angular: 10.0.8

**Comment by jamesdaniels** [comment]
use `tokenChanges` rather than `getToken`
