### ISSUE TITLE
6.0-rc.1 - Callable function with Cloud Functions emulator not working

### ISSUE THREAD

**Issue by hugovisk** [angular/angularfire#2329]
### Version info

**Angular:** 9.0.2

**Firebase:** 7.8.2

**AngularFire:** 6.0.0-rc.1

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

Point callable Functions to the Cloud Function emulator by adding ORIGIN to the providers section of your NgModule.

...
 constructor(private fns: AngularFireFunctions) { 
    const callable = fns.httpsCallable('my-fn-name');
    this.data$ = callable({ name: 'some-data' });
  }

It works on AngularFire@5.4.2 as described in docs with firebase emulators but in 6.0.0-rc.1 nothing happens, don't call the callable function neither presents any error. 

I didn't find any breaking change in CHANGELOG that needed to be updated in the docs example

### Expected behavior
point to firebase emulators and call the function

### Actual behavior
nothing happens

**Comment by leandroz** [comment]
It returns an observable, so you need to subscribe to it or transform to promise:

```
this.data$ = callable({ name: 'some-data' }).toPromise().then(...).catch(...);
```

**Comment by hugovisk** [comment]
Thank you for the response @leandroz.
