### ISSUE TITLE
[Analytics] Support lazy module without declarations field

### ISSUE THREAD

**Issue by GrandSchtroumpf** [angular/angularfire#2337]
### Version info
**Angular:** 9.0.1
**Firebase:** 7.*.*
**AngularFire:** 6.0.0-rc1
 
### How to reproduce these conditions
- Import `AngularFireAnalyticsModule` in AppModule.
- Lazy load a module without `declarations` field.

### Debug output
Cannot read __annotations__ of undefined

### How to solve
Modify this [line](https://github.com/angular/angularfire/blob/master/src/analytics/analytics.service.ts#L104) :
```typescript
const selectors = [].concat.apply([], declarations.map(...))
```
Becomes :
```typescript
const selectors = [].concat.apply([], (declarations || []).map(...))
```

**Comment by jamesdaniels** [comment]
Thanks for the report! I'll turn a fix around quickly.
