### ISSUE TITLE
Firebase functions not working with Angular 9

### ISSUE THREAD

**Issue by irm4nt45** [angular/angularfire#2338]
Version info

Angular: 9.0.2

Firebase: >= 5.5.7 <8

AngularFire: ^2.3.0

How to reproduce these conditions

Failing test unit, Plunkr, or JSFiddle demonstrating the problem

```
[info] i  hosting: Serving hosting files from: dist/spincrew/browser
[info] ✔  hosting: Local server: http://localhost:5000
[debug] [2020-02-27T16:02:43.943Z] [runtime-status] [2790] Functions runtime initialized. {"cwd":"/home/dell/Documents/pokercrew/spincrew/functions","node_version":"12.13.1"}
[debug] [2020-02-27T16:02:43.944Z] [runtime-status] [2790] Disabled runtime features: {"functions_config_helper":true,"network_filtering":true,"timeout":true,"memory_limiting":true,"admin_stubs":true,"pubsub_emulator":true}
[debug] [2020-02-27T16:02:43.946Z] [runtime-status] [2790] Resolved module firebase-admin {"declared":true,"installed":true,"version":"8.9.2","resolution":"/home/dell/Documents/pokercrew/spincrew/functions/node_modules/firebase-admin/lib/index.js"}
[debug] [2020-02-27T16:02:43.946Z] [runtime-status] [2790] Resolved module firebase-functions {"declared":true,"installed":true,"version":"3.3.0","resolution":"/home/dell/Documents/pokercrew/spincrew/functions/node_modules/firebase-functions/lib/index.js"}
[debug] [2020-02-27T16:02:43.947Z] [runtime-status] [2790] Resolved module firebase-functions {"declared":true,"installed":true,"version":"3.3.0","resolution":"/home/dell/Documents/pokercrew/spincrew/functions/node_modules/firebase-functions/lib/index.js"}
[warn] ⚠  Error: Cannot find module '/home/dell/Documents/pokercrew/spincrew/functions/dist/spincrew/server'
Require stack:
- /home/dell/Documents/pokercrew/spincrew/functions/lib/index.js
- /usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/dell/Documents/pokercrew/spincrew/functions/lib/index.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
[warn] ⚠  We were unable to load your functions code. (see above)
   - It appears your code is written in Typescript, which must be compiled before emulation.
   - You may be able to run "npm run build" in your functions directory to resolve this.
[debug] [2020-02-27T16:02:44.003Z] [worker-~diagnostic~-efe3d384-d9e1-40f7-9c5a-31bc8a13088a]: exited
[debug] [2020-02-27T16:02:44.003Z] [worker-~diagnostic~-efe3d384-d9e1-40f7-9c5a-31bc8a13088a]: FINISHED
```

Steps to set up and reproduce

"private": true,
  "dependencies": {
    "@angular/animations": "~9.0.2",
    "@angular/cdk": "^9.1.0",
    "@angular/common": "~9.0.2",
    "@angular/compiler": "~9.0.2",
    "@angular/core": "~9.0.2",
    "@angular/fire": "^5.4.2",
    "@angular/forms": "~9.0.2",
    "@angular/material": "^9.1.0",
    "@angular/platform-browser": "~9.0.2",
    "@angular/platform-browser-dynamic": "~9.0.2",
    "@angular/platform-server": "~9.0.2",
    "@angular/router": "~9.0.2",
    "@nguniversal/express-engine": "^9.0.1",
    "angularfire": "^2.3.0",
    "body-parser": "^1.19.0",
    "domino": "^2.1.4",
    "express": "^4.15.2",
    "firebase": ">= 5.5.7 <8",
    "nodemailer": "^6.4.3",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
Sample data and security rules

{
  "functions": {
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run lint",
      "npm --prefix \"$RESOURCE_DIR\" run build"
    ],
    "source": "functions"
  },
  "hosting": {
    "public": "dist/spincrew/browser",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "function": "ssr"
      }
    ]
  }
}

Debug output

![imgggg](https://user-images.githubusercontent.com/46350008/75463029-de1e2600-598d-11ea-936d-6b805eb30b16.jpg)

### Expected behavior

Firebase functions are not working with Angular 9. Maybe I am missing something and same corrections to the project must be done before deploying Angular 9 + Universal + Firebase 

Actual behavior
Firebase hosting works fine except Firebase functions.

**Comment by Ismaestro** [comment]
Same here!!

**Comment by Splaktar** [comment]
What command are you running? The emulator? or `ng deploy`?

**Comment by Ismaestro** [comment]
In my case, `ng deploy`.

**Comment by Josee9988** [comment]
Same here with angular 9!

**Comment by jamesdaniels** [comment]
Things should be better supported with newer versions of the libraries, closing as stale.
