### ISSUE TITLE
RemoteConfig observable runs outside Angular context

### ISSUE THREAD

**Issue by andresandoval** [angular/angularfire#2342]
### Version info

**Angular:**
~9.0.3
**Firebase:**
^7.8.0
**AngularFire:**
^6.0.0-rc.1
**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
Node v12.13.0, Google Chrome v80.0.3987.122, Win10Pro
### How to reproduce these conditions

Calling the firebase remote config string funcion with a subscribe method gets the rigth value from the firebase remote config, but when its assigned to a local property of the component and printed in html it doesnt shows;

console log in subscribe prints the value retrieved.

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**
none

**Steps to set up and reproduce**

app.component.ts
```
export class AppComponent implements OnInit {
  public value: any;

  constructor(private readonly remoteConfig: AngularFireRemoteConfig) {
  }

  public ngOnInit(): void {
    this.remoteConfig.strings.someValue
      .subscribe(val => {
        this.value = val; //  this.value is updated but not showed in HTML
        console.log(this.value); //  console.log prints the value in console
      });
  }
}
```

app.component.html
```
<!--No value is shown-->
{{value}} 
```

**Sample data and security rules**

none

### Debug output

javascript console log prints the value stored in Firebase Remote Config

** Errors in the JavaScript console **

none

** Output from `firebase.database().enableLogging(true);` **

none

** Screenshots **

none

### Expected behavior

If you force to include this action in the angular context zone it works as expected:

```
export class AppComponent implements OnInit {
  public value: any;

  constructor(private readonly remoteConfig: AngularFireRemoteConfig,
              private readonly zone: NgZone) {
  }

  public ngOnInit(): void {
    this.remoteConfig.strings.someValue
      .subscribe(val => {
        this.zone.run(() => {
          this.value = val; // value is updated
        });
      });
  }
}
```

Value should be added to te Angular Digenst Cicle and no manual update should be required

### Actual behavior

Manual update is required to include component change in context

**Comment by jamesdaniels** [comment]
This should be addressed as of a recent patch
