### ISSUE TITLE
[Question] Are the docs hosted online?

### ISSUE THREAD

**Issue by codex-zaydek** [angular/angularfire#2343]
Not sure if this is the right place to ask this question, but I haven’t found an answer so far.

Is [this](https://github.com/angular/angularfire/tree/master/docs) the official way to read the docs? Are the docs hosted on a dedicated website or just stored as markdown files as a part of this repo?

👉 https://github.com/angular/angularfire/tree/master/docs

Thank you.

**Comment by jamesdaniels** [comment]
They are part of this repo, yes, the two entry points we have designed for are https://firebaseopensource.com/projects/angular/angularfire2/ and the main REAME on the github root. We have a getting start doc coming to the official docsite which will be much like [the Flutter getting started](https://firebase.google.com/docs/flutter/setup) and a versioned API reference site that will be going live soon.

**Comment by aakash14goplani** [comment]
@jamesdaniels - URL https://firebaseopensource.com/projects/angular/angularfire2/ is not working as on 03/17/22 19.42 PM IST. Any known issues?
