### ISSUE TITLE
Send data from setBackgroundMessageHandler to any component in Angular 9

### ISSUE THREAD

**Issue by biswajitsamal59** [angular/angularfire#2344]
I want to send notification message data from setBackgroundMessageHandler() function to app component in Angular 9. I am using @angular/fire(5.4.0) and firebase(7.6.0) libraries. Can anyone please help me.

**Comment by Xepe** [comment]
did you find a solution ? I am looking for the same

**Comment by jamesdaniels** [comment]
Closing as outdated. Firebase v8 made this easier.

**Comment by rajhim** [comment]
Is there a way in angular 8 , firebase 7 , angular fire ^5.2.3 for above question?

I cant upgrade angular version. Help me out anyone .

thankyou.
