### ISSUE TITLE
Received Token is null very often

### ISSUE THREAD

**Issue by ChristianBathe** [angular/angularfire#2345]
Hello,
i'm using AngularFireMessaging for an angular application to register users for push-notifications.
Basically this is working. I can accept notifications in my browser and receive push-notifications.
It's an public application: www.pflege-kleinanzeigen.de .

Somehow ca. 50% of the tokens i get from firebase are null and i don't know why because basically it is working fine.

May it be possible that plugins like Privacy Badger, AdBlockers or firewalls can filter out the tokens?

Thanks in advance for your ideas!

### Version info

**Angular:** 6.1.10

**Firebase:** 5.11.1

**AngularFire:** 5.4.2
 
### How to reproduce these conditions

**Application Code**
**app.component.ts:**
...
import { PushNotificationService } from './services/push-notification.service';
....
  ngOnInit(): void {
    this.userCategoryService.loadData(); // Kein Login nötig

    if (this.authenticationService.isLoggedIn()) {
      this.userService.loadCurrentUser();

      this.subscriptions.add(this.messageService.unreadMessageCount.subscribe(unreadMessageCount => {
        this.unreadMessageCount = unreadMessageCount;
      }));
    }

    this.initFirebaseCloudMessaging();
  }

  initFirebaseCloudMessaging() {
    const guid = this.authenticationService.getCurrentFirebaseGuid();
    this.pushNotificationService.requestPermission(guid);
    // Token kann sich ändern.
    this.pushNotificationService.tokenChanges(guid);
    this.pushNotificationService.receiveMessage();
    this.message = this.pushNotificationService.currentMessage;
  }
....

**push-notification.service.ts:**

import { Injectable } from '@angular/core';
import { AngularFireMessaging } from '@angular/fire/messaging';
import { BehaviorSubject } from 'rxjs';
import { HttpService } from './http.service';

@Injectable()
export class PushNotificationService {

    currentMessage = new BehaviorSubject(null);

    constructor(
        private httpService: HttpService,
        private angularFireMessaging: AngularFireMessaging) {
        this.angularFireMessaging.messaging.subscribe(
            (_messaging) => {
                _messaging.onMessage = _messaging.onMessage.bind(_messaging);
                _messaging.onTokenRefresh = _messaging.onTokenRefresh.bind(_messaging);
            }
        );
    }

    /**
     * request permission for notification from firebase cloud messaging
     */
    requestPermission(guid: string) {
        this.angularFireMessaging.requestToken.subscribe(
            async (token) => {
                console.log(token);
                if (token == null) {
                    this.getToken(guid);
                } else {
                    await this.httpService.createFirebaseToken(guid, token); // token + guid in DB speichern
                    await this.httpService.log('requestPermission', 'push-notification.service', guid + ' - ' + JSON.stringify(token), '');
                }
            },
            (err) => {
                console.error('Unable to get permission to notify.', err);
            }
        );
    }

    async getToken(guid: string) {
        let counter = 0;
        let token = null;
        // 3 Mal mit 3 Sekunden Abstand wiederholen --> Token zu Beginn oft null
        while (counter < 3 && token == null) {
            counter++;
            await this.delay(3000);
            this.angularFireMessaging.getToken.subscribe(
                async (firebaseToken) => {
                    token = firebaseToken;
                    await this.httpService.createFirebaseToken(guid, firebaseToken); // token + guid in DB speichern
                    await this.httpService.log('getToken', 'push-notification.service', guid + ' - ' + JSON.stringify(token), '');
                },
                (err) => {
                    console.error('Fehler bei getToken.', err);
                }
            );
        }
    }

    tokenChanges(guid: string) {
        this.angularFireMessaging.tokenChanges.subscribe(
            async (token) => {
                if (token != null) {
                    await this.httpService.createFirebaseToken(guid, token); // token + guid in DB speichern
                    await this.httpService.log('tokenChanges', 'push-notification.service', guid + ' - ' + JSON.stringify(token), '');
                }
            },
            (err) => {
                console.error('Fehler bei tokenChanges.', err);
            }
        );
    }

    /**
     * hook method when new notification received in foreground
     */
    receiveMessage() {
        this.angularFireMessaging.messages.subscribe(
            (payload) => {
                console.log('new message received. ', payload);
                this.currentMessage.next(payload);
            });
    }

    delay(ms: number) {
        return new Promise(resolve => setTimeout(resolve, ms));
    }
}

As you can see in the getToken()-Method, I am logging all received tokens even if they are null.
In that logging-table i can see those null-tokens too. 
So this.angularFireMessaging.getToken.subscribe(...) does not throw an error. 
The Repeat-Loop does not help so it not a timing issue.

### Debug output

** Screenshots **
I save all tokens to a database table.
The blacked out tokens are the correct ones.
I can't see a pattern here. 
At this moment 217 tokens of 454 are not null.
![image](https://user-images.githubusercontent.com/8076429/76142072-755c3b00-606a-11ea-91ac-3918ec9999a8.png)

### Expected behavior

All received tokens have a value which is not null.

### Actual behavior

More than 50% of the tokens are null.

**Comment by jamesdaniels** [comment]
I've cleaned up the token observable in `6.1.0-rc.2` should be acting as best as it can for now.
