### ISSUE TITLE
Logout user on delete

### ISSUE THREAD

**Issue by ix-xerri** [angular/angularfire#2346]
I'm using `"@angular/fire": "^5.2.3"` with ` "@ionic/angular": "^5.0.1"`. I'm monitoring the auth with

`this.afAuth.idTokenResult.pipe(takeUntil(this.unsubscribe$)).subscribe((token: IdTokenResult) => {	});`

If I delete the user form the firebase console, there is not update to the observable to the user is not shown as logged out.

I tried it with `this.afAuth.authState.subscribe((token)=>{})` as well.

**Comment by jamesdaniels** [comment]
Firebase authentication is stateless and does not have realtime capabilities. After account deletion their JWT will expire within the hour, at that point the SDK will be unable to refresh their credentials, and they will be logged out.
