### ISSUE TITLE
ng add @angular/fire@next ?

### ISSUE THREAD

**Issue by mackelito** [angular/angularfire#2349]
Should really the default be to install `ng add @angular/fire@next` ?
I mean.. should the docs really suggest to install an rc?

I would recommend to just use `ng add @angular/fire`

**Comment by jamesdaniels** [comment]
I think that's covered in the warning `WARNING: Master branch is the work in progress for version 6 of AngularFire. You can find version 5 here, if you're looking for documentation or to contribute to stable. Learn more about the road toward version 6 here.`

Once we have v6 stable and support Angular 9 fully on `@latest` we'll drop `@next` from the instructions.

**Comment by jamesdaniels** [comment]
I made this call because I figure most people who will be calling `ng add` are using Angular 9.
