### ISSUE TITLE
auth/invalid-credential - Facebbok PopUpLogin

### ISSUE THREAD

**Issue by Karman40** [angular/angularfire#2359]
### Version info

```
    "@angular/core": "^9.0.6",
    "@angular/fire": "^5.4.2",
    "firebase": "^7.11.0",
```
**Other:** web

### Debug output

** Errors in the JavaScript console **
`auth/invalid-credential`

`Error getting access token from facebook.com, OAuth2 redirect uri is: https://konigs-art-kft-dev.firebaseapp.com/__/auth/handler, response: OAuth2TokenResponse{params: error=OAuthException&error_description=The%20request%20is%20invalid%20because%20the%20app%20is%20configured%20as%20a%20desktop%20app, httpMetadata: HttpMetadata{status=400, cachePolicy=NO_CACHE, cacheDurationJava=null, cacheImmutable=false, staleWhileRevalidate=null, filename=null, lastModified=null, headers=HTTP/1.1 200 OK , contentSecurityPolicies=[], cookieList=[]}}
`

**Comment by paridao** [comment]
Hi @Karman40 ,
did you resolved?
Could you share the solution?
Thanks

**Comment by paridao** [comment]
Resolved.
Open your app at developers.facebook.com and go to Settings > Advanced and make sure Native or desktop app? is set to No
