### ISSUE TITLE
Load Firebase SDKs from reserved URLs

### ISSUE THREAD

**Issue by JuanSeBestia** [angular/angularfire#2360]
I am fascinated to configure the api_keys from firebase hosting, see (https://firebase.google.com/docs/hosting/reserved-urls?authuser=3)

### Version info

**Angular:** ~8.2.9

**Firebase:** ^7.8.0

**AngularFire:** 5.4.2

### How to reproduce these conditions

Tring initialization with empty props 

### Expected behavior

`AngularFireModule.initializeApp()`

### Actual behavior

`AngularFireModule.initializeApp(environment.firebase)`

**Comment by eqinox76** [comment]
I am also struggling on how to get this to work with angularfire.

So far i have been unable to use the given example
```js
fetch('/__/firebase/init.json').then(async response => {
  firebase.initializeApp(await response.json());
});
```

As i cannot get the async fetch to work well with the initialisation of my @NgModule imports or somehow initialize Firebase lazy.

**Comment by JuanSeBestia** [comment]
Ohhh but also you can import JSON like another file in ES6.

interesting...

**Comment by eqinox76** [comment]
Well i did not manage to load the init.json from external before importing the module like shown in the [setup guide](https://github.com/angular/angularfire/blob/master/docs/install-and-setup.md#4-setup-ngmodule-for-the-angularfiremodule). Any hints?

**Comment by eqinox76** [comment]
Today my google-fu is better! yruzyui solved it on [stackoverflow](https://stackoverflow.com/questions/56431192/inject-default-firebase-config-into-angular-app).
I think this ticket can be closed. Maybe a pointer in the getting started guide would be helpful.

**Comment by jamesdaniels** [comment]
Thanks for reporting this, I'll keep this issue open as I'd rather not promote the practice at this time. I have a better solution in mind for an upcoming release.

**Comment by jamesdaniels** [comment]
We'll be using __init.json in a future release, closing this as we don't plan on loading the SDKs using this method.

**Comment by tzkmx** [comment]
For anyone that could be of help as I was struggling with the global firebase object conflicting with the initialized by reserved URL, the method in that old response in SO is not working: 

> Today my google-fu is better! yruzyui solved it on [stackoverflow](https://stackoverflow.com/questions/56431192/inject-default-firebase-config-into-angular-app). I think this ticket can be closed. Maybe a pointer in the getting started guide would be helpful.

I managed to provide that statically initialized module with a little bit of tweaking and a new extraProvider:

```ts
(async () => {
  const firebaseConfig = await getFirebaseConfig();
  const firebaseModule = AngularFireModule.initializeApp(firebaseConfig);

  platformBrowserDynamic([
    { provide: FIREBASE_OPTIONS, useValue: firebaseConfig },
    { provide: AngularFireModule, useValue: firebaseModule }
  ])
    .bootstrapModule(AppModule)
    .catch(console.error);
})();
```

**Comment by jainut20** [comment]
How can we do the auth module and the firestore module ?

ERROR Error: Uncaught (in promise): Error: Component auth has not been registered yet
Error: Component auth has not been registered yet

I get the above error with the given code

> For anyone that could be of help as I was struggling with the global firebase object conflicting with the initialized by reserved URL, the method in that old response in SO is not working:
> 
> > Today my google-fu is better! yruzyui solved it on [stackoverflow](https://stackoverflow.com/questions/56431192/inject-default-firebase-config-into-angular-app). I think this ticket can be closed. Maybe a pointer in the getting started guide would be helpful.
> 
> I managed to provide that statically initialized module with a little bit of tweaking and a new extraProvider:
> 
> (async () => {
>   const firebaseConfig = await getFirebaseConfig();
>   const firebaseModule = AngularFireModule.initializeApp(firebaseConfig);
> 
>   platformBrowserDynamic([
>     { provide: FIREBASE_OPTIONS, useValue: firebaseConfig },
>     { provide: AngularFireModule, useValue: firebaseModule }
>   ])
>     .bootstrapModule(AppModule)
>     .catch(console.error);
> })();
