### ISSUE TITLE
Credentials are kept after sign out

### ISSUE THREAD

**Issue by varogonz95** [angular/angularfire#2363]
### Version info

**Angular:** 8.0.1

**Firebase:** 7.5.0

**AngularFire:** 5.2.3

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

```ts
​import​ { ​Component​, ​OnInit​ } ​from​ ​'​@angular/core​'​;
​import​ { ​AngularFireAuth​ } ​from​ ​'​@angular/fire/auth​'​;
​import​ { ​auth​ } ​from​ ​"​firebase/app​"​;

@​Component​({
        selector: ​'​login-page​'​,
        templateUrl: ​'​./login-page.component.html​'​,
        styleUrls: [​'​./login-page.component.css​'​]
})
​export​ ​class​ ​LoginPageComponent​ ​implements​ ​OnInit​ {

        ​private​ authProvider​:​ ​auth​.​GoogleAuthProvider​

        ​constructor​(​private​ ​authService​:​ ​AngularFireAuth​) {
                ​this​.​authProvider​ ​=​ ​new​ ​auth​.​GoogleAuthProvider​()
        }

        ngOnInit() {
        }

        ​async​ signIn() {
                ​await​ ​this​.​authService​.​auth​.​signInWithRedirect​(​this​.​authProvider​)
        }

        ​async​ signOut() {
                ​await​ ​this​.​authService​.​auth​.​signOut​()
        }
}
```
**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

### Expected behavior

 Show Google credentials form every time a sign in attempt occurs

### Actual behavior

After signing-out, I attempt to sign in again and it directly validates the last user credentials, no Google credentials form, no Google Account selection, no nothing. It just signs in my last used credentials right away. 
Is this a normal behavior? How can I make fireauth always display Google credentials form when trying to sign in, as it showed up the first time?

**Comment by LeftOfHere** [comment]
this drove me mostly insane the last couple of hours. Here you go.
https://stackoverflow.com/a/44987801

basically just add this
```
googleAuthProvider.setCustomParameters({
   prompt: 'select_account'
})
```
It forces the prompt to always show.

**Comment by varogonz95** [comment]
This did the trick, thanks
