### ISSUE TITLE
AngularFireAuthGuards kill change detection for Angular 9.1.0 lazy loaded routes when navigating to a protected route

### ISSUE THREAD

**Issue by jahumes** [angular/angularfire#2367]
### Version info

```json
{
  "dependencies": {
    "@angular/animations": "9.1.0",
    "@angular/cdk": "^9.2.0",
    "@angular/common": "9.1.0",
    "@angular/compiler": "9.1.0",
    "@angular/core": "9.1.0",
    "@angular/fire": "^6.0.0-rc.1",
    "@angular/forms": "9.1.0",
    "@angular/material": "^9.2.0",
    "@angular/platform-browser": "9.1.0",
    "@angular/platform-browser-dynamic": "9.1.0",
    "@angular/router": "9.1.0",
    "@nrwl/angular": "9.1.4",
    "core-js": "^2.5.4",
    "firebase": "^7.8.0",
    "moment": "^2.24.0",
    "ngx-toastr": "^12.0.0",
    "normalizr": "^3.6.0",
    "rxjs": "~6.5.0",
    "zone.js": "^0.10.2"
  }
}
```

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
node version 12.16.0
operating system mac

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

You may clone this repo (https://github.com/jahumes/angular-fire-error) and run/build the Angular app

**Steps to set up and reproduce**

Steps to reproduce the error:

1. Download app and install dependencies
2. Run `npm run start`
3. Visit `http://localhost:4205/auth/login`
4. Login to the app
5. Verify the app through the email link
6. Notice the change detection for the form at `http://localhost:4205/testing/page` is working correctly by clicking into the Name field and seeing the label get smaller and float to the top
7. Refresh the page
8. Now when you click into the Name field, the label gets smaller. To see it is change detection, you can open the dev inspector in Chrome, select the `<mat-form-field>` in the elements tab and type `ng.applyChanges(ng.getComponent($0))` into the console. You will see the label change.

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **
None

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

### Expected behavior

Change detection should be working

### Actual behavior

It is like change detection has been changed to be on push.

**Comment by jahumes** [comment]
I have found a related issue. Please see (#2367)

**Comment by jamesdaniels** [comment]
RC 2 has been released which includes the Zone fix.

**Comment by jahumes** [comment]
Thanks!

**Comment by yinonov** [comment]
could this also affect the lifecycle events of components? whenever I place canActivate: [AngularFireAuthGuard] on lazy module, it disables the lifecycle events. took me 2 days to figure this out
