### ISSUE TITLE
AngularFireStorage upload multiple files setup

### ISSUE THREAD

**Issue by weilies** [angular/angularfire#2373]
### Version info

**Angular:** 9.0.7

**Firebase:** 7.12

**AngularFire:** 5.4.2

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** Using StackBlitz

It's not really an error but i stuck because there isn't any documentation i able to reference.
I am feeling great with the example and i managed to make the example code work.

But i hit a roadblock because i need multiple upload within a page, and i am not able to make it an ARRAY with adding [] as below

  uploadPercent: Observable<number[]>;
  downloadURL: Observable<string[]>;

it just doesn't work... could anyone share a working example? Thanks a lot.

Regards,
Weilies

**Comment by jamesdaniels** [comment]
you need to use rxjs merge/concat for this
