### ISSUE TITLE
ERR_CERT_COMMON_NAME_INVALID error after initializing AngularFireAnalyticsModule

### ISSUE THREAD

**Issue by metalllus** [angular/angularfire#2374]
Version info
Angular: 9.0.0
Firebase: 7.8.1
AngularFire: 5.4.2

After adding the AngularFireAnalyticsModule to the app module I get this message in the browser console: 

GET https://www.googletagmanager.com/gtag/js?l=dataLayer net::ERR_CERT_COMMON_NAME_INVALID

The analytics work fine I have no issues but this error message bugs me.
How do I get rid of this?

**Comment by jamesdaniels** [comment]
Are you using some kind of content blocker for privacy? Can you test in a private browser session?

**Comment by jamesdaniels** [comment]
Closing as stale
