### ISSUE TITLE
[Breaking change] AngularFireStoreReference getMetadata() doesn't return anything

### ISSUE THREAD

**Issue by ioaNikas** [angular/angularfire#2375]
### Version info

**Angular:** 9.1

**Firebase:** 7.15.0

**AngularFire:** 6.0.0-rc.2

**Node:** 10

### How to reproduce these conditions

AngularFireStore works fine and my image is uploaded in the right place. Problem is that I can't access anymore the metadata of it with `getMetadata()` from AngularFireStorageReference.

I noticed that change in the last update :

from
```
getMetadata: () => from(ref.getMetadata()).pipe(
      observeOn(schedulers.outsideAngular),
      switchMap(() => ref.getMetadata()),
      keepUnstableUntilFirst
),
```

to
```
getMetadata: () => of().pipe(
      observeOn(schedulers.outsideAngular),
      switchMap(() => ref.getMetadata()),
      keepUnstableUntilFirst
),
```

And here it is how I use it right now in my code
```
goToShow() {
  this.url$ = this.ref.getDownloadURL();
  combineLatest([this.url$, this.ref.getMetadata()])
    .subscribe(([url, meta]) => {
      this.uploaded(createImgRef({
        url,
        ref: meta.fullPath,
        originalFileName: this.originalFileName,
      }));
      this.nextStep('show');
    })
}
```
Tried to do `this.ref.getMetadata().subscribe(console.log())` but nothing is showing in the console.
Am I missing something ?

**Comment by jamesdaniels** [comment]
I'll look into this later today, thanks for helping test the RC.

**Comment by vandres** [comment]
Can confirm this bug is also in the released 6.0. It was working with -rc.1

**Comment by GrandSchtroumpf** [comment]
Maybe it comes from [this change](https://github.com/angular/angularfire/commit/d91965ed9e9b3918387a40c8bf5b2c3ab604054d#diff-b13c035e0a19ed5d8957203b9ca4fe29R30). 
Would you recommand a workaround in the meantime ?

**Comment by Benny739** [comment]
Anybody found a workaround or is the only solution to use RC1 atm?

**Comment by N-Andronopoulos** [comment]
You can do something like that:
```
 this.firebaseStorage.storage.ref(path).getMetadata()
      .then(meta => meta.customMetadata);
```

**Comment by uncvrd** [comment]
I can confirm that I'm also seeing this on `@angular/fire: ^6.0.0` when attempting to do the following:

```
const transcodeObs = fileRef.getMetadata().pipe(
        tap((x) => console.log(x)),
        switchMap((metadata) => {
          return this.transcodeService.transcode$({
            readPath: metadata.fullPath
          })
        })
      )
```

**Comment by Diex** [comment]
same here:

combineLatest([
            this.storage.ref(this.path + fileItem.fileName).getMetadata(),
            this.storage.ref(this.path + fileItem.fileName).getDownloadURL(),
          ])
            .pipe(
              map(url => {
                console.log(url[0]);
                console.log(url[1]);
                return url[0];
              }));

**Comment by IvanBean** [comment]
Same issue on 6.0.0

**Comment by weilies** [comment]
> You can do something like that:
> 
> ```
>  this.firebaseStorage.storage.ref(path).getMetadata()
>       .then(meta => meta.customMetadata);
> ```

How to 'import' the code before we could execute this.firebaseStorage.storage...?

Thanks for the pointer

**Comment by Benny739** [comment]
in 6.0.2 this appears to be working again
