### ISSUE TITLE
Add migration schematic from v5 to v6

### ISSUE THREAD

**Issue by EdricChan03** [angular/angularfire#2379]
### Version info

**Angular:** v9

**Firebase:** v7.13.0

**AngularFire:** N.A.

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** N.A.

### Expected behavior

There is no migration schematic that is invoked when the `ng update @angular/fire` command is entered.

### Actual behavior

There should be a migration schematic that is invoked when the `ng update @angular/fire` command is entered.

---

Related: #2267

**Comment by jamesdaniels** [comment]
Ah, yes, I knew there was something else I was hoping to put together before launch. Will put a schematic together in the next cut.

**Comment by jamesdaniels** [comment]
Closing as outdated, never did get around to this unfortunately.
