### ISSUE TITLE
Can't generate app-shell

### ISSUE THREAD

**Issue by intencje** [angular/angularfire#2380]
### Version info
Angular: v9.1
Firebase: v7.13.1
AngularFire: v6.0.0

### Expected behavior
Command `ng run my-app:app-shell:production`should generate app-shell as described here: https://angular.io/guide/app-shell

### Actual behavior
On fresh Angular install with AngularFire@6.0.0 we get console error:

Unhandled Promise rejection: package.json does not exist at /Users/test/my-app/dist/my-app/package.json ; Zone: <root> ; Task: Promise.then ; Value: Error: package.json does not exist at /Users/test/my-app/dist/my-app/package.json

**Comment by jamesdaniels** [comment]
You'll need to add `@firebase/firestore` into `externalDependencies` in your `angular.json`'s server options. The way that package is built now doesn't work well with ngcc's bundling.
