### ISSUE TITLE
Upgrading to 6.0: FirebaseFunctions

### ISSUE THREAD

**Issue by swftvsn** [angular/angularfire#2382]
Hi,

Earlier we could do
`this._project1Functions.functions.httpsCallable`
to obtain raw promise based callable and it was really handy. Now I need to do 

`this._project1Functions.httpsCallable('name')({}).pipe(take(1)).toPromise`
which essentially converts the promise based to observable and then back to promise again.

Can we have the handy access back?

Also, I can't seem to pass timeout parameter anywhere?

**Comment by swftvsn** [comment]
Hi, just checking if you can give any estimates when you can work on these things again? Maybe during summer, or perhaps during fall? @jamesdaniels

**Comment by swftvsn** [comment]
Hi, just checking here, @jamesdaniels , any hope to get this done by the end of the year?

**Comment by jamesdaniels** [comment]
No plan for this at the moment.

**Comment by abierbaum** [comment]
@swftvsn Did you ever find a way around this.  The "normal" firebase method of using promises is so much easier to use in application code.  (unless I am missing something)

**Comment by swftvsn** [comment]
We gave in and started to use the `.pipe(take(1)).toPromise` way to do it. I have no idea why promise based access is not endorsed in this area, as an http request is perfectly modelled like Promise, not an Observable.

If the answer is simply that Angular Fire uses only promises as so does Angular itself, it would be nice to hear. 

Maybe they plan to route some streaming functions later (cloud run already supports web sockets etc., which cloud functions are built on.)? As we have no official say, I have nothing but guesses to offer.
