### ISSUE TITLE
Upgrading to 6.0 What to use instead of runInZone

### ISSUE THREAD

**Issue by swftvsn** [angular/angularfire#2383]
We're using rxfire directly in couple of places and were using runInZone also, but now that is gone - what can we use instead of that?

**Comment by jamesdaniels** [comment]
My plan is to release a pipe in 6.1 that will do all the zone wrapping / unwrapping enabled by the internal `ɵAngularFireSchedulers` class and `ɵBlockUntilFirstOperator`. I should have an unstable API available in 6.0.1 for internal use / testing.

**Comment by swftvsn** [comment]
Awesome! I also need it in a setting where I'm subscribing myself inside component - does that cover that case too?

**Comment by swftvsn** [comment]
Hi, just checking if you can give any estimates when you can work on these things again? Maybe during summer, or perhaps during fall? @jamesdaniels

**Comment by swftvsn** [comment]
Hi, just checking here, @jamesdaniels , any hope to get this done by the end of the year?

**Comment by jamesdaniels** [comment]
Feel free to use the internal APIs here, I'm not planning any major changes; but not planning to officially support this for a while yet.
