### ISSUE TITLE
functions zone issue

### ISSUE THREAD

**Issue by pgg** [angular/angularfire#2384]
### Version info

**Angular:**
9.1.0
**Firebase:**
7.13.1
**AngularFire:**
6.0.0
**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
chrome 80.0.3987.162, macOS Catalina 10.15.3
### How to reproduce these conditions
call a firebase function with the AngularFireFunctions.httpsCallable and on subscribe open any angular material popup i.e MatSnackBar, the snackbar renders top left, then center after clicked, and not all clicks are captured. Works when run inside zone, this.zone.run(() => this.snack.open('works'))

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

**Comment by pgg** [comment]
likely related to #2324

**Comment by segevsh** [comment]
I second that. There is an issue. When I subscribe to the observable and manually call `detectChanges()` (ChangeDetectorRef), changes to reflect on the page.

**Comment by rharter** [comment]
I think this is fixed [here](https://github.com/angular/angularfire/pull/2522/files#diff-e7e0d8817dc489d9fb79a1433858d66dR55).

**Comment by rharter** [comment]
For some more context, I've run into issues which require me to manually detect changes when I observe results of callable functions.  This still seems to be unreliable.

I've updated my code by copying over a simple [ZoneScheduler](https://github.com/angular/angularfire/blob/master/src/core/angularfire2.ts#L22-L45) and piping the called function observable through it using `observeOn`, and it resolves the issues.

```typescript
class ZoneScheduler implements SchedulerLike {
  constructor(private zone: any) {
  }
  now(): number {
    return asyncScheduler.now();
  }
  schedule<T>(work: (this: SchedulerAction<T>, state?: T) => void, delay?: number, state?: T): Subscription {
    const targetZone = this.zone
    const workInZone = function(this: SchedulerAction<any>, state?: any) {
      targetZone.runGuarded(() => {
        work.apply(this, [state])
      })
    }
    return asyncScheduler.schedule(workInZone, delay, state);
  }
}

export class ProfileService {

  private readonly inAngularScheduler: SchedulerLike

  constructor(
    private functions: AngularFireFunctions,
    private zone: NgZone
  ) {
    this.inAngularScheduler = new ZoneScheduler(zone)
  }

  getProfileEmailAddress(id): Observable<string> {
    const callable = this.functions.httpsCallable(`getUserEmail`)
    return callable({uid: id}).pipe(observeOn(this.inAngularScheduler))
  }
}
```

**Comment by jamesdaniels** [comment]
Functions should now be working in the zone correctly as of a recent patch.
