### ISSUE TITLE
authState subscription does not fire on 6

### ISSUE THREAD

**Issue by doczoidberg** [angular/angularfire#2393]
I migrated to 6.0 and now my browser hangs.

Seems that authState subscription does not fire:

```
 this.afAuth.authState.subscribe(x => {
        console.log("authstate : ", x); // never executes
}
```

what canI do?

**Comment by jamesdaniels** [comment]
Interesting, can you share more, I'm unable to reproduce these problems. `.user` is having troubles with Zone.js but `.authState` seems to be working fine.

Can you share more about your versions and environment?

**Comment by doczoidberg** [comment]
I think my Authgard caused the hang

**Comment by s3ppo** [comment]
hi i have a similar problem on my ionic build.. the strange thing is that it is working perfect on iphone and android, but not on ipad.. can there be differences on platforms?

**Comment by chan-dev** [comment]
any update on this one?
`user`, `onAuthChanged` or `authState` doesn't listen to auth changes at all.
