### ISSUE TITLE
requestToken not updating component property in success or error callback

### ISSUE THREAD

**Issue by alishahzadone** [angular/angularfire#2396]
### Version info

**Angular:** 9.1.0

**Firebase:** 7.6.0

**AngularFire:** 5.4.0

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

*home.component.ts*

import { Component, OnInit } from '@angular/core';
import { AngularFireMessaging } from '@angular/fire/messaging';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {

  public notificationType: number = 0;

  constructor(
    private afm: AngularFireMessaging
  ) {
    this.afm.messaging.subscribe(
      (_messaging) => {
        _messaging.onMessage = _messaging.onMessage.bind(_messaging);
        _messaging.onTokenRefresh = _messaging.onTokenRefresh.bind(_messaging);
      }
    );
  }

  ngOnInit(): void { }

  requestToken() {
    this.afm.requestToken
      .subscribe(
        (token) => {
          console.log('Token success: ', token);
          this.notificationType = 1;
        },
        (error) => {
          this.notificationType = 2;
        },
      );
  }
}

*home.component.html*

<button *ngIf="notificationType==0" type="button" (click)="requestToken()">
    Get Notified of New Cases
</button>

**Steps to set up and reproduce**

Click on the button, there'll be a browser permission pop-up and after clicking "Allow" or "Block", the component's property value isn't updating and so its not hiding the button on view.

### Debug output

No errors.

### Expected behavior

The requestToken method should change the component's property value in its success and error callbacks.

### Actual behavior

Component property value isn't changing and the button isn't hiding. But when I click again on button the value changes and button hides.

**Comment by jamesdaniels** [comment]
The zone.js issues have been resolved here. Closing.
