### ISSUE TITLE
Errors in angular fire while installing bazel.

### ISSUE THREAD

**Issue by zkBounty** [angular/angularfire#2399]
### Version info

**Angular:** 
8.2.14

**Firebase:**

**AngularFire:**
6.0.0

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
node v10.15.2
npm v6.14.4

### How to reproduce these conditions
Create a new angular project and add angular fire.
Then  try migrating the project to using Bazel with
ng add @angular/bazel

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

Here is the error the above throws during the bazel installation itself.

node_modules/@angular/fire/angularfire2.d.ts(37,49): error TS2344: Type 'T[K]' does not satisfy the constraint '(...args: any) => any'.
  Type 'T[{ [K in keyof T]: T[K] extends Function ? K : never; }[keyof T]]' is not assignable to type '(...args: any) => any'.
    Type 'T[T[keyof T] extends Function ? keyof T : never]' is not assignable to type '(...args: any) => any'.
      Type 'T[keyof T]' is not assignable to type '(...args: any) => any'.
        Type 'T[string] | T[number] | T[symbol]' is not assignable to type '(...args: any) => any'.
          Type 'T[string]' is not assignable to type '(...args: any) => any'.
node_modules/@angular/fire/angularfire2.d.ts(40,49): error TS2344: Type 'T[K]' does not satisfy the constraint '(...args: any) => any'.
  Type 'T[{ [K in keyof T]: T[K] extends Function ? K : never; }[keyof T]]' is not assignable to type '(...args: any) => any'.
    Type 'T[T[keyof T] extends Function ? keyof T : never]' is not assignable to type '(...args: any) => any'.
      Type 'T[keyof T]' is not assignable to type '(...args: any) => any'.
        Type 'T[string] | T[number] | T[symbol]' is not assignable to type '(...args: any) => any'.
          Type 'T[string]' is not assignable to type '(...args: any) => any'.
node_modules/@angular/fire/angularfire2.d.ts(48,78): error TS2344: Type 'T[K]' does not satisfy the constraint '(...args: any) => any'.
  Type 'T[{ [K in { [K in keyof T]: T[K] extends Function ? K : never; }[keyof T]]: ReturnType<T[K]> extends Promise<any> ? never : K; }[{ [K in keyof T]: T[K] extends Function ? K : never; }[keyof T]]]' is not assignable to type '(...args: any) => any'.
    Type 'T[ReturnType<T[{ [K in keyof T]: T[K] extends Function ? K : never; }[keyof T]]> extends Promise<any> ? never : { [K in keyof T]: T[K] extends Function ? K : never; }[keyof T]]' is not assignable to type '(...args: any) => any'.
      Type 'T[{ [K in keyof T]: T[K] extends Function ? K : never; }[keyof T]]' is not assignable to type '(...args: any) => any'.
        Type 'T[T[keyof T] extends Function ? keyof T : never]' is not assignable to type '(...args: any) => any'.
          Type 'T[keyof T]' is not assignable to type '(...args: any) => any'.
            Type 'T[string] | T[number] | T[symbol]' is not assignable to type '(...args: any) => any'.
              Type 'T[string]' is not assignable to type '(...args: any) => any'.
node_modules/@angular/fire/angularfire2.d.ts(48,107): error TS2344: Type 'T[K]' does not satisfy the constraint '(...args: any) => any'.
  Type 'T[{ [K in { [K in keyof T]: T[K] extends Function ? K : never; }[keyof T]]: ReturnType<T[K]> extends Promise<any> ? never : K; }[{ [K in keyof T]: T[K] extends Function ? K : never; }[keyof T]]]' is not assignable to type '(...args: any) => any'.
    Type 'T[ReturnType<T[{ [K in keyof T]: T[K] extends Function ? K : never; }[keyof T]]> extends Promise<any> ? never : { [K in keyof T]: T[K] extends Function ? K : never; }[keyof T]]' is not assignable to type '(...args: any) => any'.
      Type 'T[{ [K in keyof T]: T[K] extends Function ? K : never; }[keyof T]]' is not assignable to type '(...args: any) => any'.
        Type 'T[T[keyof T] extends Function ? keyof T : never]' is not assignable to type '(...args: any) => any'.
          Type 'T[keyof T]' is not assignable to type '(...args: any) => any'.
            Type 'T[string] | T[number] | T[symbol]' is not assignable to type '(...args: any) => any'.
              Type 'T[string]' is not assignable to type '(...args: any) => any'.
node_modules/@angular/fire/angularfire2.d.ts(50,75): error TS2344: Type 'T[K]' does not satisfy the constraint '(...args: any) => any'.
  Type 'T[{ [K in { [K in keyof T]: T[K] extends Function ? K : never; }[keyof T]]: ReturnType<T[K]> extends Promise<any> ? K : never; }[{ [K in keyof T]: T[K] extends Function ? K : never; }[keyof T]]]' is not assignable to type '(...args: any) => any'.
    Type 'T[ReturnType<T[{ [K in keyof T]: T[K] extends Function ? K : never; }[keyof T]]> extends Promise<any> ? { [K in keyof T]: T[K] extends Function ? K : never; }[keyof T] : never]' is not assignable to type '(...args: any) => any'.
      Type 'T[{ [K in keyof T]: T[K] extends Function ? K : never; }[keyof T]]' is not assignable to type '(...args: any) => any'.
node_modules/@angular/fire/angularfire2.d.ts(50,96): error TS2344: Type 'T[K]' does not satisfy the constraint '(...args: any) => any'.
  Type 'T[{ [K in { [K in keyof T]: T[K] extends Function ? K : never; }[keyof T]]: ReturnType<T[K]> extends Promise<any> ? K : never; }[{ [K in keyof T]: T[K] extends Function ? K : never; }[keyof T]]]' is not assignable to type '(...args: any) => any'.
    Type 'T[ReturnType<T[{ [K in keyof T]: T[K] extends Function ? K : never; }[keyof T]]> extends Promise<any> ? { [K in keyof T]: T[K] extends Function ? K : never; }[keyof T] : never]' is not assignable to type '(...args: any) => any'.
      Type 'T[{ [K in keyof T]: T[K] extends Function ? K : never; }[keyof T]]' is not assignable to type '(...args: any) => any'.
node_modules/@angular/fire/firebase.app.module.d.ts(2,73): error TS2305: Module '"../../firebase"' has no exported member 'analytics'.
node_modules/@angular/fire/firebase.app.module.d.ts(2,84): error TS2305: Module '"../../firebase"' has no exported member 'performance'.
node_modules/@angular/fire/firebase.app.module.d.ts(2,97): error TS2305: Module '"../../firebase"' has no exported member 'remoteConfig'.
node_modules/@angular/fire/analytics/analytics.d.ts(3,10): error TS2305: Module '"../../../firebase"' has no exported member 'analytics'.
node_modules/@angular/fire/analytics/analytics.d.ts(16,5): error TS2411: Property 'updateConfig' of type '(config: Config) => Promise<void>' is not assignable to string index type 'Promise<any> & ((...args: unknown[]) => Promise<any>) & ((...args: unknown[]) => any)'.
node_modules/@angular/fire/firestore/interfaces.d.ts(6,53): error TS2694: Namespace 'firebase.firestore' has no exported member 'PersistenceSettings'.
node_modules/@angular/fire/firestore/collection/collection.d.ts(82,53): error TS2315: Type 'QuerySnapshot' is not generic.
node_modules/@angular/fire/firestore/document/document.d.ts(71,53): error TS2315: Type 'DocumentSnapshot' is not generic.
node_modules/@angular/fire/firestore/collection-group/collection-group.d.ts(60,53): error TS2315: Type 'QuerySnapshot' is not generic.
node_modules/@angular/fire/firestore/firestore.d.ts(14,69): error TS2694: Namespace 'firebase.firestore' has no exported member 'PersistenceSettings'.
node_modules/@angular/fire/performance/performance.d.ts(3,10): error TS2305: Module '"../../../firebase"' has no exported member 'performance'.
node_modules/@angular/fire/remote-config/remote-config.d.ts(4,10): error TS2305: Module '"../../../firebase"' has no exported member 'remoteConfig'.
node_modules/@angular/fire/remote-config/remote-config.d.ts(30,14): error TS2411: Property 'changes' of type 'Observable<Parameter>' is not assignable to string index type 'Promise<any> & ((...args: unknown[]) => Promise<any>) & ((...args: unknown[]) => any)'.
node_modules/@angular/fire/remote-config/remote-config.d.ts(31,14): error TS2411: Property 'parameters' of type 'Observable<Parameter[]>' is not assignable to string index type 'Promise<any> & ((...args: unknown[]) => Promise<any>) & ((...args: unknown[]) => any)'.
node_modules/@angular/fire/remote-config/remote-config.d.ts(32,14): error TS2411: Property 'numbers' of type 'Observable<{ [key: string]: number; }> & { [key: string]: Observable<number>; }' is not assignable to string index type 'Promise<any> & ((...args: unknown[]) => Promise<any>) & ((...args: unknown[]) => any)'.
node_modules/@angular/fire/remote-config/remote-config.d.ts(37,14): error TS2411: Property 'booleans' of type 'Observable<{ [key: string]: boolean; }> & { [key: string]: Observable<boolean>; }' is not assignable to string index type 'Promise<any> & ((...args: unknown[]) => Promise<any>) & ((...args: unknown[]) => any)'.
node_modules/@angular/fire/remote-config/remote-config.d.ts(42,14): error TS2411: Property 'strings' of type 'Observable<{ [key: string]: string; }> & { [key: string]: Observable<string>; }' is not assignable to string index type 'Promise<any> & ((...args: unknown[]) => Promise<any>) & ((...args: unknown[]) => any)'.
node_modules/@angular/fire/storage/interfaces.d.ts(8,42): error TS2694: Namespace 'firebase.storage' has no exported member 'ListResult'.

** Screenshots **

### Expected behavior

Bazel should get successfully installed in the angular project.

### Actual behavior

ng add @angular/bazel itself throws errors.

**Comment by laramdr** [comment]
Hi! I have a similar issue, did you found a solution?

**Comment by manojalwisnz** [comment]
having same issue.

**Comment by jltrevizon** [comment]
I have same issue.

**Comment by jamesdaniels** [comment]
I don't know how to get bazel working with angular 12... not as simple as a schematic anymore, everything is failing and all the samples are ng10. Don't really feel like wading through hundreds of lines of bazel config to figure out what is up. 

Closing as I don't think we have the bandwidth to support Bazel ATM. Happy to accept a patch.
