### ISSUE TITLE
Initial setup ng add @angular/fire

### ISSUE THREAD

**Issue by agroupp** [angular/angularfire#2401]
In brand new Angular 9 project issue:
ng add @angular/fire

This doesn't install firebase package. Due to this npm start fails until I manually installed this package.

Angular version 9.1.1

**Comment by vanarebane** [comment]
I have the same problem, but manual installing angular/fire does not help.
With the latest node and Angular versions

**Comment by igmazzini** [comment]
I have de same problem, the firebase package does not install with "ng add @angular/fire" and "npm install firebase" failed

**Comment by vanarebane** [comment]
I have no problems when going back to Angular 8

**Comment by igmazzini** [comment]
I resolved this, run "npm install firebase" into the @angular/fire folder

**Comment by andemohit** [comment]
> I resolved this, run "npm install firebase" into the @angular/fire folder

after installing this, my application is running but I'm getting this error in the console
```
ERROR NullInjectorError: R3InjectorError(AppModule)[AngularFirestore -> InjectionToken angularfire2.app.options -> InjectionToken angularfire2.app.options -> InjectionToken angularfire2.app.options]: 
  NullInjectorError: No provider for InjectionToken angularfire2.app.options!
 
```

**Comment by igmazzini** [comment]
I m not using angularfire2, i usin the lastest and i dont have this error,
try uninstall fireangular2, install @angular/fire and then install firebase
into fire folder

**Comment by mchirico** [comment]
Maybe the startup instructions need to be modified to the following?

```
ng add @angular/fire@next
npm install firebase @angular/fire --save
```

**Comment by daviddphillips** [comment]
It would be great to only include the parts of firebase that is actually depended upon.  Personally, I'm using only the Analytics and Performance bits, and I'm hoping I can include something like this, rather than the entire firebase dependency:

```
"dependencies": {
    ....
    "@angular/fire": "^6.0.0",
    "@firebase/app": "^0.6.5",
    "@firebase/analytics": "^0.3.6",
    "@firebase/performance": "^0.3.6",   
     ....
},
```

**Comment by jamesdaniels** [comment]
Addressed in a recent fix.

**Comment by bloodred17** [comment]
I ran the command `ng add @angular/fire@next`
Kept waiting... fell asleep
woke up the next morning
still installing...
![image](https://user-images.githubusercontent.com/15933391/130309785-b145565c-cf3f-4e45-a1c3-d82333b407ec.png)

**Comment by me-tantaroth** [comment]
@bloodred17 I have the same problem
