### ISSUE TITLE
Adding AngularFireAnalyticsModule to Angular 9 project breaks change detection

### ISSUE THREAD

**Issue by agroupp** [angular/angularfire#2403]
I added AngularFireAnalyticsModule to my AppModule after AngularFireModule.initializeApp(firebaseConfig). 
Afterwards change detection in components got huge delay (like 10 - 60 seconds). 
If I invoke detectChanges manually after every property change everything works fine.
Angular version 9.1.1

**Comment by JGSolutions** [comment]
For me when I add AngularFireAnalyticsModule I get this error:

ERROR Error: Cannot instantiate cyclic dependency! AngularFireFunctions.

I am only using AngularFireFunctions in one component

**Comment by magoarcano** [comment]
@JGSolutions I think it's related to this issue: https://github.com/angular/angularfire/issues/2365
Are you using AuthGuards?

**Comment by JGSolutions** [comment]
Yes I am...
