### ISSUE TITLE
Angular 7 using AngularFire and Firebase ERROR

### ISSUE THREAD

**Issue by BenJohnThird** [angular/angularfire#2404]
Hi, I've followed the guide and installed the package for Angular Fire and Firebase but yet, after many hours of trying. I am still facing the issue. I tried downgrading packages but still no luck. Hope you can provide solutions.

**Comment by BenJohnThird** [comment]
I hope there's a proper documentation whereas we can see whether this version is compatible with the Angular Version that we are using, because following the quickstart guide on how to setup AngularFire and unknowingly it is compatible with your Angular version will drive you nuts.

**Comment by Unkn0wn0x** [comment]
How does your environment look like and which errors are thrown?

Cheers
Unkn0wn0x

**Comment by jamesdaniels** [comment]
Closing as outdated.
