### ISSUE TITLE
disable logs from analytics : screen_view 

### ISSUE THREAD

**Issue by OmarioHasan** [angular/angularfire#2406]
### Version info

**Angular:**
Angular: 9.1.1

**Firebase:**
"firebase": "^7.14.0"

**AngularFire:**
@angular/fire                     5.3.0

** Screenshots **
![image](https://user-images.githubusercontent.com/8146344/79333397-c0e1ee80-7f1e-11ea-803b-38d4e3975e01.png)

### Expected behavior
not to log

### Actual behavior
it alwayes make a console.log for everything

**Comment by katowulf** [comment]
Those are logged by the Analytics SDK. Not related to AngularFire unfortunately. : (
