### ISSUE TITLE
Getting Started guide links to inaccessible site?

### ISSUE THREAD

**Issue by ShawnTalbert** [angular/angularfire#2408]
The AngularFire QuickStart has a link to an inaccessible (to the public) site (on firebase.corp.google.com)
https://github.com/angular/angularfire/blob/6.0.0/docs/install-and-setup.md#9-run-your-app-locally

I presume that is unintended? 

In any case I was hoping that link would take me to some sort of 'next steps' for getting started.

**Comment by hiepxanh** [comment]
created PR
