### ISSUE TITLE
Property 'auth' does not exist on type 'AngularFireAuth'

### ISSUE THREAD

**Issue by n3nikita** [angular/angularfire#2409]
### Version info
**Angular:**
`"@angular/cdk": "^9.2.1"`

**Firebase:**
`"firebase": "^7.14.1"`

**AngularFire:**
`"@angular/fire": "^6.0.0"`

It works well before I've updated npm packges to the latest versions. After update I get error:
```bash
Property 'auth' does not exist on type 'AngularFireAuth'.
```

**Steps to set up and reproduce**

```typescript
import { Injectable } from '@angular/core';
import { AngularFireAuth } from '@angular/fire/auth';

@Injectable({
  providedIn: 'root'
})
export class AuthService {

  constructor(private authFire: AngularFireAuth) { }

  initAuthListener(){
    this.authFire.auth.onAuthStateChanged(user => {
      if(user) {
        // code
      } else {
        this.authFire.auth.signOut();
      }
    })
  }
}
```

** Screenshots **

![image](https://user-images.githubusercontent.com/22433209/79672640-47732600-81d4-11ea-87b6-763263c31dba.png)

**Comment by Paulovsr** [comment]
See the changelog item 6.0.0-rc.0 (2020-01-30)

@angular/fire/auth
AngularFireAuth has dropped the auth property and instead Promise Proxies the underlying Firebase auth.Auth instance

**Comment by sumpton** [comment]
An upgrade guide would be brilliant. I did see the changelog a few days ago, and I am not clear to me yet what I will need to do.

I hope this example will change.
https://github.com/angular/angularfire/blob/master/docs/auth/getting-started.md <https://github.com/angular/angularfire/blob/master/docs/auth/getting-started.md>
because it looks like “auth” is defined twice.

For examples, and my own code, I prefer avoiding shortcuts and using

public angularFireAuth: AngularFireAuth

**Comment by Unkn0wn0x** [comment]
The documentation should be fine so far. If you just updated your dependencies / packages, don't forget to restart or reload your code editor. May some old / false references are loaded.

For VS Code for example (macOS), hit `Command` + `Shift` + `P` and search for `reload`, hit enter.

After restarting / reloading your code editor, it should work without the `.auth` call, `this.authFire.auth.*` -> `this.authFire.*`. If you try to access the `currentUser` you need to change your code like following, a few examples:

```
import { AngularFireAuth }  from '@angular/fire/auth';
import * as firebase from 'firebase/app';

[...]

constructor(
  private authFire: AngularFireAuth
) {}
```

**Update Password**
Old way:
`await this.authFire.currentUser.updatePassword('Passw0rd!');`
New way:
`await (await this.authFire.currentUser).updatePassword('Passw0rd!');`

**Delete User**
Old way:
`await this.authFire.auth.currentUser.delete();`
New way:
`(await this.authFire.currentUser).delete;`

**Sign out**
Old way:
`await this.authFire.auth.signOut();`
New way:
`await this.authFire.signOut();`

**Auth state changed**
Old way:
`this.authFire.auth.onAuthStateChanged(...);`
New way:
`this.authFire.onAuthStateChanged(...);`

**Update mail**
Old way:
`await this.authFire.auth.currentUser.updateEmail(userData.mail);`
New way:
`await (await this.authFire.currentUser).updateEmail(userData.mail);`

**Reauthenticate user**
Old way:
`await this.authFire.auth.currentUser.reauthenticateWithCredential(firebase.auth.EmailAuthProvider.credential(this.authFire.auth.currentUser.email, 'Passw0rd!'));`
New way:
`await (await this.authFire.currentUser).reauthenticateWithCredential(firebase.auth.EmailAuthProvider.credential((await this.authFire.currentUser).email, 'Passw0rd!'));`

**Send password reset mail**
Old way:
`await this.authFire.auth.sendPasswordResetEmail(mail);`
New way:
`await this.authFire.sendPasswordResetEmail(mail);`

**Fetch sign in methods**
Old way:
`await this.authFire.auth.fetchSignInMethodsForEmail('some@mail.address');`
New way:
`await this.authFire.fetchSignInMethodsForEmail('some@mail.address');`

Hope it helps.

Cheers
Unkn0wn0x

**Comment by n3nikita** [comment]
Thank you guys

**Comment by sumpton** [comment]
Super helpful, @Unkn0wn0x. I really appreciate this helpful guide. I would have struggled awhile without it.

**Comment by Villanuevand** [comment]
Hello folks! 
Thanks @Unkn0wn0x for this helpful thread...
Im having some issues after my v9 upgrade. 

`TypeError: Cannot read property 'GoogleAuthProvider' of undefined`

```ts
import {AngularFireAuth} from '@angular/fire/auth';
import {auth} from 'firebase/app';
...
constructor(private afAuth: AngularFireAuth )
...
const provider = new auth.GoogleAuthProvider();
const credential = await this.afAuth.signInWithPopup(provider);
```
-- version -- 
```json
"@angular/fire": "^6.0.0",
 "firebase": "7.14.2"
```

Any having the same issue? 
thanks...

**Comment by bfromager** [comment]
How are we supposed to use this?
The doc really need to be updated. 
I really dont understand where the signin/signout/create user etc... might come from

export declare class AngularFireAuth {
    /**
     * Observable of authentication state; as of Firebase 4.0 this is only triggered via sign-in/out
     */
    readonly authState: Observable<User | null>;
    /**
     * Observable of the currently signed-in user's JWT token used to identify the user to a Firebase service (or null).
     */
    readonly idToken: Observable<string | null>;
    /**
     * Observable of the currently signed-in user (or null).
     */
    readonly user: Observable<User | null>;
    /**
     * Observable of the currently signed-in user's IdTokenResult object which contains the ID token JWT string and other
     * helper properties for getting different data associated with the token as well as all the decoded payload claims
     * (or null).
     */
    readonly idTokenResult: Observable<auth.IdTokenResult | null>;
    constructor(options: FirebaseOptions, nameOrConfig: string | FirebaseAppConfig | null | undefined, platformId: Object, zone: NgZone);
}

**Comment by harish1995** [comment]
this is old way..
this.afAuth.auth.currentUser.sendEmailVerification()

can any one explain how to used sendEmailVerification() method of updated firebase

**Comment by HnainiaHend** [comment]
Property 'signInwithEmailAndPassword' does not exist on type 'AngularFireAuth'. 
![Capture7777](https://user-images.githubusercontent.com/65108236/81493791-a859bf80-92a3-11ea-870f-46b8fe41674c.PNG)

**Comment by Unkn0wn0x** [comment]
@HnainiaHend Did you checked my comment here?
* https://github.com/angular/angularfire/issues/2409#issuecomment-616224319

May you need to restart your Code Editor to get the latest references.

Hope it helps.

Cheers
Unkn0wn0x

**Comment by yashupadhyay192001** [comment]
@HnainiaHend  the letter "w" in your property signInwithEmailAndPassword should be in upper case.

**Comment by rahilfaizan** [comment]
```
return await firebase.auth()
.createUserWithEmailAndPassword(email,password)
.then(newUser =>{
firebase.auth().currentUser.sendEmailVerification()}
```what should I change in this??

**Comment by yashupadhyay192001** [comment]
@rahilfaizan can you tell me the error you are receiving.

**Comment by rahilfaizan** [comment]
> @rahilfaizan can you tell me the error you are receiving.
> 

I actually resolved it.thank you

**Comment by luciano1997** [comment]
como lo solucionaste ?
![sendmail](https://user-images.githubusercontent.com/43941133/84453975-4cc67d00-ac27-11ea-99c4-badcfaf769e2.png)

**Comment by luciano1997** [comment]
Como lo solucionaste ?
how did you solve it ?

![sendmail](https://user-images.githubusercontent.com/43941133/84453999-623ba700-ac27-11ea-887f-366a0974b7d7.png)

**Comment by 02jaysenghani** [comment]
> The documentation should be fine so far. If you just updated your dependencies / packages, don't forget to restart or reload your code editor. May some old / false references are loaded.
> 
> For VS Code for example (macOS), hit `Command` + `Shift` + `P` and search for `reload`, hit enter.
> 
> After restarting / reloading your code editor, it should work without the `.auth` call, `this.authFire.auth.*` -> `this.authFire.*`. If you try to access the `currentUser` you need to change your code like following, a few examples:
> 
> ```
> import { AngularFireAuth }  from '@angular/fire/auth';
> import * as firebase from 'firebase/app';
> 
> [...]
> 
> constructor(
>   private authFire: AngularFireAuth
> ) {}
> ```
> 
> **Update Password**
> Old way:
> `await this.authFire.currentUser.updatePassword('Passw0rd!');`
> New way:
> `await (await this.authFire.currentUser).updatePassword('Passw0rd!');`
> 
> **Delete User**
> Old way:
> `await this.authFire.auth.currentUser.delete();`
> New way:
> `(await this.authFire.currentUser).delete;`
> 
> **Sign out**
> Old way:
> `await this.authFire.auth.signOut();`
> New way:
> `await this.authFire.signOut();`
> 
> **Auth state changed**
> Old way:
> `this.authFire.auth.onAuthStateChanged(...);`
> New way:
> `this.authFire.onAuthStateChanged(...);`
> 
> **Update mail**
> Old way:
> `await this.authFire.auth.currentUser.updateEmail('some@mail.address');`
> New way:
> `await (await this.authFire.currentUser).updateEmail('some@mail.address');`
> 
> **Reauthenticate user**
> Old way:
> `await this.authFire.auth.currentUser.reauthenticateWithCredential(firebase.auth.EmailAuthProvider.credential(this.authFire.auth.currentUser.email, 'Passw0rd!'));`
> New way:
> `await (await this.authFire.currentUser).reauthenticateWithCredential(firebase.auth.EmailAuthProvider.credential((await this.authFire.currentUser).email, 'Passw0rd!'));`
> 
> **Send password reset mail**
> Old way:
> `await this.authFire.auth.sendPasswordResetEmail(mail);`
> New way:
> `await this.authFire.sendPasswordResetEmail(mail);`
> 
> **Fetch sign in methods**
> Old way:
> `await this.authFire.auth.fetchSignInMethodsForEmail('some@mail.address');`
> New way:
> `await this.authFire.fetchSignInMethodsForEmail('some@mail.address');`
> 
> Hope it helps.
> 
> Cheers
> Unkn0wn0x

Thank you

**Comment by parthdevloper** [comment]
> Como lo solucionaste ?
> how did you solve it ?
> 
> ![sendmail](https://user-images.githubusercontent.com/43941133/84453999-623ba700-ac27-11ea-887f-366a0974b7d7.png)

> **Here is your solution:** 

`  SendVerificationMail() {`
`    return this.afAuth.currentUser.then(u => u.sendEmailVerification())`
 `   .then(() => {`
  `    this.router.navigate(['verify-email-address']);`
   ` })`
  `}`

**Comment by jonathan-chin** [comment]
thanks for this. I'm trying to set the languageCode here. This works:

```
firebase.auth().languageCode = language;
```

but this does not:

```
this.angularFireAuth.languageCode = language;
```

is languageCode exposed through AngularFireAuth?

**Comment by axul** [comment]
I'm having the same problem as @jonathan-chin

**Comment by Keawkanok** [comment]
Hi well if it's true But this worked for me.

1 - npm uninstall firebase @angular/fire

2- package.json

3 - dependencies { ... "@angular/fire": "6.0.0", "firebase": "7.14.1", ... }

4 - change

5 - npm i @angular/fire@5.4.2

6 - npm install --save firebase

- dependencies { ... "@angular/fire": "^5.4.2",  "firebase": "7.21.0", ... }

- save

![image](https://user-images.githubusercontent.com/53214515/94138208-f4438480-fe91-11ea-9a50-ba2a7080f1ee.png)

![image](https://user-images.githubusercontent.com/53214515/94138379-3bca1080-fe92-11ea-820d-51adae0f7735.png)

**Comment by cfficaurzua** [comment]
HI everyone, 
I'm trying to grant offline access to use google apis.
This works great with the google Sign In for websites.

```
grantOfflineAccess(){
   return new Promise((resolve, reject)=>{ 
    this.googleAuth.getAuth().subscribe((authInstance:any)=>{
      authInstance.grantOfflineAccess({
        access_type: 'offline',
        redirect_uri: 'postmessage',
        prompt: 'consent',
        approval_prompt: null,
      }).then(offlineAccessExchangeCode =>{
          const authResp = authInstance.currentUser.get().getAuthResponse();
          console.log(authResp)
          const credential = auth.GoogleAuthProvider.credential(authResp.id_token);
          this.afAuth.signInWithCredential(credential).then(credential=>{
          const callable = this.fns.httpsCallable('offlineAccessExchangeCode');
          callable(offlineAccessExchangeCode).subscribe((tokens)=>{
            resolve(this.updateUserData(credential, tokens))
          }
          );     
        });
      })
    })
   })
```
but is it possible to use the firebase auth to achieve the same?

I have tried
```
this.afAuth.grantOfflineAccess()
this.afAuth.auth.grantOfflineAccess()
```

**Comment by whoiscarlo** [comment]
The fix is to use `firebase.default.auth` **instead** of `firebase.auth`

**Comment by lucasmrl** [comment]
After reading all the comments here, I still can't see why I got this error.
"Error: src/app/app.component.ts:70:20 - error TS2339: Property 'authFire' does not exist on type 'typeof import("/Users/main/Desktop/angular-facial-recognition/node_modules/firebase/index")'."

`import { Component } from '@angular/core';
import { AngularFireAuth } from '@angular/fire/auth';
//import firebase from 'firebase/app'; //for google, it workspace
import * as firebase from 'firebase/app';

@Component({
  selector: 'app-root',
  template: `
    <div *ngIf="authFire.user | async as user; else showLogin">
      <h1>Hello {{ user.displayName }}!</h1>
      <button (click)="logout()">Logout</button>
    </div>
    <ng-template #showLogin>
      <p>Please login.</p>
      <button (click)="login()">Login with Google</button>
    </ng-template>
  `,
})
export class AppComponent {
  constructor(public authFire: AngularFireAuth) {}
  login() {
    this.authFire.signInWithPopup(
      new firebase.authFire.signInWithEmailAndPassword(
        'lucas@teste.com',
        123123123
      )
    );
  }
  logout() {
    this.authFire.signOut();
  }
}`

**Comment by eluemeln** [comment]
hello guys I'm having issues with login with google authentication on my angular application since the auth has been removed.
what should I do any ideas?

this is my package.json file

"dependencies": {
    "@angular/animations": "^11.1.2",
    "@angular/cdk": "^11.1.1",
    "@angular/common": "~11.1.2",
    "@angular/compiler": "~11.1.2",
    "@angular/core": "~11.1.2",
    "@angular/fire": "^6.1.4",
    "@angular/forms": "~11.1.2",
    "@angular/material": "^11.1.1",
    "@angular/platform-browser": "~11.1.2",
    "@angular/platform-browser-dynamic": "~11.1.2",
    "@angular/router": "~11.1.2",
    "firebase": "^8.2.6",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1101.4",
    "@angular/cli": "~11.1.4",
    "@angular/compiler-cli": "~11.1.2",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.2.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.1.2"
  }

below is my authservice.ts file

import { stringify } from '@angular/compiler/src/util';
import { Injectable } from '@angular/core';

import {AngularFireAuth} from '@angular/fire/auth';

@Injectable({
  providedIn: 'root'
})
export class AuthService {

  constructor(private login:AngularFireAuth ) { }
 LoginWithGoogle()
  {
    
    this.login.signInWithRedirect()
  }
 
}

I'm not getting any recommendation for the "auth" and I'm kind of confused

**Comment by eluemeln** [comment]
before i saw it used to be this. login.auth.SigninWithRedirect(new firebase.auth.Googleprovider())
please, i need help with both the sign-in and signout.
Thanks

**Comment by andrejonn31** [comment]
> > Como lo solucionaste ?
> > how did you solve it ?
> > ![sendmail](https://user-images.githubusercontent.com/43941133/84453999-623ba700-ac27-11ea-887f-366a0974b7d7.png)
> 
> > **Here is your solution:**
> 
> ` SendVerificationMail() {`
> ` return this.afAuth.currentUser.then(u => u.sendEmailVerification())`
> ` .then(() => {`
> ` this.router.navigate(['verify-email-address']);`
> ` })`
> `}`

Wrote the same but the u.sendEmailVerification() in ... (u => u.sendEmailVerification())...... was flagged as "parameter u: firebase.User | null. object is possibly null" error. How does one fix that?

**Comment by gestorjornada-app** [comment]
How can I get the uuid for an authenticated user?

**Comment by rahulsha01** [comment]
> Property 'signInwithEmailAndPassword' does not exist on type 'AngularFireAuth'.
> ![Capture7777](https://user-images.githubusercontent.com/65108236/81493791-a859bf80-92a3-11ea-870f-46b8fe41674c.PNG)

Any resolution on this?

**Comment by ZiedNS** [comment]
hello , Any resolution on this , thank you ? 
![2021-10-01_17h16_12](https://user-images.githubusercontent.com/82616045/135654235-3fbfa8df-d7f8-4ec0-914e-465c9169c14e.png)
