### ISSUE TITLE
Clarification on multiple where clauses and strategy without.

### ISSUE THREAD

**Issue by ganySA** [angular/angularfire#2410]
Hi 

I am trying to figure out if you can query by multiple ‘where’ clauses across multiple fields.
I believe Firestore does support this, is this achievable with angularfire? In the docs it says you cannot do multiple where clauses which just seems incredibly limiting.

Alternatively - how does one go about decreasing the volume of data that is brought to the client.
Assuming a contact list which is linked to a login UID in a document.

Let’s say i have a contactlist collection, which contains a UID for the User it belongs to but i also want to search it on first name and last name.

If i can only filter contact list with a single where clause on the UID, that would potentially bring in potentially thousands of records which i then need to filter on the client.

Thanks.

**Comment by hiepxanh** [comment]
can you give a clear detail example data? I cannot understand which case are you trying to resolve

**Comment by jamesdaniels** [comment]
You need to combine multiple queries with RXJS; as it sounds like you are going to be over-sampling i'd suggest either compound indexes (you have to make these by hand), restructure / denormalize your database, or look into Firestore.
