### ISSUE TITLE
How to reinitialise after .termiante() & .clearPersistence()

### ISSUE THREAD

**Issue by dodomui** [angular/angularfire#2411]
**Steps to set up and reproduce**

```
 this.afs.firestore.terminate().then(() => {
      this.afs.firestore.clearPersistence().then(() => {
      });
});
```
After run above code to clear firestore local cache, how could I reinitialize the firestore?

### Debug output

** Errors in the JavaScript console **
Currently receive below error after run .terminate()
`FirebaseError: The client has already been terminated.`
** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

### Expected behavior

I need to clear current user data completely once user logout.
Therefore I use clearPersistence() function.
It need to run terminate() before clearPersistence().

Any advice how to re initialise firestore instance or any better way to achieve?
Thanks.

**Comment by KingDarBoja** [comment]
Did you find a way to perform the re-initialization after termiante + clearPersistence ? Thank you

**Comment by JLardapide** [comment]
any solution?

**Comment by dodomui** [comment]
> any solution?

The only way I figure out now is to reload the web app. Not the wise solution but at least works

**Comment by dodomui** [comment]
> Did you find a way to perform the re-initialization after termiante + clearPersistence ? Thank you

Just saw your comment, I did force reload whole web app after terminate😅
