### ISSUE TITLE
how can I login using Phone Authentication in ionic 5 using angularFire

### ISSUE THREAD

**Issue by raviranjan528** [angular/angularfire#2413]
Version info
Angular:
 "@angular/core": "~8.2.14",

Ionic 
"@ionic-native/core": "^5.0.7",
Firebase:
"firebase": "^7.14.1"

AngularFire:
"@angular/fire": "^6.0.0"

I'm using Angular 8 with ionic, I want to know how can I log in through phone Authentication using angular Fire?

**Comment by Unkn0wn0x** [comment]
Please read the docs (especially the auth ones) ...

https://github.com/angular/angularfire/blob/master/docs/auth/getting-started.md

Cheers
Unkn0wn0x
