### ISSUE TITLE
FirebaseObjectObservable replaced to AngularFireObject created an error .

### ISSUE THREAD

**Issue by manzilsubedi** [angular/angularfire#2417]
here when i want yo implement an canActivate method for admin-auth guard service it generates the error.
`import { Observable } from 'rxjs/Observable';
import { UserService } from './user.service';
import { AuthService } from './auth.service';
import { Injectable } from '@angular/core';
import { CanActivate } from '@angular/router';
import 'rxjs/add/operator/switchMap';
import 'rxjs/add/operator/map';
import * as firebase from 'firebase';

@Injectable()
export class AdminAuthGuardService  implements CanActivate{
 

  constructor(private auth: AuthService, private userService : UserService) { }

  canActivate(): Observable<boolean> {
    return this.auth.user$ 
      .switchMap(user => this.userService.get(user.uid))
      .map((appUser) => appUser.isAdmin);
    }
 
  } 
  `

![helpppps](https://user-images.githubusercontent.com/24939768/79942218-0ace5580-8486-11ea-92e1-2a22099cd193.JPG)

**Comment by asmaaMous556** [comment]
try this to use  **pipe**
constructor(private auth: AuthService, private userService: UserServiceService) { }
  canActivate(): Observable<boolean>{
    return this.auth.appUser$
      .pipe(map(appuser => appuser.isAdmin));

  }
