### ISSUE TITLE
signInWithPhoneNumber

### ISSUE THREAD

**Issue by anshumansworld** [angular/angularfire#2427]
Can anyone help in providing example for signInWithPhoneNumber? I tried many ways along with firebaseui but no luck. Couldn't find any doc related to it.

Version: 6.0.0

**Comment by Villanuevand** [comment]
@anshumansworld did you solved it? 

Im having problems with `GoogleAuthProvider` after v9 update... 

returns `TypeError: Cannot read property 'GoogleAuthProvider' of undefined`.
