### ISSUE TITLE
ng deploy --preview command error - 'open'

### ISSUE THREAD

**Issue by jdgamble555** [angular/angularfire#2428]
### Version info

**Angular:** 9

**Firebase:** 7

**AngularFire:** 6

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** Windows 10, Visual Studio Code Terminal

### How to reproduce these conditions

I believe this is a simple Windows problem for something built on Linux.

**Steps to set up and reproduce**

ng deploy --preview (on a project on windows)

### Expected behavior

to deploy locally

### Actual behavior
**'open' is not recognized as an internal or external command**

![error](https://user-images.githubusercontent.com/8333090/80297313-a8a47780-8747-11ea-901d-aa3bd0a42b0a.png)

**Comment by jdgamble555** [comment]
Few things here, I believe this might be able to be fixed:
  
Replace: ```child_process_1.execSync(`open http://localhost:${port} || true`);``` 
with this: ```child_process_1.execSync(`start http://localhost:${port} || true`);```

two times in **actions.js**.  Not sure what works on Mac/Unix, Although, I still l get the **http://undefined** problem:
```
=== Serving from 'C:\angular projects\testssr'...

i  hosting: Serving hosting files from: public
+  hosting: Local server: http://undefined:5000
i  hosting[testssr]: Serving hosting files from: dist/testssr/dist/testssr/browser
+  hosting[testssr]: Local server: http://undefined:5005
::1 - - [27/Apr/2020:05:24:27 +0000] "GET / HTTP/1.1" 404 139 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36"
+  functions: Using node@10 from host.
+  functions: functions emulator started at http://localhost:5001
i  functions: Watching "C:\angular projects\testssr\dist\testssr" for Cloud Functions...
>  dist/testssr/server
+  functions[ssr]: http function initialized (http://localhost:5001/jokecan-dev/us-central1/ssr).
```
Also maybe related, I notice the **public** file path in **firebase.json** seems to be double deep.  I don't know if this is just a windows problem.  ```"public": "dist\\testssr\\dist\\testssr\\browser",``` and you can see the files are built normally, but then renamed for some unknown reason to be double deep AFTER they are built correctly in **actions.js** here:
```
    const staticOut = project.build.options.outputPath;
    const serverOut = project.server.options.outputPath;
    const newClientPath = path_1.join(path_1.dirname(staticOut), staticOut);
    const newServerPath = path_1.join(path_1.dirname(serverOut), serverOut);
    fsHost.moveSync(staticOut, newClientPath);
    fsHost.moveSync(serverOut, newServerPath);
    fsHost.writeFileSync(path_1.join(path_1.dirname(serverOut), "package.json"), getPackageJson(context, workspaceRoot));
    fsHost.writeFileSync(path_1.join(path_1.dirname(serverOut), "index.js"), functions_templates_1.defaultFunction(serverOut));
```


**Side note**: I also I noticed this warning problem, which needs to just be updated like in **angular/cli*** [here](https://github.com/angular/angular-cli/pull/16344/files).
```Option 'bundleDependencies' string value is deprecated since version 9. Use a boolean value instead.```

**Comment by EdricChan03** [comment]
`open` is a valid command on Unix/Linux-related systems - view the [manpage](http://man7.org/linux/man-pages/man2/open.2.html) for more info.

**Comment by jdgamble555** [comment]
@EdricChan03 Yes, but it is not on Windows.  The code needs to be changed to work on BOTH.  Either an if statement like ``` if (process.platform === "win32)";``` or the code could be written to use something like **shelljs** which works on all platforms.

**Comment by jdgamble555** [comment]
Also noting, until this issues is resolved in the source code, you cannot deploy the **ssr** function at the same time as your other functions.  A work-around is to change your **firestore.json** file so that ```functions.source = ""``` when you want to deploy your functions, and back to ```functions.source = "dist/YOUR_MODULE"``` when you want to deploy the SSR function.

Also, if you have not **init functions** before, you need to do that, add **firebase** to the **functions/package.json**, then run **npm run deploy** for the first time (to add firebase to the function includes), then re-run **ng deploy** in order for this to work!  Many many bugs here, but once it gets updated, this will save so much time!

**Comment by NothingEverHappens** [comment]
How about using https://www.npmjs.com/package/open

**Comment by jdgamble555** [comment]
@NothingEverHappens That could work.  I have no control on the source code though.  I assume whatever they use for **firebase serve** would work here.

-----------------------------------------------------------------------------------------------------

@jamesdaniels Any way we can get this updated?  These seem to be pretty **SIMPLE FIXES** that go a long way:

**1.)** Fixing `child_process_1.execSync('open http://localhost:${port} || true');` to be platform independent, which should hopefully get rid of the `http://undefined` error as well. (needs to be tested on Windows before commit) in **actions.ts**  You could use `if (process.platform === "win32")` and use **start**, or use something like the [open](https://www.npmjs.com/package/open) package as suggested above.  Very easy.

**2.)** Change the copy command so that "`public": "dist\\YOUR-MODULE\\dist\\YOUR-MODULE\\browser",` is not double deep, but instead copies into the functions directory.  It may copy to the correct path on Mac/Unix, not sure, but it does copy to deep folders on Windows..  These lines need to be updated in **actions.ts** so the paths are correct before the **server** and **browser** folder are moved to the correct place, probably **functions/dist/YOUR-MODULE**
```
    const newClientPath = path_1.join(path_1.dirname(staticOut), staticOut);
    const newServerPath = path_1.join(path_1.dirname(serverOut), serverOut);
```
Also, **ng-add.ts** will probably need to be updated so that ```functions.source``` is added correctly in **firebase.json**.

**3.)** Add an include in **functions/index.ts** that would include **functions/dist/YOUR-MODULE/index.ts** so that you can **ng deploy** all your functions at once instead of having to constanly edit **firebase.json** if you want to deploy your functions vs deploy your project. 2.) would need to be fixed first.

**4.)** **function-templates.ts** is deployed using **actions.ts** in the ```if (existsSync(join(workspaceRoot, 'angular.json'))) {``` section.  It will not know to **import firebase** unless it is specifically declared in the functions folder.  Basically, this does not work out of the box.

**5.)** Not a big deal, but very simple fix.  Get rid of 'bundleDependencies' warning by changing `bundleDependencies: 'all'` in **builder.ts** to `budleDependencies: true` (I believe that would work here).

Again, I did not write these modules, but I imaging the author would know how to fix these issues very simply.  Thanks!

**Comment by jdgamble555** [comment]
@NothingEverHappens @jamesdaniels Is anyone working on these fixes? I have laid out all the fixes so there shouldn't be much work necessary. This effects **EVERY windows user** so that they cannot use ```ng deploy --preview```!
