### ISSUE TITLE
Namespace 'admin' has no exported member 'firestore'

### ISSUE THREAD

**Issue by abdul-maroof-confiz** [angular/angularfire#2429]
### Version info

**Angular: 9.0.0**

**Firebase:5.5.4**

**AngularFire: 5.1.0**

**firebase-admin: 5.1.0**

**firebase-functions: 3.6.1**

### How to reproduce these conditions

** I am using following function and getting this error
        functions.database
      .ref('broadcast')
      .onCreate((snapshot, context) => {
        const user = snapshot;
      }); **

### Debug output

** ERROR in ./node_modules/firebase-admin/node_modules/isemail/lib/isemail.js
Module not found: Error: Can't resolve 'dns' in 'C:\Users\abdul.maroof\repos\feed-portal\node_modules\firebase-admin\node_modules\isemail\lib'
ERROR in ./node_modules/firebase-admin/lib/auth/credential.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\abdul.maroof\repos\feed-portal\node_modules\firebase-admin\lib\auth'
ERROR in ./node_modules/request/lib/har.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\abdul.maroof\repos\feed-portal\node_modules\request\lib'
ERROR in ./node_modules/firebase-admin/node_modules/faye-websocket/lib/faye/websocket/client.js
Module not found: Error: Can't resolve 'net' in 'C:\Users\abdul.maroof\repos\feed-portal\node_modules\firebase-admin\node_modules\faye-websocket\lib\faye\websocket'
ERROR in ./node_modules/firebase-admin/node_modules/joi/lib/string.js
Module not found: Error: Can't resolve 'net' in 'C:\Users\abdul.maroof\repos\feed-portal\node_modules\firebase-admin\node_modules\joi\lib'
ERROR in ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'net' in 'C:\Users\abdul.maroof\repos\feed-portal\node_modules\forever-agent'
ERROR in ./node_modules/tough-cookie/lib/cookie.js
Module not found: Error: Can't resolve 'net' in 'C:\Users\abdul.maroof\repos\feed-portal\node_modules\tough-cookie\lib'
ERROR in ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'net' in 'C:\Users\abdul.maroof\repos\feed-portal\node_modules\tunnel-agent'
ERROR in ./node_modules/firebase-admin/node_modules/faye-websocket/lib/faye/websocket/client.js
Module not found: Error: Can't resolve 'tls' in 'C:\Users\abdul.maroof\repos\feed-portal\node_modules\firebase-admin\node_modules\faye-websocket\lib\faye\websocket'
ERROR in ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'tls' in 'C:\Users\abdul.maroof\repos\feed-portal\node_modules\forever-agent'
ERROR in ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'tls' in 'C:\Users\abdul.maroof\repos\feed-portal\node_modules\tunnel-agent' **

** Screenshots **
![Screenshot (710)](https://user-images.githubusercontent.com/47100460/80315288-eff63b00-880f-11ea-9a82-9b4abb12fb9f.png)

![Screenshot (711)](https://user-images.githubusercontent.com/47100460/80315292-f2f12b80-880f-11ea-9ce1-b4dc5d3a8d2b.png)

### Expected behavior

It should compile properly and the event should be triggered in my client code when on firestore database collection (broadcast named collection in my case) something is created but it fails on the compilation.

### Actual behavior

Fails during compilation.

**Comment by abdul-maroof-confiz** [comment]
@jeffbcross @urish Can you guys please help me on this.

**Comment by EdricChan03** [comment]
Chances are the issue you're facing is due to a mix up of the [`firebase-admin`](https://www.npmjs.com/package/firebase-admin) package with the [`firebase`](https://www.npmjs.com/package/firebase) package. They are **not the same** packages:

- `firebase-admin` is intended for server-related infrastructure;
- while `firebase` is intended for web and server clients.

**Comment by abdul-maroof-confiz** [comment]
@EdricChan03 I am following the steps defined in [this](https://blog.usejournal.com/angular-and-firebase-the-perfect-pair-part-6-609136fea2b7) link but I am getting the error I reported. I am unable to resolve it. Please help me if you have any solution.
