### ISSUE TITLE
Error Initilizing Firestore service with 6.0.0 and Angular 9.1.3

### ISSUE THREAD

**Issue by Alsmith141510** [angular/angularfire#2432]
**Angular:**
Angular CLI: 9.1.3
Node: 12.16.2
OS: win32 x64

Angular: 9.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.901.3
@angular-devkit/build-optimizer   0.901.3
@angular-devkit/build-webpack     0.901.3
@angular-devkit/core              9.1.3
@angular-devkit/schematics        9.1.3
@angular/cdk                      9.2.1
@angular/fire                     6.0.0
@angular/flex-layout              9.0.0-beta.29
@angular/material                 9.2.1
@ngtools/webpack                  9.1.3
@schematics/angular               9.1.3
@schematics/update                0.901.3
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

**Firebase:**
firebase -V
8.2.0
**AngularFire:**
verion 6.0.0
**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
PAckage.JSON
{
  "name": "teach",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^9.1.3",
    "@angular/cdk": "^9.2.1",
    "@angular/common": "~9.1.3",
    "@angular/compiler": "~9.1.3",
    "@angular/core": "~9.1.3",
    "@angular/fire": "^6.0.0",
    "@angular/flex-layout": "^9.0.0-beta.29",
    "@angular/forms": "~9.1.3",
    "@angular/material": "^9.2.1",
    "@angular/platform-browser": "~9.1.3",
    "@angular/platform-browser-dynamic": "~9.1.3",
    "@angular/router": "~9.1.3",
    "@fortawesome/angular-fontawesome": "^0.6.1",
    "@fortawesome/fontawesome-svg-core": "^1.2.28",
    "@fortawesome/free-brands-svg-icons": "^5.13.0",
    "@fortawesome/free-regular-svg-icons": "^5.13.0",
    "@fortawesome/free-solid-svg-icons": "^5.13.0",
    "@ngx-translate/core": "^12.1.2",
    "@ngx-translate/http-loader": "^4.0.0",
    "firebase": "^7.14.2",
    "ngx-toastr": "^12.0.1",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.3",
    "@angular/cli": "~9.1.3",
    "@angular/compiler-cli": "~9.1.3",
    "@angular/language-service": "~9.1.3",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3",
    "@angular-devkit/architect": "~0.900",
    "firebase-tools": "^8.0.0",
    "fuzzy": "^0.1.3",
    "inquirer": "^6.2.2",
    "inquirer-autocomplete-prompt": "^1.0.1"
  }
}

### How to reproduce these conditions
Call the following code in the constructor
    this.user$ = this.afAuth.authState.pipe(
      switchMap(user => {
        if (user) {
          return this.afs.doc<User>('users/${user.uid}').valueChanges();
        } else {
          return of(null);
        }
      })/*, tap(user => localStorage.setItem('user', JSON.stringify(user)))*/
    );

    this.afAuth.authState.subscribe(
      (r) => {
        if (r != null) {
          // console.log(r);
          this.getUserById(r.uid).subscribe(
            res => {
              // console.log(res);
              this.userData = res;
              console.log(this.userData);
            }
          );
          // this.userData.country = r.phoneNumber;
          // this.userData.phoneNumber = r.phoneNumber;
        }
      })
**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**
    this.user$ = this.afAuth.authState.pipe(
      switchMap(user => {
        if (user) {
          return this.afs.doc<User>('users/${user.uid}').valueChanges();
        } else {
          return of(null);
        }
      })/*, tap(user => localStorage.setItem('user', JSON.stringify(user)))*/
    );

    this.afAuth.authState.subscribe(
      (r) => {
        if (r != null) {
          // console.log(r);
          this.getUserById(r.uid).subscribe(
            res => {
              // console.log(res);
              this.userData = res;
              console.log(this.userData);
            }
          );
          // this.userData.country = r.phoneNumber;
          // this.userData.phoneNumber = r.phoneNumber;
        }
      })

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output
ChunkLoadError: Loading chunk firebase-auth failed.
(timeout: http://localhost:4200/firebase-auth.js)
    at Function.requireEnsure [as e] (http://localhost:4200/runtime.js:127:26)
    at http://localhost:4200/vendor.js:104803:35
    at ZoneDelegate.invoke (http://localhost:4200/polyfills.js:3718:30)
    at Zone.run (http://localhost:4200/polyfills.js:3477:47)
    at NgZone.runOutsideAngular (http://localhost:4200/vendor.js:98283:91)
    at SwitchMapSubscriber.project (http://localhost:4200/vendor.js:104800:20)
    at SwitchMapSubscriber._next (http://localhost:4200/vendor.js:215648:27)
    at SwitchMapSubscriber.next (http://localhost:4200/vendor.js:209133:18)
    at Notification.observe (http://localhost:4200/vendor.js:208476:50)
    at QueueAction.dispatch (http://localhost:4200/vendor.js:214134:22)
zone-evergreen.js:659
Unhandled Promise rejection: Loading chunk firebase-auth failed.
(timeout: http://localhost:4200/firebase-auth.js) ; Zone: <root> ; Task: Promise.then ; Value:
** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

### Expected behavior
The intial screen should be rendered after the call. So that the home page displayed and the user can login to the database.
### Actual behavior
The screen goes to a hang state and the Homepage is not rendered. The only way to get out is to kill the browser.
Under devtools--> source--> with pause on exception set. t stops in the angular-fire-firestore.js

**Comment by jdgamble555** [comment]
This is not a problem with **angularfire**, but a problem with your code.  Please reformat your code in correct ```code blocks``` so that people can understand what is what.  Generally speaking, your problem is this code:

```
this.afAuth.authState.subscribe(
  (r) => {
    if (r != null) {
      // console.log(r);
      this.getUserById(r.uid).subscribe(
        res => {
          // console.log(res);
          this.userData = res;
          console.log(this.userData);
        }
      );
      // this.userData.country = r.phoneNumber;
      // this.userData.phoneNumber = r.phoneNumber;
    }
  })
```
You have a subscribe inside a subscribe.  If you are using templates, you don't need subscribe at all but an **async pipe**.  It is not clear at all what you're trying to do.  This is better suited for stackoverflow.  If you want to get the **userId** from the **user$** object, try something like this:
```
this.user$ = this.afAuth.authState
  .pipe(
	shareReplay(),
	switchMap(user => {
	  return user
		? this.afs.doc<User>(`users/${user.uid}`).snapshotChanges().pipe(
		  map((doc: any) => {
			const data = doc.payload.data();
			const uid = doc.payload.id;
			return { uid, ...data };
		  })
		)
		: of(null);
	})
  );
```
Put this code in an **auth service**, include it in your component, and get the variable using a **subscribe** or **async pipe**.  It looks like you're getting a userById, which is not the current user or would only need to be fetched once, and would be better using a **promise**, again, nothing is clear here.

**Comment by Alsmith141510** [comment]
:). Thanks for the response. Although sarcastic i understand the spirit. Rest assured this issue doesn't belong to Stackflow. This code is indeed part of the service. and I do use async pipe during the display. 
After the angular upgrade to 9 the application stops at the point where it is starting to initailize angular auth.  
Please note the system works fine if I rollback angualr/fire to the previous version keeping the angular version at 9.

**Comment by jdgamble555** [comment]
You should not use **| async** with subscribe.  It will throw an error.  However, I have no idea what the issue here is.  Again, go back and edit your original post so that all code is in code block and explain more clearly your problem so that people can understand if you still need help.  I suspect you have some issues with [breaking changes](https://github.com/angular/angularfire/blob/master/CHANGELOG.md) in the 6.0 releases.  Either way, you should be able to modify my code to fit your needs. Depending on what data you're trying to access, promises are better to use as well with **AngularFireAuth**.
