### ISSUE TITLE
Firebase Cloud Message doesn't prompt for 'Allow Notification?'. No other error message in console

### ISSUE THREAD

**Issue by weilies** [angular/angularfire#2442]
### Version info

**Angular:** 9.1

**Firebase:** 7.14.2

**AngularFire:** 5.4.2

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** 
IDE: StackBlitz
Browser: Chrome Version 81

I have done all the setups i could here my demo project. I really don't know what's missing
https://stackblitz.com/edit/ng-messaging-dny45

### How to reproduce these conditions

1. Access my application URL
2. hit the to trigger code below under app.component.ts
`  requestPermission() {
    console.log('request permission trigger')
    this.afMessaging.requestPermission.subscribe(
      () => {
        console.log("Permission granted!");
      },
      error => {
        console.error(error);
      }
    );
  }`

### Debug output
console log output 'request permission trigger' everytime i hit the button to request cloud message access. 

### Expected behavior
Prompt for 'Allow notification' window to receive alert

### Actual behavior
There ain't any other error available but it suppose to prompt 'Allow notification', Yes/No option.
i couldn't upgrade to AngularFire 6.0 as i will hit another error 
"Error: Failed to resolve module specifier angular firebase/messaging'

**Comment by jamesdaniels** [comment]
The firebase/messaging issue should be resolved, please upgrade everything, I've not been able to reproduce with new versions.
