### ISSUE TITLE
Callbacks are not working after update/set/add

### ISSUE THREAD

**Issue by luckyycool** [angular/angularfire#2454]
this.counter++;
this.afs.doc(`users/kGYry149A9Vou57KzMcYPqJmupN2`).set({
      name: "Los Angeles_"+this.counter,
      state: "CA",
      country: "USA"
    })
      .then(function () {
        this.name = 'one_'+ this.counter;
        console.log("Document successfully written!");
      })
      .catch(function (error) {
        this.name = 'two_'+ this.counter;
        console.error("Error writing document: ", error);
      })

Not working example is - https://stackblitz.com/edit/angular-ivy-w4fmak

none of the callbacks get called.

**Comment by jamesdaniels** [comment]
This was addressed in a recent patch release
