### ISSUE TITLE
Video is not available

### ISSUE THREAD

**Issue by Pingear** [angular/angularfire#2463]
https://github.com/angular/angularfire/blob/master/docs/universal/cloud-functions.md
At the bottom of the page, in additional resources, there is a link to a video that is no longer available.
Probably need to remove this link.
![image](https://user-images.githubusercontent.com/16469484/82315416-ef4a6200-99d3-11ea-835e-0f249744c617.png)

**Comment by wiedzmin26** [comment]
AngularFirebase SSR Videos -> https://angularfirebase.com/tag/ssr/
@codediodeio can you give new link with "ssr" tag for fireship.io?
