### ISSUE TITLE
Adding AngularFireAnalyticsModule causes an error

### ISSUE THREAD

**Issue by juliusn** [angular/angularfire#2464]
Adding AngularFireAnalyticsModule in my StackBlitz project's app module causes an error:

> Error in /turbo_modules/@angular/fire@6.0.0/bundles/angular-fire-analytics.umd.js (646:45)
> Failed to resolve module specifier 'firebase/auth'

Here's my app.module:
```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { RouterModule } from '@angular/router';
import { ReactiveFormsModule } from '@angular/forms';
import { AppComponent } from './app.component';
import { TopBarComponent } from './top-bar/top-bar.component';
import { HttpClientModule } from '@angular/common/http';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

import { MatIconModule } from '@angular/material/icon';
import { AuthService } from './services/auth.service';

import { AngularFireModule } from '@angular/fire';
import { environment } from '../environments/environment';
import { AngularFireAnalyticsModule } from '@angular/fire/analytics';
import { AngularFirestoreModule } from '@angular/fire/firestore';

@NgModule({
  imports: [
    BrowserModule,
    HttpClientModule,
    ReactiveFormsModule,
    RouterModule.forRoot([
    ]),
    BrowserAnimationsModule,
    MatIconModule,
    AngularFireModule.initializeApp(environment.firebase),
    AngularFireAnalyticsModule,
    AngularFirestoreModule
  ],
  declarations: [
    AppComponent,
    TopBarComponent
  ],
  bootstrap: [ AppComponent ],
  providers: [AuthService]
})
export class AppModule { }
```

**Comment by Splaktar** [comment]
Do you have a StackBlitz example that could be used to debug this?

Have you tried importing `AngularFireAuthModule`?

**Comment by nikmartin** [comment]
I get the exact same error. here's a repo:
https://stackblitz.com/edit/angular-fire-start-m9eqpr?file=app%2Fapp.module.ts
AngularFireAuthModule is able to be added with no issues

**Comment by nikmartin** [comment]
Edit: here is a fresh fork of a minimal repro:
https://stackblitz.com/edit/angular-fire-start-lxnywr

The error is: 
`Error in /turbo_modules/@angular/fire@6.0.0/bundles/angular-fire-functions.umd.js (36:44)
app.functions is not a function`

**Comment by jamesdaniels** [comment]
Should be functioning much much better with the release of Firebase v8. I recommend everyone jump to that ASAP.

**Comment by ElCarsten** [comment]
In my case I had to remove this

`import { FirebaseApp } from '@angular/fire';`

and this line

`providers: [
        FirebaseApp,
...`
in app.module.ts

I don't know why I added them (it was during an upgrade process to resolve another error).

Anyway both errors are gone right now and everything works well. I thought this might help someone.
