### ISSUE TITLE
Disable hell of warnings.

### ISSUE THREAD

**Issue by Smiranin** [angular/angularfire#2465]
Hello! 
How I can disabled warnings in angularfire?

<img width="1433" alt="Screenshot 2020-05-20 at 11 08 46" src="https://user-images.githubusercontent.com/14183958/82422040-9b4e8480-9a8a-11ea-9d2e-a3f17e5bd79b.png">

**Comment by Splaktar** [comment]
Have you tried adding the `.indexOn` setting as suggested?

Some other suggested fixes are mentioned [here](https://stackoverflow.com/q/43260689/633107) and the official docs on this are [here](https://firebase.google.com/docs/database/security/indexing-data).

**Comment by Smiranin** [comment]
@Splaktar Tnx, I understand i can fix warnings  by doing their suggestions! But I ask, how I can disable any console warnings. Many libraries and frameworks have such setting. I think firebase should has too.

**Comment by jamesdaniels** [comment]
I'd suggest you file [over on the JS SDK](https://github.com/firebase/firebase-js-sdk/issues).
