### ISSUE TITLE
Property 'listCollections' does not exist on type 'AngularFirestoreDocument<unknown>'.

### ISSUE THREAD

**Issue by csudarshan259** [angular/angularfire#2467]
When will listCollections property be available for angularfire:?

**Comment by wiedzmin26** [comment]
@csudarshan259 Can you find it in https://firebase.google.com/docs/reference/js/firebase.firestore ? I can't find it in JavaScript SDK

**Comment by csudarshan259** [comment]
It's available for node.js but not for web. https://firebase.google.com/docs/firestore/query-data/get-data

**Comment by wiedzmin26** [comment]
nodeJS SDK is for backend side, not frontend side.
