### ISSUE TITLE
In vs code, package version 6.0.0 auto imports the breaking package '@angular/fire/firestore/firestore' instead of '@angular/fire/firestore'

### ISSUE THREAD

**Issue by moscoso** [angular/angularfire#2474]
### Version info

**Angular:** 

**Firebase:**

**AngularFire:** 6.0.0

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

In an Angular project, try to inject AngularFirestore as a depedency: 

@Component({
    'selector': 'app-create',
    'templateUrl': './create.page.html',
    'styleUrls': ['./create.page.scss'],
})
export class CreatePage implements OnInit {

    constructor(
        public angularFire: AngularFirestore,
    ) {}
} 

### Expected behavior

Vs code to auto import 
import { AngularFirestore } from '@angular/fire/firestore';

### Actual behavior

import { AngularFirestore } from '@angular/fire/firestore/firestore;

**Comment by jamesdaniels** [comment]
Not a AngularFire issue IMO and I haven't seen it in a while, did VS Code fix this?
