### ISSUE TITLE
Registration failed - push service error

### ISSUE THREAD

**Issue by pgedzba** [angular/angularfire#2475]
### Version info

**Angular:**9.1.9

**Firebase:**7.14.4

**AngularFire:**6.0.0

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**Brave/Chrome

### How to reproduce these conditions

After logging in I am calling this function:
![image](https://user-images.githubusercontent.com/26221715/82792864-52bf0e80-9e70-11ea-997c-c6a421f0fa4d.png)
It returns an error on line 57, which is described below. If I remove **requestToken** and change it to **requestPermission** then there is no error, but I am not receiving any messages.

I have VAPID key from firebase cloud messaging.

Below is full messaging.service.ts
`
@Injectable()
export class MessagingService {

    currentMessage = new BehaviorSubject(null);

    constructor(
        private angularFireDB: AngularFireDatabase,
        private angularFireAuth: AngularFireAuth,
        private angularFireMessaging: AngularFireMessaging,
        private httpClient: HttpClient) {
        this.angularFireMessaging.usePublicVapidKey(environment.VAPID_KEY);
        // this.angularFireMessaging.messaging.subscribe(
        //     (_messaging) => {
        //         _messaging.onMessage = _messaging.onMessage.bind(_messaging);
        //         _messaging.onTokenRefresh = _messaging.onTokenRefresh.bind(_messaging);
        //     }
        // );
    }

    /**
     * update token in firebase database
     *
     * @param userId userId as a key
     * @param token token as a value
     */
    updateToken(userId, token) {
        // we can change this function to request our backend service
        this.angularFireAuth.authState.pipe(take(1)).subscribe(
            () => {
                const data = {};
                data[userId] = token;
                this.httpClient.post(environment.API_URL + '/api/device_tokens', { token }).subscribe();
                this.angularFireDB.object('fcmTokens/').update(data);
            });
    }

    /**
     * request permission for notification from firebase cloud messaging
     * 
     * @param userId userId
     */
    requestPermission(userId) {
        this.angularFireMessaging.requestToken.subscribe(
            (token) => {
                this.updateToken(userId, token);
            },
            (err) => {
                console.error('Unable to get permission to notify.', err);
            }
        );
    }

    /**
     * hook method when new notification received in foreground
     */
    receiveMessage() {
        this.angularFireMessaging.messages.subscribe(
            (payload) => {
                this.currentMessage.next(payload);
            });
    }
}
`

### Debug output

** Errors in the JavaScript console **
`messaging.service.ts:57 Unable to get permission to notify. DOMException: Registration failed - push service error`

![image](https://user-images.githubusercontent.com/26221715/82792831-489d1000-9e70-11ea-9caa-127f68244486.png)

### Expected behavior

Notifications should register

### Actual behavior

I get an error

**Comment by naveedahmed1** [comment]
Any update on this?

**Comment by pgedzba** [comment]
I didn't find the solution yet

**Comment by naveedahmed1** [comment]
Its strange that its working on some devices and throwing this error on other devices.

**Comment by naveedahmed1** [comment]
@pgedzba can you please check if it's working on Firefox on same machine? In my case it's working fine on Firefox but throwing error in Chrome.

**Comment by pgedzba** [comment]
I can not install any other browser on this machine

**Comment by shadow1349** [comment]
I've been having a similar problem specifically on Brave:

![push service error](https://user-images.githubusercontent.com/9685464/96356249-7f8af100-10b1-11eb-822f-4a66b107c9da.png)

This one has been particularly annoying because I can't use any of my callable functions on Brave without getting this exact same error which is just plain weird.

**Comment by jamesdaniels** [comment]
Closing here in favor of the js sdk bug, as it's not AngularFire specific.
