### ISSUE TITLE
Foreground and background notifications work well in the localhost and not working in the https. In https only working background notification using firebase 7.6.0

### ISSUE THREAD

**Issue by karthik11788** [angular/angularfire#2477]
### Version info

**Angular:**

**Firebase:**

**AngularFire:**

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

**Comment by hiepxanh** [comment]
please provide the basic repository, more information, basicly, I'm working with noti and it doesn't have any problem

**Comment by jamesdaniels** [comment]
Closing since lack of details.
