### ISSUE TITLE
Feature Request - Release this plugin as ES2015 module

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angularfire#2478]
When compiling Angular project with latest version of Angular CLI it throws below warning:

```
node_modules\@angular\fire\__ivy_ngcc__\fesm2015\angular-fire.js depends on firebase/app. CommonJS or AMD dependencies can cause optimization bailouts.

node_modules\firebase\app\dist\index.cjs.js depends on @firebase/app. CommonJS or AMD dependencies can cause optimization bailouts.
```

Google advises against using CommonJS modules because it can impact the tree-shaking of application as explained here https://web.dev/commonjs-larger-bundles/

I would therefore request you to please release this plugin as es2015 module.

Thank you

**Comment by rodolfojnn** [comment]
same here on Angular 10

**Comment by jamesdaniels** [comment]
This library is released as es2015 and abides by APF, however Firebase's main package is a CJS whereas Angular expects it to be a UMD. We can't change that until at least the next major. Please raise over there, https://github.com/firebase/firebase-js-sdk.

In the meantime, I've been working on a possible work-around for Angular developers using [`ngcc.config.js`](https://github.com/angular/angularfire/blob/master/sample/ngcc.config.js) which allows one to override the package.json for modules. This seems to be working much better for me in NG 10 but spits out a lot of errors as many of the Firebase JS SDK sub-packages are referencing the same `.d.ts` files, with `ngcc` complains about quite loudly.

**Comment by jamesdaniels** [comment]
Closing as it's not an issue with AngularFire, feel free to continue discussing. Pinning since I expect a lot of duplicate issues here.

FYI @Feiyang1 @StephenFluin

**Comment by naveedahmed1** [comment]
Thank you so much @jamesdaniels for explaining this, I'd wait for your possible work-around and will also post it on https://github.com/firebase/firebase-js-sdk .

**Comment by naveedahmed1** [comment]
Here's the link to feature request on `firebase-js-sdk` https://github.com/firebase/firebase-js-sdk/issues/3315
