### ISSUE TITLE
Getting started with AngularFire and Universal outdated

### ISSUE THREAD

**Issue by robindijkhof** [angular/angularfire#2480]
### Version info

**Angular:** Lastest (9.1.9)

**Firebase:**

**AngularFire:**

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

Create a new project with the CLI
Execute the steps provided in " Getting started with AngularFire and Universal" https://github.com/angular/angularfire/blob/master/docs/universal/getting-started.md

### Expected behavior

I should have a basic project which can be served using Angular Universal

### Actual behavior

When serving I get the following error:
Error: ENOENT: no such file or directory, open '/path/to/project/projectname/dist/projectname/index.html'

**Comment by hiepxanh** [comment]
PR coming to rescuse https://github.com/angular/angularfire/pull/2372
preview: https://github.com/angular/angularfire/blob/a45e0ad4f1c918e78a1610d2b73dee3cc9b1f6b1/docs/universal/getting-started.md
But it not allow to merge yet 😄

**Comment by BianchiSeb** [comment]
Hello angularFire team. I literally spend a ton of money in your app for my clients. At least answer us. It’s a shame that core features are broken. 
It’s a shame you don’t manage the PR. 
At least give us back the projets lead and we can manage it like a TRUE open source project.
