### ISSUE TITLE
Is this repository still maintained?

### ISSUE THREAD

**Issue by vandres** [angular/angularfire#2481]
I think there a lot of big issues in the current ^6.0, but there is very little response. I am loving the way of using Firebase the Angular way and I am sorry to ask this, but is this repository still maintained?

**Comment by hiepxanh** [comment]
Currently, there is alot of PR, there is only @jamesdaniels maintain it but he seem busy now. @davideast is seem very busy on firebase HQ.

**Comment by hiepxanh** [comment]
I would like to maintain it but don't know how 😄

**Comment by jamesdaniels** [comment]
Yes. We've been a bit busy though, welcome any assistance. I'm hoping to start cutting fixes pretty rapidly this week.

**Comment by vandres** [comment]
Very glad to hear that!
