### ISSUE TITLE
Cloud Storage not compatible with Angular Ivy

### ISSUE THREAD

**Issue by longcharmroeun** [angular/angularfire#2491]
### Version info

**Angular:**  9.1.7

**Firebase:**  8.4.2

**AngularFire:** 6.0.0

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

**Node:** v12.18.0
**Browser:** chrome
**OS:** windows 10 Pro

**Steps to set up and reproduce**

**Sample data and security rules**

### Debug output

**Errors in the JavaScript console**

```
ERROR in node_modules/@angular/fire/storage/storage.d.ts:16:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library (@angular/fire/storage) which declares AngularFireStorage has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
```
** Screenshots **

![package json - website - Visual Studio Code 6_8_2020 6_21_42 PM](https://user-images.githubusercontent.com/42161560/84024946-f5b97180-a9b4-11ea-8d0e-9704bff611c0.png)

**Comment by vandres** [comment]
Did you import the AngularFireStorageModule in your app.module.ts?

**Comment by jamesdaniels** [comment]
Import from `@angular/fire/storage` instead of `@angular/fire/storage/storage`

**Comment by longcharmroeun** [comment]
> Did you import the AngularFireStorageModule in your app.module.ts?

I already important it.

**Comment by longcharmroeun** [comment]
> Import from `@angular/fire/storage` instead of `@angular/fire/storage/storage`

I already important it.

**Comment by longcharmroeun** [comment]
The problem solved after I restarted my IDE.
I'm still don't know what is the problem yet.

**Comment by abuyukkilic** [comment]
After restarting ide, this problem solved...
