### ISSUE TITLE
this.afs.collectionGroup()).get() not returning Promise

### ISSUE THREAD

**Issue by ali-ajam** [angular/angularfire#2492]
### Version info

**Angular:**
"@angular/cdk": "^9.2.2"
**Firebase:**
"firebase": "^7.14.2",
**AngularFire:**
"@angular/fire": "^6.0.0",

** Screenshots **

![image](https://user-images.githubusercontent.com/24878772/84174671-825f4080-aa44-11ea-962c-9160246cdb12.png)

### Expected behavior

this.afs.collectionGroup('profile', ref => ref.orderBy('uid')).get() expected behavior is returning Promise

### Actual behavior

this.afs.collectionGroup('profile', ref => ref.orderBy('uid'))  returns observable

**Comment by yasinkocak** [comment]
if u want returning Promise then use following
```js
return new Promise(() => this.afs.collectionGroup('profile', ref => ref.orderBy('uid')).get());
```

**Comment by ali-ajam** [comment]
Thanks for the reply, I put this as a bug since per angular fire documentation this supposed to return Promise and might confuse other developers as well.
