### ISSUE TITLE
How to  change path where firebase-analytics.js & firebase-auth.js are loaded from?

### ISSUE THREAD

**Issue by koraysels** [angular/angularfire#2493]
### Version info

**Angular: 9.1.7**

**Firebase: 7.15.0**

**AngularFire: 6.0.0 **

### How to reproduce these conditions
When using angular/fire and the root domain is not the same as the base from angular app , these files still try to get loaded from the root. 

How to  change path where firebase-analytics.js & firebase-auth.js are loaded from?

**Comment by yasinkocak** [comment]
use in html
```
<base href="/">
```

**Comment by koraysels** [comment]
The problem is I have bootstrapped multiple components in a wordpress website. So If I change the base href, my entire wordpress theme loads assets relative to this path. Is there a way to have the paths be programmatically written during build ?

**Comment by jamesdaniels** [comment]
I'm sure there's some flag in webpack to rewrite the paths of the dynamic imports... but I'm not sure what that would be. Feel free to continue discussing, but closing as it's out of scope for the library.
