### ISSUE TITLE
Inferred types of default AuthPipes are incompatible with `AuthPipe` under TypeScript strict mode

### ISSUE THREAD

**Issue by wSedlacek** [angular/angularfire#2494]
### Version info

**Angular: 9.1.9

**Firebase: 7.14.6

**AngularFire: 6.0.0

### How to reproduce these conditions

`app-routing.module.ts`
```ts
import {
  AuthPipeGenerator,
  canActivate,
  redirectUnauthorizedTo,
} from '@angular/fire/auth-guard';

const redirectUnauthorizedToLogin: AuthPipeGenerator = () => redirectUnauthorizedTo(['login']);
```

With Strict mode enabled.
`tsconfig.json`
```json
{
  ...
  "compilerOptions": {
    ...
    "strict": true,
  },
}
```

### Debug output

```
Type 'UnaryFunction<Observable<User>, Observable<true | any[]>>' is not assignable to type 'AuthPipe'.ts(2322)
```

### Expected behavior

`redirectUnauthorizedTo` should return the shape of `AuthPipe` even while under Strict mode.

### Actual behavior

`redirectUnauthorizedTo` and a few other helper pipes have the typing of `UnaryFunction<Observable<User>, Observable<true | any[]>>`

**Comment by koraysels** [comment]
any idea how to fix this ? because i have the same issues ...

**Comment by wSedlacek** [comment]
Type cast the result of your Sigh pipe factories with `as` as a temporary work around.

**Comment by koraysels** [comment]
But now when i fix this i get cyclic dependency errors.. super weird

Sorry for being brief, sent from my iPhone

**Comment by wSedlacek** [comment]
@koraysels looks like my patch got merged. If you are still having issues after that lands you may want to see if there's another issue that more closely resembles the circlet dependencies you described or create a new issue.
