### ISSUE TITLE
AngularFirePerformance Error: Trace was started before

### ISSUE THREAD

**Issue by shadow1349** [angular/angularfire#2501]
I am trying to use Firebase Performance to track how long users spend on certain pages. To do this I have created a custom decorator that overrides ngOnInit and ngOnDestroy

```typescript
import { AngularFirePerformance, trace } from '@angular/fire/performance';
import { AppModule } from 'src/app/app.module';
export function MonitorComponentPerformance(data: {
  pageName?: string;
  traceName: string;
}): ClassDecorator {
  return function (constructor: Function) {
    const performance = AppModule.injector.get(AngularFirePerformance);
    const trace = performance.trace(`${data.traceName} page`);
    const onInit: Function = constructor.prototype.ngOnInit;
    const onDestroy: Function = constructor.prototype.ngOnDestroy;
    constructor.prototype.ngOnInit = function (...args) {
      trace.then((t) => {
        t.start();
      });
      onInit && onInit.apply(this, args);
    };
    constructor.prototype.ngOnDestroy = function (...args) {
      trace.then((t) => {
        t.stop();
      });
      onDestroy && onDestroy.apply(this, args);
    };
  };
}
```

It works just fine the first time I enter and leave a page, but if I go back I get the following error 

`FirebaseError: Performance: Trace dashboard goals was started before. (performance/trace started).`
 
After stepping through the code I have verified that the trace is stopped before a new one is started and that the names for the traces are accurate.

### Version info

**Angular:** 9.1.11

**Firebase:** 7.15.0

**AngularFire:** 6.0.0

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
Chome/FireFox/Brave tested on Windows/Mac/Linux.

### How to reproduce these conditions

**Failing test unit, Stackblitz demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

### Debug output

** Errors in the JavaScript console **
`FirebaseError: Performance: Trace dashboard goals was started before. (performance/trace started).`

** Screenshots **
![Screenshot from 2020-06-13 11-27-26](https://user-images.githubusercontent.com/9685464/84574704-dda77080-ad6d-11ea-9c95-fd3cceb25994.png)

### Expected behavior

I want to be able to monitor how long a user spends on a page using a custom decorator and a custom trace.

### Actual behavior

My trace wont start a second time because it says the trace has already been started, even though I verified that the `stop()` method had been called on the trace.

**Comment by jamesdaniels** [comment]
You need to create a fresh trace object or file a feature request against the JS SDK.
