### ISSUE TITLE
How to deploy SSR and Prerender app in Firebase?

### ISSUE THREAD

**Issue by jeslomo** [angular/angularfire#2508]
### Version info

**Angular:** 9.1.11

**Firebase:** 7.15.1

**AngularFire:** 6.0.0

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** Node 10

### How to reproduce these conditions

**Steps to set up and reproduce**

```
ng new TestSSRAndPrerendering

ng add @nguniversal/express-engine

ng add @angular/fire (with option "We detected an Angular Universal project. Do you want to deploy as a Firebase Function? Yes")

npm run prerender
```

### Expected behavior

I would like that when doing "ng deploy" the web were published having 2 behaviors. 1, that the URLs chosen as "prerender" will be prerendered and those that are not, will be rendered via SSR.

### Actual behavior

When i run "npm run prerender" and "ng deploy", fist generate code in "dist/<name-project>/browser" and server and the last statement generate code in "dist/<name-project>/dist/<name-project>/broswer and server" and this is what is finally uploaded and executed by the Firebase Function, and this is what is finally uploaded and executed by the function, ignoring what the "prerender" statement generated.

**Comment by yasinkocak** [comment]
Follow this docs: https://github.com/angular/angularfire/blob/master/docs/deploy/getting-started.md

**Comment by jeslomo** [comment]
> Follow this docs: https://github.com/angular/angularfire/blob/master/docs/deploy/getting-started.md

Sorry, you may not have explained me well. The "ng deploy" command only builds the application in SSR mode, it does not build it in "prerender" mode. What I want is to build some pages in "prerender" mode and others in SSR mode.

The repository documentation also talks about the old way of doing it, it is not updated to Angular 9.

**Comment by jamesdaniels** [comment]
I'm hoping to support prerendering in `ng deploy` in an upcoming release, it is not currently supported.
