### ISSUE TITLE
bundleDependencies warning on 'ng deploy'

### ISSUE THREAD

**Issue by jdgamble555** [angular/angularfire#2509]
### Version info

**Angular:** 9.1.11

**Firebase:** 7.15.1

**AngularFire:** 6

When you run **ng deploy** you get this warning:

`Option 'bundleDependencies' string value is deprecated since version 9. Use a boolean value instead.`

This can easily be fixed by changing the value to **true** in the core code.

**Comment by jamesdaniels** [comment]
Not an issue with AngularFire, as we don't manage your `angular.json` for you beyond flipping a couple flags when you `ng add @angular/fire`. 

You'll need to adjust that yourself.

**Comment by GrandSchtroumpf** [comment]
@jamesdaniels looks like the problem comes from the [deploy builder](https://github.com/angular/angularfire/blob/master/src/schematics/deploy/builder.ts#L48). I'm not sure it's possible to adjust that ourselves.

**Comment by jdgamble555** [comment]
@jamesdaniels Can we please reopen this issue or fix it? It is a simple fix as @GrandSchtroumpf said!
