### ISSUE TITLE
CORS  error in Cloud Function

### ISSUE THREAD

**Issue by weilies** [angular/angularfire#2512]
### Version info

**Angular:** 9.1.9

**Firebase:** 7.14.6

**AngularFire:**^6.0.0

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### Debug output

Access to fetch at 'https://us-central1-<my-project-id>cloudfunctions.net/helloWorld' from origin 'https://<project id from GCP>-devshell.appspot.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

### Expected behavior
I followed the documentation from [GitHub](https://github.com/angular/angularfire/blob/24734fffc544f796162bc5daef498b7b08145688/docs/functions/functions.md)
I am expecting the angular app could run on GCP (my development app), as well as in firebase hosting.

**cloud function index.ts**
```
export const helloWorld = functions.https.onRequest((request, response) => {

    response.send("Hello from Firebase!");
});

```

**angular TS**
```
import { AngularFireFunctions } from "@angular/fire/functions";
import { Observable } from "rxjs";
....
    onTestCloudFunc() {
        console.log('calling onTestCloudFunc()')
        const callable = this.afFnc.httpsCallable("helloWorld");
        this.data = callable({ name: 'some-data' });

    }
```
**angular template**
```
    <div>
    <button pButton label="Call Cloud Fn" (click)="onTestCloudFunc()"></button>
    <div>Data: {{data  | async}}</div>
    </div>
```

**Firebase.json**
```
  "hosting": {
    "public": "dist/airworkz",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "/<my project id>/us-central1/helloWorld",
        "function": "helloWorld"
      },
      {
        "source": "/<my project id>/us-central1/reqWithParam",
        "function": "reqWithParam"
      }
```

To return "Hello firebase..." when angular app clicked

### Actual behavior
Hit error under chrome console
Access to fetch at 'https://us-central1-<my-project-id>cloudfunctions.net/helloWorld' from origin 'https://<project id from GCP>-devshell.appspot.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by weilies** [comment]
cancel as resolved myself

**Comment by quedicesebas** [comment]
How to achieve this with functions v2?
