### ISSUE TITLE
use CI system --token flag on ng deploy

### ISSUE THREAD

**Issue by yasinkocak** [angular/angularfire#2523]
**Angular:*9.1.11*

**Firebase:*7.15.4*

**AngularFire:*6.0.2*

For Ci/CD want use Ci system of firebase-tools:
https://www.npmjs.com/package/firebase-tools#using-with-ci-systems

ng deploy is not possible to use --token flag

**Steps to set up and reproduce**

On bitbucket pipeline use --token flag
`ng deploy --token= $FIREBASE_TOKEN

### Expected behavior

Deploying to firebase hosting,functions

### Actual behavior

get error 
Unknown option: '--token'

**Comment by yasinkocak** [comment]
#2525

**Comment by BianchiSeb** [comment]
Hello angularFire team. I literally spend a ton of money in your app for my clients. At least answer us. It’s a shame that core features are broken. 
It’s a shame you don’t manage the PR. 
At least give us back the projets lead and we can manage it like a TRUE open source project.

**Comment by leblancmeneses** [comment]
work around:
```
 npm run build:staging 

 npx firebase deploy --token $npm_package_config_token
```
configure .firebaserc to use targets

**Comment by YogliB** [comment]
any progress on this issue?

**Comment by jamesdaniels** [comment]
This API is now available in `6.1`

**Comment by stevebrowndotco** [comment]
After seeing that this was resolved, I tested `ng deploy --token {TOKEN}` and i still get "Unknown option: '--token'" . What am I doing wrong?

**Comment by danieldanielecki** [comment]
I'm on `@angular/fire` version `6.1.4` and with `ng deploy --token $ACCESS_TOKEN_FIREBASE` I'm getting `Cannot run login in non-interactive mode. See login:ci to generate a token for use in non-interactive environments.`

I've noticed `Firebase` has changed the way of handling CI for SSR, now the automatically generated in `package.json` scripts `predeploy` and `deploy` aren't that useful. Especially with the new setup for `.firebaserc` for which I couldn't find any official documentation, just some StackOverflow... Mayday.

**Comment by RezaRahmati** [comment]
using `@angular/fire: 6.1.4` and still same error

```
 ng deploy landing --configuration='production' --token 1/omytoken
Unknown option: '--token'
Unknown option: '1/omytoken'
```

**Comment by vvvhung** [comment]
From @RezaRahmati story, I realized that within FIREBASE_TOKEN env variable, `ng deploy` can run well (without `--token $ACCESS_TOKEN_FIREBASE`)
