### ISSUE TITLE
Won't build with Angular 10

### ISSUE THREAD

**Issue by shadow1349** [angular/angularfire#2526]
When I try to build or run my project it won't do either. It says that `ModuleWithProviders<T>` requires 1 type argument (screenshot attached below).

### Version info

**Angular:** 10.0.1

**Firebase:** 7.15.1

**AngularFire:** 6.0.2

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

Create an Angular 10 project (with @angular/core version 10.0.1). Add @angular/fire libary. Try to build. 

### Expected behavior

I should be able to build and run the project.

### Actual behavior

![Screenshot from 2020-06-26 23-42-45](https://user-images.githubusercontent.com/9685464/85914803-5fd07400-b807-11ea-823a-439ea1097725.png)

**Comment by shadow1349** [comment]
I tried downgrading to 10.0.0 and I got the same behavior.

**Comment by Mihai-MCW** [comment]
You may want to check [this  link](https://github.com/angular/angularfire/issues/2267) . It seems to me like support is only offered up to 8, but I could be wrong.

**Comment by shadow1349** [comment]
@Mihai-MCW according to their changelog, 6.0.2 shoud work on angular 10 https://github.com/angular/angularfire/blob/master/CHANGELOG.md

**Comment by fritzschoff** [comment]
+1

**Comment by yasinkocak** [comment]
I made a PR for this

**Comment by shadow1349** [comment]
@yasinkocak thank you!

**Comment by DominikDitoIvosevic** [comment]
I have the same problem. Can I just copy paste this here firestore.module.d.ts:7:74 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s). because this is how I googled for the issue and didn't get any results

**Comment by BianchiSeb** [comment]
Hello angularFire team. I literally spend a ton of money in your app for my clients. At least answer us. It’s a shame that core features are broken. 
It’s a shame you don’t manage the PR. 
At least give us back the projets lead and we can manage it like a TRUE open source project.

**Comment by kaptain-ti** [comment]
set enableIvy to true in tsconfig and tsconfig.app

**Comment by shadow1349** [comment]
@kaptain-ti I had to turn that off because I was using a custom decorator which is not supported by Ivy yet. If that issue is fixed in angular 10 then I will be able to turn ivy back on

**Comment by vtregner** [comment]
Fix is already merged to master, but not released. Can you release new version? Due this issue I cannot update my library to Angular 10...

**Comment by Kungitoo** [comment]
Wow, over 1 month for a type fix

**Comment by shadow1349** [comment]
@vtregner you can install the canary version `npm i @angular/fire@canary` that has the fix in and is fully working.

**Comment by hlpupo** [comment]
I have the same problem, any update?

**Comment by fritzschoff** [comment]
@hlpupo like @shadow1349  suggested, use the canary version. `npm i @angular/fire@canary`

**Comment by djabif** [comment]
Is there an estimated date for releasing 6.0.3?

> Fix is already merged to master, but not released. Can you release new version? Due this issue I cannot update my library to Angular 10...

**Comment by taylormills** [comment]
The fix for this was merged over 2 months ago, what's the hold up on releasing? I would rather not have production code relying on a canary version.

**Comment by Kungitoo** [comment]
@davideast @jeffbcross can we in any way help speed up the process in general? I would really like to help blockers like these go into production code sooner. Angular 11 is around the corner and we still cannot build all stable libraries with 10

**Comment by vtregner** [comment]
It seems the project is dead. Unbelievable ignorance.

**Comment by Splaktar** [comment]
With the fix for https://github.com/angular/angularfire/issues/2505 getting into the latest Canary, it looks like (based on https://github.com/angular/angularfire/issues/2505#issuecomment-698097239) that a `6.0.3` release is coming very soon.

**Comment by Splaktar** [comment]
I found another place where `ModuleWithProviders` is needed and fixed it in PR: https://github.com/angular/angularfire/pull/2598.
