### ISSUE TITLE
Error in firebase.analytics() when open browser in incognito mode

### ISSUE THREAD

**Issue by jet-lee-m** [angular/angularfire#2530]
### Version info

Angular: 9.0.5
Firebase: 7.14.5
AngularFire: 5.2.1

### How to reproduce these conditions

Call firebase.analytics() in app.component.ts and  open website in firefox incognito mode cause an error in browser console.

### Debug output

I get the following message in browser console:

"ERROR Error: "Uncaught (in promise): InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.""

### Expected behavior

No error in console.

### Actual behavior

Got an error in browser console and analytics not work.

**Comment by jamesdaniels** [comment]
Please open an issue over on the [Firebase JS SDK](https://github.com/firebase/firebase-js-sdk) side, as we just wrap them. Looks like remote config is also unhappy in Firefox private browsing too FWIW.
