### ISSUE TITLE
TypeError: e.__spreadArrays is not a function

### ISSUE THREAD

**Issue by pradeepKaatnam** [angular/angularfire#2532]
Application startup is failing with below error for the below mentioned configuration.

**TypeError: e.__spreadArrays is not a function**
![image](https://user-images.githubusercontent.com/12966342/86484865-cf4ce300-bd74-11ea-9c82-07cf1ee6b6f5.png)

**Angular:** 5.2.11

**Firebase:** 7.15.5

**AngularFire:** 6.0.2

**Ionic: ** 3.9.2

Note: I have used npm install since it is an ionic application

**Comment by yasinkocak** [comment]
How we can reproduce this?

**Comment by jamesdaniels** [comment]
Sounds like your missing tslib.
