### ISSUE TITLE
NodeJs crashes when using along Angular Universal

### ISSUE THREAD

**Issue by gcamara** [angular/angularfire#2533]
### Version info

**Angular:** 10

**Firebase:** 8.4.3

**AngularFire:** 6.0.2

### How to reproduce these conditions

**Steps to set up and reproduce**

1. Create a new Angular project (or use an existing one)
2. Install Angular Universal dependencies
  ``ng add @nguniversal/express-engine`` 
3. Install Angular Fire dependencias
  ``ng add @angular/fire`` 
4. Setup the project following the quickstart guide
5. Create a simple service injecting `AngularFireDatabase`
6. Create a function that returns `database.list().valueChanges()` or `database.list().stateChanges()` observable
7. Create a function on any component that consumes the early created service
8. Run `npm run dev:ssr`

At this point, some warnings are fired, but they can be easily solved by adding dependencies on ``angular.json`` file.
The project builds smoothly, but the application crashes when opened in browser.

**IMPORTANT**
The same does not happen when running via `ng serve` command

### Debug output

**Warnings**
![image](https://user-images.githubusercontent.com/4623526/86494137-75cfbe80-bd4a-11ea-8566-beaab0db03a2.png)

**App Crashing**
![image](https://user-images.githubusercontent.com/4623526/86494146-82541700-bd4a-11ea-825a-11c7ed764da1.png)

### Expected behavior

The application keeps running 

### Actual behavior

The application crashes on open

**Comment by jamesdaniels** [comment]
This should be addressed in all the latest versions. Database is working in SSR in my tests.
