### ISSUE TITLE
Add Documentation for DI AngularFire dynamically

### ISSUE THREAD

**Issue by ajonp** [angular/angularfire#2538]
I would like to create some documentation within the repo to better demonstrate how to use AngularFire in multiple instances within an application.

@jamesdaniels and I had a great discussion on this topic on twitter

https://twitter.com/CodingCatDev/status/1259104571688976385?s=20

I would love to create some stackblitz examples and document the multiple varieties in which this might occur for people using the app. Here is an example where I am using the Firebase Management API to look for my projects, but then logging into each project with another separate user.

https://res.cloudinary.com/ajonp/video/upload/v1594251437/ajonp-ajonp-com/Screen_Recording_2020-07-08_at_7.24.28_PM.webm

**Comment by jamesdaniels** [comment]
Addressed in the v7 modular API, you can now provide / inject multiple instances.
