### ISSUE TITLE
WARNING in ./node_modules/@angular/fire/fesm2015/angular-fire-auth.js 91:137-145

### ISSUE THREAD

**Issue by indraraj26** [angular/angularfire#2540]
### Version info

**Angular:**  Angular: 7.0.4

**Firebase:**     "firebase": "^7.16.0",

**AngularFire:**@angular/fire  6.0.2

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**  Browser

### How to reproduce these conditions

**Failing test unit, Stackblitz demonstrating the problem**

**Steps to set up and reproduce**

Repo: https://github.com/indraraj26/angular-testing/tree/extra-routes
Branch: extra-routes
Step: npm install && ng serve -o

**Sample data and security rules**

### Debug output

** Errors in the Terminal console **
```
error :
WARNING in ./node_modules/@angular/fire/fesm2015/angular-fire-auth.js 91:43-61
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@angular/fire/fesm2015/angular-fire-auth.js 91:137-145
"export 'ɵɵinject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/fire/fesm2015/angular-fire-auth.js 91:165-173
"export 'ɵɵinject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/fire/fesm2015/angular-fire-auth.js 91:197-205
"export 'ɵɵinject' was not found in '@angular/core'

WARNING in ./node_modules/@angular/fire/fesm2015/angular-fire-auth.js 91:220-228
"export 'ɵɵinject' was not found in '@angular/core'
```

** Errors in the Browser console **
```

Uncaught TypeError: Object(...) is not a function
    at Module../node_modules/@angular/fire/fesm2015/angular-fire-auth.js (angular-fire-auth.js:91)
    at __webpack_require__ (bootstrap:83)
    at Module../src/app/app.component.ts (main.js:131)
    at __webpack_require__ (bootstrap:83)
    at Module../src/app/app.module.ts (app.component.ts:11)
    at __webpack_require__ (bootstrap:83)
    at Module../src/main.ts (main.ts:1)
    at __webpack_require__ (bootstrap:83)
    at Object.0 (main.ts:12)
    at __webpack_require__ (bootstrap:83)
```
** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

### Expected behavior

It should not through any error
### Actual behavior

App is not getting compile with this pkg

**Comment by neryortez** [comment]
I'm not sure. but I believe v6 of angular/fire does not support Angular v7

**Comment by indraraj26** [comment]
Where i can find docs of deprecated/remove change log and support version compatible

**Comment by neryortez** [comment]
The part of the changelog that interests you is this:
https://github.com/angular/angularfire/blob/master/CHANGELOG.md#600-rc0-2020-01-30

**Comment by indraraj26** [comment]
Thank you @neryortez
