### ISSUE TITLE
FCM - open notifications do not count

### ISSUE THREAD

**Issue by miguelsmuller** [angular/angularfire#2541]
Hi Guys,

I implemented FCM on my PWA. It works for receiving messages. I received the message myself. I clicked on the notification and it was not counted by on the dashboard. I believe that other users have also clicked and also not been counted. The open notification number is 0.

do i need to do any more configuration to count the openings?

![fcm](https://user-images.githubusercontent.com/4589909/87303590-cfbe4a00-c4e9-11ea-8347-23c122cfceda.png)

**Comment by jamesdaniels** [comment]
I do not believe Analytics for the web supports FCM delivery reports, I'd suggest opening up a feedback issue with Firebase support. 

If there is something that can be done with Google Analytics and FCM on the web, get back at me, as I think it would make a fine addition to AngularFire or the Firebase JS SDK itself.
