### ISSUE TITLE
AngularFireAnalyticsModule Missing App configuration value: "appId"

### ISSUE THREAD

**Issue by doczoidberg** [angular/angularfire#2543]
I did include AngularfireAnalyticsModule as described in the docs:
```

   AngularFireModule.initializeApp(environment.firebase),
    AngularFireAnalyticsModule;
```

in my environemt.firebase it includes the appID and measurementID, But I get the error:

### Debug output

```
Installations: Missing App configuration value: "appId" (installations/missing-app-config-values). ; Zone: <root> ; Task: Promise.then ; Value: FirebaseError: Installations: Missing App configuration value: "appId" (installations/missing-app-config-values).
    at getMissingValueError (http://localhost:4200/firebase-analytics.js:1912:26)
    at extractAppConfig (http://localhost:4200/firebase-analytics.js:1893:23)
```

### Version info

**Angular:**
10.0.3

**Firebase:**
7.16.0

**AngularFire:**
6.0.2

**Comment by rubenheymans** [comment]
do you have an appId in your environment file?
` AngularFireModule.initializeApp(environment.firebase),`

**Comment by doczoidberg** [comment]
yes

**Comment by rubenheymans** [comment]
do you have the latest angularfire version? ` "@angular/fire": "^6.0.2",`   
I don't see any error in my code but both analytics and performance monitoring are not working at all

**Comment by doczoidberg** [comment]
Firebase:
7.16.0

AngularFire:
6.0.2

**Comment by doczoidberg** [comment]
I use `NgxAuthFirebaseUIModule` and missed to put the appId there

**Comment by rubenheymans** [comment]
Does the analytics plugin work for you though?

**Comment by doczoidberg** [comment]
it never worked for me
