### ISSUE TITLE
is not completing my code

### ISSUE THREAD

**Issue by AdamTeodoro** [angular/angularfire#2544]
constructor(public fireAuth: AngularFireAuth) {
  }

login() {
    return this.fireAuth.signInWithEmailAndPassword(param, param);//is not completing my code

}

**Comment by yasinkocak** [comment]
``js
login(email, password) {
    return this.fireAuth.signInWithEmailAndPassword(email, password);
}
``

**Comment by ng-model** [comment]
@AdamTeodoro please try the above @yasinkocak mentioned way, it will work.
