### ISSUE TITLE
FirebaseError: Installations: Create Installation request failed with error "400 INVALID_ARGUMENT: Request contains an invalid argument."

### ISSUE THREAD

**Issue by eng-dibo** [angular/angularfire#2546]
I just followed the instructions here
https://github.com/angular/angularfire/blob/master/docs/messaging/messaging.md

in addition I tried to use the default ngsw file instead of 'firebase-messaging-sw.js' (I didn't know how to get irebase-messaging-sw.js).

so I added this code to `app.component.ts`

```
import { AngularFireMessaging } from "@angular/fire/messaging";
import { FirebaseApp } from "@angular/fire";


export class AppComponent {
//additional code
constructor(
    private afMessaging: AngularFireMessaging,
    private firebase: FirebaseApp
  ) {

    const messaging = this.firebase.messaging();
    navigator.serviceWorker.getRegistration().then(registration => {
      if (
        !!registration &&
        registration.active &&
        registration.active.state &&
        registration.active.state === "activated"
      ) {
        messaging.useServiceWorker(registration);
        this.getNotifsPermition();
        //this.messagingSvc.receiveMessage();
      } else {
        console.warn(
          "No active service worker found, not able to get firebase messaging"
        );
      }
    });
  }


requestPermission() {
    this.afMessaging.requestToken.subscribe(
      token => {
        console.log("Permission granted! Save to the server!", token);
      },
      error => {
        //todo: tutorial how to remove site from block list
        console.error("Permission denied!", error);
      }
    );
  }

}


but I got the following error:
```
Permission denied! FirebaseError: Installations: Create Installation request failed with error "400 INVALID_ARGUMENT: Request contains an invalid argument." (installations/request-failed).
    at http://localhost:4200/main-es2015.cb8bdd2270442fc00ec0.js:1:5067
    at http://localhost:4200/main-es2015.cb8bdd2270442fc00ec0.js:1:41437
    at Object.next (http://localhost:4200/main-es2015.cb8bdd2270442fc00ec0.js:1:41542)
    at o (http://localhost:4200/main-es2015.cb8bdd2270442fc00ec0.js:1:40281)
    at l.invoke (http://localhost:4200/polyfills-es2015.690002c25ea8557bb4b0.js:1:6624)
    at i.run (http://localhost:4200/polyfills-es2015.690002c25ea8557bb4b0.js:1:2036)
    at http://localhost:4200/polyfills-es2015.690002c25ea8557bb4b0.js:1:12968
    at l.invokeTask (http://localhost:4200/polyfills-es2015.690002c25ea8557bb4b0.js:1:7242)
    at i.runTask (http://localhost:4200/polyfills-es2015.690002c25ea8557bb4b0.js:1:2651)
    at m (http://localhost:4200/polyfills-es2015.690002c25ea8557bb4b0.js:1:9236)
```

**Comment by Benneee** [comment]
Is there no fix available for this? It's been open for weeks now.

**Comment by EliasTouil** [comment]
I ran into the same error because I did not copy the config properly (appId)
As seen [here](https://github.com/prescottprue/generator-react-firebase/issues/211#issuecomment-622083220)

**Comment by garrettlove8** [comment]
I got this error in a React app, I believe it is caused by the Firebase config object not having the correct values. In my case I was setting up a second Firebase project to serve as my dev environment and was using React's .env files to dynamically set the Firebase config object. Not sure how it works in Angular, but for React restarting the app also reloads the .env file values which fixed the problem.

**Comment by SanjulaD** [comment]
i had the same problem but not solved on firebase v9

**Comment by dasrajan** [comment]
> here

Hello @SanjulaD did you find any solution?

**Comment by nagthgr8** [comment]
Why this ticket is closed without any resolution?

**Comment by lorenzojkrl** [comment]
In my case, the syntax in .env was the problem.

The React syntax in .env should be something like
`REACT_APP_FIREBASE_API_KEY=AIzaSycdskjnhkjdnfvAQObMYqZ8c2I_8Xsdcvfdr`

After restarting React everything was fine.
