### ISSUE TITLE
Memory Leak: “JS event listeners” count infinitely incrementing

### ISSUE THREAD

**Issue by karmasakshi** [angular/angularfire#2550]
JS event listeners infinitely incrementing in batches of 2.

<img width="890" alt="Screenshot 2020-07-21 at 3 08 24 PM" src="https://user-images.githubusercontent.com/4698762/88038575-09cfc180-cb64-11ea-98e5-26cacfeeeadc.png">

### Version info

**Angular:** 10.0

**Firebase:** 7.13.1

**AngularFire:** 6.0.2

Verified on Chrome on macOS. Safari on iPhone heats up the device when loading the affected site.

### How to reproduce these conditions

**Steps to set up and reproduce**

1. Create a new Angular project using the CLI
2. Add AngularFire using `ng add @angular/fire`
3. Add configuration and `AngularFireAnalyticsModule`

Please note that the problem may not be with `AngularFireAnalyticsModule` but it is enough to reproduce the error. I am getting this error on a project that uses MixPanel too.

StackBlitz: https://angular-fire-start-d8ivab.stackblitz.io/
Please open DevTools > Performance Monitor and note the "JS event listeners" count increase

Editable StackBlitz: https://stackblitz.com/edit/angular-fire-start-d8ivab?file=app%2Fapp.module.ts

### Expected behaviour

The JS event listeners should be static after a certain point. (Or should be cleaned up regularly).

**Comment by Ivans51** [comment]
Me too, 171 request, i don't know why

![image](https://user-images.githubusercontent.com/24858611/88112242-10b30000-cb75-11ea-93c9-2cc11ad412d5.png)

**Comment by karmasakshi** [comment]
@Ivans51 Sorry mate, I don't think we're talking about the same thing.

**Comment by Ivans51** [comment]
@karmasakshi  ok, thanks

**Comment by karmasakshi** [comment]
This block in `zone-evergreen.js` gets fired repeatedly and returns undefined:

<img width="1279" alt="Screenshot 2020-07-30 at 10 05 27 PM" src="https://user-images.githubusercontent.com/4698762/88958335-5d9f8080-d2b1-11ea-8d3c-b13ecf6438dd.png">

<img width="769" alt="Screenshot 2020-07-30 at 7 37 51 PM" src="https://user-images.githubusercontent.com/4698762/88958344-61cb9e00-d2b1-11ea-97ce-921cf862d50a.png">

**Comment by karmasakshi** [comment]
Another sample project: https://github.com/karmasakshi/angular-memory-leak. Deployed here: https://karmasakshi.github.io/angular-memory-leak/

**Comment by karmasakshi** [comment]
Related: https://github.com/firebase/firebase-js-sdk/issues/1420

**Comment by karmasakshi** [comment]
Related discussion on SO: https://stackoverflow.com/questions/59101363/angular-firebase-app-crashes-after-20-hours-with-1-gigabyte-of-memory-allocatio/59259004#59259004

**Comment by jamesdaniels** [comment]
@karmasakshi has the resolution of 1420 addressed this issue for you? Or should i investigate?

**Comment by jamesdaniels** [comment]
Going to close assuming 1420 addressed, will reopen if not.

**Comment by karmasakshi** [comment]
Not 1420, but one of the recent commits did fix it. Thanks.

**Comment by nonodev96** [comment]
This bug continues in the versions `@angular/fire: 6.1.5` with `firebase: 8.8.1`

It is normal?

![image](https://user-images.githubusercontent.com/23743639/133923234-836a1484-86d5-4bc0-9ae3-e89e63f9a814.png)
