### ISSUE TITLE
Angular9 SSR Functions Region

### ISSUE THREAD

**Issue by willroxby** [angular/angularfire#2558]
### Version info

**Angular:** 9.1.9

**Firebase:** 7.14.2

**AngularFire:** 6.0.2

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### Expected behavior

I want to change my SSR Function to deploy to region - europe-west1.

### Actual behavior

When I run ng deploy the index.js is overwritten, setting the region back to us-central1.

Is there a way to change the default index.js file to update the region the function gets deployed to.

Current index.js - [Image](https://i.gyazo.com/1cb5e2478cd1034a377b536ec94f850a.png)

**Comment by saurabh1234** [comment]
I am also interested.

**Comment by jamesdaniels** [comment]
I wouldn't advise this at this time as Firebase Hosting requires the function be in `us-central-1`, https://firebase.google.com/docs/hosting/functions

**Comment by mkayswork** [comment]
Unfortunately, this doesn't solve the problem. Assuming I want to host a ssr angular application while my customer all sit in Europe, my score via lighthouse gets worse from this config. Is there any way to configure the region properly? As soon as I set the region like mentioned in the docs, my command `ng deploy` fails.
