### ISSUE TITLE
AngularFire catch background notifications

### ISSUE THREAD

**Issue by Mtz21** [angular/angularfire#2563]
Is there a any way to catch push notification while angular application is running in Background (second tab)?

I have this function for catch push notifications:

```
      receiveMessage() {
        this.afMessaging.messages.subscribe((payload) => {
          console.log("new message received. ", payload);
          this.currentMessage.next(payload);
        });
      }
```

But it don't fired when application is in background (second tab).

**Comment by Dragons0458** [comment]
I think with this you can: [https://firebase.google.com/docs/cloud-messaging/js/receive#handle_messages_when_your_web_app_is_in_the_background](url)

**Comment by jamesdaniels** [comment]
Closing, there's a different API for background notifications.
