### ISSUE TITLE
ERROR in node_modules/@angular/fire/firestore/firestore.module.d.ts:7:74 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).

### ISSUE THREAD

**Issue by ramitdour** [angular/angularfire#2571]
```
ERROR in node_modules/@angular/fire/firestore/firestore.module.d.ts:7:74 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).
    
    7     static enablePersistence(persistenceSettings?: PersistenceSettings): ModuleWithProviders;
```

I am getting the above error on adding firebase to my Angular 10 project. (no issues with old angular 9 project)

**Steps I took to add firebase**

 1. *npm install firebase @angular/fire --save*

 2. *ng add @angular/fire*

 3. updated **environment.ts** 

```export const environment = {
  production: false,
  firebase: {
    apiKey: <secret> ,
    authDomain: <secret>,
    databaseURL: <secret>,
    projectId: <secret>,
    storageBucket: <secret>,
    messagingSenderId: <secret>,
    appId: <secret>,
    measurementId: <secret>
  }
}; 
```

 4. Updated **app.module.ts**

```
// Firebase imports
import { AngularFireModule } from '@angular/fire';
import { AngularFirestoreModule} from '@angular/fire/firestore';
import { environment } from '../environments/environment';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    QuicklinkModule,
    BrowserModule,
    AppRoutingModule,
    BrowserAnimationsModule,
    FlexLayoutModule,
    SharedModule,

    AngularFireModule.initializeApp(environment.firebase), // Main Angular fire module
    AngularFirestoreModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

```

> [ModuleWithProviders Migration Angular.io documentation][1]

  [1]: https://angular.io/guide/migration-module-with-providers

**Comment by ramitdour** [comment]
[fixed](https://github.com/angular/angularfire/commit/93912bc3e9e41d48628a8671c766b0c2e8b65dc8)

**Comment by jltrevizon** [comment]
> Hi, after update from angular 13 to angular 16 I noticed this error: Error: node_modules/rxfire/firestore/lite/interfaces.d.ts:8:29 - error TS2314: Generic type 'AggregateQuerySnapshot' requires 1 type argument(s).
> 
> 8 export type CountSnapshot = lite.AggregateQuerySnapshot<{ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 9 count: lite.AggregateField;
> 
> ```
> 10 }, any, DocumentData>;
> ~~~~~~~~~~~~~~~~~~~~~
> ```

me too

**Comment by Hartaithan** [comment]
similar problem

```
"@angular/core": "^16.2.0",
"@angular/fire": "^7.6.1",
```

```
Error: node_modules/rxfire/firestore/lite/interfaces.d.ts:8:29 - error TS2314: Generic type 'AggregateQuerySnapshot<T>' requires 1 type argument(s).

 8 export type CountSnapshot = lite.AggregateQuerySnapshot<{
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 9     count: lite.AggregateField<number>;
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
10 }, any, DocumentData>;
   ~~~~~~~~~~~~~~~~~~~~~
```

**Comment by Hartaithan** [comment]
@sperticati @jltrevizon 

found a temporary solution
`npm i rxfire@6.0.4`

[issue in rxfire repo](https://github.com/FirebaseExtended/rxfire/issues/88)
