### ISSUE TITLE
signInWithRedirect / signInWithPopup not working on Ionic Capacitor

### ISSUE THREAD

**Issue by dodomui** [angular/angularfire#2572]
### Version info

"firebase": "^7.17.1",
"@angular/fire": "^6.0.2",

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
Ionic:

   Ionic CLI                     : 6.11.1 (/Users/../.nvm/versions/node/v12.16.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.2.2
   @angular-devkit/build-angular : 0.901.9
   @angular-devkit/schematics    : 9.1.9
   @angular/cli                  : 9.1.9
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.2.0
   @capacitor/core : 2.4.0

Utility:

   cordova-res : 0.15.1
   native-run  : 1.0.0

System:

   NodeJS : v12.16.1 (/Users/../.nvm/versions/node/v12.16.1/bin/node)
   npm    : 6.14.7
   OS     : macOS Catalina

Run afAuth.signInWithRedirect() or afAuth.signInWithPopup in android will change URL to *.firebaseapp.com for authentication but the actual page keep blank
Expected to open browser for authentication.

It's working on Ionic + Cordova, may I know how could I make it on Ionic + Capcitor?
Thanks.

**Comment by jamesdaniels** [comment]
Closing as there are other issues / posts that address how to get AF working in cordova, out of scope for the issues here.
