### ISSUE TITLE
Angular10 - Loading chunk firebase-analytics failed

### ISSUE THREAD

**Issue by kousenlsn** [angular/angularfire#2575]
### Version info

**Angular:** 10.0.5 / 10.0.1 / 10.0.0

**Firebase:** 7.19.0 / 7.15.1

**AngularFire:** 6.0.2 / 6.0.3-canary.93912bc

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** Any browser, Mac

### How to reproduce these conditions

- Create a new Angular project via CLI (```ng new test-project```) (Angular CLI 10.0.4)
- Install ```firebase``` and ```Angular/fire```
- Import to app.modules, and to a constructor the analytics service.
- (optional) add to ```angular.json``` ```"allowedCommonJsDependencies": [ "firebase/app", "@firebase/auth"]``` to disable ES module / commonjs module warning at the console.

**Additional**:
I tried to use ```npm i @angular/fire@canary```without any success, following [#2526](https://github.com/angular/angularfire/issues/2526), and even downgrading the versions of both Angular and firebase.

I also tried to disable vendor-chunk and common-chunk, and some multiple other options.

### Debug output

![Screen Shot 2020-08-25 at 10 56 48](https://user-images.githubusercontent.com/14895129/91183484-eac3d280-e6c1-11ea-8851-3b1862388901.png)

![Screen Shot 2020-08-25 at 10 58 33](https://user-images.githubusercontent.com/14895129/91183524-f4e5d100-e6c1-11ea-8b89-817d07690722.png)

### Expected behavior

Imports and works ?!

### Actual behavior

Error at the console, can't use the service.

**Comment by HugoSart** [comment]
Had the same issue. In my case, I found out that my AdBlock was preventing the library from downloading the firebase-analytics file.

**Comment by kousenlsn** [comment]
@HugoSart Wow I can't believe it, it is indeed AdBlock, it works when disabled. Now I don't know what to do, as I can't control that

**Comment by jdmasoft** [comment]
i have the same problem :(

**Comment by Splaktar** [comment]
I'm not sure that there is much that the library can do to avoid ad blockers. Most likely any update would be met with a change to the ad blocker to make sure that it breaks loading again.

**Comment by jdmasoft** [comment]
Thanks for You reply

**Comment by MadyAkira** [comment]
Does it mean that firebase analytics won't be able to send data from user using adBlock/uBlock Origin ? 
Or this issue only occur during debug / development mode ?
