### ISSUE TITLE
add change language method 

### ISSUE THREAD

**Issue by AttalliAyoub** [angular/angularfire#2578]
i'm just asking if you could add a method to change the language in the auth api.
![SharedScreenshot](https://user-images.githubusercontent.com/41020025/91623480-8dff3b00-e993-11ea-82ec-3d9919494730.jpg)
this is the link;
https://firebase.google.com/docs/auth/web/facebook-login?authuser=0

**Comment by jamesdaniels** [comment]
`6.1.0-rc.2` now has `USE_DEVICE_LANGUAGE` and `LANGUAGE_CODE` DI tokens that you can provide to set the language to afAuth.
