### ISSUE TITLE
Add support for getting document's id in CollectionGroupQuery

### ISSUE THREAD

**Issue by simonxabris** [angular/angularfire#2579]
### Version info

**Angular: 9.1.6**

**Firebase: 7.15.0**

**AngularFire: 6.02**

Hi!

I'm using angularfire on a project and I've tried to use `collectionGroup.valueChanges({ idField: 'docId' })` to retrieve a collection group with the document ids mapped to the `docId` property as I saw in the [docs](https://github.com/angular/angularfire/blob/master/docs/firestore/querying-collections.md#collection-group-queries). When I tried this, TS complained that the `valueChanges` function does not expect any arguments, so I took a quick look at the source and found out that the implementation is missing.

I'll be providing a PR with the implementation of this shortly.

**Comment by jamesdaniels** [comment]
Addressed in `6.1` :)

**Comment by simonxabris** [comment]
Thank you for merging!
