### ISSUE TITLE
Upload to Storage from Google Drive fails only on Android

### ISSUE THREAD

**Issue by maganap** [angular/angularfire#2582]
### Version info

```
Angular CLI: 9.1.8
Node: 12.14.1
OS: darwin x64
Angular: 9.1.11
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.8
@angular-devkit/build-angular     0.901.8
@angular-devkit/build-optimizer   0.901.8
@angular-devkit/build-webpack     0.901.8
@angular-devkit/core              9.1.7
@angular-devkit/schematics        9.1.7
@angular/cli                      9.1.8
@angular/fire                     6.0.0
@ngtools/webpack                  9.1.8
@schematics/angular               9.1.7
@schematics/update                0.901.8
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
```

### How to reproduce these conditions

To allow the user to select a file for upload, we're following these examples:
https://github.com/angular/angularfire/blob/master/docs/storage/storage.md

This is the input to select the file:
```
<input  type="file" #fileDropRef id="fileDropRef"
  multiple
  accept="image/*, .pdf, .doc, .docx, .xls, .xlsx, .ppt, .pptx"
  (change)="fileBrowseHandler($event.target.files)" />

```
The problem comes when the user selects a file from Google Drive.
The call to `this.storage.upload(path, file);` fails with `ERR_UPLOAD_FILE_CHANGED`.

*Only fails on Android + Chrome + Google Drive*. If a local file is selected, there's no problem. It only fails when the file comes from Google Drive.

### Debug output

With Android phone, cable connected:
`net::ERR_UPLOAD_FILE_CHANGED`

### Expected behavior

The file uploads to storage, the same way it does when selecting a local file for upload.

### Actual behavior

The call to `this.storage.upload(path, file);` fails with `ERR_UPLOAD_FILE_CHANGED`.

**Comment by poorna-code** [comment]
I can confirm that this is an issue on Chrome 86
![Screenshot_20201028-102952_Chrome](https://user-images.githubusercontent.com/66749274/97392748-8cf17800-1908-11eb-8451-03f63a7f578e.jpg)

**Comment by jamesdaniels** [comment]
I'd guess this is an issue that you should file on the [Firebase JS SDK](https://github.com/firebase/firebase-js-sdk) rather than here, as it seems very unlikely that AngularFire is the culprit here.

**Comment by gustavohenke** [comment]
If anyone arrives here, here's a self contained example:
https://codepen.io/gustavohenke/pen/poPrOPQ?editors=1011

Whichever file you select from GDrive without downloading it to the device first -- doesn't work.
