### ISSUE TITLE
Analytics sends page_view event with router url before replacing the parameters

### ISSUE THREAD

**Issue by blasco** [angular/angularfire#2587]
### Version info

**Angular:** 10:1.0

**Firebase:** 7.17.1

**AngularFire:** 6.0.0

### Expected behavior

page_view should log the url after replacing the router parameters

### Actual behavior

the event is logged before replacing the parameters: 
`/route/:param/`

**Comment by blasco** [comment]
Am I the only one experiencing this behavior?

**Comment by Splaktar** [comment]
Can you paste more details like the actual URL and payload that is being sent?

I'm not seeing this in my `screen_view` events sent to GA when testing out the latest `6.0.3-canary.77a9a15` along with `firebase@^7.21.0`.

**Comment by blasco** [comment]
it seems like it got fixed with `6.0.3-canary.77a9a15`, I'm closing the issue. Thank you for the great work!
