### ISSUE TITLE
Updating Firebase packages

### ISSUE THREAD

**Issue by frantchessico** [angular/angularfire#2591]
Hello community, my main concern is in the firebase packages more specifically in the firebase and firebase-admin packages, my opinion is that, it would be better to update the packages starting with firebase-admin that whose version here is 8.10.0 while yours latest version is 9.2.0. I think this has been the problem with several open source projects, the delay in updating packages and other things. Without saying anything else, thank you very much.

**Comment by jamesdaniels** [comment]
Firebase-admin on the SSR side is indeed behind a major, I'll look into upgrading the schematic.

**Comment by jamesdaniels** [comment]
Addressed in 7.1.0-rc.0
