### ISSUE TITLE
Upgrade the firebase version to 7.21.

### ISSUE THREAD

**Issue by kjs054** [angular/angularfire#2603]
Version Info:

Angular: 10.0.3

Firebase-Tools: 8.11.2

AngularFire: 6.0.3

Upgrade the firebase version to 7.21 to support '!=' and not-in query operators.

**Comment by jamesdaniels** [comment]
We support that version of Firebase, as we're set to `^7.13.1`. After you `ng add` us managing your package version is up to you however, you'll need to upgrade with either NPM or yarn.

**Comment by kjs054** [comment]
Ah that did the trick. Thanks James!
