### ISSUE TITLE
Storage putString() documentation details are wrong

### ISSUE THREAD

**Issue by tgv1975** [angular/angularfire#2606]
### Version info

**Angular:** 9.1.9

**Firebase:** 7.22.0

**AngularFire:** 6.0.3

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** n/a

### How to reproduce these conditions

**Failing test unit, Stackblitz demonstrating the problem**
n/a

**Steps to set up and reproduce**

Visit the storage upload documentation [the Uploading BLOBs section](https://github.com/angular/angularfire/blob/master/docs/storage/storage.md#uploading-blobs).

The explanation for `putString` seems to be out of place:

> Updates an existing item in the array. Accepts a key, database reference, or an unwrapped snapshot.

**Sample data and security rules**

n/a

### Debug output

n/a

**Screenshots**

![image](https://user-images.githubusercontent.com/15803440/95021945-bce88b00-067c-11eb-884c-ea38b013dbe8.png)

### Expected behavior

A relevant explanation for `putString`, such as:

> Upload a raw, `base64`, `base64url`, or `data_url encoded` string to the storage reference's path. Returns an `AngularFireUploadTask` for upload monitoring.

### Actual behavior

The explanation for `putString` is nonsensical:

> Updates an existing item in the array. Accepts a key, database reference, or an unwrapped snapshot.

**Comment by jamesdaniels** [comment]
Guessing this is just a copy/paste error. Welcome any updates.

**Comment by jamesdaniels** [comment]
Dunno if we fixed but closing as outdated since we're revamping the docs for the new version.
