### ISSUE TITLE
Setting auth.languageCode is impossible due to PromiseProxy.

### ISSUE THREAD

**Issue by kertof** [angular/angularfire#2609]
This issue comes from the PromiseProxy and the fact that languageCode is both a getter and setter.

### Version info

**Angular:**
"@angular/core": "~10.1.4",
**Firebase:**
"firebase": "^7.19.1",
**AngularFire:**
"@angular/fire": "^6.0.2",

### How to reproduce these conditions

```javascript
// Try to change AngularFIreAuth languageCode
this.fireAuth.languageCode = 'fr';
// This fails because "Type 'string' is not assignable to type 'Promise<string>'."
// This comes from the PromiseProxy and the fact that languageCode is both a getter and setter.

// Setting to a Promise doesn't have any effect.
this.fireAuth.languageCode = new Promise(() => 'fr');
```

### Expected behavior
I should be able to change the languageCode of the auth Object, to send email action templates in the user's language.

### Actual behavior
The languageCode property doesn't work with the PromiseProxy. All email action templates are sent with the default Firebase Console language setting.

**Comment by jamesdaniels** [comment]
I'm aiming to support language code in 6.1, hopefully should have the time to take a pass shortly

**Comment by kertof** [comment]
Fantastic!

As a current workaround, I use firebase directly, with a delay, to make sure the app is initialized by AngularFire first.

```ts
import * as firebase from 'firebase/app';
import 'firebase/auth';

firebase.auth().languageCode = langCode;

```

**Comment by jamesdaniels** [comment]
`6.1.0-rc.2` now has `USE_DEVICE_LANGUAGE` and `LANGUAGE_CODE` DI tokens which allow configuration of the auth language.

**Comment by bartosz-kepka** [comment]
With:
- Angular ^12.2.0
- Firebase ^8.10.0
- AngularFire ^6.1.5

setting `LANGUAGE_CODE `  DI token value does not impact email language.

Value of `languageCode` stored in AngularFireAuth service equals the one provided with DI token.
```
import { AngularFireAuth } from '@angular/fire/auth';

  constructor(
    private authService: AngularFireAuth,
  ) {
    this.authService.languageCode.then((languageCode) =>
      console.log(languageCode) // will print a value provided with DI token, e.g. "pl"
    );
  }
```
but emails are still sent in the default language.

Must still use `firebase.auth()` directly to change email language:
```
import * as firebase from 'firebase/app';
import 'firebase/auth';

firebase.auth().languageCode ='pl'; // emails will be sent in provided language
```

**Comment by vytautas-pranskunas-** [comment]
I am still facing this issue... ```this.afAuth.languageCode = Promise.resolve(lang);``` still sends emails with default template language set in firebase console. 
![Screenshot 2022-11-30 at 11 15 18](https://user-images.githubusercontent.com/3918999/204769562-7887d107-6430-4ed0-a365-f57aa2ce8afb.png)

```
import * as firebase from 'firebase/app';
import 'firebase/auth';

firebase.auth().languageCode ='pl'; // emails will be sent in provided language
```

this workaround does not work because auth() does not exsists in firebase..

any solution anyone?
