### ISSUE TITLE
feat(deploy): Support for Preview Channels

### ISSUE THREAD

**Issue by lacolaco** [angular/angularfire#2612]
Firebase Hosting finally supports the Preview Channel feature!

https://firebase.googleblog.com/2020/10/preview-channels-firebase-hosting.html

So I think `ng deploy` should allow developers to choose the channels. 

```
# Just a proposal inspired by https://github.com/marketplace/actions/deploy-to-firebase-hosting

{
  "builder": "@angular/fire:deploy",
  "options": {
    "channelId": "preview",
    "expires": "7d"
  } 
}
```

**Comment by jamesdaniels** [comment]
Absolutely aiming to support this. Need to bump the firebase-tools version in the next release.
