### ISSUE TITLE
fcm foreground notification web app not working

### ISSUE THREAD

**Issue by Josutoral** [angular/angularfire#2614]
### Version info

**Angular:**

**Firebase:**

**AngularFire:**

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Stackblitz demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

**Comment by jamesdaniels** [comment]
More information needed.
