### ISSUE TITLE
Question: How to force token refresh?

### ISSUE THREAD

**Issue by vella-nicholas** [angular/angularfire#2616]
With reference to the Firebase custom claims documentation (https://firebase.google.com/docs/auth/admin/custom-claims#propagate_custom_claims_to_the_client), is it possible to achieve 
`An ID token is force refreshed by calling currentUser.getIdToken(true)` using angular fire?

Thanks in advance!

**Comment by askilondz** [comment]
`currentUser` is returned as a promise in AngularFire. So need to do:
`(await this.fireAuth.currentUser).getIdToken(true)`

Another option is you don't have to use AngularFire for this but just the firebase js sdk and do:
`firebase.auth().currentUser.getIdToken(true);`

...so long as you are importing `import 'firebase/auth'`

**Comment by vella-nicholas** [comment]
I confirm this works. For anyone using Observables, this is my solution:

```
public getToken$(): Observable<firebase.auth.IdTokenResult> {
    return from(this.angularFireAuth.currentUser).pipe(switchMap(user => {
      return from(user.getIdTokenResult(true)).pipe(map(token => {
        return token;
      }));
    }));
  }
```

**Comment by AurelienLoyer** [comment]
> I confirm this works. For anyone using Observables, this is my solution:
> 
> ```
> public getToken$(): Observable<firebase.auth.IdTokenResult> {
>     return from(this.angularFireAuth.currentUser).pipe(switchMap(user => {
>       return from(user.getIdTokenResult(true)).pipe(map(token => {
>         return token;
>       }));
>     }));
>   }
> ```
Thanks for the tips 👍 

With one line format:
```
public token$ = from(this._angularFireAuth.currentUser.then(user => user?.getIdTokenResult(true)))
```
