### ISSUE TITLE
AngularFire module issue

### ISSUE THREAD

**Issue by vishalsinghpoker** [angular/angularfire#2623]
Hi,

I am using angular 10 and angular fire latest version but during ng server compiler showing below eoor-
`import { analytics, app, auth, database, firestore, functions, messaging, performance, remoteConfig, storage } from 'firebase/app';
                                                                     ~~~~~~~~~
    node_modules/@angular/fire/firebase.app.module.d.ts:2:75 - error TS2614: Module '"../../firebase"' has no exported member 'performance'. Did you mean to use 'import performance from "../../firebase"' instead?
`

Any idea about this issue.

**Comment by jamesdaniels** [comment]
Please use Firebase v7 until we add support for v8. #2619
