### ISSUE TITLE
i have this problem

### ISSUE THREAD

**Issue by rahrl** [angular/angularfire#2631]
i have this problem 

**e**rror TS2694: Namespace '"C:/Users/mo-ro/code/myApp/node_modules/firebase/index"' has no exported member 'User'.

9 user:Observable<firebase.User>**

en my package.json is

"dependencies": {
    "-": "0.0.1",
    "@angular/animations": "~10.1.4",
    "@angular/common": "~10.1.4",
    "@angular/compiler": "~10.1.4",
    "@angular/core": "~10.1.4",
    "@angular/fire": "^6.0.4",
    "@angular/forms": "~10.1.4",
    "@angular/localize": "~10.1.4",
    "@angular/platform-browser": "~10.1.4",
    "@angular/platform-browser-dynamic": "~10.1.4",
    "@angular/router": "~10.1.4",
    "@ng-bootstrap/ng-bootstrap": "^7.0.0",
    "angularfire2": "^5.4.2",
    "bootstrap": "^4.5.3",
    "firebase": "^8.0.0",
    "firestore-models": "^1.6.3",
    "rxjs": "~6.6.0",
    "save": "^2.4.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/architect": ">= 0.900 < 0.1100",
    "@angular-devkit/build-angular": "~0.1001.4",
    "@angular/cli": "^10.1.7",
    "@angular/compiler-cli": "~10.1.4",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "firebase-tools": "^8.0.0",
    "fuzzy": "^0.1.3",
    "inquirer": "^6.2.2",
    "inquirer-autocomplete-prompt": "^1.0.1",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "open": "^7.0.3",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"
  }
}

what is the problem please
                           ~~~~**

_Originally posted by @rahrl in https://github.com/angular/angularfire/issues/1708#issuecomment-720140549_

**Comment by jamesdaniels** [comment]
comments on your other post, since you upgraded to Firebase v8 you'll want to mind the API changes that brought

**Comment by rahrl** [comment]
How i return to lower version of firebase
