### ISSUE TITLE
Running an ionic ios mobile app with Angularfire integration will open the firebase project webpage on Safari

### ISSUE THREAD

**Issue by amjadyahya1** [angular/angularfire#2641]
When developing an Ionic app with Angularfire integration and then deploying and running on an iPhone device, the app would often open the Safari app then show the Firebase project webpage with this url: https://app-project-name.firebaseapp.com.

This is defiantly a bad user experience and a potential security risk as it exposes to any attacker the real firebase project url.

Development Environment:

Angular/core: 10.0.0
Firebase: ^7.23.0
AngularFire:^6.0.3
Ionic: 5.0.0
Cordova-ios: ^6.1.1
Node: 10.15.3
Operating system: MacOS: 10.14.6
Xcode: 11.3
iPhone: 7 with iOS version 13.3.1

**Steps to set up and reproduce**

Create and ionic/angular project.

Integrate Angularfire like so in app.module.ts
const config = {
  apiKey: "********************",
  authDomain: "project-name.firebaseapp.com",
  databaseURL: "https://*********.firebaseio.com",
  projectId: "*******************",
  storageBucket: "project-name.appspot.com",
  messagingSenderId: "*******************",
  appId: "*******************",
  measurementId: "*******************"
};

Add any angularfire functionality: Auth, Firestore.

Build for iOS and run on a physical device, upon running the app it would open Safari and point to your project's firebase url.

### Debug output

No errors or warnings

**Comment by jamesdaniels** [comment]
Closing as there are other issues and solutions to this going around & it's not specific to AngularFire.

**Comment by amjadyahya1** [comment]
For those who are facing the same issue, this is a cordova-ios 6.0.0 - 6.1.1 issue. 
https://github.com/apache/cordova-ios/issues/988
Temporary fix in this pull request:
https://github.com/apache/cordova-ios/pull/1023
