### ISSUE TITLE
Angular 11 released

### ISSUE THREAD

**Issue by rkchaudhary4** [angular/angularfire#2651]
Angular version 11 has been released but the latest version of angularfire is not compatible with it. Following dependency errors are there:
                  Package "@angular/fire" has an incompatible peer dependency to "@angular/common" (requires "^9.0.0 || ^10.0.0", would install "11.0.0")
                  Package "@angular/fire" has an incompatible peer dependency to "@angular/core" (requires "^9.0.0 || ^10.0.0", would install "11.0.0")
                  Package "@angular/fire" has an incompatible peer dependency to "@angular/platform-browser" (requires "^9.0.0 || ^10.0.0", would install "11.0.0")
                  Package "@angular/fire" has an incompatible peer dependency to "@angular/platform-browser-dynamic" (requires "^9.0.0 || ^10.0.0", would install "11.0.0")
 Kindly upgrade angularfire to support the new version of angular.

**Comment by Splaktar** [comment]
I believe that this is already being worked on. I don't see these when I use `6.1.0-rc.1`.

**Comment by Splaktar** [comment]
Also after updating to Angular v11, I was getting an error with `ng deploy` due to some deprecated Workspace APIs being removed in the CLI devkit.
```
An unhandled exception occurred: Cannot read property 'Workspace' of undefined
```
That is resolved in `6.1.0-rc.1` via PR https://github.com/angular/angularfire/pull/2647.

**Comment by aram-m** [comment]
Hey i got this after v11 update 
`node_modules/@angular/fire/storage/observable/fromTask.d.ts:3:83 - error TS2694: Namespace 'firebase' has no exported member 'default'.`

**Comment by jamesdaniels** [comment]
[Per the compatibility table](https://github.com/angular/angularfire#compatibility), please upgrade to 6.1.0-rc for now. We'll release to stable once we've had enough testing on Angular 11 to be comfortable.

I'd also suggest you upgrade to Firebase v8.0.1+, if you haven't yet.

**Comment by jamesdaniels** [comment]
Closing with work-around, pinning since a lot of folk will probably run into this.

**Comment by jamesdaniels** [comment]
`6.1.0` is out, unpinning.
