### ISSUE TITLE
associateQuery result is used in swapped order.

### ISSUE THREAD

**Issue by wu-hui** [angular/angularfire#2657]
`associateQuery` returns `{query, ref}`, but it is used as `{ref, query}` instead, this will make all the query conditions invalid?

This is just from my eye-ball checking though, please take a look!

Definition:
https://github.com/angular/angularfire/blob/b00e14bd6f3abbcfe2cb7234db779e9578f93196/src/firestore/firestore.ts#L57

Usage:
https://github.com/angular/angularfire/blob/master/src/firestore/document/document.ts#L66

**Comment by jamesdaniels** [comment]
No error here, that's just ES shorthand. It's equivalent to saying `{ query: query, ref: ref }` and usage is shorthand for 

```ts
const it = associateQuery(collectionRef, queryFn);
const query = it.query;
const ref = it.ref;
```
