### ISSUE TITLE
Docs request: Document all DI tokens with example usage

### ISSUE THREAD

**Issue by johngrimsey** [angular/angularfire#2663]
It would be great to update the docs to include clear examples of how to config correctly via the DI tokens. Currently it requires a bit of guesswork and looking in the code, and it isn't obvious to me. I've had troubles getting 6.1.0 to work with Firebase emulators, and even caused white screen of death when trying to update from old `SETTINGS` DI token to use the new tokens.

**Comment by jamesdaniels** [comment]
Agreed, just had to get 6.1 out the door. I should have some time to work on the docs in the next week. Welcome any assistance in the meantime.

**Comment by johngrimsey** [comment]
Cheers @jamesdaniels if I can find time and I can figure it out I'll happily contribute. Tough to debug. Well done on 6.1 👍

**Comment by jamesdaniels** [comment]
Going to close as we've made some headway here but the DI tokens are going away with the introduction of v7 modular
