### ISSUE TITLE
Permission denied during development if browser tab is not in foreground

### ISSUE THREAD

**Issue by matteobucci** [angular/angularfire#2664]
### Version info

Basically what we have noticed is that, during the development, all our reads to the Realtime Database fail with
`ERROR Error: Uncaught (in promise): Error: PERMISSION_DENIED: Permission denied`

After several attempts, we are able to reproduce the issue.
When the Angular app refresh for whatever reason (code saved or manual refresh) and the tab is not on foreground, the app is not able to successfully operate with the database.
Our first read that fails is the one on our presence services and the code is the following:
`
	updateOnUser() {
		const connection = this.db.object('.info/connected').valueChanges().pipe(
			map(connected => connected ? 'online' : 'offline')
		);
`
`
return this.afAuth.authState.pipe(
			switchMap(user => user ? connection : of('offline')),
			tap(status => this.setPresence(status))
		);
	}
`

And several operations that depends on the AuthState fail as well.

It is important to notice that this doesn't happen in production mode, but I assume this is not the intended behaviour.

**Angular:** 10

**Firebase:** 8.0.1

**AngularFire:** 6.0.4

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
Happens on Linux/Firefox and MacOS/Chrome. I tried on Linux/Chromium but it doesn't appear

**Comment by jamesdaniels** [comment]
Interesting, I'm guessing this has something to do with the Auth not being able to access the storage APIs when the page is refreshed in the background. I bet Angular 11 HMR should address this issue for you, when you have a chance to upgrade, as it won't reload the entire page.

**Comment by jamesdaniels** [comment]
Closing as I outlined a work-around and there's nothing we can really do here.
