### ISSUE TITLE
Token issue when time is incorrect

### ISSUE THREAD

**Issue by JohanBeekers** [angular/angularfire#2673]
### Version info

**Angular:** 10.1.0

**Firebase:** 7.19.1

**AngularFire:** 6.0.3

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
Node: 12.18.4

### How to reproduce these conditions

**Steps to set up and reproduce**
Some customers were complaining about errors and when investigating the issue I figured out that it was caused by incorrect device times. (The complaints were around the time when we switched to winter time) I noticed this because the Firebase fieldValue.serverTimeStamp gave a different result as 'new Date()'.
To test this, you can set up a new project with the versions mentioned above. Initially this will work fine. But after changing your device time to an hour later, it will start giving errors when trying to retrieve data from Firestore.

**Sample data and security rules**
Not applicable. Full permissions.

### Debug output

The error that occurs when trying to retrieve data while the local time is incorrect:
![error](https://user-images.githubusercontent.com/3511550/99670456-da2cb980-2a70-11eb-9b18-105a0f079454.png)

### Expected behavior
These issues don't seem to occur when directly using Firestore without AngularFire. So I wouldn't expect this to be an issue here either.

### Actual behavior
When the local device time is incorrect, errors occur when trying to retrieve data from Firestore using AngularFire.

**Comment by jamesdaniels** [comment]
I've not been unable to isolate token issues like this
