### ISSUE TITLE
Docs: include auth localization examples

### ISSUE THREAD

**Issue by conde2** [angular/angularfire#2675]
### Version info

**Angular:**
10.2.3
**Firebase:**
8.0.2
**AngularFire:**
6.0.4

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
Ionic, Arch Linux

I was searching throught the documentation and I didnt find any mention about how to dynamic change the auth language dynamic, following the recent changes I saw that LANGUAGE_CODE, USE_DEVICE_LANGUAGE has been introduced, would be very good examples on how we can change this dynamicaly. (Eg user changes the website language and FirebaseAuth also changes it localization)

Also would like to say that you are doing an amazing job @jamesdaniels, I always follow this repository and closing more than 200 issues in the past weeks! You are a beast ! Amazing job =D Thanks.

**Comment by swftvsn** [comment]
Thank you for the hard efforts too!

We're also interested how to set firebase.auth().languageCode on the fly? After we have logged in user, we know the language, and it'll affect restore password etc. functionality. Thus we need to be able to set it after initialisation too.

**Comment by conde2** [comment]
@jamesdaniels this can be closed

If someone want to set it dynamic, use the following

```ts
    firebase.auth().languageCode = language;
```
