### ISSUE TITLE
DocumentReference in a doc obtained with snapshotChanges arent instanceof firebase.firestore.DocumentReference

### ISSUE THREAD

**Issue by rulamon** [angular/angularfire#2690]
### Version info

**Angular: 11.0.0**

**Firebase: 8.1.1**

**AngularFire: 6.1.1 and 6.1.2**

### How to reproduce these conditions

https://stackblitz.com/edit/angularfire-docref-bug?file=src/app/app.component.html

**Steps to set up and reproduce**

Retrieve a collection with a document containing a DocumentReference through AngularFirestore.collection.snapshotChanges, and check document.docRef instanceof firebase.firestore.DocumentReference

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

### Expected behavior

docRef instanceof firebase.firestore.DocumentReference should return true

### Actual behavior

docRef instanceof firebase.firestore.DocumentReference returns false, this is a regression

**Comment by jamesdaniels** [comment]
Not an AngularFire issue, see https://stackblitz.com/edit/angularfire-docref-bug-kbsb5t?file=src%2Fapp%2Fapp.component.ts please [open with the Firebase JS SDK](https://github.com/firebase/firebase-js-sdk/issues).

**Comment by jamesdaniels** [comment]
Perhaps this is the underlying issue https://github.com/firebase/firebase-js-sdk/issues/4125
