### ISSUE TITLE
Do I need to import AngularFirestoreModule?

### ISSUE THREAD

**Issue by favdev** [angular/angularfire#2693]
It works without having to import the module. Is this intentional?

![ice_screenshot_20201126-120539](https://user-images.githubusercontent.com/51066860/100299805-4747ce00-2fe0-11eb-907a-51f9fa46ecfc.png)
![ice_screenshot_20201126-120604](https://user-images.githubusercontent.com/51066860/100299809-4878fb00-2fe0-11eb-86ab-e282e6ee3992.png)

**Comment by jamesdaniels** [comment]
It works, but technically unsupported. It can change at any time.
