### ISSUE TITLE
[AngularFireStorage] Documentation - getDownloadURL() is not a method of AngularFireUploadTask

### ISSUE THREAD

**Issue by binodmx** [angular/angularfire#2709]
Under [Monitoring upload percentage](https://github.com/angular/angularfire/blob/master/docs/storage/storage.md#monitoring-upload-percentage) in the AngularFireStorage documentation shows `getDownloadURL(): Observable<any>` as a method of `AngularFireUploadTask`. But `getDownloadURL(): Observable<any>` is actually a method of `storage reference`. It should be changed accordingly otherwise, it's confusing for developers.

**Comment by jamesdaniels** [comment]
Ah yeah, this is a problem with the docs. It used to be this way but Firebase changed in a past version, we depreciated, removed but must have missed the docs.

**Comment by jamesdaniels** [comment]
Further, now that I've fixed up our storage integration, perhaps we could add the downloadUrl() function again as a convenience.
