### ISSUE TITLE
AngularFireAnalytics no send data to Firebase

### ISSUE THREAD

**Issue by Hanzofm** [angular/angularfire#2721]
### Version info

**Angular:10.1.4**

**Firebase:7.22.1**

**AngularFire:6.0.3**

**Node:10.16.1**

**Cordova:9.0.0**

**Cordova-android:9.0.0**

**Ionic/angular:5.3.4**

### My config

**app.module.ts**

```
       AngularFireModule.initializeApp({
            apiKey: 'myinfo',
            authDomain: 'myinfo.firebaseapp.com',
            databaseURL: 'https://myinfo.firebaseio.com/',
            projectId: 'myinfo',
            storageBucket: 'myinfo.appspot.com',
            messagingSenderId: 'myinfo',
            appId: 'myinfo:web:myinfo',
            measurementId: 'myinfo',
        },),
        AngularFireAuthModule,
        AngularFireDatabaseModule,
        AngularFireAnalyticsModule,

...

providers: [
        ScreenTrackingService,
        {provide: APP_NAME, useValue: 'MyAppName'},
        {provide: APP_VERSION, useValue: '1.0.0'},
...
```

**my-page.ts**

```
this.analytics.logEvent('my-tag', {}).then(re=>{
            console.error('done')
        });
```

**auth-guard.service.ts**

`this.analytics.setCurrentScreen(state.url);`

Analytics enabled on firebase console and the android, ios and web projects are configured.

### Expected behaviour

Events should appear on StreamView on firebase console section. 

### Expected behaviour
Events not appears on Streamview  firebase console section. 

On network section of chrome inspector the request to analytics to write events fires and work fine(204 code).

If I enable debug mode the events appears correctly on debugView section of Firebase console.

Am I doing something wrong?

**Comment by jamesdaniels** [comment]
If I recall correctly stream view isn't going to show any traffic until you meet certain privacy thresholds. For development debug mode is what you want.

**Comment by jamesdaniels** [comment]
You should see the collected analytics in a day or so.

**Comment by wallstudios** [comment]
Can we confirm that this works on Android? iOS and web data is both sent to firebase but never Android.
