### ISSUE TITLE
ReferenceError: globalThis is not defined

### ISSUE THREAD

**Issue by aminemshady2080** [angular/angularfire#2723]
Hey guys its been weeks that my app(ionic angular firebase) was running great in browser as serve or serve -l and on some android devices as build -prod and build as apk or run.
but not running on other devices like android v8.1 it was just the blank white screen

now i found a way to remote debug it in chrome devtools, this is the error output:

```
ReferenceError: globalThis is not defined
    at Module.<anonymous> (vendor-es5.js:158248)
    at Module.spgP (vendor-es5.js:158400)
    at __webpack_require__ (runtime-es5.js:85)
    at Module.ZAI4 (main-es5.js:295)
    at __webpack_require__ (runtime-es5.js:85)
    at Module.zUnb (main-es5.js:647)
    at __webpack_require__ (runtime-es5.js:85)
    at Object._ (main-es5.js:19)
    at __webpack_require__ (runtime-es5.js:85)
    at checkDeferredModules (runtime-es5.js:46)
capacitor.handleError @ capacitor-runtime.js:358
capacitor.handleWindowError @ capacitor-runtime.js:378
```

if i follow in those vendor-es5.js files the error that they is an undefined
globalThis.  on these lines of angular fire

`globalThis.ɵAngularfireInstanceCache || (globalThis.ɵAngularfireInstanceCache = new Map());`

help me know what to do in this situation plx
and thx in advance

**Comment by jamesdaniels** [comment]
globalThis is an ES2020 feature that we use, you'll need to polyfill it https://github.com/angular/angularfire#polyfills

**Comment by aminemshady2080** [comment]
thx for the reply
but how do i go by polyfill it
can `npm i globalthis` solve it?

**Comment by jamesdaniels** [comment]
@aminemshady2080 I'd suggest asking in our discussions under Q&A or one of the other forums for that kind of discussion. I've also polyfilled it in the sample app at the root of this repository.

**Comment by stephane-ordeready** [comment]
Hello,

Install globalthis:
`npm install globalthis`

Add:
`import 'globalthis/auto';`
in polyfills.ts

**Comment by robertIsaac** [comment]
> Hello,
> 
> Install globalthis:
> `npm install globalthis`
> 
> Add:
> `import 'globalthis/auto';`
> in polyfills.ts

this isn't working

**Comment by cooervo** [comment]
I was getting this same error while running jest test coverage. The **solution was using same nodejs version as other team mates** my nodejs version was different hope this helps someone else.
