### ISSUE TITLE
[Feature Request] add 'disableWarnings' option to emulators

### ISSUE THREAD

**Issue by geromegrignon** [angular/angularfire#2724]
### Version info

**Angular:**
11.0.5

**Firebase:**
8.0

**AngularFire:**
6.1.4

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### Description

When using the emulators tokens (https://github.com/angular/angularfire/blob/master/docs/emulators/emulators.md), it uses the `useEmulator(url)` **firebase-js-jdk** function under the hood.
But it miss the **disableWarnings** option is stated here : https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth/src/auth.js

```
/**
 * Sets the emulator configuration (go/firebase-emulator-connection-api).
 * @param {string} url The url for the Auth emulator.
 * @param {?Object=} options Optional options to specify emulator settings.
 */
fireauth.Auth.prototype.useEmulator = function(url, options) {
  // Emulator config can only be set once.
  if (!this.emulatorConfig_) {
    if (!/^https?:\/\//.test(url)) {
      throw new fireauth.AuthError(
          fireauth.authenum.Error.ARGUMENT_ERROR,
          'Emulator URL must start with a valid scheme (http:// or https://).');
    }
    // Emit a warning so dev knows we are now in test mode.
    const disableBanner = options ? !!options['disableWarnings'] : false;
    this.emitEmulatorWarning_(disableBanner);
    // Persist the config.
    this.emulatorConfig_ = { url };
    // Disable app verification.
    this.settings_().setAppVerificationDisabledForTesting(true);
    // Update RPC handler endpoints.
    this.rpcHandler_.updateEmulatorConfig(this.emulatorConfig_);
    // Notify external event listeners.
    this.notifyEmulatorConfigListeners_();
  }
}
```

This option allows to hide the bottom banner : 
![image](https://user-images.githubusercontent.com/32737308/102712406-6ffe7300-42c1-11eb-9493-1a5a20b8401f.png)

### How to reproduce these conditions

**Steps to set up and reproduce**

- create an angular project with `ng new myProject`
- install firebase tools with `npm install -g firebase-tools`
- run `firebase init` to initialize a firebase project with at least one feature
- run `firebase init` and choose 'emulators' to setup the emulators for the previous chosen features
- add the angular-fire tokens to the providers array of the AppModule
- run `ng serve`

The banner should be visible.

### Expected behavior

The token should be improved by adding the *disableWarnings option*

### Actual behavior

The banner is always visible and can hide content.

### Proposal

I can create a PR if you approve this change (it'll be applied to each token).

**Comment by lbar** [comment]
Waiting for this. Any plans for resolution please?

**Comment by geromegrignon** [comment]
@lbar i'm waiting for validation before submitting a PR.
Meanwhile you can hide the banner with css : 
```css
.firebase-emulator-warning {
  // hide the warning banner as AngularFire doesn't support the 'disableWarnings' option
  display: none;
}
```

**Comment by GrandSchtroumpf** [comment]
@geromegrignon What kind of validation you're waiting for ?

The way I see it, to solve this issue one should: 
- Update the [UseEmulatorArguments type](https://github.com/angular/angularfire/blob/master/src/auth/auth.ts#L23) to `[string, number, { disableWarnings: boolean }]`
- Change the [useEmulator](https://github.com/angular/angularfire/blob/master/src/auth/auth.ts#L90) to something like: 

```typescript
if (useEmulator) {
  // Firebase Auth doesn't conform to the useEmulator convention, let's smooth that over
  const [url, port, options] = useEmulator;
  auth.useEmulator(`http://${url}:${port)}`, options);
}
```

**Comment by geromegrignon** [comment]
@GrandSchtroumpf i wanted to make sure there is no work in progress about that.

I created a PR using your solution.
Thanks for the feedback.

**Comment by jamesdaniels** [comment]
Addressed in v7

**Comment by Trindade7** [comment]
changing the injection token URL from 'localhost' to ['http://localhost'  worked for me:

```typescript
...
{ provide: USE_AUTH_EMULATOR, useValue: environment.useEmulators ? ['http://localhost', 9099] : undefined },
...
```

**Comment by Premodial** [comment]
Thanks @Trindade7
