### ISSUE TITLE
Inclusion of AngularFireAuth in the constructor causes snapshotChanges to emit three times

### ISSUE THREAD

**Issue by chhaymenghong** [angular/angularfire#2727]
### Version info

**Angular:*~11.0.5*

**Firebase:*~8.2.1*

**AngularFire:*^6.1.4*

**Other (e.g. Ionic/Cordova, Node, browser, operating system):*chrome*

### How to reproduce these conditions

**Failing test unit, Stackblitz demonstrating the problem**

**Steps to set up and reproduce**

```
constructor(private angularFireStore: AngularFirestore,
                   private angularFireAuth: AngularFireAuth
              ) {
  }
this.angularFireStore
      .collection('collectionName')
      .snapshotChanges()
      .pipe(
        map(actions => {
          return actions
            .map(action => {
              return action.payload.doc.data();
            });
        })
      )
      .subscribe(a => {
        console.log('here');
      });
```

**Sample data and security rules**

### Debug output

** Errors in the JavaScript console **

** Output from `console.log('here');` **
'here' is printed three times. One time for when the action type is 'added'. One time for when it is 'modified' with fromCache set to true and one time for when action type is 'modified' with fromCache set to false.

** Screenshots **

### Expected behavior

'here' should be printed one time only for the initial load.

### Actual behavior

'here' should be printed three times.

**Comment by jamesdaniels** [comment]
But there are changes, as you mentioned... what can I do here? Sounds to me like after your map, since you're just using `.data()`, you'll want to add a `distinctUntilChanged` pipe.
