### ISSUE TITLE
docs(messaging): @angular/pwa and @angular/fire/messaging service workers not compatible

### ISSUE THREAD

**Issue by ngfelixl** [angular/angularfire#2731]
Hi everyone,

unfortunately I can not get the Angular PWA service worker working with the **firebase-messaging-sw.js**. There is nothing in the docs about it. There is the following material I've found:

- [Unanswered stackoverflow question](https://stackoverflow.com/questions/64564844/correct-way-to-implement-angularfire-messaging-push-notifications)
- [Can not get this SO post working, combining ngsw-worker and firebsae-messaging-sw](https://stackoverflow.com/questions/62043508/push-notifications-multiple-service-workers-angular-ionic-5-pwa-for-web-androi)
- [Blog post with deprecations, overwriting firebase-messaging-sw with ngsw-worker](https://medium.com/kabbage-engineering/angular-pwa-app-notification-using-firebase-cloud-messaging-d1b7bd171b98)

What I've tried is to use a combined service worker like

```javascript
importScripts('ngsw-worker.js');
importScripts('firebase-messaging-sw.js');
```

And import that in the app.module.ts 
```
ServiceWorkerModule.register('combined-sw.js', { enabled: environment.production })
```

but with no success.

### Version info

**Angular:** 11.0.4
**Firebase:** ^7.13.1
**AngularFire:** ^6.1.4

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
Browser: Chrome, Brave
Node: 14
Operating System: MacOS 10.15.6

### How to reproduce these conditions

Trying to add the @angular/pwa package that registers the **ngsw-worker.js**. Then try to implement the firebase messaging.

### Expected behavior

It should be simple and documented to set up the **@angular/fire/messaging** in combination with **@angular/pwa**.

### Actual behavior

No official documentation and no solution.

Thank you very much for maintenance. I would be interested in helping with the issue/documentation if some guidance is provided.

**Comment by geromegrignon** [comment]
There is a mention about that at the top of Messaging docs : https://github.com/angular/angularfire/blob/master/docs/messaging/messaging.md

**Comment by ngfelixl** [comment]
Oh, I am sorry for opening this issue. Thank you for sharing.
