### ISSUE TITLE
Authentication lost on reload page when using emulators

### ISSUE THREAD

**Issue by carminemilieni** [angular/angularfire#2736]
### Version info

**Angular:** 10.0.7

**Firebase:** 8.2.2

**AngularFire:** 6.1.4

### How to reproduce these conditions

**Steps to set up and reproduce**

Enable emulators 
`{provide: USE_AUTH_EMULATOR, useValue: environment.useEmulators ? ['localhost', 9099] : undefined},
 {provide: USE_DATABASE_EMULATOR, useValue: environment.useEmulators ? ['localhost', 9500] : undefined},
        {provide: USE_FIRESTORE_EMULATOR, useValue: environment.useEmulators ? ['localhost', 8080] : undefined},
        {provide: USE_FUNCTIONS_EMULATOR, useValue: environment.useEmulators ? ['localhost', 5001] : undefined},
        { provide: NEW_ORIGIN_BEHAVIOR, useValue: true },
        { provide: FUNCTIONS_ORIGIN, useFactory: () => isDevMode() ? undefined : location.origin }`
Reload page "Command+R" after logged in

### Debug output

**Errors in the JavaScript console**
After reload page, on chrome debug console displayed this error message 
`zone-evergreen.js:2845 POST https://www.googleapis.com/identitytoolkit/v3/relyingparty/getAccountInfo?key=XXXXX`

**Comment by markgoho** [comment]
@carminemilieni more info on this bug can be found here:
- [Firebase Tools issue](https://github.com/firebase/firebase-tools/issues/2877#issuecomment-744365693)
- [Firebase JS SDK issue](https://github.com/firebase/firebase-js-sdk/issues/4110)

This is a known bug with the SDK. A temporary workaround is provided by @jamesdaniels in the [SDK Issue thread](https://github.com/firebase/firebase-js-sdk/issues/4110#issuecomment-747540037)

**Comment by jamesdaniels** [comment]
Going to close as there's nothing AngularFire can do for now. I'd have to push a major change to make AngularFireAuth (which is lazy) resolve optionally before AngularFireStore, etc. (which aren't lazy right now).
