### ISSUE TITLE
> Como lo solucionaste ?

### ISSUE THREAD

**Issue by pankhuri0209** [angular/angularfire#2738]
> Como lo solucionaste ?
> how did you solve it ?
> 
> ![sendmail](https://user-images.githubusercontent.com/43941133/84453999-623ba700-ac27-11ea-887f-366a0974b7d7.png)

> **Here is your solution:** 

`  SendVerificationMail() {`
`    return this.afAuth.currentUser.then(u => u.sendEmailVerification())`
 `   .then(() => {`
  `    this.router.navigate(['verify-email-address']);`
   ` })`
  `}`

_Originally posted by @parthdevloper in https://github.com/angular/angularfire/issues/2409#issuecomment-645931579_

Hi, with reference to your solution, I am getting --> (parameter) u: firebase.User | null
Object is possibly 'null'.ts(2531) error.

**Comment by jamesdaniels** [comment]
You need to await currentUser or chain as it's a promise, `return (await this.ngFireAuth.currentUser).sendEmailVerification()...` or `retrun this.ngFireAuth.currentUser.then(u => u.sendEmailVerification()).then(...)`
