### ISSUE TITLE
Cannot find namespace NodeJS after upgrade to Angular 11

### ISSUE THREAD

**Issue by WimPiteco** [angular/angularfire#2743]
### Version info
Angular CLI: 11.1.0
Node: 14.15.4
OS: win32 x64

Angular: 11.1.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... material-moment-adapter, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.0
@angular-devkit/build-angular   0.1101.0
@angular-devkit/core            11.1.0
@angular-devkit/schematics      11.1.0
@angular/fire                   6.1.4
@angular/flex-layout            11.0.0-beta.33
@schematics/angular             11.1.0
@schematics/update              0.1101.0
rxjs                            6.6.3
typescript                      4.0.5

### How to reproduce these conditions
ng serve

### Debug output

Build at: 2021-01-22T07:06:52.692Z - Hash: 1aa3cee1fd2184af867f - Time: 6982ms

Error: node_modules/@google-cloud/firestore/types/firestore.d.ts:1388:15 - error TS2503: Cannot find namespace 'NodeJS'.

1388     stream(): NodeJS.ReadableStream;
                   ~~~~~~


Error: node_modules/@google-cloud/firestore/types/firestore.d.ts:1948:14 - error TS2591: Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i @types/node` and then add `node` to the types field in your tsconfig.

1948     build(): Buffer;
                  ~~~~~~

### Expected behavior

Error free build

### Actual behavior

Errors in build

**Comment by donateoa** [comment]
I have the same problem with firebase 8.2.5.
for the moment i added `skipLibCheck: true` in tsconfig.json
```
"compilerOptions": {
    ...
    "skipLibCheck": true
  },
```
and it solved.

**Comment by WimPiteco** [comment]
The skipLibCheck is indeed a workaround but it doesn't solve the root cause. In the meantime, I found the root cause. In one of my services I had a wrong import statement.
`import { DocumentReference } from '@google-cloud/firestore';`
while this should be 
`import { DocumentReference } from '@angular/fire/firestore';`

solved!
