### ISSUE TITLE
Error installing the package

### ISSUE THREAD

**Issue by akshaybabloo** [angular/angularfire#2745]
When trying to add this package I am getting as error as:

```
Cannot find module '/Users/akshayrajgollahalli/Documents/GitHub/rex-ui/node_modules/semver/index.js'. Please verify that the package.json has a valid "main" entry
```

Though the package looks like it's been installed.

**Update**

I think the file `index.js` should be `semver.js`. I may be wrong. Because there is no path `/node_modules/semver/index.js` but there is `node_modules/semver/semver.js`.

### Version info

**Angular:** 11.1.0

**Firebase:** ^8.0.0

**AngularFire:** 6.1.4

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

1. Create a new Angular project
2. Add `ng add @angular/fire`

**Failing test unit, Stackblitz demonstrating the problem**

**Steps to set up and reproduce**

Same as above

**Sample data and security rules**

### Debug output

The only error I get is:

```
(base) akshayrajgollahalli@MacBook-Pro rex-ui % ng add @angular/fire
Installing packages for tooling via yarn.
Installed packages for tooling via yarn.
UPDATE package.json (1555 bytes)
✔ Packages installed successfully.
Cannot find module '/Users/akshayrajgollahalli/Documents/GitHub/rex-ui/node_modules/semver/index.js'. Please verify that the package.json has a valid "main" entry
```

### Expected behavior

It should install the package and ask for projects to choose.

### Actual behavior

I get an error.

**Comment by jamesdaniels** [comment]
Unable to repro

**Comment by Darrow8** [comment]
I am experiencing this error as well. I am getting `An unhandled exception occurred: Cannot find module 'semver'` when trying to install @angular/cli
