### ISSUE TITLE
Method .get() not working in mode Angular Universal out of the NgZone 

### ISSUE THREAD

**Issue by dianmonblan** [angular/angularfire#2746]
### Version info

**Angular:** 11.1.0

**Firebase:** ^7.0 || ^8.0

**AngularFire:** ^6.1.4

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** Node

### How to reproduce these conditions

Run ```npm run build:ssr && npm run serve:ssr```

Option number one used
```
    this._angularFirestore.collection('collentionName').get()
      .subscribe((snapshot: QuerySnapshot) => {
        this.title = snapshot.docs[0].data().name;
        console.log(`this.title`, this.title);
      });
```

Option number two used
```
    this._angularFirestore.collection('collentionName').get()
      .subscribe((snapshot: QuerySnapshot) => this._ngZone.run(() => {
          this.title = snapshot.docs[0].data().name;
          console.log(`this.title`, this.title);
        })
    );
```
No option works!

**Failing test unit, Stackblitz demonstrating the problem**

**Steps to set up and reproduce**

Same as above

**Sample data and security rules**

### Debug output

**Errors in the JavaScript console** Without errors

**Output from `firebase.database().enableLogging(true);`**

**Screenshots**

Results only on shell console ```title Hello word!```

### Expected behavior

Rendering of documents on **HTML**

### Actual behavior

Does not render documents on **HTML** problen with NgZone

**Comment by jamesdaniels** [comment]
Should be addressed in recent api releases.
