### ISSUE TITLE
Angular SSR customized region via providers not working with ng deploy

### ISSUE THREAD

**Issue by mkayswork** [angular/angularfire#2747]
Hello there.

I am using Angular Fire in combination with SSR. I want to deploy my application definetely to Europe for my audience (both customer and users of my products). I followed the documentation,  but setting the region via providers inside `app.server.module.ts` does not work:

`import {NgModule} from '@angular/core';
import {ServerModule} from '@angular/platform-server';
import {AppModule} from './app.module';
import {AppComponent} from './app.component';
import {FlexLayoutServerModule} from '@angular/flex-layout/server';
import {AngularFireFunctionsModule, REGION} from '@angular/fire/functions';

@NgModule({
  imports: [
    AppModule,
    ServerModule,
    FlexLayoutServerModule,
    AngularFireFunctionsModule
  ],
  providers: [
    { provide: REGION, useValue: 'europe-west3'}
  ],
  bootstrap: [AppComponent]
})
export class AppServerModule {
}
`

As soon as I provide the region in an explicit way like here (I just followed the documentation), my command `ng deploy` fails. The CLI always tries to deploy at us-central1. However, this is a K.O criteria for me to use angularfire, as I cannot optimize my website or my customer's website for SEO. Any ideas on how to solve this issue?

**Comment by Ashvin-Pal** [comment]
Hey I have the same issues. Tried adding regions in Angular.json but nothing changed. It still deployed to Uscentral 1

**Comment by phihochzwei** [comment]
Also waiting desperately for this :)

**Comment by Morstis** [comment]
That is not a problem of angular fire, but of firebase-tools.
See here: https://github.com/firebase/firebase-tools/issues/842

You can not change the functions origin, because the hosting servers are only supporting us-central1 as origin and therefore always use us-central1 as function. As a result you can not rewrite to a europe function in your firebase.json config.
