### ISSUE TITLE
why aren't showing my product list in admin-products on angular from firebase

### ISSUE THREAD

**Issue by Abbas-programmer** [angular/angularfire#2748]
### `product.service.ts`

import { AngularFireDatabase } from '@angular/fire/database';
import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ProductService {

  constructor(private db: AngularFireDatabase) { }

  create(product){
    return this.db.list('/product').push(product);
  }

  getAll(){
   return this.db.list('/products').valueChanges();
}
}

### Admin-product.component.html ### 
<p><a routerLink="/admin/products/new" class="btn btn-primary">New Product</a></p>
<table class="table">
    <thead>
        <tr>
            <th>Title</th>
            <th>Price</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <tr *ngFor="let p of products$ |async">
            <td>{{p.title}}</td>
            <td>{{p.price}}</td>
            <td>
                <a [routerLink]="['/admin/products/']">Edit</a>
            </td>
        </tr>
    </tbody>
</table>

### Admin-product.component.ts ### 
import { ProductService } from './../../Services/product.service';
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-admin-products',
  templateUrl: './admin-products.component.html',
  styleUrls: ['./admin-products.component.css']
})
export class AdminProductsComponent implements OnInit {
 products$;
  constructor(private productService:ProductService) { 
    this.products$=this.productService.getAll();
  }

  ngOnInit(): void {
  }

}

### my 

- [ ] _output
![Screenshot (43)](https://user-images.githubusercontent.com/74951799/106360665-b7a40000-633f-11eb-82a5-2ad304b2e482.png)
###_

**Comment by geromegrignon** [comment]
Please add the code of the template of ** AdminProductsComponent**.

Please use markdown format for code blocks for an easier reading of your code.

**Comment by jamesdaniels** [comment]
Guessing your not using your async pipe correctly in your view template
