### ISSUE TITLE
Angular 11 Universal + PWA doesn't work deploying SSR as Firebase Function

### ISSUE THREAD

**Issue by Sangarllo** [angular/angularfire#2749]
### Version info

**Angular:** 11.1
**Firebase:** "^7.0 || ^8.0"
**AngularFire:** "^6.1.4"
**Node:** 14.0.0

### How to reproduce these conditions

Repo in [GitHub](https://github.com/Sangarllo/ng-sample-ssr-pwa).
Issue in [StackOverflow](https://stackoverflow.com/questions/65978758/problem-with-angular-11-universal-ssr-pwa-deploying-ssr-as-cloud-function-fun).

**Steps to set up and reproduce**

1. ng new ng-sample-ssr-pwa
2. ng add @nguniversal/express-engine
3. ng add @angular/pwa
4. ng add @angular/fire and develop `app.component.ts` and `app.module.ts` following [Getting Started with AngularFire](https://github.com/angular/angularfire/blob/master/docs/install-and-setup.md) instructions.

My `app.module` file:

```ts
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { ServiceWorkerModule } from '@angular/service-worker';
import { AngularFireModule } from '@angular/fire';
import { AngularFirestoreModule } from '@angular/fire/firestore';
import { environment } from '../environments/environment';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule.withServerTransition({ appId: 'serverApp' }),
    AppRoutingModule,
    AngularFireModule.initializeApp(environment.firebase),
    AngularFirestoreModule,
    ServiceWorkerModule.register('ngsw-worker.js', { enabled: environment.production }),
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

### Debug output

In development mode (in localhost) everything is fine:

```bash
npm run dev:ssr
```
or
```bash
npm run build:ssr && npm run serve:ssr
```
![image](https://user-images.githubusercontent.com/33560100/106383602-4740c180-63c7-11eb-92b2-9ef3d5936fbf.png)

### Expected behavior

`ng deploy` should deploy PWA app in firebase-hosting, and SSR as firebase-function

### Actual behavior

`ng deploy` retrieves error "Functions did not deploy properly", and "Functions deploy had errors with the following functions: ssr" with no useful details:

```bash
+  hosting[sample-ssr-pwa]: file upload complete
i  functions: uploading functions in project: ssr(us-central1)
i  functions: creating Node.js 10 function ssr(us-central1)...
!  functions[ssr(us-central1)]: Deployment error.
Function failed on loading user code. This is likely due to a bug in the user code. Error message: Error: please examine your function logs to see the error
cause:
https://cloud.google.com/functions/docs/monitoring/logging#viewing_logs.
Additional troubleshooting documentation can  be found at
https://cloud.google.com/functions/docs/troubleshooting#logging.
Please visit https://cloud.google.com/functions/docs/troubleshooting
for in-depth troubleshooting documentation.

Functions deploy had errors with the following functions:
       ssr
```

![image](https://user-images.githubusercontent.com/33560100/106383651-7f480480-63c7-11eb-87d4-253cf1269e15.png)

### Extra info

- When I remove `AngularFireModule.initializeApp(environment.firebase)` from app.module, features as Firestore doesn't work (of course), but `ng deploy` works fine and SSR is deployed as firebase function

![image](https://user-images.githubusercontent.com/33560100/106383787-157c2a80-63c8-11eb-9cff-98d3704c4501.png)

**Comment by akilah007** [comment]
Update angular.json file
`
       "deploy": {
          "builder": "@angular/fire:deploy",
          "options": {
            "ssr": true,
            "functionsNodeVersion": 12
          }
        }`

**Comment by Sangarllo** [comment]
Thank you @akilah007. Your configuration helped to show my SSR function in firebase as Node 12, but i got the solution with this steps:
 1. Install node 12 (and use) in my computer
 2. Add globalThis pollyfil to my project.

**Comment by Sangarllo** [comment]
Solved with these steps:

1. Install (and use) node 12, as needed by firebase.
2. Add globalThis pollyfil to my project.
