### ISSUE TITLE
Many functions have a possible return value of null, causing a error with TypeScript

### ISSUE THREAD

**Issue by Uncodeable864** [angular/angularfire#2758]
### Version info

**Angular:** 11.2.0

**Firebase:** 8.2.7

**AngularFire:** 6.1.4

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** Windows, VS Code, Angular Materials

### How to reproduce these conditions

**Failing test unit, Stackblitz demonstrating the problem**

**Steps to set up and reproduce**

1. Set up a project in VS Code with Angular and Angular Fire.
2. In the main `app.component.ts` file, use the this code with the necessary imports and other data.
```
constructor(public app: FirebaseApp, private afAuth: AngularFireAuth) { }

  async printUID() {
    const user = await this.afAuth.currentUser;
    console.log(user.uid);
  }

```
3. VS Code should display an error as the Promise `currentUser` returns `Promise<firebase.User | null>` so it could be null.

**Sample data and security rules**
Firebase Auth

### Debug output

** Errors in the JavaScript console **
```
src/app/app.component.ts:17:17 - error TS2531: Object is possibly 'null'.



17     console.log(user.uid);

                   ~~~~
```
** Output from `firebase.database().enableLogging(true);` **
There is no database involved
** Screenshots **

### Expected behavior

No errors.

### Actual behavior

![image](https://user-images.githubusercontent.com/49599682/108130842-ea573380-7075-11eb-878c-0e0784cff882.png)

TypeScript shows a object may be 'null' error

**Comment by KidKoder09923** [comment]
I found a quick and easy fix for this, use the `?.` operator for example `user?.uid`, shouldn't return an error
