### ISSUE TITLE
[feat] Multiple trackers

### ISSUE THREAD

**Issue by AsimNet** [angular/angularfire#2759]
Hey guys,

thank you for your great work!

I have a multi-tenant app, and I'd like to have multiple trackers for analytics. This is possible using: 
https://developers.google.com/analytics/devguides/collection/analyticsjs/creating-trackers#working_with_multiple_trackers
Is there a possible way to have it with AngularFire?

thanks again

**Comment by jamesdaniels** [comment]
You should be able to provide multiple analytics instance in AF now, with the v7 api
