### ISSUE TITLE
Feature Request:  Verify logged in firebase account before project selection.

### ISSUE THREAD

**Issue by thenetimp** [angular/angularfire#2760]
Last week I had started an Angular project on Udemy that uses Angular/Firebase.  I used a personal Google/Firebase account for the classwork.  Today i wanted to create a new project using a different Google/Firebase account related to the client work I was working on.  However when I went to add Angularfire to the Angular project it only gave me the list of projects associated with the account I first logged into.  There was no way to log out, and re-authenticate against a new account.  It took me about 2hrs to figure out I needed to download the firebase CLI and log out, and then that got me past the hurdle.  It would be better in my opinion if instead of throwing a user directly into project selection, if first they were able to verify the account they want to use, and if not allow them to log out, and log in to a new account.

**Comment by geromegrignon** [comment]
the `ng add @angular/fire` schematic uses *firebase-tools* under the hood to communicate with Firebase. Such feature request should be proposed there : https://github.com/firebase/firebase-tools

**Comment by jamesdaniels** [comment]
Shelling it out in an upcoming release #2954
