### ISSUE TITLE
.getToken() method on AngularFireMessaging fails too early on notification mermission.

### ISSUE THREAD

**Issue by nmggithub** [angular/angularfire#2762]
### Version info

**Angular:** 11.2.0

**Firebase:** 8.2.7

**AngularFire:** 6.1.4

### How to reproduce these conditions

**Steps to set up and reproduce**
Simply call `.getToken()` on an AngularFireMessaging object when the notification permission in the browser is set to `default`.

### Debug output

None / N/A

### Expected behavior

[As is the case](https://firebase.google.com/support/release-notes/js#fcm_4) with the regular `firebase.messaging()` object, it requests the permission when called.

### Actual behavior

The notification permission is not requested, and the observable returns null.

**Comment by geromegrignon** [comment]
Do you use Angular Service Worker? https://github.com/angular/angularfire/blob/master/docs/messaging/messaging.md

**Comment by nmggithub** [comment]
> Do you use Angular Service Worker? https://github.com/angular/angularfire/blob/master/docs/messaging/messaging.md

No I do not. This issue is only here because the PR I made required one. This is a failure in the code logic.

**Comment by jamesdaniels** [comment]
the new v7 api, modular, mirrors the JS SDK exactly rather than keeping with legacy
