### ISSUE TITLE
SSR + i18n ENOENT: no such file or directory, rename index.html -> index.original.html

### ISSUE THREAD

**Issue by juliocardosoventura** [angular/angularfire#2765]
### Version info

**Angular:**
 ^11.2.3
**Firebase:**
^7.0 || ^8.0
**AngularFire:**
^6.1.4
**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Stackblitz demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

### Debug output

** Errors in the JavaScript console **

ENOENT: no such file or directory, rename 'dist/my-app/dist/my-app/browser/index.html' -> 'dist/my-app/dist/my-app/browser/index.original.html'

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

<img width="1432" alt="Screen Shot 2021-02-27 at 1 32 32 PM" src="https://user-images.githubusercontent.com/38664182/109387211-53ee0200-7900-11eb-8f73-2baa322bc613.png">

### Expected behavior

this is the line in schematics/deploy/actions.js / fsHost.renameSync(path_1.join(newClientPath, 'index.html'), path_1.join(newClientPath, 'index.original.html')); get path from side firebase.json hosting.public or another config property received from the buildTarget because when the dist/browser have another path the action.js fail.

### Actual behavior

ENOENT: no such file or directory, rename 'dist/my-app/dist/my-app/browser/index.html' -> 'dist/my-app/dist/my-app/browser/index.original.html'

**Comment by Teebo** [comment]
Hi @juliocardosoventura  have you found a solution to this issue?

**Comment by Teebo** [comment]
@jamesdaniels if you have any suggestions to circumvent this issue please share in the meantime.
Is this an issue on my side maybe as I have opened an issue https://github.com/angular/angularfire/issues/2847

**Comment by jamesdaniels** [comment]
Addressed in 7.0.3
