### ISSUE TITLE
SnapshotChanges seems to ignore .limit(1) query

### ISSUE THREAD

**Issue by alexdabast** [angular/angularfire#2767]
### Version info

**Angular:**
^11.2.3
**Firebase:**
^7.0 || ^8.0
**AngularFire:**
^6.1.4
**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Stackblitz demonstrating the problem**
Stackblitz
https://stackblitz.com/edit/snapshotbug?file=app/app.component.ts

**Steps to set up and reproduce**
Press the Add a record button to add a new record to the collection
Both value changes and snapshot changes show 1 record as expected from the .limit(1)
Press now again add a record button
Values changes .limit(1) show the latest record as expected
Snapshotchanges.limit(1) show 2 latest records

**Sample data and security rules**
N/A

### Debug output

** Errors in the JavaScript console **
No errors
** Output from `firebase.database().enableLogging(true);` **
No output
** Screenshots **
N/A
### Expected behavior
I would expect that snapshotchanges .limit(1) like valuechanges.limit(1) show only the latest record

### Actual behavior
The actual behavior is that all the records are retrieved from snapshotchanges 
That might be the correct behavior because the documentation says
Create a stream of synchronized changes. This method keeps the local array in sorted query order.

**Comment by jamesdaniels** [comment]
This is because you're filtering for the added event type in snapshotChanges, which doesn't means it's not going to receive the delete/reorder commands from Firestore. If you take off the `['added']` argument, the problem is addressed.

**Comment by alexdabast** [comment]
Thank you @jamesdaniels for your reply. In other words, there are no way to get the latest added document from a collection with a where criteria?

A use case
My user login the application and I want to receive the latest "notification" document from his document collection and I don't want to be notify on delete, modify. It work for the first document added in the collection but not after a second one. I could close the subscription and reopen it but it looks like a hack. I could also remove the `added` argument and filter with rxjs but again that will trigger more reads and more cost

**Comment by jamesdaniels** [comment]
With our current API there's no way to achieve what you're looking for. We'd have to be "smarter" about our filtering of the raw snapshots and take into account the limit, currently I'm not peering into the query itself & I don't know if there's a public API to do so.

There's no difference in reads if you drop `added` and just do it yourself with a filter, all of that is happening client side.
