### ISSUE TITLE
Past authorization code here on ng add

### ISSUE THREAD

**Issue by zzj0402** [angular/angularfire#2768]
### Version info

```txt

Angular CLI: 11.2.3
Node: 15.10.0
OS: linux x64

Angular: 11.2.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.3
@angular-devkit/build-angular   0.1102.3
@angular-devkit/core            11.2.3
@angular-devkit/schematics      11.2.3
@angular/cdk                    11.2.3
@angular/cli                    11.2.3
@angular/fire                   6.1.4
@angular/material               11.2.3
@schematics/angular             11.2.3
@schematics/update              0.1102.3
rxjs                            6.6.6
typescript                      4.1.5
```

### How to reproduce these conditions

In a new angular project, 'ng add @angular/fire'

### Debug output
```
ℹ Using package manager: npm
✔ Found compatible package version: @angular/fire@6.1.4.
✔ Package information loaded.
✔ Package successfully installed.
UPDATE package.json (1603 bytes)
✔ Packages installed successfully.
? Allow Firebase to collect CLI usage and error reporting information? Yes
? Paste authorization code here: 
```
### Expected behavior

Directions on getting authorization code

### Actual behavior

A clueless authorization code request

**Comment by ZanMarolt** [comment]
Figured this out, I had to install firebase cli tools: https://firebase.google.com/docs/cli#install-cli-mac-linux

After that ran 
```bash
firebase login:ci --no-localhost
```

Open the login URL in your browser and login with your google account that holds the desired firebase database. Copy the authorization code from the browser and run `ng add @angular/fire` in a separate terminal window and paste the authorization code in there once it asks for one. 😁

I am wondering if this is the desired behavior though, would love to hear from the maintainers

**Comment by chiranshu14** [comment]
@ZanMarolt  How can I change the google account? I had first added account_1, but I need to use account_2 for angular/fire deploy. I tried readding the @angular/fire library. It directly asks me to select proejct

**Comment by ZanMarolt** [comment]
@chiranshu14 You can use the `firebase logout` cli command.

Check doc [reference](https://firebase.google.com/docs/cli#command_reference)

**Comment by chiranshu14** [comment]
@ZanMarolt  It worked, Thank you !!
I was looking for something like ng add --reauth
