### ISSUE TITLE
TypeError: this.afAuth.auth.signInWithPopup is not a function?

### ISSUE THREAD

**Issue by kapilSoni101** [angular/angularfire#2769]
**Introduction**
Hi Team,
I am implemeting social login with twitter but i got above error in my console. Project is created with Angular CLI. As of now, no build errors.

**Configuration:**
Angular : 10
 "firebase": "^8.2.7",
 "@angular/fire": "^6.1.4",

**Code**
`import { Component, OnInit } from '@angular/core';
import { FormGroup, FormControl } from '@angular/forms';
import { Router, NavigationEnd } from '@angular/router';
import firebase from "firebase/app";
import { AngularFireAuth } from "@angular/fire/auth";

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {
  constructor(
   public afAuth: AngularFireAuth) {
	   this.twitterAuth();
   }	   
   
    twitterAuth() {
      return this.AuthLogin(firebase.auth.TwitterAuthProvider);
    }  
  AuthLogin(provider) {
    return (<any>this.afAuth).auth.signInWithPopup(provider).then((result) => {
        console.log('You have been successfully logged in!')
    }).catch((error) => {
        console.log(error)
    })
  }
}`

**Error Screenshort**

![firebase](https://user-images.githubusercontent.com/26578635/110230797-88357400-7f39-11eb-85bb-479e53334c63.PNG)

Team  can you please check and let me know what to fix?

Regards
kapil

**Comment by kapilSoni101** [comment]
@google-oss-bot - but sir i have already shared all the details?

**Comment by jamesdaniels** [comment]
It's just `this.afAuth.signInWithPopup(provider)` these days, no need for the extra `.auth`
