### ISSUE TITLE
snapshotChanges() and valueChanges() emits twice, even when the document hasn't changed

### ISSUE THREAD

**Issue by pixelbits-mk** [angular/angularfire#2776]
### Version info

**Angular:**

    "@angular/animations": "11.0.1",
    "@angular/common": "11.0.1",
    "@angular/compiler": "11.0.1",
    "@angular/core": "11.0.1",
    "@angular/forms": "11.0.1",
    "@angular/platform-browser": "11.0.1",
    "@angular/platform-browser-dynamic": "11.0.1",
    "@angular/router": "11.0.1",

**Firebase:**

    "firebase": "8.2.9",

**AngularFire:**

    "@angular/fire": "6.1.4",

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Stackblitz demonstrating the problem**

The issue is also reported on StackOverflow:
https://stackoverflow.com/questions/66608321/snapshotchanges-emits-twice-even-when-the-document-hasnt-changed

And reproduced in StackBlitz:
https://stackblitz.com/edit/angular-ivy-tbj64s?file=src%2Fapp%2Fapp.component.ts

The issue also exists for `valueChanges()`:
https://stackblitz.com/edit/angular-ivy-fb4r8p?file=src%2Fapp%2Fapp.component.ts

**Steps to set up and reproduce**

**Sample data and security rules**

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

![image](https://user-images.githubusercontent.com/7643369/111008136-6b94a400-835e-11eb-97e9-bcd744997733.png)

### Expected behavior

document snapshot listener should only emit from `snapshotChanges()` once, when the document changes

### Actual behavior

document snapshot listener is emitting from `snapshotChanges()` twice, regardless of whether the document has changed.

### Likely Reason

The issue was introduced in version 6.1.0.  It does not exist in version 6.0.5.  The likely reason is this line:

https://github.com/angular/angularfire/blob/50edaffe99c0ba2bb6e2cbc14139958213610b12/src/firestore/observable/fromRef.ts#L13

The code on line 13 is including metadata changes,  so it will emit a change whenever the metadata's `pendingWrites` property changes from true to false, which happens whenever the document is updated.
```
function _fromRef<T, R>(ref: Reference<T>, scheduler: SchedulerLike = asyncScheduler): Observable<R> {
  return new Observable(subscriber => {
    let unsubscribe: () => void;
    if (scheduler != null) {
      scheduler.schedule(() => {
        unsubscribe = ref.onSnapshot({ includeMetadataChanges: true }, subscriber);
      });
    } else {
      unsubscribe = ref.onSnapshot({ includeMetadataChanges: true }, subscriber);
    }

    return () => {
      if (unsubscribe != null) {
        unsubscribe();
      }
    };
  });
}

```

**Comment by mifo111** [comment]
Hi pixelbits-mk, 
I'm having the same issue. What is the solution here?

Thank you!
