### ISSUE TITLE
Type AngularFireModule does not have 'ɵmod' property.

### ISSUE THREAD

**Issue by DDChuru** [angular/angularfire#2778]
Building an ionic app and getting the following error

core.js:1127 Uncaught Error: Type AngularFireModule does not have 'ɵmod' property

my app module 
`mport { AngularFireModule } from '@angular/fire';
import { AngularFirestoreModule } from '@angular/fire/firestore';
import { AngularFireStorageModule } from '@angular/fire/storage';
import { AngularFireAuthModule } from '@angular/fire/auth';
import { AngularFireMessagingModule } from '@angular/fire/messaging';
import { environment } from 'src/environments/environment';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

import { NativeStorage } from '@ionic-native/native-storage/ngx';
import { SharedModule } from './shared/shared.module';

@NgModule({
  declarations: [AppComponent],
  entryComponents: [],
  imports: [
    BrowserModule,
    IonicModule.forRoot(),
    AngularFireModule.initializeApp(environment.firebase),
    AngularFireStorageModule,
    AngularFireAuthModule,
    AngularFirestoreModule,
    AngularFireMessagingModule,
    FormsModule,
    ReactiveFormsModule,
    SharedModule,
    HttpClientModule,
    AppRoutingModule],`

any help appreciated tried unistalling and reinstalling angularfire

**Comment by akshaybabloo** [comment]
This may help -> #2669

**Comment by Masskim** [comment]
Hello, 

Thank you @akshaybabloo but my issue (same as the poster's one) cannot be solved like this.

My imports are 
```
import { AngularFireModule } from '@angular/fire'; 
import { AngularFireDatabaseModule } from '@angular/fire/database';
```

So i'm currently using the fix of the other topic (importing XXXModule instead of XXX), but i doesn't work.

I don't understand because I use Firebase on an other project and everything is ok there. 

Thanks

**Comment by HuynhNhon198** [comment]
are you fixed this error? now this error is happening with me
