### ISSUE TITLE
The suggested firebase emulator suite integration results in increased production bundle size

### ISSUE THREAD

**Issue by vajahath** [angular/angularfire#2797]
To integrate with firebase emulator suite, Angularfire suggests [[ref](https://github.com/angular/angularfire/blob/master/docs/emulators/emulators.md#610-method)]
```ts
// app.module.ts
import { USE_EMULATOR as USE_AUTH_EMULATOR } from '@angular/fire/auth';
import { USE_EMULATOR as USE_DATABASE_EMULATOR } from '@angular/fire/database';
import { USE_EMULATOR as USE_FIRESTORE_EMULATOR } from '@angular/fire/firestore';
import { USE_EMULATOR as USE_FUNCTIONS_EMULATOR } from '@angular/fire/functions';

@NgModule({
  // ... Existing configuration
  providers: [
    // ... Existing Providers
    { provide: USE_AUTH_EMULATOR, useValue: environment.useEmulators ? ['localhost', 9099] : undefined },
    { provide: USE_DATABASE_EMULATOR, useValue: environment.useEmulators ? ['localhost', 9000] : undefined },
    { provide: USE_FIRESTORE_EMULATOR, useValue: environment.useEmulators ? ['localhost', 8080] : undefined },
    { provide: USE_FUNCTIONS_EMULATOR, useValue: environment.useEmulators ? ['localhost', 5001] : undefined },
  ]
})
export class AppModule { }
```
But this results in increased production bundle size, even if `environment.useEmulators` is set to `false`.
I observed a difference of 327 KB.

### Version info
**Angular:** ~11.2.8

**Firebase:** ^8.0

**AngularFire:** ^6.1.4

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** Windows

## How to reproduce these conditions
Compare the bundle size difference of the following snippets. This is the commented and uncommented versions of the above snippet.

![image](https://user-images.githubusercontent.com/12165822/114034661-03bd7480-989c-11eb-9b9b-9b105c4883ec.png)

### Suggested method:
![image](https://user-images.githubusercontent.com/12165822/114034992-5434d200-989c-11eb-9e78-aa13e51bf9f5.png)

`ng build --prod` (939 KB)
![image](https://user-images.githubusercontent.com/12165822/114035572-da511880-989c-11eb-8ed3-df3bfac02937.png)

`source-map-explorer .\dist\orderzoo-mob-web\main.0565c62a593fbee846c5.js`
![image](https://user-images.githubusercontent.com/12165822/114036124-6a8f5d80-989d-11eb-9a79-cd5267788525.png)

### Commented out
![image](https://user-images.githubusercontent.com/12165822/114037053-39635d00-989e-11eb-97d4-014739180f5c.png)

`ng build --prod` (612 KB)
![image](https://user-images.githubusercontent.com/12165822/114036902-16d14400-989e-11eb-81c5-04df97e3e999.png)

`source-map-explorer \dist\orderzoo-mob-web\main.c491975a0bf56c4a1db7.js` (No sign of firebase)
![image](https://user-images.githubusercontent.com/12165822/114037137-5435d180-989e-11eb-9fef-8e5ffe10a6b6.png)

### Expected behavior
Either way firebase should not be on initial bundle
### Actual behavior
Firebase is on initial bundle

**Comment by KingDarBoja** [comment]
This should be solved with the upcoming modular SDK, you can read more at https://modularfirebase.web.app/get-started/why-change
