### ISSUE TITLE
AngularFireAuth fails to send auth object and verify security rules of RealtimeDatabase incase of multiple databases in a single project

### ISSUE THREAD

**Issue by Noble-Shiva** [angular/angularfire#2798]
### Version info

**Angular:**  "@angular/core": "^10.1.5",

**Firebase:** "firebase": "^7.0.0 || ^8.0.0",

**AngularFire:** "@angular/fire": "^6.0.4",

**Operating system:** Windows

I am developing a project on Angular 10 and Firebase, hence using AngularFire. I have issue with AngularFireAuth and authenticating multiple databases, i have described my issue and also have attached few screen-shots required below.

### Issue
I have created multiple Realtime-Databases in my firebase-project, both for dev and prod environment.

![tempsnip](https://user-images.githubusercontent.com/25147932/114308545-fdc8cd00-9b01-11eb-8afa-c6e653d19561.png)
------ (IMG-1)

I have also defined read, write rules respectively, and hence strictly checking auth state of the current user accessing the data.

![tempsnip-1](https://user-images.githubusercontent.com/25147932/114308570-0e794300-9b02-11eb-88d5-f8c4481e87d8.png)
------ (IMG-2)

AngularFireAuth library successfully authenticates the **default** database which is underlined in red in (IMG-1) and is able to read and write data from it, verifying the rules successfully.

![tempsnip-2](https://user-images.githubusercontent.com/25147932/114308803-aecf6780-9b02-11eb-97c3-eb792fa34c3e.png)

### How to reproduce these conditions

**Getting back to Issue :** 

When i change the database from **default** to one of the **dev** databases, AngularFireAuth fails to satisfy the db-rules and throws and error.

------ (Rules) (Selected Database is underlined in red)

![tempsnip-4](https://user-images.githubusercontent.com/25147932/114309463-cc053580-9b04-11eb-94a4-d282bfffa120.png)

### Debug output
------ (Error)(Permission Denied Error)

![tempsnip-3](https://user-images.githubusercontent.com/25147932/114309157-df63d100-9b03-11eb-9f97-c60e5db1a361.png)

But, when i have changed the rules giving read, write permissions to true, it started working.

------ (Rules) (Selected Database is underlined in red)(changed rules underlined in green)

![tempsnip-6](https://user-images.githubusercontent.com/25147932/114309950-a416d180-9b06-11eb-82ef-e18b3cb141e4.png)

### Debug output
------ (Data retrieved successfully)(Marked in red)

![tempsnip-5](https://user-images.githubusercontent.com/25147932/114309681-a0367f80-9b05-11eb-8f6c-e75f28703cfa.png)

**Client Side Usage**

`environment.ts`

![tempsnip-7](https://user-images.githubusercontent.com/25147932/114310858-f9081700-9b09-11eb-90c1-9e9f89d38984.png)

**Custom Factory methods** (implemented multiple database url's)() database url's underlined in red)

![tempsnip-8](https://user-images.githubusercontent.com/25147932/114311054-d4606f00-9b0a-11eb-8309-5d645768fcea.png)

`app.module.ts`  (defining custom factory methods)

![tempsnip-9](https://user-images.githubusercontent.com/25147932/114310874-04f3d900-9b0a-11eb-8eb9-e74f21e07510.png)

**Custom Firebase Database Service** (to utilize different databases)

![tempsnip-10](https://user-images.githubusercontent.com/25147932/114310928-3bc9ef00-9b0a-11eb-8c76-6207096e20d3.png)

### Expected behavior
I was under the assumption that AngularFireAuth, authenticates user for the entire project and has no dependency on multiple databases, but the above says otherwise.

I have been stuck on this issue since a week, any help would be appreciated.
Thanks in Advance

**Comment by jamesdaniels** [comment]
If you are using multiple apps you need to authenticate across each app. Closing since this is no longer relevant to the design of v7, as you can provide multiple database instances without custom DI.
