### ISSUE TITLE
Missing info in documentation on how to auth users using Google Cloud Identity Platform with multi-tenant enabled. 

### ISSUE THREAD

**Issue by aponski** [angular/angularfire#2799]
### Version info

**Angular: 11**

**Firebase: 7**

**AngularFire: 6.1.4**

### How to reproduce these conditions

Missing info in documentation on how to auth users using Google Cloud Identity Platform with multi-tenant enabled. 

### Expected behavior

Please provide guides on how to auth users by providing tenant Id.

**Comment by jamesdaniels** [comment]
Closing as the new API mirrors Firebase JS SDK exactly, we can refer to their docs
