### ISSUE TITLE
Requested feature: Fire Storage 'list' for pagination of large results

### ISSUE THREAD

**Issue by rsivan** [angular/angularfire#2801]
Firebase cloud storage includes a pagination method (list) defined under [https://firebase.google.com/docs/storage/web/list-files?authuser=1#paginate_list_results](url).
It would be great to have a similar feature under this library (I am using 6.1.4 and there is no 'list()' method).

Thanks.

**Comment by jamesdaniels** [comment]
Will be released as part of 7.1
