### ISSUE TITLE
AngularFireAuth does not save logged in user on page refresh when using emulators and injecting AngularFirestore

### ISSUE THREAD

**Issue by EthanSK** [angular/angularfire#2803]
### Version info

**Angular:** 11

**Firebase:** 8.4.1

**AngularFire:** 6.1.4

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
MacOS Big Sur

### How to reproduce these conditions

If I inject AngularFirestore into any service, and i'm using the auth emulator (I have all the emulators enabled), then AngularFireAuth does not save the logged in user when I reload the page. If I turn don't use emulator for auth, it works fine.

I am getting the user with `this.afAuth.user.subscribe`

**Comment by KingDarBoja** [comment]
Take a look at this comment: https://github.com/firebase/firebase-js-sdk/issues/4110#issuecomment-747540037

**Comment by EthanSK** [comment]
@KingDarBoja Thanks, seems to have a workaround (haven't tested), but this _does_ need to be fixed in angular fire

**Comment by jamesdaniels** [comment]
There's no way to fix this in AngularFire without altering the API.

**Comment by KingDarBoja** [comment]
I haven't got issues writing to firestore with the emulators and have same set of security rules as well.

**Comment by muellerdberlin** [comment]
Hi there, I have the same problem. Firestore, Functions, etc. is working fine, but authenticated users loose authentication (including token) after refreshing the page. Seems like `firebaseLocalStorage` is cleared after refresh as well.
I followed this guide: https://github.com/angular/angularfire/blob/master/docs/auth/getting-started.md

environment:
```
Angular 11.2.7,
"firebase": "^8.3.1",
"@angular/fire": "^6.1.4",
"firebase-tools": "^9.10.2",
```

The workaround with `firebase-initialization.ts` did not work for me as well. AngularFire tries to connect to the cloud database all time. My workaround - which is a very one - is to **deactivate my wifi.** If wifi (or general: internet connection) is deactivated, everything works fine. But to deactivate wifi all the time is just a very unsatisfied "solution".

**Comment by jamesdaniels** [comment]
This should be addressed in v7
