### ISSUE TITLE
Angular not inizialize app

### ISSUE THREAD

**Issue by CrashOverride97680** [angular/angularfire#2811]
### Version info
**Angular**: 11.2.11
**Firebase**: 8.4.2

I use the latest version of angular 11 but as soon as the app starts it doesn't initialize it, I copied the parameters for the SDK from firebase but despite everything the structure that I followed is not working is this:
`
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { AppComponent } from './app.component';
import { AngularFireModule } from '@angular/fire';
import { environment } from '../environments/environment';

@NgModule({
  imports: [
    BrowserModule,
    AngularFireModule.initializeApp(environment.firebaseConfig)
  ],
  declarations: [ AppComponent ],
  bootstrap: [ AppComponent ]
})
export class AppModule {}
`
All modules are loaded lazy.

**Comment by KingDarBoja** [comment]
Did you followed the [Quick Start Docs](https://github.com/angular/angularfire/blob/master/docs/install-and-setup.md) ? How do you know it hasn't been initialized?

**Comment by jamesdaniels** [comment]
No repro
