### ISSUE TITLE
When USE_AUTH_EMULATOR, application makes requests to production Google API anyway

### ISSUE THREAD

**Issue by hosuaby** [angular/angularfire#2824]
### Version info

Angular: 11.2.13
Firebase: 8.5.0
@angular/fire: 6.1.4

### How to reproduce these conditions

Firebase Auth makes a HTTP call to google API `/getAccountInfo` even when Emulator is used for development.

Firebase config in `environement.ts`: 

```
firebaseConfig: {
  apiKey: 'my-emulator-key',
  projectId: 'my-project-1661770927187',
}
```

`app.module.ts` : 

```typescript
@NgModule({
  imports: [
    AngularFireModule.initializeApp(environment.firebaseConfig, 'My-Project'),
    // ...
  ],
  providers: [
    {
      provide: USE_AUTH_EMULATOR,
      useValue: !environment.production ? ['localhost', 9099] : undefined
    },
    {
      provide: USE_FUNCTIONS_EMULATOR,
      useValue: !environment.production ? ['localhost', 5001] : undefined
    },
    {
      provide: FIRESTORE_SETTINGS,
      useValue: environment.firestoreSettings
    }
  ],
  // ...
})
export class AppModule {}
```

But in browser, in development console I see failed (error code 400) request to Google API:

```
POST https://www.googleapis.com/identitytoolkit/v3/relyingparty/getAccountInfo?key=my-emulator-key 400
```

### Expected behavior

It is expected that application, running in development mode against emulator to not make any requests to production API.

**Comment by muellerdberlin** [comment]
i have the same problem in a Angular 11 app. After refreshing the page, the SDK makes a call to google API instead of localhost, even if I could login via emulator auth before the refresh.

**Comment by ideodora** [comment]
may related to this.
[https://github.com/firebase/firebase-js-sdk/issues/4110](https://github.com/firebase/firebase-js-sdk/issues/4110)

**Comment by hosuaby** [comment]
For some reason, I can not longer reproduce this error. I am using now:
Angular: 12.1.0
Firebase: 8.6.8

I didn't used workaround proposed by @ideodora 

I am closing this issue
