### ISSUE TITLE
How to change the name of cloud function name while working with Multiple angular SSR hosting in same project as the function name is default to SSR?

### ISSUE THREAD

**Issue by Alex-911** [angular/angularfire#2825]
I was working in a project with I needed 3 web hosting and all of them are angular SSR application. Things worked fine when there is only one angular SSR app. But as another angular SSR app was added. The corresponding cloud function for the second SSR app was updating the previously created SSR function.

How do I change the name of cloud function so it can deployed saperatly??

**Comment by jamesdaniels** [comment]
There's now a `functionName` option in 7.1.0-rc.0. On fresh `ng add @angular/fire@next` it will default to `ssr_${project}`.
