### ISSUE TITLE
Uncaught TypeError: Cannot assign to read only property 'settings' of object '[object Object]'

### ISSUE THREAD

**Issue by xiongemi** [angular/angularfire#2826]
### Version info

**Angular:** 11.2.14

**Firebase:** 8.6.1

**AngularFire:** 6.1.4

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Stackblitz demonstrating the problem**

**Steps to set up and reproduce**

when adding settings to auth followed instructions at https://github.com/angular/angularfire/blob/master/docs/auth/getting-started.md

```
import { SETTINGS as AUTH_SETTINGS } from '@angular/fire/auth';

@NgModule({
  // ... Existing configuration
  providers: [
    // ... Existing Providers
    { provide: AUTH_SETTINGS, useValue: { appVerificationDisabledForTesting: true } },
  ]
})
export class AppModule { }
```

it throws an error for line ` { provide: AUTH_SETTINGS, useValue: { appVerificationDisabledForTesting: true } },`, remove this line and the error is gone.

**Sample data and security rules**

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

in the browser, it throws:
```
Uncaught TypeError: Cannot assign to read only property 'settings' of object '[object Object]'
    at angular-fire-auth.js:134
    at ɵfetchInstance (angular-fire.js:460)
    at angular-fire-auth.js:113
    at ZoneDelegate.invoke (zone-evergreen.js:364)
    at Zone.run (zone-evergreen.js:123)
    at NgZone.runOutsideAngular (core.js:28520)
    at MapSubscriber.project (angular-fire-auth.js:105)
    at MapSubscriber._next (map.js:29)
    at MapSubscriber.next (Subscriber.js:49)
    at MapSubscriber._next (map.js:35)
```

** Screenshots **

**Comment by KingDarBoja** [comment]
Seems to me it is caused by how the firebase-js-sdk defined the `settings` property in the auth prototype: [firebase-js-sdk/auth](https://github.com/firebase/firebase-js-sdk/blob/50860d794bfe711143b5d287e1042eeb5187e47b/packages/auth/src/auth.js#L71).

```js
fireauth.object.setReadonlyProperty(this, 'settings', new fireauth.AuthSettings())
```

**Comment by KingDarBoja** [comment]
Please update to next version (v6.1.5) which contains this fix 🚀

**Comment by GrandSchtroumpf** [comment]
@KingDarBoja looks like version 6.1.5 is not on npm yet.

![image](https://user-images.githubusercontent.com/8143464/118680243-dcdd5100-b7fe-11eb-9fc8-059014ffd5df.png)

**Comment by jamesdaniels** [comment]
Github Actions has been degraded all morning, sorry about that, our CI/CD should be caught up soon.
