### ISSUE TITLE
Feature request: ng add @angular/fire should add hosting cache to .gitignore

### ISSUE THREAD

**Issue by StephenFluin** [angular/angularfire#2828]
### Version info

**Angular:** 12.0

**Firebase:** 9.6.1

**AngularFire:** 6.1.4

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
NA

### How to reproduce these conditions

**Steps to set up and reproduce**
```
npx @angular/cli new my-app
cd my-app
ng add @angular/fire # init project and select hosting
ng deploy
```

A firebase hosting cache file will be created, something like `hosting.sdf83k.cache` in the `.firebase` folder. 

### Expected behavior

I wish this file (or folder) was automatically added to my .gitignore

### Actual behavior

I am dumb so I accidentally check it into my repository.

**Comment by jamesdaniels** [comment]
Great request! I’m refactoring the schematics too

**Comment by jamesdaniels** [comment]
Added in 7.1.0-rc.0
