### ISSUE TITLE
installation error: The package that you are trying to add does not support schematics

### ISSUE THREAD

**Issue by sloansobie** [angular/angularfire#2830]
**Version info**
Angular: 12.0.0

Firebase: 9.10.2

AngularFire: 0.0.0 (this is the error)

**How to reproduce these conditions**
install @angular/fire in terminal through `ng add @angular/fire` command. 

**Expected behavior**
Latest version of @angular/fire installs

**Actual behavior**
version 0.0.0 @angular/fire is installed

**Comment by the-xentropy** [comment]
Same here.

```
░▒▓    ng add @angular/fire        
Node.js version v15.12.0 detected.
Odd numbered Node.js versions will not enter LTS status and should not be used for production. For more information, please see https://nodejs.org/en/about/releases/.
ℹ Using package manager: npm
✔ Found compatible package version: @angular/fire@0.0.0.
✔ Package information loaded.
 
The package @angular/fire@0.0.0 will be installed and executed.
Would you like to proceed? Yes
✔ Package successfully installed.
The package that you are trying to add does not support schematics. You can try using a different version of the package or contact the package author to add ng-add support.
```

@0.0.0 is very suspicious indeed.

Also tried with Node LTS (14.17.0); same issue.

**Comment by jamesdaniels** [comment]
We haven't marked Angular 12 as a compatible peer yet, make sure to specify a version/tag. `ng add @angular/fire@latest` should do it.

**Comment by sloansobie** [comment]
@jamesdaniels thank you! This worked
