### ISSUE TITLE
Add initializetestapp() like firebase-rules-testing

### ISSUE THREAD

**Issue by warrendodsworth** [angular/angularfire#2839]
Have a feature request?
========================
How will it make current
workarounds straightforward? What potential bugs and edge cases does it help to avoid?

Add initializetestapp() to AngularFireModule
To enable auth mocking, like they do with the firebase-rules-testing initialization. 

Currently need to disable rules to test angular services with angular fire.

**Comment by jamesdaniels** [comment]
Our current recommendation is to use the emulators entirely in AngularFire, as swapping out AngularFireModule for initializeTestApp is not trivial (and likely not possible with the current AF API).

Including auth https://firebase.google.com/docs/emulator-suite/connect_auth
