### ISSUE TITLE
Document usage of Angularfire dev dependencies

### ISSUE THREAD

**Issue by KingDarBoja** [angular/angularfire#2840]
Should be a good idea to document the following dependencies being added by the ng-add schematic:

- fuzzy
- inquirer
- inquirer-autocomplete-prompt
- open

In this case, only `open` is being used for the `ng deploy --preview` command (as stated in the Angular discord firebase channel) whereas the others are needed only in the ng add step, so those can be safely removed after it 🤔

**Comment by jamesdaniels** [comment]
FWIW open and inquirer, maybe even fuzzy / autocomplete, are likely already in your node_modules between firebase-tools and ng-cli. I’m adding them to devDeps to be defensive.

**Comment by jamesdaniels** [comment]
Dropped dev dependencies in 7.1.0-rc.0
