### ISSUE TITLE
angular fire is it not working with SSR because, globalThis is not defined

### ISSUE THREAD

**Issue by robertIsaac** [angular/angularfire#2848]
### Version info

**Angular:** 12.0.2

**Firebase:** 8.6.3

**AngularFire:** 6.1.5

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** locally node 14.16.1, in the function node 10

### How to reproduce these conditions

**Steps to set up and reproduce**

repo for the reproduce
https://github.com/robertIsaac/firebase-auth-ssr-reproduce

steps are simple
```
ng new firebase-auth-ssr-reproduce
ng add @nguniversal/express-engine
ng add @angular/fire
```

then go with this example
https://github.com/angular/angularfire/blob/master/docs/auth/getting-started.md

and then just run `ng deploy`

### Debug output

** Errors in the JavaScript console **

```
Provided module can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: ReferenceError: globalThis is not defined
    at Object.6107 (/workspace/dist/firebase-auth-ssr-reproduce/server/main.js:1:448397)
    at __webpack_require__ (/workspace/dist/firebase-auth-ssr-reproduce/server/main.js:1:2152223)
    at /workspace/dist/firebase-auth-ssr-reproduce/server/main.js:1:3192052
    at /workspace/dist/firebase-auth-ssr-reproduce/server/main.js:1:3202684
    at Object.<anonymous> (/workspace/dist/firebase-auth-ssr-reproduce/server/main.js:1:3202916)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) 
```

### Expected behavior

it should deploy

### Actual behavior

it never deploy

### notes
I tried to follow https://github.com/angular/angularfire/issues/2723#issuecomment-775886598 by importing globalthis, but it didn't work

### workaround
after it fails go manually to `dist/firebase-auth-ssr-reproduce/package.json` and change engines.node to 12 (instead of 10) to make it work then run `firebase deploy --only "functions:ssr"`

adding engines in the package.json doesn't affect the dist one

**Comment by jamesdaniels** [comment]
You need to polyfill globalThis https://github.com/angular/angularfire#polyfills

**Comment by robertIsaac** [comment]
> You need to polyfill globalThis https://github.com/angular/angularfire#polyfills

i did as i said

> I tried to follow #2723 (comment) by importing globalthis, but it didn't work

still not working
