### ISSUE TITLE
The angular 9 application is not running in IE 11 with the polyfills

### ISSUE THREAD

**Issue by shayan-paul** [angular/angularfire#2851]
### Version info

**Angular:**
   9.0.7
**Firebase:**
   8.6.3
**AngularFire:**
   6.1.5
**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Stackblitz demonstrating the problem**

**Steps to set up and reproduce**

I have tried adding the polyfills.
"first-input-delay": "^0.1.3",
"proxy-polyfill": "^0.3.2",
"whatwg-fetch": "^3.4.1" and core-js/stable just like mentioned in the sample

the ng build worked fine but when I tried to open the application its saying syntax error on inside vendor js on line 
class AngularFireMessaging {

**Sample data and security rules**

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **
![image](https://user-images.githubusercontent.com/68581520/120652889-cf31f780-c49d-11eb-95c9-022731fde88c.png)

### Expected behavior

should open the application with all the polyfills

### Actual behavior
throwing error as syntax error in AngularFireMessaging

**Comment by metaloha** [comment]
I think you need the `globalThis` polyfill as well for IE 11.

**Comment by shayan-paul** [comment]
@metaloha Thanks for the response, but I could not find out how to add this in Angular polyfills.ts file. I mean the correct import statement.

**Comment by metaloha** [comment]
https://github.com/es-shims/globalThis#readme (from https://github.com/angular/angularfire#polyfills). Adding one of those `require` lines should do the job.

Worst case scenario, copy the shim code into your `index.html` file and see if it works 😄  It won't be exact, you'll need to modify it I'm sure.

**Comment by shayan-paul** [comment]
@metaloha Adding one of those require lines might not do the job cause the module resolution configured for my Angular application is esnext and I think the require statement is falls under common JS module resolution pattern.

**Comment by jamesdaniels** [comment]
I think we're at the point were we can no longer put in cycles to attempting to support IE. If we incidentally support it that's good but we're already at the point that we're no longer testing in it. 

Closing, feel free to continue discussions and I'd accept a PR to fix any problems.
