### ISSUE TITLE
RTDB security rule auth variable is null after refreshed a page

### ISSUE THREAD

**Issue by Mocsa1974** [angular/angularfire#2861]
I am using angular 12, firebase 8.6.7 and angular fire 6.1.5
After sign in into firebase with angularfireauth signinwithcustomtoken method which was created with admin sdk createCustomToken method. Everything works fine.
After refresh a page onAuthStateChanged triggers with a sign in user credentials as expected, but when getting some data from rtdb i got a permission denied error message (Client doesn't have permission to access the desired data)
When i changed my code to firebase-js-sdk (without angular fire) everything works fine after page refresh.

Thanks

**Comment by amjadyahya1** [comment]
I'm facing the same issue here, it drives me crazy, I'm using signInWithEmailAndPassword though.

After long period of testing I have noticed that triggering sign in more than once in the same session fixes the problem, I mean the first time fails and the subsequent times succeeds.

**Comment by amjadyahya1** [comment]
https://github.com/angular/angularfire/issues/2864#issue-920714955

**Comment by jamesdaniels** [comment]
This was addressed, it was a bug in the JS SDK
