### ISSUE TITLE
version 6.1 seems to break SSR

### ISSUE THREAD

**Issue by Methodician** [angular/angularfire#2865]
### Version info

**Angular:**
Tested with versions 11 and 12

**Firebase:**
Works with Firebase version 8.6.1 and below as long as AngularFire is below 6.1
(there's another issue related to Firebase versions over 8.6.1 breaking things)

**AngularFire:**
Works up to 6.0.5 and breaks on anything over 6.1.0

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
```
"dependencies": {
    "@angular/animations": "~12.0.4",
    "@angular/cdk": "^12.0.4",
    "@angular/common": "~12.0.4",
    "@angular/compiler": "~12.0.4",
    "@angular/core": "~12.0.4",
    "@angular/fire": "^6.0.5",
    "@angular/forms": "~12.0.4",
    "@angular/material": "^12.0.4",
    "@angular/platform-browser": "~12.0.4",
    "@angular/platform-browser-dynamic": "~12.0.4",
    "@angular/platform-server": "~12.0.4",
    "@angular/router": "~12.0.4",
    "@google-cloud/debug-agent": "^4.0.0",
    "@nguniversal/express-engine": "^12.0.1",
    "axios": "^0.19.2",
    "core-js": "^3.6.5",
    "express": "^4.17.1",
    "firebase": "^8.6.1",
    "lodash": "^4.17.20",
    "ngx-quill": "^14.0.0",
    "quill": "^1.3.7",
    "quill-image-resize": "^3.0.9",
    "quill-image-resize-module": "^3.0.0",
    "rxjs": "~6.6.2",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.0.4",
    "@angular/cli": "^12.0.4",
    "@angular/compiler-cli": "~12.0.4",
    "@angular/language-service": "~12.0.4",
    "@nguniversal/builders": "^12.0.1",
    "@types/express": "^4.17.0",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/lodash": "^4.14.165",
    "@types/node": "^12.12.41",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.3.3",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "prettier": "^2.1.2",
    "protractor": "~7.0.0",
    "ts-loader": "^5.2.0",
    "ts-node": "~7.0.0",
    "tslint": "~6.1.0",
    "tslint-config-prettier": "^1.18.0",
    "tslint-plugin-prettier": "^2.1.0",
    "typescript": "~4.2.4",
    "webpack-cli": "^3.1.0"
  }
```

### How to reproduce these conditions
Attempt to update a code base with working SSR using Angular Universal, Firebase, and AngularFire such that you're using a version of @angular/fire >= 6.1.0 and run the command `npm run dev:ssr` then check your page source

**Failing test unit, Stackblitz demonstrating the problem**
If necessary I will attempt to create a demo of the problem. It's a bit time consuming to set one up with SSR and all this stuff, so hopefully I'm not alone in experiencing this issue and it's easy to re-create in your own repo. Having finally found a compatible version mix I'll be getting back to work after posting this.

### Debug output

** Errors in the JavaScript console **
I'm getting the following warnings in the terminal output working and broken conditions so they may not be relevant:

> ./node_modules/ws/lib/buffer-util.js:105:21-42 - Warning: Module not found: Error: Can't resolve 'bufferutil' in '/home/methodician/CoSourcerySSR/node_modules/ws/lib'
> 
> ./node_modules/ws/lib/validation.js:86:20-45 - Warning: Module not found: Error: Can't resolve 'utf-8-validate' in '/home/methodician/CoSourcerySSR/node_modules/ws/lib

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **
What source can look like when it works:
![ssr issue working](https://user-images.githubusercontent.com/4460470/121959928-44ad8b80-cd1a-11eb-9567-1bea721f2947.png)

What source can look like when it breaks:
![ssr issue broken](https://user-images.githubusercontent.com/4460470/121959959-52631100-cd1a-11eb-9178-59730bf8466b.png)

### Expected behavior

using npm to run dev:ssr and viewing page source in browser, one should see all kinds of SEO-friendly pre-rendered content using data from the database. At the bottom, one should find a line like this:
`<script id="serverApp-state" type="application/json">{&q;latestArticles&q;:.......<LOADS OF DATA FROM DB HERE>...........mYpZk2&q;}]}</script></body></html>`

### Actual behavior

Viewing page source in browser, don't see any content from the database rendered in the HTML. The bottom of the source has this line: `<script id="serverApp-state" type="application/json">{}</script></body></html>` with no data in the cu.

**Comment by jamesdaniels** [comment]
Not having trouble in the recent releases. Please file new bug if running into it in the 7 series
