### ISSUE TITLE
Cookie Storage = none for analytics

### ISSUE THREAD

**Issue by petya-v** [angular/angularfire#2866]
I suppose this is a feature request because I can't find it documented anywhere.

It would be nice if we could set:
`storage='none'`

It seems that here we've added a way to turn off analytics completely. However is there a way to disable cookies for analytics?
Perhaps this can be configured via a provider?
https://github.com/angular/angularfire/pull/2187

https://developers.google.com/analytics/devguides/collection/analyticsjs/cookies-user-id#disabling_cookies

**Comment by petya-v** [comment]
Relevant: https://stackoverflow.com/questions/67166213/google-analytics-consent-mode-with-angularfire

**Comment by KingDarBoja** [comment]
Hi Petya! 

It is hard to tell if it will ever be supported via Firebase as it is part of Google infrastructure and not Firebase itself as you may have noticed in the official documentation: https://firebase.google.com/docs/analytics/get-started#firebase-gtag

**Comment by jamesdaniels** [comment]
I believe the existing firebase analytics settings function should allow this option to be set, if it is not please send a feature request over to the JS SDK

**Comment by coleridge72** [comment]
@jamesdaniels 
I tried the following in my app.module providers, but cookies still appear after deleting and refreshing the page...  have I put them in the wrong place?
```
provide: CONFIG, useValue: {
  ads_storage: 'denied',
  analytics_storage: 'denied',
  send_page_view: true,
  allow_google_signals: false,
  allow_ad_personalization_signals: false,
  anonymize_ip: true,
}
```
