### ISSUE TITLE
Firebase Cloud Messaging in subdirectory  not working ?

### ISSUE THREAD

**Issue by rajhim** [angular/angularfire#2870]
**Angular:  10 **

**Firebase: 8.0.0 **

**AngularFire:6.0.4 **

```

importScripts('https://www.gstatic.com/firebasejs/8.0.0/firebase-app.js');
importScripts('https://www.gstatic.com/firebasejs/8.0.0/firebase-messaging.js');
// messagingSenderId.
firebase.initializeApp({
  apiKey: '',
  authDomain: '',
  projectId: '',
  storageBucket: '',
  messagingSenderId: '',
  appId: '',
  measurementId: ''
});


// Retrieve an instance of Firebase Messaging so that it can handle background
// messages.

const messaging = firebase.messaging();
```

created service for notification,
```
@Injectable({
  providedIn: 'root'
})
export class FirebaseMessagingService {
  currentMessage = new BehaviorSubject(null);
  tokenSubject;
  constructor(private angularFireMessaging: AngularFireMessaging, private http: HttpClient) {
  }

  getToken(){

  }
  requestPermission() {
    this.angularFireMessaging.requestPermission
      .subscribe(
        () => {
          this.angularFireMessaging.requestToken.subscribe(
            (token) => {
              this.subscribeTokenToTopic(token)
                .subscribe(dat=>{

                })
            });
        },
        (error) => { console.error(error); },
      );

  }

  receiveMessage() {
    this.angularFireMessaging.onMessage((payload) => {
      this.currentMessage.next(payload);
    });
    // this.angularFireMessaging.messages.subscribe(
    //   (msg) => {
    //     console.log("show message!", msg);
    //     this.currentMessage.next(msg);
    //   })
  }
  subscribeTokenToTopic(token, data?): Observable<any> {

    this.tokenSubject = token;
    return this.http.post<any>('https://iid.googleapis.com/iid/v1/' + token + '/rel/topics/admin',
      data, {headers: this.getHttpHead()})
      .pipe(
        catchError((error) => {
          return error;
        })
      );
  }

}
```

called service in app.component.ts on ngOnit
 It is working fine in locally.
 
 when I  build with href  /extraUrl/admin/  with sub route
 
 the following error will occur after deploying it .
 
` FirebaseError: Messaging: We are unable to register the default service worker. Failed to register a ServiceWorker for scope ('https://url.com/firebase-cloud-messaging-push-scope') with script ('https://url.com/firebase-messaging-sw.js'): A bad HTT FirebaseError: Messaging: We are unable to register the default service worker. Failed to register a ServiceWorker for scope ('https://url.com/firebase-cloud-messaging-push-scope') with script ('https://url.com/firebase-messaging-sw.js'): A bad HTTP response code (404) was received when fetching the script. (messaging/failed-service-worker-registration).P response code (404) was received when fetching the script. (messaging/failed-service-worker-registration).`

any requirement needed please let me know.

**Comment by jamesdaniels** [comment]
Use the `SERVICE_WORKER` DI Token to override the assumed location of the Firebase messaging service worker. https://github.com/angular/angularfire/blob/master/sample-compat/src/app/app.module.ts#L91
