### ISSUE TITLE
SSR stuck due to observables not completing

### ISSUE THREAD

**Issue by blasco** [angular/angularfire#2875]
This was a known issue, I've waited over a year and hoped it got resolved. Is there a fix or walk around already?

Simply doing the following:
```
      this.afStore.firestore.doc(path).get();
``` 
Makes the SSR not to complete. Funny enough, if reloading the page twice, it works... which has been mentioned here:
https://stackoverflow.com/questions/65430975/angular-universal-app-will-not-load-until-clicking-refresh-twice

Is there a way to get around this issue? Thank you for the support

**Comment by jamesdaniels** [comment]
This is not an issue with this library. When you call out to the firestore instance like that you're opting out of AngularFire and using the SDK directly, without the benefit of our zone.js work.

Use `this.afStore.doc(path).valueChanges()`

**Comment by blasco** [comment]
I do not think this issue has been solved. @jamesdaniels  I can confirm that this causes the problem too, which is part of the sdk:
```
this.afStore.doc(path).get();
 ```  
And valueChanges is even worse... with the get method I can get the page to load after reloading twice, but valueChanges hangs for ever, the page never loads:

```
  // SSR never completes
  private afGetDoc(path: string) {
    return new Promise(async res => {
      this.afStore.doc(this.getPath(path)).valueChanges().pipe(
        take(1)
      ).subscribe(data => {
        console.log(`data received path: ${path}`); // I can see the data in the SSR console
        console.log(data);
        res(data);
      });
    });
  }
```
It seems to hang the node server:
```
    res.render(indexPath, 
      {
        req,
        providers: [{ provide: APP_BASE_HREF, useValue: req.baseUrl }],
      }, (_, html) => {
        if (html) {
            console.log('sending compiled source'); // <----- I can see this printed
            res.send(html); // <------- the browser doesn't get the response
``
