### ISSUE TITLE
Infinity loading. Angular 9 Universal + Firebase

### ISSUE THREAD

**Issue by Teebo** [angular/angularfire#2876]
### Version info

**Angular:**
9.0.3
**Firebase:**
8.2.1
**AngularFire:**
@angular/fire

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

My function implementation is below

```
export const ssr = functions.runWith({
  timeoutSeconds: 300,
  memory: "1GB"
}).https.onRequest((request, response) => {
  require(`${process.cwd()}/dist/mot/server`).app(request, response);
});

```

For more defails. I also have a SO question: https://stackoverflow.com/questions/68362185/angular-universal-route-resolver-firebase-loading-timeout

**Failing test unit, Stackblitz demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

### Expected behavior

See the page source code when browser View page source option is cliked.

### Actual behavior
The page refreshes forever without errors.
Checking the error logs for the SSR function shows nothing until the function times out.
It happens with specific pages not all of them.

**Comment by MNorgren** [comment]
@Teebo  - I see you closed this issue. Did you get it resolved?

**Comment by Ross-Rawlins** [comment]
How did you resolve this?
