### ISSUE TITLE
Bug: Remote Config does not get loaded on iOS 14.6 browsers after cold start

### ISSUE THREAD

**Issue by SwonVIP** [angular/angularfire#2882]
### Version info

**Angular:** 12.1.4

**Firebase:** 8.8.1

**AngularFire:** 6.1.5

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** iOS 14.6 (latest Safari, Chrome 92)

### How to reproduce these conditions

**Hello World App with Remote Config**
https://fir-test-67641.web.app/

**Source code:**
https://github.com/SwonVIP/remote-config-angularfire

**Steps to set up and reproduce**

1. Open URL on the above described system/ browser.
2. You will see the default value of "Hello World" which will get replaced by the Remote Config value "Hi Angular" a few ms later
3. Close and kill the browser (browser process has to be stopped entirely)
4. Re-open the browser
5. Web app should show again - however it will be stuck on the default "Hello World" value.
6. When investigating the network traffic via debugging on a Mac you will see that no fetch request to the firebase remote source has been sent. No errors in the console are visible either.
7. If you reload the page it will work and you will see the remote config value

Adding polyfills did not resolve the issue either

**Comment by tmk1991** [comment]
Experiencing something similar across all devices with remote config. All responses are coming back empty on the client but I can confirm they're visible in the firebase console. 

When putting AngularfireRemoteConfig on debug mode, I'm seeing strange errors:
`@firebase/remote-config: Returning static value for key "theme". Define a default or remote value if this is unintentional.`

As mentioned, there  are values inside of remote config. 

Upgraded to latest SDK and latest @angular/fire and no luck.

Lowered the fetch interval timeout so I know its supposed to be fetching:
`@firebase/remote-config: Config fetch cache check. Cache age millis: 373720. Cache max age millis (minimumFetchIntervalMillis setting): 5000. Is cache hit: false.`

Might be related to this: https://github.com/firebase/firebase-ios-sdk/issues/7424

**Comment by jamesdaniels** [comment]
This wouldn't be an issue with AF IMO, please file with the JS SDK
