### ISSUE TITLE
SSR not working for the compat api

### ISSUE THREAD

**Issue by blasco** [angular/angularfire#2902]
Versions:

```
    "@angular/core": "12.1.4",
    "@nguniversal/express-engine": "12.1.0",
    ...
    "@angular/fire": "7.0.0",
    "firebase": "9.0.0",

```

I've upgraded to the latest version. The following works fine:
```
@NgModule({
  imports: [
     provideFirebaseApp(() => initializeApp(environment.firebase)),
...
```
But the compat mode only works with `ng serve` , it breaks the universal app
```
@NgModule({
  imports: [
    AngularFireModule.initializeApp(environment.firebase),
...
```

Is this a known issue? 

I'm also getting this error with `ng serve`, I wonder if it is related:
```
error TS2305: Module '"@firebase/app"' has no exported member '_FirebaseAppInternal'.

19 import { _FirebaseAppInternal as _FirebaseAppExp } from '@firebase/app';
```

**Comment by thervl** [comment]
Hey @blasco, yeah SSR is down for me too. I am also having issues with another error.

Whenever I try to use the new @angular/fire functions I get this new error:
Uncaught Error: AngularFireModule has not been provided at getSchedulers

I think it has something to do with the initialisation of the app:
provideFirebaseApp(() => initializeApp(firebaseConfig)),

Were you able to successfully initialise and provide your firebase instance with version 7?

**Comment by jamesdaniels** [comment]
both issues should be adressed in the next js sdk releases 7.0.1 #2903

**Comment by nternouski** [comment]
> Hey @blasco, yeah SSR is down for me too. I am also having issues with another error.
> 
> Whenever I try to use the new @angular/fire functions I get this new error:
> Uncaught Error: AngularFireModule has not been provided at getSchedulers
> 
> I think it has something to do with the initialisation of the app:
> provideFirebaseApp(() => initializeApp(firebaseConfig)),
> 
> Were you able to successfully initialise and provide your firebase instance with version 7?
 
@thervl 
I have the same error, Do you resolved it?
