### ISSUE TITLE
Cannot Get Authentication Working in New Angular 12 App

### ISSUE THREAD

**Issue by BaronVonPerko** [angular/angularfire#2906]
### Version info

**Angular:** 12.0.2

**Firebase:** 9.0.0

**AngularFire:** 7.0.0

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** Node 16.5.0, Windows 10 WSL2 Ubuntu, Edge Latest

**Failing test unit, Stackblitz demonstrating the problem**

Will provide if absolutely necessary.

### How to reproduce these conditions

**Steps to set up and reproduce**

Create a brand new Angular + AngularFire application.  Following the quickstart guide to get Auth working, I am unable to import firebase:

```typescript
import firebase from "firebase/app";
import EmailAuthProvider = firebase.auth.EmailAuthProvider;
```

Error: 

> **Module '..../node_modules/firebase/app/dist/app/index' has no default export**

Changing this line to:

```typescript
import * as firebase from "firebase/app";
import EmailAuthProvider = firebase.auth.EmailAuthProvider;
```
causes the next issue: 

> **Namespace '..../node_modules/firebase/app/dist/app/index' has no exported member 'auth'.**

Here is the full component:

```typescript
import { Component } from '@angular/core';
import { AngularFireAuth } from "@angular/fire/compat/auth";
import * as firebase from "firebase/app";
import EmailAuthProvider = firebase.auth.EmailAuthProvider;

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

  constructor(public auth: AngularFireAuth) {
  }

  showLoginPopup() {
    this.auth.signInWithPopup(new EmailAuthProvider());
  }
}
```

Here is the **app.module.ts** file:

```typescript
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { AngularFireModule } from "@angular/fire/compat";
import { environment } from "../environments/environment";
import { AngularFirestoreModule } from "@angular/fire/compat/firestore";
import { ParkComponent } from './pages/park/park.component';
import { ParkListComponent } from './pages/park-list/park-list.component';
import { AngularFireAuthModule } from "@angular/fire/compat/auth";

@NgModule({
  declarations: [
    AppComponent,
    ParkComponent,
    ParkListComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    AngularFireModule.initializeApp(environment.firebase),
    AngularFirestoreModule,
    AngularFireAuthModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {
}
```

### Expected behavior

It should be able to compile as this is how it is explained in the docs.

### Actual behavior

Error compiling, cannot run app.

**Comment by BaronVonPerko** [comment]
Closed as I was able to figure it out using *compat* mode.

**Comment by falk-stefan** [comment]
Any idea why I am getting:

```none
./src/app/services/auth.service.ts:3:0-39 - Error: Module not found: Error: Package path ./compat is not exported from package /home/sfalk/workspaces/web-mobile/node_modules/firebase (see exports field in /home/sfalk/workspaces/web-mobile/node_modules/firebase/package.json)
```

All my imports are coming from `@angular/fire/compat/` so why is this not working?

See also my [stackoverflow question](https://stackoverflow.com/questions/69054603/error-package-path-compat-is-not-exported-from-package).
