### ISSUE TITLE
ng update modifies files out of the project

### ISSUE THREAD

**Issue by jnizet** [angular/angularfire#2907]
### Version info

**Angular:**
12.2.1

**Firebase:**
8.9.1

**AngularFire:**
6.1.5

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
macOS

### Expected behavior

`ng update @angular/fire` modifies source files of the Angular project only

### Actual behavior

`ng update @angular/fire` modifies source files outside of the angular project.

I have a subdirectory `functions` in my root project directory, containing... a firebase function, with its own package.json etc. When running the update from the root directory containing the package.json for the Angular poject, the update also modifies the file `functions/src/index.ts` and replaces `import * as functions from 'firebase-functions';` by `import * as functions from 'firebase/compat-functions';`.

**Comment by jamesdaniels** [comment]
Yuck, sorry about that, I would've expected the angular workspace to only include the relevant files. Clearly I need to grab the project root. Thanks for reporting!

**Comment by jamesdaniels** [comment]
Cutting 7.0.1 now. Thanks for reporting!
