### ISSUE TITLE
provided region for cloud functions is ignored

### ISSUE THREAD

**Issue by YannicEl** [angular/angularfire#2909]
### Version info

**Angular:** 12.2.3

**Firebase:** 9.0.0

**AngularFire:** 7.0.0

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** node: v14.17.0, chrome: 92.0.4515.159

### How to reproduce these conditions

**Failing test unit, Stackblitz demonstrating the problem**

i could't get angularfire 7 running in stackblitz, sorry.

**Steps to set up and reproduce**

1. Setup a angualrfire 7 project
2. use the provideFunctions method in the app.module.ts
3. specify a region in the getFunctions function

```
@NgModule({
  ...
  imports: [
    provideFirebaseApp(() => initializeApp(environment.firebase)),
    provideFunctions(() => getFunctions(getApp(), 'europe-west1')),
  ],
  ...
})
```

### Debug output

![image](https://user-images.githubusercontent.com/42739553/131338309-69c95b2f-7a6b-48e3-ab4a-1fa58e17a94a.png)
The function is called from the default region even though I specified a region 

### Expected behavior

The function should be called with the region 'europe-west1'

### Actual behavior

The function is called with the default region 'us-central1'

I think the provided region for cloud functions is ignored.

**Comment by jamesdaniels** [comment]
Hmmm... good catch. It's probably that the injected Functions instance is the "default" instance with respect to the SDK. Clearly I should prioritize the one that is passed to `provideFunctions`...

In the meantime you should be able to access your function initialized with a region by injecting the `FunctionsInstances` array.

**Comment by jamesdaniels** [comment]
Cutting 7.0.1 now, which will have the fix. Thanks for catching this!

**Comment by YannicEl** [comment]
wow that was quick. thanks a lot.

**Comment by Rawquete** [comment]
Excuse me i still have the same error, i am on an angular 13 version and angularfire 7.2. For the moment I use the cloud functions emulator. Could you unblock me?

**Comment by GaneshVersionx** [comment]
> getApp(), '



> Hmmm... good catch. It's probably that the injected Functions instance is the "default" instance with respect to the SDK. Clearly I should prioritize the one that is passed to `provideFunctions`...
> 
> In the meantime you should be able to access your function initialized with a region by injecting the `FunctionsInstances` array.

I'm not getting  briefly explanation Please
