### ISSUE TITLE
How can I enable Offline Capabilities for Realtime DB?

### ISSUE THREAD

**Issue by orenkatz-lp** [angular/angularfire#2910]
I know w/ Firestore you can enable persistence but how can I do it with Realtime DB?
According to Firebase doc, you should be able to set the persistence to true.
https://firebase.google.com/docs/database/ios/offline-capabilities#swift

Thanks,
Oren

**Comment by jamesdaniels** [comment]
Persistence is available out of box for RTDB on iOS and Android, not web unfortunately. There may be some open source initiatives that fill this gap?
