### ISSUE TITLE
ng update @angular/fire migration failed (7.0.3) - The "path" argument must be of type string

### ISSUE THREAD

**Issue by mazlano27** [angular/angularfire#2924]
### Version info

**Angular: 12**

**Firebase: 8.1.0 (before migration)**

**AngularFire: 6.1.5 (before migration)**

**Steps to set up and reproduce**

Run ng update@angular/fire  in an existing angular firebase project

### Debug output

`❯ Update @angular/fire to v7. ✖ Migration failed: The "path" argument must be of type string. Received undefined See "/private/var/folders/_8/g0bkbl8s2pj6wyzc3g76rfhr0000gn/T/ng-St0QKH/angular-errors.log" for further details.`

The log file shows →

`[error] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined at validateString (internal/validators.js:124:11) at Object.join (path.js:1110:7) at /Users/Azlan_Mac/Desktop/Dev/Project-X/node_modules/@angular/fire/schematics/update/v7/index.js:45:77 at Array.map (<anonymous>) at /Users/Azlan_Mac/Desktop/Dev/Project-X/node_modules/@angular/fire/schematics/update/v7/index.js:45:58 at MergeMapSubscriber.project (/Users/Azlan_Mac/Desktop/Dev/Project-X/node_modules/@angular-devkit/schematics/src/rules/call.js:75:24) at MergeMapSubscriber._tryNext (/Users/Azlan_Mac/Desktop/Dev/Project-X/node_modules/rxjs/internal/operators/mergeMap.js:67:27) at MergeMapSubscriber._next (/Users/Azlan_Mac/Desktop/Dev/Project-X/node_modules/rxjs/internal/operators/mergeMap.js:57:18) at MergeMapSubscriber.Subscriber.next (/Users/Azlan_Mac/Desktop/Dev/Project-X/node_modules/rxjs/internal/Subscriber.js:66:18) at Observable._subscribe (/Users/Azlan_Mac/Desktop/Dev/Project-X/node_modules/rxjs/internal/util/subscribeToArray.js:5:20)`

### Expected behavior

Should migrate to Angular Fire 7 & Firebase 9

### Actual behavior

Migration is failing. 

Please note that when migrating using version 7.0.1 of the schematics, the migration was successful (after cleaning up the issues related to the schematic updating imports in files outside the project's scope).

**Comment by jamesdaniels** [comment]
Oh interesting, do you mind emailing me your angular.json? `jamesdaniels@google.com`. I think I know what this is related to but it would suggest there’s something I’m not expecting in there. Thanks.

**Comment by mazlano27** [comment]
> jamesdaniels@google.com

Sent with the subject line "Angular JSON file for debugging" 👍
