### ISSUE TITLE
Compat + emulators isn't working well

### ISSUE THREAD

**Issue by falk-stefan** [angular/angularfire#2932]
It's been two completely wasted days now. I have not the slightest idea what could be wrong with my setup or what kind of information I am missing here but please somebody put me out of my misery here.

> **tl;dr:** I follow a simple example where I want to create a new user using Google Sign-Up. The user gets created in the Auth service but not in the Firestore. I have no idea how my local `firebaseConfig` should look like and why this is not working. 

### Version info

**Angular:** 12

**Firebase:** 9.0.1

**AngularFire:** 7.0.3

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

Node: 16

### How to reproduce these conditions

You can clone [this repository](https://github.com/falk-stefan/angularfire-i2932) and give it a try yourself.

I don't really know. All I did was run `firebase init`, and fire ap the base with:

```
$ npm run build --prefix functions && firebase emulators:start --inspect-functions & tsc --watch
```

All I am trying to to is save a new user to the Firestore:

```typescript
  async googleSignIn() {
    this.logger.debug('User signs in with Google.')
    const provider = new auth.GoogleAuthProvider();
    const credentials = await this.afAuth.signInWithPopup(provider);
    return await this.updateUserData(credentials.user);
  }

  private async updateUserData(user: User | null) {

    if (!user) {
      throw "User cannot be null.";
    }

    const userRef: AngularFirestoreDocument<User> = this.afs.doc(`/users/${user.uid}`);
    const data: any = {
      uid: user.uid,
      email: user.email,
      displayName: user.displayName ? user.displayName : user.email,
      photoURL: user.photoURL
    }
    return userRef.set(data, {merge: true});
  }
```

Using

```typescript
import {NgModule} from '@angular/core';
import {BrowserModule} from '@angular/platform-browser';

import {AppComponent} from './app.component';
import {AppRouting} from "./app.routing";
import {LoggerModule, NgxLoggerLevel} from "ngx-logger";
import {environment} from "../environments/environment";
import {HttpClientModule} from "@angular/common/http";
import {SharedModule} from "./modules/shared.module";
import {BrowserAnimationsModule} from "@angular/platform-browser/animations";
import {AngularFireModule} from "@angular/fire/compat";
import {USE_EMULATOR as USE_AUTH_EMULATOR} from '@angular/fire/compat/auth';
import {AngularFirestore, USE_EMULATOR as USE_FIRESTORE_EMULATOR} from '@angular/fire/compat/firestore';
import {USE_EMULATOR as USE_FUNCTIONS_EMULATOR} from '@angular/fire/compat/functions';


const envFirebase = environment.firebase;

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    SharedModule,
    BrowserModule,
    BrowserAnimationsModule,
    HttpClientModule,
    AppRouting,

    // Logging
    LoggerModule.forRoot({
      serverLoggingUrl: '/',
      level: environment.production ? NgxLoggerLevel.OFF : NgxLoggerLevel.TRACE,
      serverLogLevel: NgxLoggerLevel.OFF
    }),
    // Firebase
    AngularFireModule.initializeApp(envFirebase.config),
  ],
  providers: [
    // Firebase
    {provide: USE_AUTH_EMULATOR, useValue: envFirebase.useEmulators ? ['http://localhost:9099'] : undefined},
    {provide: USE_FUNCTIONS_EMULATOR, useValue: envFirebase.useEmulators ? ['http://localhost:5001'] : undefined},
    {provide: USE_FIRESTORE_EMULATOR, useValue: envFirebase.useEmulators ? ['http://localhost:8080'] : undefined},
  ],
  bootstrap: [AppComponent]
})
export class AppModule {
  constructor(firestore: AngularFirestore) {
    firestore.firestore.settings({experimentalForceLongPolling: true})
  }
}
```  

### Debug output

After the user got created in the Authentication Service I am seeing this in my console.

** Errors in the JavaScript console **

```
FirebaseError: Missing or insufficient permissions.
```

![Screenshot from 2021-09-08 18-36-00](https://user-images.githubusercontent.com/58136779/132549372-03df6b6a-3a15-42aa-8df1-5516e22cfbd1.png)

### Also:

```
export const environment = {
  production: false,
  firebase: {
    useEmulators: true,
    config: {
      apiKey: "*******",
      authDomain: ""*******-dev.firebaseapp.com",
      projectId: ""*******-dev",
      storageBucket: ""*******-dev.appspot.com",
      messagingSenderId: ""*******",
      appId: "1:"*******:web:"*******",
      measurementId: ""*******"
    },
  }
};
``` 

The interesting thing is that I see this in https://console.firebase.google.com/project/project/firestore/usage/last-24h/reads:

![Screenshot from 2021-09-08 18-39-57](https://user-images.githubusercontent.com/58136779/132549875-d041f500-9cb5-4e45-bd00-45865d4c6608.png)

Even though I started using Emulators from the very beginning. 

These are my Firestore settings:

![Screenshot from 2021-09-08 18-40-46](https://user-images.githubusercontent.com/58136779/132549985-78d73f01-3fab-4881-9889-5be208f6dc56.png)

which are the same as  my local settings:

```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if true;
    }
  }
}
```

**Comment by jamesdaniels** [comment]
Your Firestore and functions emulator tokens are in the wrong format. They’re inconsistent with auth, so you’re trying to hit prod with emulated credentials. Use `[‘host’, port]`, see https://github.com/angular/angularfire/blob/b22c82478dc4bc2df108bf8fae6de40a9107c646/sample-compat/src/app/app.module.ts#L81 

‘Tis a silly API I know but it’s the one that shipped 😉

**Comment by falk-stefan** [comment]
@jamesdaniels I am not sure if this is correct. I started off with the `['host', port]` format but that didn't work at all. I explicitly had to changed this to `['http://localhost:9099']`. I think I saw a post somewhere that `['host', port]` is not supported in v9 anymore.

Please reopen this issue.

**Comment by tja4472** [comment]
Change

```json
  providers: [
    // Firebase
    {provide: USE_AUTH_EMULATOR, useValue: envFirebase.useEmulators ? ['http://localhost:9099'] : undefined},
    {provide: USE_FUNCTIONS_EMULATOR, useValue: envFirebase.useEmulators ? ['http://localhost:5001'] : undefined},
    {provide: USE_FIRESTORE_EMULATOR, useValue: envFirebase.useEmulators ? ['http://localhost:8080'] : undefined},
  ],
```

to

```json
  providers: [
    // Firebase
    {provide: USE_AUTH_EMULATOR, useValue: envFirebase.useEmulators ? ['http://localhost:9099'] : undefined},
    {provide: USE_FUNCTIONS_EMULATOR, useValue: envFirebase.useEmulators ? ['localhost', 5001] : undefined},
    {provide: USE_FIRESTORE_EMULATOR, useValue: envFirebase.useEmulators ? ['localhost', 8080] : undefined},
  ],
```

**Comment by falk-stefan** [comment]
@tja4472 Still the same. I get no logs in http://localhost:4000/firestore/requests

Well.. the error message changed slightly but essentially I'm still getting "permission denied":

![Screenshot from 2021-09-09 15-56-09](https://user-images.githubusercontent.com/58136779/132699184-929cd813-840e-4866-8d99-a14ed2c37350.png)

**Comment by falk-stefan** [comment]
@tja4472 @jamesdaniels 

I have now created a repository from scratch. There's a single button that you can use i.o. to try out the Google sign-in.

If you want to reproduce the issue I have just clone https://github.com/falk-stefan/angularfire-i2932

**Comment by jamesdaniels** [comment]
I'm able to reproduce, it turns out my sample still had a v9 release candidate... this seems like an issue with the JS SDK however, I'll investigate.

**Comment by jamesdaniels** [comment]
Updating my `firebase-tools` fixed the issue, it does seem that Firebase v9 requires newer versions of the emulators. Guessing it has something to do with fetch vs xmlhttprequest. Downloading your repo now.

**Comment by jamesdaniels** [comment]
confirmed fixed, no trouble with your repo if firebase-tools is updated.

**Comment by falk-stefan** [comment]
@jamesdaniels Thanks a lot! :+1:
