### ISSUE TITLE
RTDB startAfter has a startAt behavior

### ISSUE THREAD

**Issue by mparpaillon** [angular/angularfire#2965]
### Version info

**Angular:** 12.2.0

**Firebase:** 9.0.2

**AngularFire:** 7.0.4

### How to reproduce these conditions

```ts
const listRef = this.ref('people');

const constraints: QueryConstraint[] = [
  orderByChild('age'),
  startAfter(10)
];

const q = query(listRef, ...constraints);

return listVal(q);
```

This will include age 10 in the query results as if I used startAt instead of startAfter

Is there a stackblitz template for the new API ? I could create an example.

### Debug output

No output to show

### Expected behavior

I expect the start after to start... after the given value. And not include it inside the results

### Actual behavior

I expect the start after to start... after the given value. And not include it inside the results

**Comment by mparpaillon** [comment]
I think endBefore has the same issue. But since this looks broken I'm not sure

**Comment by jamesdaniels** [comment]
seems to me that this should be filed as a bug with the JS SDK as angularfire has no additional logic here
