### ISSUE TITLE
How to use ng deploy with CI systems like GitHub Actions

### ISSUE THREAD

**Issue by OmarioHassan** [angular/angularfire#2981]
### Discussed in https://github.com/angular/angularfire/discussions/2957

<div type='discussions-op-text'>

<sup>Originally posted by **OmarioHassan** September 14, 2021</sup>
I'm trying to use ng deploy with token but I can't
Any help </div>

**Comment by jamesdaniels** [comment]
Closing as this is not related to AngularFire but something with your setup.

**Comment by OmarioHassan** [comment]
@jamesdaniels  the worst support I see in my life 
npm un @angular/fire

**Comment by jamesdaniels** [comment]
> @jamesdaniels the worst support I saw in my life
> npm un @angular/fire

Please see the README https://github.com/angular/angularfire#having-troubles
