### ISSUE TITLE
[AngularFirestore -> InjectionToken angularfire2.app.options -> InjectionToken angularfire2.app.options -> InjectionToken angularfire2.app.options -> InjectionToken angularfire2.app.options]: 

### ISSUE THREAD

**Issue by Corovino** [angular/angularfire#2985]
### Version info

Angular CLI: 12.2.7
Node: 14.16.0
Package Manager: npm 6.14.11
OS: win32 x64

Angular: 12.2.7
... animations, cli, common, compiler, compiler-cli, co
... platform-browser, platform-browser-dynamic, router

Package                         Version
-------------------------------------------------------
@angular-devkit/architect       0.1200.5
@angular-devkit/build-angular   12.2.7
@angular-devkit/core            12.2.7
@angular-devkit/schematics      12.2.7
@angular/fire                   7.0.4
rxjs                            6.6.7    
typescript                      4.3.5  

### How to reproduce these conditions
I tried to u firebase  whi modular lazy load  and call  fireAngular from 
a service  but when  i call the route i got this error :
`NullInjectorError: R3InjectorError(DashboardModule)[AngularFirestore -> InjectionToken angularfire2.app.options -> InjectionToken angularfire2.app.options -> InjectionToken angularfire2.app.options -> InjectionToken angularfire2.app.options]: 
  NullInjectorError: No provider for InjectionToken angularfire2.app.options!`

**Failing test unit, Stackblitz demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **
![image](https://user-images.githubusercontent.com/5142742/134957067-db1dd090-3794-4877-9a5c-1cdd89f6bd82.png)
![image](https://user-images.githubusercontent.com/5142742/134957168-a5e95e0f-9cc5-4aad-9832-a0597dcd5a93.png)
![image](https://user-images.githubusercontent.com/5142742/134957207-183e4007-868e-46d3-82b5-e4bfae4822cb.png)
![image](https://user-images.githubusercontent.com/5142742/134957254-3119ee25-8f65-415e-92c9-8ffc2aa386a9.png)

I have tried to provide  angularFire in my app.module and as well in my dashboard lazy module but nothing works

**Comment by jagdishjadeja** [comment]
i am also facing same issue
can someone provide solution for this issue ?

**Comment by jamesdaniels** [comment]
You're providing and injecting `AngularFirestore`, while using the new `provide*` methods. Mixing compat and the new modular SDK. While this might work in places, I'd recommend going with one of the other.

**Comment by Corovino** [comment]
Im sorry but what exactly u means  whit one of the others i followed the documentation  and i still having the  error

**Comment by Corovino** [comment]
> You're providing and injecting `AngularFirestore`, while using the new `provide*` methods. Mixing compat and the new modular SDK. While this might work in places, I'd recommend going with one of the other.

Im sorry but what exactly u means whit one of the others i followed the documentation and i still having the error

**Comment by pacoyx** [comment]
Cuando quieras usar el Auth de firebase declara asi en el modulo:

**Module:**
`import { environment } from '../environments/environment';
import { initializeApp, provideFirebaseApp } from '@angular/fire/app';
import { provideAuth, getAuth } from '@angular/fire/auth';
import { provideFirestore, getFirestore } from '@angular/fire/firestore';

@NgModule({
    ...
    imports: [
      ...
      provideFirebaseApp(
          () => initializeApp(environment.firebaseConfig)), 
          provideAuth(() => getAuth()), 
          provideFirestore(() => getFirestore(),
      ),
    ],
    ...
})`

`import { FIREBASE_OPTIONS } from '@angular/fire/compat';

@NgModule({
    ...
    providers: [
        { provide: FIREBASE_OPTIONS, useValue: environment.firebaseConfig }
    ],
})`

**Comment by MaratMartirosyan999** [comment]
For me, it worked just adding the provider in the app.module.ts

```
  **providers: [
    {provide: FIREBASE_OPTIONS, useValue: environment.firebaseConfig}
  ],**
```

**Comment by Ameerusa86** [comment]
I'm using Angular 17, and faced a lot of issues to make Firebase to like Angular 17 unlike the 16 version, adding the below lines to app.config.ts fixed my issue

import { FIREBASE_OPTIONS } from '@angular/fire/compat';
{ provide: FIREBASE_OPTIONS, useValue: environment.firebaseConfig },

**Comment by bhushankalvani** [comment]
> ### Cuando quieras usar el Auth de firebase declara asi en el modulo:
> **Module:**
> 
> ```
> import { environment } from '../environments/environment';
> import { initializeApp, provideFirebaseApp } from '@angular/fire/app';
> import { provideAuth, getAuth } from '@angular/fire/auth';
> import { provideFirestore, getFirestore } from '@angular/fire/firestore';
> 
> @NgModule({
>     ...
>     imports: [
>       ...
>       provideFirebaseApp(
>           () => initializeApp(environment.firebaseConfig)), 
>           provideAuth(() => getAuth()), 
>           provideFirestore(() => getFirestore(),
>       ),
>     ],
>     ...
> })
> ```
> 
> Tambien agregale este objeto a tu provider de tu modulo:
> 
> ```
> import { FIREBASE_OPTIONS } from '@angular/fire/compat';
> 
> @NgModule({
>     ...
>     providers: [
>         { provide: FIREBASE_OPTIONS, useValue: environment.firebaseConfig }
>     ],
> })
> ```

This works for Angular 17 auth as well. Here's my config if anyone ends up finding a solution for Angular 17.

```
export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(routes),
    provideHttpClient(),
    importProvidersFrom(provideFirebaseApp(
      () => initializeApp(environment.firebaseConfig)),
      provideAuth(() => getAuth()), 
    ),
    {
      provide: HTTP_INTERCEPTORS,
      useValue: HttpInterceptor,
      multi: true,
    }
  ]
};

```

**Comment by Mathiasfx** [comment]
> I'm using Angular 17, and faced a lot of issues to make Firebase to like Angular 17 unlike the 16 version, adding the below lines to app.config.ts fixed my issue
> 
> import { FIREBASE_OPTIONS } from '@angular/fire/compat'; { provide: FIREBASE_OPTIONS, useValue: environment.firebaseConfig },

this solution works for me

**Comment by MarcinTomkiewicz** [comment]
This is how my AppConfig looks like:
`import { ApplicationConfig, importProvidersFrom } from '@angular/core';
import { provideRouter } from '@angular/router';

import {
  getAnalytics,
  provideAnalytics,
} from '@angular/fire/analytics';
import { initializeApp, provideFirebaseApp } from '@angular/fire/app';
import { getAuth, provideAuth } from '@angular/fire/auth';
import { getFirestore, provideFirestore } from '@angular/fire/firestore';
import { getFunctions, provideFunctions } from '@angular/fire/functions';
import { getMessaging, provideMessaging } from '@angular/fire/messaging';
import { getPerformance, providePerformance } from '@angular/fire/performance';
import { getStorage, provideStorage } from '@angular/fire/storage';
import { FIREBASE_OPTIONS } from '@angular/fire/compat';
import { environment } from '../environments/environment';
import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(routes),
    { provide: FIREBASE_OPTIONS, useValue: environment.firebaseConfig },
    importProvidersFrom([
      provideFirebaseApp(() => initializeApp(environment.firebaseConfig)),
      provideAnalytics(() => getAnalytics()),
      provideAuth(() => getAuth()),
      provideFirestore(() => getFirestore()),
      provideFunctions(() => getFunctions()),
      provideMessaging(() => getMessaging()),
      providePerformance(() => getPerformance()),
      provideStorage(() => getStorage()),
    ]),

  ],
};
`
I am still getting the error:

> main.ts:6 NullInjectorError: R3InjectorError(Standalone[_AppComponent])[_AngularFireAuth -> InjectionToken angularfire2.app.options -> InjectionToken angularfire2.app.options -> InjectionToken angularfire2.app.options]: 
  NullInjectorError: No provider for InjectionToken angularfire2.app.options!
    at NullInjector.get (core.mjs:1654:27)
    at R3Injector.get (core.mjs:3093:33)
    at R3Injector.get (core.mjs:3093:33)
    at R3Injector.get (core.mjs:3093:33)
    at injectInjectorOnly (core.mjs:1100:40)
    at ɵɵinject (core.mjs:1106:42)
    at Object.AngularFireAuth_Factory [as factory] (angular-fire-compat-auth.mjs:160:42)
    at core.mjs:3219:47
    at runInInjectorProfilerContext (core.mjs:866:9)
    at R3Injector.hydrate (core.mjs:3218:21)<

I have tried literally everything. I am using standalone components and it JUST DOESN'T WORK.

**Comment by Nevi63** [comment]
> I'm using Angular 17, and faced a lot of issues to make Firebase to like Angular 17 unlike the 16 version, adding the below lines to app.config.ts fixed my issue
> 
> import { FIREBASE_OPTIONS } from '@angular/fire/compat'; { provide: FIREBASE_OPTIONS, useValue: environment.firebaseConfig },

this still works in angular 18, at least it worked for me

**Comment by akaaljotsingh** [comment]
> I'm using Angular 17, and faced a lot of issues to make Firebase to like Angular 17 unlike the 16 version, adding the below lines to app.config.ts fixed my issue
> 
> import { FIREBASE_OPTIONS } from '@angular/fire/compat'; { provide: FIREBASE_OPTIONS, useValue: environment.firebaseConfig },

Works well , thanks

**Comment by wilhan25** [comment]
I'm using Angular 19 and what worked for me was to change the app.config.ts as follows:
import in the imports field.
import { FIREBASE_OPTIONS } from '@angular/fire/compat';

and then add { provide: FIREBASE_OPTIONS, useValue: firebaseConfig }, in the providers, as in the example below
```
export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes),
    provideClientHydration(withEventReplay()),
    provideAnimationsAsync(),
    // Firebase Provider
    { provide: FIREBASE_OPTIONS, useValue: firebaseConfig },
    provideFirebaseApp(() => initializeApp(firebaseConfig)),
    provideFirestore(() => getFirestore()),
    provideAuth(() => getAuth()) 
  ],
```
};

**Comment by isaac-svg** [comment]
Thanks @MaratMartirosyan999, It worked
