### ISSUE TITLE
Error: Module not found: Error: Can't resolve 'rxfire/auth'

### ISSUE THREAD

**Issue by pacoita** [angular/angularfire#2991]
### Version info

**Angular:**  12.2.7

**Firebase:**  9.1.0

**AngularFire:** 7.0.4

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** Node v14.17.0 - Windows 10 - Chrome 94

### How to reproduce these conditions

**Steps to set up and reproduce**

- Execute the `ng update @angular/fire` command from an Angular project running angular/fire (prior v 7).

### Debug output

** Errors in the JavaScript console **

```
./node_modules/@angular/fire/fesm2015/angular-fire-auth.js:8:0-93 - Error: Module not found: Error: Can't resolve 'rxfire/auth' in 'C:\Pet Projetcs\blood-pressure\node_modules\@angular\fire\fesm2015'

./node_modules/@angular/fire/fesm2015/angular-fire-firestore.js:9:0-288 - Error: Module not found: Error: Can't resolve 'rxfire/firestore' in 'C:\Pet Projetcs\blood-pressure\node_modules\@angular\fire\fesm2015'

Error: node_modules/@angular/fire/auth/rxfire.d.ts:1:77 - error TS2307: Cannot find module 'rxfire/auth' or its corresponding 
type declarations.

1 import { authState as _authState, user as _user, idToken as _idToken } from 'rxfire/auth';
                                                                              ~~~~~~~~~~~~~
Error: node_modules/@angular/fire/firestore/rxfire.d.ts:1:261 - error TS2307: Cannot find module 'rxfire/firestore' or its corresponding type declarations.

1 import { collectionChanges as _collectionChanges, collection as _collection, sortedChanges as _sortedChanges, auditTrail as 
_auditTrail, collectionData as _collectionData, doc as _doc, docData as _docData, snapToData as _snapToData, fromRef as _fromRef } from 'rxfire/firestore';
```

A complete new installation of node_modules did not fixed it, nor updating the individual angular/fire modules.

### Expected behavior

The new library would be updated installing also all dependencies.

### Actual behavior

The error prevents from correctly build the project with the latest angular/fire and firebase libraries.

**Comment by rulaman123** [comment]
I think you should install rxfire first.
I installed angular/fire, rxfire, firebase and rxjs.

**Comment by pacoita** [comment]
I tried that too, but it did not help at first. 

However after a complete reboot, I installed the node_modules again and this time all went through. Probably something was still cached somehow.

It would though be nice if the all peer dependencies would be downloaded without having to go individually searching for the missing pieces.

Closing the ticket as it worked at the end.

**Comment by cevaris** [comment]
@rulaman123 👍 
thanks
