### ISSUE TITLE
Why angular/fire does not have any dependencies to rxfire and firebase

### ISSUE THREAD

**Issue by benzmarkus** [angular/angularfire#2992]
<!--

Angular: 12

Firebase: newest

AngularFire: newest

### How to reproduce these conditions
just add "yarn add @angular/fire"

### Actual behavior
no dependencies are installed. need to manually add rxfire and firebase

**Comment by jamesdaniels** [comment]
They're peerDependencies, as we expect the developer to use/maintain those dependencies and we mark what versions we're compatible with. This is an NPM best practice. `ng add @angular/fire` will install those peers for you.
