### ISSUE TITLE
where to import connectEmulator from?

### ISSUE THREAD

**Issue by Pingear** [angular/angularfire#3040]
since there is no documentation, I will gradually find out the information I need for work.

Please tell me where to import connectEmulator from? Thanks)

**Comment by tja4472** [comment]
See:

https://github.com/angular/angularfire/blob/d724d81eafe003d2ec18728998cec7682aaaaeec/samples/modular/src/app/app.module.ts#L4-L7

**Comment by Pingear** [comment]
> See:
> 
> https://github.com/angular/angularfire/blob/d724d81eafe003d2ec18728998cec7682aaaaeec/samples/modular/src/app/app.module.ts#L4-L7

Thanks)
I was misled by the fact that the migration guide specifies connectEmulator

<img width="554" alt="Screenshot 2021-11-01 at 19 30 06" src="https://user-images.githubusercontent.com/16469484/139714747-d206055a-2ba0-44d5-ba1f-e27770ec3847.png">

I made a pull request. - https://github.com/angular/angularfire/pull/3041

Just yesterday I found out that the project has no v7 documentation, one sheet and that one with errors))
Does anyone know why the project looks abandoned?
