### ISSUE TITLE
AngularFireMessaging: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [angular/angularfire#3049]
**Angular:** 12.2.11

**Firebase:** 9.1.3

**AngularFire:** 7.1.11

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

chrome browser

### How to reproduce these conditions

I've added firebase-messaging-sw.js as described here:
https://github.com/angular/angularfire/blob/master/samples/modular/src/firebase-messaging-sw.js
and added it to angular.json

after deploying I get the following message in devtools console:
![image](https://user-images.githubusercontent.com/1098243/140661817-4416db4b-b477-40f6-9734-28b811cbaf87.png)

It seems to be related to ESM Modules, but I don't know how to solve it.
I can't imagine that the idea would be to add type: module to package.json right?

**Comment by jamesdaniels** [comment]
You need to tell it it's a module when you register a service worker https://github.com/angular/angularfire/blob/master/samples/modular/src/app/messaging/messaging.component.ts#L29

Browser support isn't good though, so I'd recommend sticking with compat for the service workers or bundling them yourself for now.

**Comment by LanderBeeuwsaert** [comment]
@jamesdaniels Great, indeed, I've reverted to compat for now. Thanks for the help!
