### ISSUE TITLE
ng g @angular/fire:ng-add fails in a project where sourceRoot starts with the project's root

### ISSUE THREAD

**Issue by AgentEnder** [angular/angularfire#3052]
### Version info

**Angular:** 12.2.0

**Firebase:** latest

**AngularFire:** latest

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

This can be easily reproduced in Nx by following these steps, but would occur in a regular Angular project if the angular.json file had a similar project configuration to below. Reproduction steps for Nx are found in the Issue mention, for angular just `ng new` and update the configuration.

### Debug output

** Screenshots **
![image](https://user-images.githubusercontent.com/6933928/140972133-ae4fe7ab-4375-40ee-a552-1b10e14e6b16.png)

### Expected behavior

`ng add @angular/fire` passes if sourceRoot and root are both relative to the workspace root

### Actual behavior

`ng add @angular/fire` only passes if sourceRoot is relative to root

----

In a workspace with a project configured as below, `ng add @angular/fire` fails due to the sourceRoot path being appended to the root, rather than replacing it.

```json
{
  "root": "apps/admin"
  "sourceRoot": "apps/admin/src"
}
```

https://github.com/angular/angularfire/blob/5ecf8757d5ea5cbd93e0c0881a95deea9f0310e3/src/schematics/setup/index.ts#L36

Maybe this portion of code could use something like
```typescript
const sourcePath = project.sourceRoot?.startsWith(project.root) 
		? project.sourceRoot 
		: [project.root, project.sourceRoot].filter(it => !!it).join('/'); 
```

I'd be happy to put in a PR to make the change if its agreed upon.

**Comment by jamesdaniels** [comment]
Oh whooops, good catch, feel free to send a PR :)
