### ISSUE TITLE
AppCheck does not work with Analytics

### ISSUE THREAD

**Issue by NBprojekt** [angular/angularfire#3097]
### Version info

**Angular:** 13.0

**Firebase:** 9.4

**AngularFire:** 7.2

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
Ionic: 6.18, Node: 14.17, Chrome, Windows/Mac

### How to reproduce these conditions

**Steps to set up and reproduce**

1. Create new ionic project using `ionic start`
1. Add angular fire `ng add @angular/fire`
1. Update `environment.ts`
```
export const environment = {
  firebase: {
    config: {
      projectId: 'projectId',
      appId: 'appId',
      databaseURL: 'databaseURL',
      storageBucket: 'storageBucket',
      locationId: 'locationId',
      apiKey: 'apiKey',
      authDomain: 'authDomain',
      messagingSenderId: 'messagingSenderId',
    },
    appCheck: {
      recaptcha3SiteKey: 'recaptcha3SiteKey',
      isTokenAutoRefreshEnabled: true,
    },
  },
  production: false,
};
``` 
4. Import angular fire modules 
```
import { getApp, initializeApp, provideFirebaseApp } from '@angular/fire/app';
import { initializeAppCheck, provideAppCheck, ReCaptchaV3Provider } from '@angular/fire/app-check';
import { provideAuth, getAuth } from '@angular/fire/auth';
import { providePerformance, getPerformance } from '@angular/fire/performance';
import {
  provideAnalytics,
  getAnalytics,
  ScreenTrackingService,
  UserTrackingService,
} from '@angular/fire/analytics';
...

@NgModule({
  declarations: [AppComponent],
  entryComponents: [],
  imports: [
    BrowserModule,
    IonicModule.forRoot(),
    AppRoutingModule,
    provideFirebaseApp(() => initializeApp(environment.firebase.config)),
    provideAppCheck(() => initializeAppCheck(getApp(), {
      provider: new ReCaptchaV3Provider(environment.firebase.appCheck.recaptcha3SiteKey),
      isTokenAutoRefreshEnabled: environment.firebase.appCheck.isTokenAutoRefreshEnabled,
    })),
    provideAuth(() => getAuth()),
    provideAnalytics(() => getAnalytics()),
    providePerformance(() => getPerformance()),
  ],
...
```

**Sample data and security rules**

### Debug output

** Errors in the JavaScript console **
![image](https://user-images.githubusercontent.com/24683383/146885424-0ac67065-bbfb-40cc-958c-d0b498c5485a.png)

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

### Expected behavior
Importing app check and analytics should not throw any errors.

### Actual behavior
When using `provideAppCheck()` and `provideAnalytics()` the error above is shown in the console.
Using only one of this functions works fine.

**Comment by franklin142** [comment]
I had the same problem, but I solved it by adding the token to the debug token log as indicated by the console "App Check debug token: b9418c84-8763-xxxx-xxxxx-xxxxxxxxx. You will need to add it to your app's App Check settings in the Firebase console for it to work. " You need to copy that token and paste it into the debug tokens form in firebase
![Captura de pantalla de 2022-01-05 16-29-36](https://user-images.githubusercontent.com/46903621/148299765-5a90c579-a653-43a6-973c-17f3447a670a.png)

Go to firebase project then settings and find the verification app panel

![Captura de pantalla de 2022-01-05 16-27-11](https://user-images.githubusercontent.com/46903621/148299975-493a77b0-9ad4-442d-a753-8272e1aeceb6.png)

Finaly you will see this form, paste your token and then reload your localhost tab in your browser
![Captura de pantalla de 2022-01-05 16-30-20](https://user-images.githubusercontent.com/46903621/148300139-e5d68af5-9289-462a-be83-c504b72665be.png)

_sorry for grammatical mistakes, I am just beginning to learn English. I hope I have been helpful_

**Comment by NBprojekt** [comment]
@franklin142 Awesome!

Works like a charm.
