### ISSUE TITLE
ng add @angular/fire -> Package install failed

### ISSUE THREAD

**Issue by jopmiddelkamp** [angular/angularfire#3105]
Running `ng add @angular/fire` on a fresh install of Angular results into `Package install failed`

### Version info

**Angular:**
13.1.2
**Node:**
16.13.1
**npm:**
8.1.2
**Firebase:**
10.0.1
**AngularFire:**
7.2.0
**OS:**
macOS Monterey (12.0.1)

### How to reproduce these conditions
```
ng new <project>
ng add @angular/fire (no matter which option is chosen)
```

### Result
```
ℹ Using package manager: npm
✔ Found compatible package version: @angular/fire@7.2.0.
✔ Package information loaded.

The package @angular/fire@7.2.0 will be installed and executed.
Would you like to proceed? Yes
✔ Package successfully installed.
UPDATE package.json (1171 bytes)
✔ Packages installed successfully.
? What features would you like to setup? ng deploy -- hosting
✖ Package install failed.
/Users/<user>/Projects/<project>/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/util/hostReportError.js:4
    setTimeout(function () { throw err; }, 0);
                             ^

TypeError: Cannot read properties of undefined (reading 'message')
    at Object.error (/Users/<user>/Projects/<project>/node_modules/@angular/cli/models/schematic-command.js:432:47)
    at SafeSubscriber.__tryOrUnsub (/Users/<user>/Projects/<project>/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.error (/Users/<user>/Projects/<project>/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:156:26)
    at Subscriber._error (/Users/<user>/Projects/<project>/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:92:26)
    at Subscriber.error (/Users/<user>/Projects/<project>/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:72:18)
    at TapSubscriber._error (/Users/<user>/Projects/<project>/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/tap.js:75:26)
    at TapSubscriber.Subscriber.error (/Users/<user>/Projects/<project>/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:72:18)
    at MergeMapSubscriber.SimpleOuterSubscriber.notifyError (/Users/<user>/Projects/<project>/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/innerSubscribe.js:72:26)
    at SimpleInnerSubscriber._error (/Users/<user>/Projects/<project>/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/innerSubscribe.js:30:21)
    at SimpleInnerSubscriber.Subscriber.error (/Users/<user>/Projects/<project>/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:72:18)
```

**Comment by kevin192291** [comment]
Yep, Same issue here

**Comment by VipsPurpleSquirrel** [comment]
I have exactly the same problem. I have tried downgrading @angular/cli and node, and also now upgrading to the latest..

`Angular CLI: 12.2.14
Node: 17.1.0 (Unsupported)
Package Manager: npm 8.1.2
OS: darwin arm64

Angular: 12.2.15
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.14
@angular-devkit/build-angular   12.2.14
@angular-devkit/core            12.2.14
@angular-devkit/schematics      12.2.14
@angular/cli                    12.2.14
@angular/fire                   7.2.0
@schematics/angular             12.2.14
rxjs                            6.6.7
typescript                      4.3.5
`
Thanks in advance for any help from anyone!

**Comment by skryde** [comment]
Hi.
Same issue here. In my case i'm using Angular CLI `13.1.3` and Angular `13.1.0`
Here the `ng version`output:
```
user in ~/Path/to/project on main λ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.1.3
Node: 14.18.2
Package Manager: npm 8.3.0
OS: linux x64

Angular: 13.1.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.3
@angular-devkit/build-angular   13.1.3
@angular-devkit/core            13.1.3
@angular-devkit/schematics      13.1.3
@angular/cli                    13.1.3
@angular/fire                   7.2.0
@schematics/angular             13.1.3
rxjs                            7.4.0
typescript                      4.5.4
```

**Comment by rkoyama** [comment]
Had the same error message. Just ran the install script with `sudo` and got past it:
`sudo ng add @angular/fire`

ng version output:
```
Angular CLI: 13.1.3
Node: 16.13.2
Package Manager: npm 8.3.1
OS: linux x64

Angular: 13.1.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.2
@angular-devkit/build-angular   13.1.2
@angular-devkit/core            13.1.2
@angular-devkit/schematics      13.1.3
@angular/cdk                    13.1.2
@angular/cli                    13.1.3
@angular/fire                   7.2.0
@angular/material               13.1.2
@schematics/angular             13.1.3
rxjs                            7.4.0
typescript                      4.5.4
```

**Comment by MajesticString** [comment]
I found that if you run
`npm i firebase-tools`
manually, this will fix the problem.

**Comment by manuelmanx** [comment]
> npm i -D firebase-tools

Thanks

**Comment by riker09** [comment]
I think I'm having this issue. I've successfully created a new Angular project with `ng new my-app`. Afterwards I want to `ng add @angular/fire` and get stuck at the point where I should select a project. I'm not even able to `CTRL + C` my way out of the dialogue. It's stuck there until I terminate the process.

I tried adding ` npm i -D firebase-tools` after creating the Angular project and before adding `@angular/fire` but then the wrong version is detected:

```bash
$ ng add @angular/fire
ℹ Using package manager: npm
✔ Found compatible package version: @angular/fire@0.0.0.
✔ Package information loaded.

The package @angular/fire@0.0.0 will be installed and executed.
Would you like to proceed? Yes
✔ Package successfully installed.
The package that you are trying to add does not support schematics. You can try using a different version of the package or contact the package author to add ng-add support.
```

**Comment by riker09** [comment]
I believe I found a solution: It was mentioned in issue #3121  that a downgrade to `firebase-tools@9.9.0` fixes this. And low and behold, it did. So I did not get the error in THIS issue, but that from 3121. Apologies.

**Comment by TaiKamilla** [comment]
Try the following, it did work for me
```shell
npm install --save-dev @angular/cli@latest && \
sudo npm install --save-dev @angular/cli@latest -g && \
npm i -D firebase-tools && \
ng add @angular/fire@latest
```

**Comment by VipsPurpleSquirrel** [comment]
@Yafar -Thank you…it worked

  

Vipul Kapadia | Founder & CEO 
+1 678 823 0159

 
www.thinqshift.com

**Comment by Hrytmy** [comment]
doesnt work :

ng add @angular/fire
ℹ Using package manager: npm
✔ Found compatible package version: @angular/fire@7.3.0.
✔ Package information loaded.

The package @angular/fire@7.3.0 will be installed and executed.
Would you like to proceed? Yes
npm ERR! code ECONNRESET
npm ERR! syscall read
npm ERR! errno -4077
npm ERR! network read ECONNRESET
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings..
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:                              bug-0.log
npm ERR!     C:\Users\HP\AppData\Local\npm-cache\_logs\2022-04-09T11_15_26_666Z-debug-0.log

**Comment by gvsakhil** [comment]
Installing firebase-tools fixed the issue

firebase login
npm i -D firebase-tools
ng add @angular/fire@latest

**Comment by HarryAlvarado28** [comment]
try 
```
firebase login --reauth
```
or
```
$ firebase logout

$ firebase login
```

**Comment by robmanganelly** [comment]
I had the same issue so, I'll share how i solved 

* `sudo firebase login`      _login link received and process completed_
* `sudo ng add @angular/firebase`   _after this the process is straightforward_

i used sudo on login because the installation breaks otherwise, by asking a code in the middle of the process. So I just logged with sudo and voila. That happened while working with Linux Kubuntu OS

**Comment by jerusso** [comment]
What worked for me was:

sudo npm i -D firebase-tools
ng add @angular/fire

I recently migrated to a new computer, so I forgot to install firebase-tools in the project.

**Comment by ryanlogsdon** [comment]
I solved it by running:

terminal > `curl -sL https://firebase.tools | bash`

this comes from https://firebase.google.com/docs/cli#install-cli-mac-linux

then running

```
`ng generate environments`
`npm install @angular/fire`
`ng add @angular/fire`
```

**Comment by Manishac12** [comment]
Hi I'm using this packages with Angular 13.3.12 version with "@angular/fire": "^7.5.0", "firebase": "^9.15.0", packages and till thursday it'w working fine but suddenly on friday it stop working and start getting error  
![Screenshot (1)](https://user-images.githubusercontent.com/62536851/230843775-f436b565-83fb-4d82-b5b1-821597a6d833.png)

did any one know how can I fix this?

**Comment by jalle007** [comment]
It still doesn't work soo frustrating !

ng add @angular/fire@latest

ℹ Using package manager: npm
✔ Package information loaded.

The package @angular/fire@latest will be installed and executed.
Would you like to proceed? Yes
✖ Packages installation failed, see above.

**Comment by vasantheeswaran** [comment]
> Try the following, it did work for me
> 
> ```shell
> npm install --save-dev @angular/cli@latest && \
> sudo npm install --save-dev @angular/cli@latest -g && \
> npm i -D firebase-tools && \
> ng add @angular/fire@latest
> ```

it actually worked for me , thank you

**Comment by Elie-E** [comment]
That what I did and it work : 

`firebase login`

then logged to my firebase account
after that i could run

`ng add @angular/fire`
