### ISSUE TITLE
Project still supported?

### ISSUE THREAD

**Issue by kevin192291** [angular/angularfire#3107]
Sorry for not using the template, 
I am just wondering if this project is still supported?
I loved angular + firebase years ago, and I just came back, but all of the examples seem to no longer work
or they create compile errors.

have the projects docs moved, or this is just a buggy version?

Thanks!

**Comment by pechisworks** [comment]
AngularFire has recently updated to Version 7.0 with a new modular api.
You can find some docs for the new api here:
[https://github.com/angular/angularfire/blob/master/docs/version-7-upgrade.md#upgrading-to-angularfire-70
](https://github.com/angular/angularfire/blob/master/docs/version-7-upgrade.md#upgrading-to-angularfire-70
)
