### ISSUE TITLE
iOS build broken with latest Firebase 9.6.1 & Angularfire 7.2.0 version after update from Firebase v8 and AngularFire v6

### ISSUE THREAD

**Issue by deroux** [angular/angularfire#3112]
### Version info

**Angular:** 12

**Firebase:** 9.6.1

**AngularFire:** 7.2.0

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** Ionic 5, Capacitor 3

### How to reproduce these conditions

Use firebase and angularfire compatibility layer in ionic 5, angular 12 project.

**Steps to set up and reproduce**

1. Setup project using compatibility layers of firebase and angularfire and run.
2. Works fine on web.
3. iOS Build is broken and shows only black screen.

### Expected behavior

iOS 11.0 + build is working properly as before the update to the latest version.

### Actual behavior

iOS build shows black screen after start and does not load any further.

**Comment by deroux** [comment]
The getAuth() function automatically assumes a web-context.

 auth = initializeAuth(getApp(), {
          persistence: indexedDBLocalPersistence
        })
        
This should work on mobile devices, and iOS app loads afterwards again, but strange that no error etc. is thrown.

**Comment by engineirie** [comment]
I exactly got the same issue with the same parameters

**Comment by engineirie** [comment]
I'm using the web sdk but got the same issue
