### ISSUE TITLE
Terminal freeze when running `ng add @angular/fire` on selecting Firebase app step

### ISSUE THREAD

**Issue by ksom** [angular/angularfire#3121]
### Version info

**Angular:13.1.1**

**Firebase:9.6.3**

**AngularFire:7.2.0**

**Node: 14 & 16 & 17**

### How to reproduce these conditions

**Steps to set up and reproduce**

Running `ng add @angular/fire`

### Debug output

```sh
Node.js version v17.3.0 detected.
Odd numbered Node.js versions will not enter LTS status and should not be used for production. For more information, please see https://nodejs.org/en/about/releases/.
Skipping installation: Package already installed
UPDATE package.json (3190 bytes)
✔ Packages installed successfully.
? What features would you like to setup? ng deploy -- hosting
Using firebase-tools version 10.1.0
? Which Firebase account would you like to use? vxxxxxxx@gmail.com
✔ Preparing the list of your Firebase projects
? Please select a project: (Use arrow keys or type to search)
  [CREATE NEW PROJECT] 
❯ MyProjectName
```

** Screenshots **
<img width="1201" alt="output ng add @angular:fire" src="https://user-images.githubusercontent.com/4030561/149639507-3633e82d-1246-4940-baae-80e6fd577819.png">

### Expected behavior

Continue the installation process.

### Actual behavior

- Selection of features works
- Selection of Firebase account works
- Selection of project freeze.

I cannot move between options with arrows nor press enter nor ctrl+c to end process. The only thing I can do is exiting the terminal window.
I tried with Iterm, and native Mac os Terminal. I tried with fish, zsh and bash shells.
Always same behavior. 

### [EDIT]

Notice that with `firebase init` this step works perfectly: I can use the arrow keys to navigate and select an entry.

**Comment by vhmeijering** [comment]
Have the same issue, do you have a solution yet?

**Comment by ksom** [comment]
Not, I'm trying to install it through firebase cli and add @angular/fire with npm but I don't have a working setup at the moment.

**Comment by ksom** [comment]
> Have the same issue, do you have a solution yet?

Are you on Mac m1 ?

**Comment by vhmeijering** [comment]
> > Have the same issue, do you have a solution yet?
> 
> Are you on Mac m1 ?

Yes, M1 Max

**Comment by ksom** [comment]
I'm too on mac m1

**Comment by adzunyan** [comment]
I was facing that problem too, but  when I downgraded `firebase-tools` from v10 to v9, it was resolved.

```
$ firebase --version
> 9.23.3
```

**Comment by shinoshu** [comment]
```
$ npm uninstall -g firebase-tools
$ npm install -g firebase-tools@9.9.0
```

https://github.com/angular/angularfire/blob/master/src/schematics/firebaseTools.ts#L45

**Comment by vhmeijering** [comment]
> ```
> $ npm uninstall -g firebase-tools
> $ npm install -g firebase-tools@9.9.0
> ```
> 
> https://github.com/angular/angularfire/blob/master/src/schematics/firebaseTools.ts#L45

Downgrading solved the issue, thank you :)

**Comment by brunodiascultural** [comment]
Downgrading solved the issue, thank you!

**Comment by jadl7721** [comment]
> ```
> $ npm uninstall -g firebase-tools
> $ npm install -g firebase-tools@9.9.0
> ```
> 
> https://github.com/angular/angularfire/blob/master/src/schematics/firebaseTools.ts#L45

Me funciono

**Comment by abhishek1234321** [comment]
Downgrading helped, thanks!

**Comment by ribalnasr** [comment]
Same problem here with Mac M1. Is anyone not on M1 having the same problem?

**Comment by MrMic** [comment]
Same issue.
The fix solves it! Thanks!

**Comment by yasmineDoghri6** [comment]
Same problem with Mac also. Solved with "npm install -g firebase-tools@9.9.0"

**Comment by peavers** [comment]
Same problem, on a Mac but **not** an M1 chip.

**Comment by tama3bb** [comment]
firebase-tools@10.1.0 freezes.
firebase-tools@10.0.1 works.

**Comment by mraible** [comment]
FWIW, the latest version of `firebase-tools` (v10.1.5) doesn't work either.

**Comment by MrMarteng** [comment]
I ran into the same issue on a M1 Mac. Manual downgrade is not working for me because of other dependencies.
Any update?
