### ISSUE TITLE
Performance should work on web 

### ISSUE THREAD

**Issue by scorsi** [angular/angularfire#3142]
Actually it appears performance is disabled on web platform:
https://github.com/angular/angularfire/blob/b60670c3fdf813d8a00645458b0642a0c5162191/src/performance/performance.module.ts#L17
https://github.com/angular/angularfire/blob/b60670c3fdf813d8a00645458b0642a0c5162191/src/performance/performance.module.ts#L25

Performance for web is now available : https://firebase.google.com/docs/perf-mon/get-started-web

**Comment by jamesdaniels** [comment]
Note the `!`, that translates to "not isPlatformBrowser". What issues are you having with perf?

**Comment by scorsi** [comment]
Yep it's true ! But I got no data into Firebase... I left Angular in favor to React (using reactfire) and I got no issues with perf. 
I close that issue as I can't dig up further on what was wrong.
