### ISSUE TITLE
I'm unable to install latest version of angular/fire in my project, I'm using a Mac with an M1 chip

### ISSUE THREAD

**Issue by wontlearn2codewithme** [angular/angularfire#3145]
### Version info

**Angular:**  13.2.1

**Firebase:**  Using firebase-tools version 10.1.4

**AngularFire:** 7.2.0

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
I'm using a Macbook Air with an M1 chip, if that matters
Angular CLI: 13.2.2
Node: 16.13.0
Package Manager: yarn 1.22.17
OS: darwin arm64

Angular: 13.2.1
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
@angular-devkit/architect       0.1302.2
@angular-devkit/build-angular   13.2.2
@angular-devkit/core            13.2.2
@angular-devkit/schematics      13.2.2
@angular/cli                    13.2.2
@angular/fire                   7.2.0
@schematics/angular             13.2.2
rxjs                            7.5.2
typescript                      4.5.5

### How to reproduce these conditions

**Failing test unit, Stackblitz demonstrating the problem**

**Steps to set up and reproduce** 

- run the command 'ng add @angular/fire' in your terminal
- add any feature you want to add to the project (I tried several)
- login to your firebase account
- When you try to navigate through the list of your projects the terminal always gets stuck and can't continue with the installation of this component. No typing or navigation via keyboard.

**Sample data and security rules**

### Debug output

** Errors in the JavaScript console ** none

** Output from `firebase.database().enableLogging(true);` ** none

** Screenshots **

<img width="705" alt="Captura de pantalla 2022-02-07 a las 21 33 20" src="https://user-images.githubusercontent.com/81021336/152867437-fce42139-dfa6-4672-9c6c-51e329e0adc5.png">

### Expected behavior

It should allow you to select any project in the list.

### Actual behavior

It gets blocked and doesn't seem to respond to any keyboard input.

**Comment by jamesdaniels** [comment]
This looks to be a conflict either between inquirer, inquirer-autocomplete, or fuzzy and the versions that Firebase CLI is pinning. I'm investigating and hopefully will have a fix today.

**Comment by jamesdaniels** [comment]
Cutting 7.2.1 with the fix now

**Comment by wontlearn2codewithme** [comment]
> Cutting 7.2.1 with the fix now

I'm sorry @jamesdaniels but this fix didn't solve the issue for me, I don't know if I can give you some more information in any way, let me know what could I do to help.
