### ISSUE TITLE
AngularFireUploadTask only possible with compat? Request for documentation

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [angular/angularfire#3165]
Hello,

In our application we're using in some occasions the following code:

import firebase from 'firebase/compat/app';
import storage = firebase.storage;
import UploadTaskSnapshot = storage.UploadTaskSnapshot;
import { MessageDialog } from '../message-dialog/message-dialog.component';
import { take } from 'rxjs/operators';
import { AngularFireUploadTask } from '@angular/fire/compat/storage'; 

this.task = this.afStorage.upload(path, file);
this.percentage = this.task.percentageChanges();
this.snapshot = this.task.snapshotChanges();

We're trying to migrate to modular Firebase, however, I don't find how to do this in modular firebase.
Documentation or a sample for this would be mightely appreciated.

Have a nice week

**Comment by DogAndDoll** [comment]
Hey, take a look at `uploadBytesResumable` and `percentage` function from '@angular/fire/storage'. I'm pretty sure that is what you are looking for.

**Comment by Sapython** [comment]
Check the storage docs [here](https://github.com/Sapython/angularfire/blob/new_docs/docs/storage.md)

**Comment by LanderBeeuwsaert** [comment]
yes indeed, both comments got me where I wanted. Thanks
