### ISSUE TITLE
App check initializer has a required FirebaseApp argument unlike all other initializers.

### ISSUE THREAD

**Issue by Sapython** [angular/angularfire#3186]
### Version info

**Angular:** 12.2.6

**Firebase:** 9.6.8

**AngularFire:** 7.2.1

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** ionic 5

### How to reproduce these conditions

**Failing test unit, Stackblitz demonstrating the problem**
```ts
provideAppCheck(() =>
        initializeAppCheck(firebaseApp, {
          provider: new ReCaptchaV3Provider(
            'test123456789012345678901234567890'
          ),
          isTokenAutoRefreshEnabled: true,
        })
    ),
```

**Steps to set up and reproduce**
Just initialize the app check-in angular firebase

### Expected behavior
It should not have a required FirebaseApp requirement

### Actual behavior
It is required to pass FirebaseApp in app check initializer

**Comment by jamesdaniels** [comment]
[I know it's a bit odd, but that's the API that Firebase uses](https://firebase.google.com/docs/reference/js/app-check). FWIW you can pass `undefined` to the first argument to use the default app. [See our advanced example which uses this override](https://github.com/angular/angularfire/blob/master/samples/advanced/src/app/app.module.ts#L45).
