### ISSUE TITLE
`AngularFirestore` compatibility does not work with `serverTimestamp()`

### ISSUE THREAD

**Issue by briandiloreto** [angular/angularfire#3219]
### Version info

**Angular:** ~13.3.0

**Firebase:** ^9.6.9

**AngularFire:** ^7.3.0

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** Browser

### How to reproduce these conditions

**Steps to set up and reproduce**

```ts
import {AngularFirestore} from '@angular/fire/compat/firestore';
import {serverTimestamp} from "firebase/firestore";

// private afs: AngularFirestore

this.afs.collection('collection').doc('doc').update({
  updatedAt: serverTimestamp()
});
```

### Debug output

** Errors in the JavaScript console **

> Function DocumentReference.update() called with invalid data. Unsupported field value: a custom ih object (found in field updatedAt in document collection/doc)

### Expected behavior

Update from V6 to V7 should not break `serverTimestamp()`

### Actual behavior

Update fails

**Comment by rulaman123** [comment]
You could try change the import to `import { serverTimestamp } from '@angular/fire/firestore'`
I don't know if that could fix something. But i think it's recommended to import from angularfire instead from firebase?!
But maybe i'ts the same. I think worth a try.

**Comment by briandiloreto** [comment]
@rulaman123 Thanks for the recommendation!  That makes sense, and seems to work.

**Comment by itismenga** [comment]
> You could try change the import to `import { serverTimestamp } from '@angular/fire/firestore'` I don't know if that could fix something. But i think it's recommended to import from angularfire instead from firebase?! But maybe i'ts the same. I think worth a try.

I spent the whole day to finally find the solution from you, thanks!

**Comment by cfficaurzua** [comment]
Thanks, it worked.
Nonetheless, this should be well documented. 
And the import statement and use for the compat sample  is wrong.

https://github.com/angular/angularfire/blob/73b40da11f7f56884c86da9cbe1123f3d00bc866/samples/compat/src/app/upboats/upboats.component.ts#L4
https://github.com/angular/angularfire/blob/73b40da11f7f56884c86da9cbe1123f3d00bc866/samples/compat/src/app/upboats/upboats.component.ts#L42

> You could try change the import to `import { serverTimestamp } from '@angular/fire/firestore'` I don't know if that could fix something. But i think it's recommended to import from angularfire instead from firebase?! But maybe i'ts the same. I think worth a try.
