### ISSUE TITLE
Emulator not working in Angular 14, AngularFire 7, Firebase 9  -  Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds.

### ISSUE THREAD

**Issue by jhades** [angular/angularfire#3240]
After upgrading to Angular 14, Firebase  to 9 and AngularFire to 7.4.1 following the version compatibility matrix in the AngularFire docs, the firestore emulator has stopped working.

The error I get in the Browse console is:

    [2022-06-15T08:48:35.346Z]  @firebase/firestore: Firestore (9.8.3): Could not reach Cloud Firestore backend. Backend didn't 
    respond within 10 seconds.
    This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in 
    offline mode until it is able to successfully connect to the backend.

I checked and the port I'm running the Firestore emulator is not blocked on my machine.

I switched the configuration of the emulator to the new format, so that is not the cause:

      { provide: USE_AUTH_EMULATOR, useValue: environment.useEmulators ? ['http://localhost:9099'] : undefined },
      { provide: USE_FIRESTORE_EMULATOR, useValue: environment.useEmulators ? ['http://localhost:9100'] : undefined },
      { provide: USE_FUNCTIONS_EMULATOR, useValue: environment.useEmulators ? ['http://localhost:5001'] : undefined },

### Version info

**Angular:** 14.0.1

**Firebase:** 9.8.3

**AngularFire:** 7.4.1

Node: 16.13.1

Browser: Chrome and Firefox

Operation system: Mac OS Monterey 12.2.1

**Comment by jamesdaniels** [comment]
Auth is the only emulator to use the string URL format.  See the compat sample here https://github.com/angular/angularfire/blob/master/samples/compat/src/app/app.module.ts#L80
