### ISSUE TITLE
Create documentation for new API!

### ISSUE THREAD

**Issue by julianlumets** [angular/angularfire#3243]
Hey! I cannot find a documentation suiting for the new api ( i am using angular fire 7.4.1) ? It would be really nice if the doc gets updated or you could tell me where i can find all the new methods and so on.... thank you!

**Comment by mystiquewolf** [comment]
Who sane person releases new API without documentation? Insanity!

**Comment by jamesdaniels** [comment]
The new API is largely the same as Firebase JS SDK as we just wrap it. This is documented on the firebase site. WIP for the new reference-style docs are here #3236
