### ISSUE TITLE
 incorrectly extends interface 'DocumentSnapshot<DocumentData>

### ISSUE THREAD

**Issue by elvysmarcos** [angular/angularfire#3288]
### Version info

**Angular:14.2.9**

**Firebase:*9.14.0**

**AngularFire:*7.4.1**

### How to reproduce these conditions

We are  only trying build an app

**Steps to set up and reproduce**

ng build

**Sample data and security rules**

### Actual behavior

Error: node_modules/@angular/fire/compat/firestore/interfaces.d.ts:13:18 - error TS2430: Interface 'DocumentSnapshotExists<T>' incorrectly extends interface 'DocumentSnapshot<DocumentData>'.
  The types returned by 'data(...)' are incompatible between these types.
    Type 'T' is not assignable to type 'DocumentData | undefined'.
      Type 'T' is not assignable to type 'DocumentData'.

**Comment by abierbaum** [comment]
I ran into the same thing with typescript 4.8.x.  I had to downgrade to typescript 4.7.x.

**Comment by juane1000** [comment]
This is a show stopper with Angular V15 having launched today. Just ran into this problem after updating.

**Comment by ylno** [comment]
Same problem with Angular V15. It occurs only when the compat api is used.
