### ISSUE TITLE
ng add bugs

### ISSUE THREAD

**Issue by lazar0303** [angular/angularfire#3298]
### Version info

**Angular:**15.0.2

**Firebase:**latest

**AngularFire:**7.5

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** Fedora 37

### How to reproduce these conditions

**Steps to set up and reproduce**

1. install of Fedora 37 in new VM instance
2. `sudo dnf install npm`
3. `sudo npm install -g @angular/cli`
4. `ng new my-app`
5. `cd my-app`
6. `ng add @angular/fire`
7. Analytics prompt: yes
8. Install angular fire 7.5.0: yes
9. Features required: hosting, Authentication, Firestore, Analytics, Performance Monitoring

**First error:** `An unhandled exception occurred: catch clause variable is not an Error instance`
**Source of error:** Not logged in to Firebase
**Workaround:**
1. `sudo npm install -g firebase-tools`
2. `firebase login`
3. login in the browser

**Expected behaviour:** Include the workaround in the documentation, or on ng add give a login prompt if not logged in

10. Login with account: select my account
11. Which project: [Create New Project]
12. Which website: the auto generated
13. Which app: [Create New App]
14. What name: same as project

**Second error:** `File /src/environments/environment.ts does not exist`
**Source of error:** File does not exist
**Workaround:**
1. create file /src/environments/environment.ts with following content:
```
export const environment = {
  production: false
};
```
2. Repeat steps from no. 6
3. After installation is done create file /src/environments/environment.prod.ts with similar content to the other environment file, if you plan to use the same firebase project in production. Obviously in this case the difference would be production: true. (This is necessary because `ng build` uses this file)

**Expected behaviour:** Include the workaround in the documentation, or on ng add create the files if missing.

15. Use any feature of angular fire (like authguard) and `ng serve`

**Third error:** 
```
ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(AppModule)[AngularFireAuthGuard -> AngularFireAuth -> InjectionToken angularfire2.app.options -> InjectionToken angularfire2.app.options -> InjectionToken angularfire2.app.options]: 
  NullInjectorError: No provider for InjectionToken angularfire2.app.options!
```
**Source of error:** `provideFirebaseApp(() => initializeApp(environment.firebase))` can't read the options
**Workaround:**
1.  Add the following to app.module.ts:
```
@NgModule({
  ...
  providers: [
    ...
    { provide: FIREBASE_OPTIONS, useValue: environment.firebase }
  ],
})
```

**Expected behaviour:** Include the workaround in the documentation, or on ng add edit the app.module.ts properly.

Even if this issue gets closed, I hope this can serve as a guide to developers who are brand new to angular fire.

**Comment by jamesdaniels** [comment]
Fixed in the latest release, we're creating the file if it doesn't exist
