### ISSUE TITLE
Adding latest angular fire to a project breaks the production build

### ISSUE THREAD

**Issue by jlcvp** [angular/angularfire#3305]
### Version info

**Angular:**
15.1.0
**Firebase:**
11.19.0
**AngularFire:**
7.5.0
**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
Node LTS 16.15.1
MacOS Ventura
### How to reproduce these conditions

**Failing test unit, Stackblitz demonstrating the problem**
- Example project
https://github.com/WorkaroundTech/angular-fire-production-build-bug

**Steps to set up and reproduce**

1. Create a new blank project using `ng new`
2. Create the `environments/environment.ts` file with the following structure to avoid errors in the setup wizard:
```typescript
export const environment = {
    production: false
}
```
3. Add the lib with `ng add @angular/fire` (I used an existing firebase project and selected `authentication`, `firestore`, `storage` and `hosting` features)
4. Run production build with `ng build`  
**Sample data and security rules**

### Debug output

** Errors in the console **

> ng build
One or more browsers which are configured in the project's Browserslist configuration will be ignored as ES5 output is not supported by the Angular CLI.
Ignored browsers: chrome 60
⠋ Generating browser application bundles (phase: setup)...    TypeScript compiler options "target" and "useDefineForClassFields" are set to "ES2022" and "false" respectively by the Angular CLI. To control ECMA version and features use the Browerslist configuration. For more information, see https://angular.io/guide/build#configuring-browser-compatibility
✔ Browser application bundle generation complete.
> 
> Error: Optimization error [main.1ff7801206882aa5.js]: SyntaxError: Unexpected token: punc (()

** Screenshots **
![image](https://user-images.githubusercontent.com/2317417/212045376-c7c23cf9-5fac-4c53-b0c6-9489cc6755be.png)

### Expected behavior
We should be able to run the production build after adding the angular fire lib to the project

### Actual behavior
We get a `Error: Optimization error [main.1ff7801206882aa5.js]: SyntaxError: Unexpected token: punc (()` message

**Comment by YouZag** [comment]
Same issue. I've attempted to debug but have failed to pin down what line is causing the syntax error.

**Comment by jnizet** [comment]
See https://github.com/angular/angular-cli/issues/24526.
