### ISSUE TITLE
Using App Check with AngularFire:  Android

### ISSUE THREAD

**Issue by physedo** [angular/angularfire#3314]
### Discussed in https://github.com/angular/angularfire/discussions/3194

<div type='discussions-op-text'>

<sup>Originally posted by **gillarf** March 28, 2022</sup>
Hi everyone

We'd really like to use Firebase App Check in our iOS and Android apps, built using AngularFire, but I can't find any documentation on it.

Does anyone have an examples of an AngularFire implementation?

Thanks very much for any help with this.

Kevin</div>

**Comment by davideast** [comment]
Closing as this is more of a discussion.

**Comment by physedo** [comment]
AngularFire implementation?
documentation?
