### ISSUE TITLE
Anular 15 cli ionic project fire base installed. when import mudule.ts have issue

### ISSUE THREAD

**Issue by Azeez-Mc** [angular/angularfire#3327]
Anular 15 cli ionic project fire base installed. when import mudule.ts have issue

![Screenshot 2023-03-23 101629](https://user-images.githubusercontent.com/127472359/227105818-0d7bbdbb-77ea-44ec-9251-a7ad53ad59a3.png)

also is this show terminal
![Screenshot 2023-03-23 103002](https://user-images.githubusercontent.com/127472359/227107764-99adb3bc-2b43-464b-a33c-f5eec17f30ac.png)
its only shows when add firebase details add in modue.ts

**Comment by davideast** [comment]
@Paul-D-Dev is correct with the new set of imports.
