### ISSUE TITLE
RxJs Dependency Version

### ISSUE THREAD

**Issue by artask** [angular/angularfire#3346]
Is Angularfire 7.4 compatible with RxJs 7?

The Angularfire 7.1 [release notes](https://github.com/angular/angularfire/blob/master/CHANGELOG.md#710-2021-10-08) lists "Mark compatibility with rxjs 7"

However current package.json has "rxjs": "~6.6.0" as a dependency.

Is this an error?

**Comment by jamesdaniels** [comment]
The production package.json is sourced from `src/package.json`, that lists rxjs as a 6|7 peer dep
