### ISSUE TITLE
Firebase is not supported by @angular 16.0.0 

### ISSUE THREAD

**Issue by sivanshkamat** [angular/angularfire#3359]
Hi guys,
I was trying to add firebase to our project but while installing the package I got several errors:
sivansh@Jorah:~/Desktop/angular/Premiere-League$ ng add @angular/fire --save
Skipping installation: Package already installed
UPDATE package.json (1143 bytes)
⠋ Installing packages (npm)...npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @angular/animations@16.0.3
npm ERR! Found: @angular/core@15.2.9
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"^15.2.8" from the root project
npm ERR!   peer @angular/core@"15.2.9" from @angular/common@15.2.9
npm ERR!   node_modules/@angular/common
npm ERR!     @angular/common@"^15.2.8" from the root project
npm ERR!     peer @angular/common@"^12.0.0 || ^13.0.0 || ^14.0.0 || ^15.0.0" from @angular/fire@7.5.0
npm ERR!     node_modules/@angular/fire
npm ERR!       @angular/fire@"^7.5.0" from the root project
npm ERR!     1 more (@angular/forms)
npm ERR!   2 more (@angular/fire, @angular/forms)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@"16.0.3" from @angular/animations@16.0.3
npm ERR! node_modules/@angular/animations
npm ERR!   @angular/animations@"^16.0.0" from the root project
npm ERR!   peer @angular/animations@"^16.0.0 || ^17.0.0" from @angular/material@16.0.1
npm ERR!   node_modules/@angular/material
npm ERR!     @angular/material@"^16.0.1" from the root project
npm ERR!   1 more (@angular/platform-browser)
npm ERR! 
npm ERR! Conflicting peer dependency: @angular/core@16.0.3
npm ERR! node_modules/@angular/core
npm ERR!   peer @angular/core@"16.0.3" from @angular/animations@16.0.3
npm ERR!   node_modules/@angular/animations
npm ERR!     @angular/animations@"^16.0.0" from the root project
npm ERR!     peer @angular/animations@"^16.0.0 || ^17.0.0" from @angular/material@16.0.1
npm ERR!     node_modules/@angular/material
npm ERR!       @angular/material@"^16.0.1" from the root project
npm ERR!     1 more (@angular/platform-browser)
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /home/sivansh/.npm/_logs/2023-05-26T08_54_10_823Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sivansh/.npm/_logs/2023-05-26T08_54_10_823Z-debug-0.log
✖ Package install failed, see above.
The Schematic workflow failed. See above.

**Comment by jamesdaniels** [comment]
Fixed in 7.6.0, which should be released momentarily
