### ISSUE TITLE
missing colon

### ISSUE THREAD

**Issue by danielmmf** [angular/angularfire#3371]
### Version info

**Angular:**

**Firebase:**

**AngularFire:**

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Stackblitz demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

**Comment by danielmmf** [comment]
import { User, Unsubscribe, ActionCodeInfo, UserCredential, Auth, IdTokenResult, MultiFactorError, MultiFactorResolver, PopupRedirectResolver, Dependencies, AuthCredential, ApplicationVerifier, ConfirmationResult, AuthProvider, MultiFactorUser, NextOrObserver, ErrorFn, CompleteFn, ActionCodeSettings, Persistence, PhoneAuthCredential } from "@firebase/auth";

**Comment by davideast** [comment]
Hey @danielmmf I'll need more information to help.
