### ISSUE TITLE
X-Firebase-AppCheck custom header

### ISSUE THREAD

**Issue by smargozzini** [angular/angularfire#3374]
I am enabling App Check authentication in Firebase, and for that, I need to send the X-Firebase-AppCheck header in the login request.

Given this, I propose the ability to include the custom header in the signInWithEmailAndPassword login request.

Something like:

```
const requestOptions = {
  headers: {
    'X-Firebase-AppCheck': appCheckToken
  }
};
  
try {
  await signInWithEmailAndPassword(email, password, requestOptions);
  // User successfully signed in
} catch (error) {
  // Handle error
}
```

**Comment by nohe427** [comment]
I believe that AppCheck already has built in support for authentication. There is no need to pass in the header when calling the authentication endpoints. This was [introduced a couple weeks ago](https://youtu.be/iYA0QYP9ocw?t=263).
