### ISSUE TITLE
Missing Function "count()" in AngularFire 7

### ISSUE THREAD

**Issue by Golldden** [angular/angularfire#3401]
I would like to report that the "count()" function is missing in the latest version of AngularFire, version 7. This function was essential for retrieving document counts in previous versions. Its absence has caused inconvenience and hindered my development process. I kindly request guidance on an alternative approach or the potential reintroduction of the "count()" function in a future release.

**Comment by davideast** [comment]
Tracking this in #3320. This is our biggest focus at the moment but there's a lot of work to get the library up to date for TypeScript 5 so we don't have an ETA.

**Comment by davideast** [comment]
Follow #3402
