### ISSUE TITLE
Firebase 10.0.0 compatibility

### ISSUE THREAD

**Issue by Timebutt** [angular/angularfire#3406]
### Version info

**Angular:**
```
Angular CLI: 16.1.4
Node: 18.12.1
Package Manager: yarn 1.22.17
OS: darwin arm64

Angular: 16.1.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, google-maps, material, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.4
@angular-devkit/build-angular   16.1.4
@angular-devkit/core            16.1.4
@angular-devkit/schematics      16.1.4
@angular/fire                   7.6.1
@angular/flex-layout            15.0.0-beta.42
@schematics/angular             16.1.4
rxjs                            7.8.1
typescript                      5.1.6
```

**Firebase:**
`10.0.0`

**AngularFire:**
`7.6.1`

### How to reproduce these conditions

Upgrade an existing Angular application that uses Firebase with `@angular/fire` version below `10.0.0` to the latest release and serve the application.

### Debug output

** Errors in the JavaScript console **
```
Unhandled Promise rejection: Firebase: No Firebase App '[DEFAULT]' has been created - call initializeApp() first (app/no-app). ; Zone: <root> ; Task: Promise.then ; Value: FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call initializeApp() first (app/no-app).
```

### Expected behavior
The app should start correctly when upgrading `firebase` to its latest version.

### Actual behavior
The app cannot initialize since a runtime error is thrown by the Firebase SDK.

**Comment by davideast** [comment]
We do not support 10.0.0 yet since it was just released today. However we are making progress so follow along in #3402!

**Comment by Timebutt** [comment]
Thanks @davideast! For context: I created this issue as a tracker for myself and others to start the discussion around the `10.0.0` upgrade, knowing full well Rome wasn't built in a day ;) That's always hard to read from a dry issue like this though obviously. Looking forward to the next release!

**Comment by MedaiP90** [comment]
In version `10.3.0` of firebase there is an **important** fix about the compatibility of the library with Safari/iOS devices. There are updates about the compatibility?

**Comment by Timebutt** [comment]
I was also wondering about the same thing: is there a scenario in which compatability with `firebase` `10.x.x` can be released separately from the Angular 16 and TypeScript 5 upgrade?

**Comment by tgangso** [comment]
> I was also wondering about the same thing: is there a scenario in which compatability with `firebase` `10.x.x` can be released separately from the Angular 16 and TypeScript 5 upgrade?

https://github.com/angular/angularfire/pull/3402#issuecomment-1694723401

**Comment by atsjo** [comment]
if using pnpm you can override via

```
  "pnpm": {
    "overrides": {
      "@angular/fire>firebase": "$firebase"
    }
  }
```

similar solutions for other package managers... I have done this since 10.x, shouldn't need to do this, but works fine...

**Comment by MedaiP90** [comment]
> if using pnpm you can override via
> 
> ```
>   "pnpm": {
>     "overrides": {
>       "@angular/fire>firebase": "$firebase"
>     }
>   }
> ```
> 
> similar solutions for other package managers... I have done this since 10.x, shouldn't need to do this, but works fine...

Thank you, that works fine waiting for the official release

**Comment by fkolar** [comment]
Any news on this ?

**Comment by tgangso** [comment]
Update? Why no progress?
