### ISSUE TITLE
docs(auth): Add to developer guide approaches to managing authentication state

### ISSUE THREAD

**Issue by choopage** [angular/angularfire#343]
How to manage AngularFire2 authentication state (emit observable of sign-in or logout status) and Angular2 (RC4 and above) route guard to work with angularfire2? 

I asked a question in [Stackoverflow](http://stackoverflow.com/questions/38284173/how-to-get-angularfire2-authentication-as-an-observable/38284377#38284377). But I feel that a detailed documentation here would benefit AngularFire2 Community.

**Comment by samirthebti** [comment]
Yes  we need a detailed documentation for use AngularFire .

**Comment by davideast** [comment]
Agreed! We will be expanding our docs in a future release.

**Comment by choopage** [comment]
It would be good if AngularFire2 documentation could include detailed explanation on this 

> AngularFire2 has a af.auth.subscribe() to subscribe to the auth service. The question is how can i make the guard wait for the observable and then return either true or false?

From [reddit.com/r/Angular2/comments/4trb3v/how_to_implement_guard_with_angularfire2/](https://www.reddit.com/r/Angular2/comments/4trb3v/how_to_implement_guard_with_angularfire2/)

**Comment by choopage** [comment]
Hi @davideast I can lend a hand if you need me. You could put together an application for this purpose. I'll use that application that you put together to enhance the existing markdown documentation. Hope this would be helpful.

**Comment by bogacg** [comment]
Is there any progress in this front. I've tried same approach in my app, with similar auth-service of [todo-angular2-firebase](https://github.com/r-park/todo-angular2-firebase) example, having auth-guard and unauth-guard. When I logout, `canActivate` gets called always prior to auth object nulls. I've tried `.take(1)` or `.first()`...no luck.
Why `.logout()` does not return promise anyways?

**Comment by jeremyputeaux** [comment]
Is there any progress on this ?

**Comment by rashnk** [comment]
AngularFire vs AngularFireAuth , both returns the same result , so AngularFire will handle all opereation it seems
```
constructor(public auth$: AngularFireAuth, public navCtrl: NavController, public af: AngularFire) {

    this.authState = auth$.getAuth();
    auth$.subscribe((state: FirebaseAuthState) => {
      this.authState = state;
      console.log(state);
    });
    //af.auth.getAuth()
    this.af.auth.subscribe(auth => {
      console.log(auth)
      
    });// user info is inside auth object
  }
```

**Comment by ElecTreeFrying** [comment]
With `Angular v6`, `Firebase v5.0.*` and `angularfire2 5 rc 10` you can do something like this.

```
...
import { AngularFireAuth } from 'angularfire2/auth';
import { map } from 'rxjs/operators';

...
export class DashboardGuard implements CanActivate, CanActivateChild {

  constructor(private router: Router, private auth: AngularFireAuth) { }
  // #2
  canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) {
    // #1
    return this.auth.authState.pipe(
      // #3
      map((user: any) => user !== null) // <--- [1]
    );

  }

  canActivateChild(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) {
    return this.canActivate(route, state);
  }

}
```

Directly with `AngularFireAuth`'s `authState` just pipe it down and check if user is not equal to null `[1]`.

1. `authState` returns `Observable<firebase.User>`
2. `canActivate()` returns `Observable<boolean> | Promise<boolean> | boolean`
3. subscribing to `authState` will emit `null` if not authenticated else emits `firebase.User` (see screenshot below).

I've just discovered that I can now do this with the latest versions -> return an `Observable<boolean>` in `canActivate`... Because in the last versions although in the documentation it says that `canActivate` returns `Observable<boolean>` it gives me tons of errors. but now yea!

btw I just want to share how I write route guards before angular v6. using promises

```
constructor(private router: Router, private afAuth: AngularFireAuth) {}

canActivate(next: ActivatedRouteSnapshot, state: RouterStateSnapshot) {
  const promise = new Promise(
    (resolve, reject) => {
      this.afAuth.authState.subscribe((state: any) => {
        resolve(state !== null);
      });
    }
  );

  return promise.then((data: boolean) => {
    if (data) {
      return data;
    } else {
      this.router.navigate(['/']);
    }
  });
}
```

![capture](https://user-images.githubusercontent.com/19801459/41476882-62d16d36-70f5-11e8-814c-a08d20b5f164.PNG)

**Comment by jamesdaniels** [comment]
Closing as outdated, we've revamped all of our auth handling have guards, etc. now all fairly well documented.
