### ISSUE TITLE
authState is not working with Auth argument

### ISSUE THREAD

**Issue by amide-inc** [angular/angularfire#3430]
export class TestService {
  users$: Observable<User | null>; 
  constructor(
    private auth: Auth,
    private _af: Firestore
  ) { 
    this.users$ = authState(this.auth).pipe(
      switchMap(async user => {
        if(user) {
          localStorage.setItem('userId', user.uid);
          localStorage.setItem('email', user.email ?? '');
          return (await getDoc(doc(this._af, `${DB.users}/${user.uid}`))).data() as User
        } else {
          return null;
        }
    })
  );
  }

**Comment by amide-inc** [comment]
Issue has been resolved
we need to pass auth of firebase not the angularFire one 

export class TestService {
  users$: Observable<User | null>; 
  constructor(
    public auth: Auth,
    private fAuth: FAuth,
    private _af: Firestore
  ) { 
    this.users$ = authState(this.fAuth).pipe(
      switchMap(async user => {
        if(user) {
          localStorage.setItem('userId', user.uid);
          localStorage.setItem('email', user.email ?? '');
          return (await getDoc(doc(this._af, `${DB.users}/${user.uid}`))).data() as User
        } else {
          return null;
        }
    })
  );
  }

**Comment by jbgomez21** [comment]
What does it mean that it doesn't work with Auth from @angular/fire?
I'm having issues with authState(this.auth); sometimes it returns null even when authenticated.

`  private authState(): Promise<User | null> {
    return firstValueFrom(
      from(this.auth.authStateReady()).pipe(
        switchMap(() => authState(this.auth))
      )
    )
  }`

The function above also returns null sometimes even after performing the authentication previously.
