### ISSUE TITLE
"Bt.messaging is not a function" when buildOptimizer is true in angular.json

### ISSUE THREAD

**Issue by pablorsk** [angular/angularfire#3433]
### Version info

**Angular:** 13
**Firebase:** 9.15.0
**AngularFire:** 7.5.0

### How to reproduce these conditions

On any AngularFire application, from version 7.0.4 to 7.6.1. On develpment or with `buildOptimizer: false`, all works perfect. Its a problem between AngularFire and build method. Also, we try with angular 12 and 13.

**Steps to set up and reproduce**

Final app builded `buildOptimizer: false` in `angular.json` or on development mode, angular application works fine.

But, when app is built with `buildOptimizer: true`, you receive this on DevTools console:

`Bt.messaging is not a function`

Of course, on each build, the `Bt` variable name changes.

More details about our service code:

```typescript
@Injectable({ providedIn: 'root' })
export class FirebaseMessagingService {
    public constructor(private afMessaging: AngularFireMessaging) {}

    public listen(): void {
        this.afMessaging.messages.subscribe(); // this line throws the AngularFire error.
    }
 }
```

And in app.module.ts:

```typescript
imports: [ AngularFireModule.initializeApp(environment.FIREBASE_CONFIG), AngularFireMessagingModule, ]
```

And in firebase-messaging-sw.js:

```typescript
import { firebase } from 'firebase'

var firebaseConfig = {
    apiKey: '',
    authDomain: '',
    projectId: '',
    storageBucket: '',
    messagingSenderId: '',
    appId: '',
};

firebase.initializeApp(firebaseConfig);

const messaging = firebase.messaging();
```

### Debug output

** Errors in the JavaScript console **

```
TypeError: Bt.messaging is not a function
    at pe.<anonymous> (main.462d9011f1c1f1cf.js:1:336767)
    at Generator.next (<anonymous>)
    at main.462d9011f1c1f1cf.js:1:335892
    at new t (polyfills.46dcebb06f25fe2c.js:1:17816)
    at L (main.462d9011f1c1f1cf.js:1:335586)
    at main.462d9011f1c1f1cf.js:1:336724
    at H (main.462d9011f1c1f1cf.js:1:340950)
    at main.462d9011f1c1f1cf.js:1:336665
    at x.subscribe.J (main.462d9011f1c1f1cf.js:1:888335)
    at c._next (main.462d9011f1c1f1cf.js:1:881326)
```

** Screenshots **

![image](https://github.com/angular/angularfire/assets/938894/bd6faaf9-648d-4ee4-8437-32ebd2e2bf9f)

### Expected behavior

Use AngularFireMessaging service with `buildOptimizer: true`.

### Actual behavior

Code stops on `afMessaging.messages.subscribe()`, returning `Bt.messaging is not a function` error if `buildOptimizer: true`.

**Comment by pablorsk** [comment]
Solution:

Use only [AngularFire following all instructions](https://www.npmjs.com/package/firebase#use-firebase-in-your-app). But dont follow any [instruction of Firebase](https://www.npmjs.com/package/firebase#use-firebase-in-your-app). Both implementations causes problems after build, but never on development environment.

Make only one instance of `ProcessEnv` or any extended class.

**Comment by M0h-st** [comment]
Sorry I don't understand may you explain more ?
