### ISSUE TITLE
Error running ng add angular/fire on macOS

### ISSUE THREAD

**Issue by theonlybenjamin** [angular/angularfire#3453]
### Version info

**Angular:** 16.0.0

**Firebase:** 10.5.2

**AngularFire:** 16.0.0

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** MacOS Sonoma 14.0.0

### How to reproduce these conditions

error occurs when run command ng add @angular/fire
<!-- 
<img width="872" alt="Captura de pantalla 2023-10-28 a la(s) 10 39 03" src="https://github.com/angular/angularfire/assets/47691286/bc7cab08-ed1d-4160-abf3-b46c461cb963">

**Comment by jamesdaniels** [comment]
What is the error?

**Comment by theonlybenjamin** [comment]
<img width="1920" alt="Captura de pantalla 2023-10-25 a la(s) 11 42 59 (2)" src="https://github.com/angular/angularfire/assets/47691286/a5376b31-fb0f-4dc7-b5e1-701c104e80b6">

**Comment by theonlybenjamin** [comment]
<img width="872" alt="Captura de pantalla 2023-10-28 a la(s) 10 39 03" src="https://github.com/angular/angularfire/assets/47691286/64a69a98-9460-47b8-9003-e525d88418a3">

**Comment by theonlybenjamin** [comment]
im sorry I thought I uploaded evidence. I tried to run ng add angular fire 16.0.0 from Sonoma MacOS an from Windows 11 and got the same error

**Comment by jamesdaniels** [comment]
Ah, it seems one the schematic API we are using wasn't added until after 16. Let me investigate how to mitigate.

**Comment by guigamer666** [comment]
I have the same error but. I'm using windows 10 with angular 16.0.0

**Comment by guigamer666** [comment]
![Captura](https://github.com/angular/angularfire/assets/45331658/20600585-d59a-446c-b0dc-28f46f1978e5)

**Comment by jamesdaniels** [comment]
Yeah it seems the API was added in 16.1 or 16.2, I probably just have to gate that functionality for now as we're prepping for v17

**Comment by vcomperq** [comment]
i have the same issue :-(

**Comment by theonlybenjamin** [comment]
Hi guys, I solved this error running: ng update @angular/core @angular/cli, this updated mi dependencies version and now I can run ng add @angular/fire

**Comment by theonlybenjamin** [comment]
Hi guys, I solved this error running: ng update @angular/core @angular/cli, this updated mi dependencies version and now I can run ng add @angular/fire
