### ISSUE TITLE
Cannot upgrade to 16.0.0

### ISSUE THREAD

**Issue by IsaacSomething** [angular/angularfire#3454]
### Version info

**Angular:** 16.2.11

**Firebase:** 9.23.0

**AngularFire:** 7.6.1

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** node: 18.8.0

### How to reproduce these conditions

**Failing test unit, Stackblitz demonstrating the problem**

**Steps to set up and reproduce** 
It is just a simple upgrade issue from 7 to 16

**Sample data and security rules**
none

### Debug output

**Errors in the JavaScript console**

>Updating multiple major versions of '@angular/fire' at once is not supported. Please migrate each major version individually.
Run 'ng update @angular/fire@8' in your workspace directory to update to latest '8.x' version of '@angular/fire'.
For more information about the update process, see https://update.angular.io/?v=7.0-8.0

**Output from `firebase.database().enableLogging(true);`** 

N/A

** Screenshots

![Screenshot 2023-10-30 180034](https://github.com/angular/angularfire/assets/25283027/c4f81cc8-0b7a-42d5-84a2-c61da7611f96)
 **

### Expected behavior

An upgrade

### Actual behavior

`ng update` prevents multiple major version update

**Comment by jamesdaniels** [comment]
Ah, that's unfortunate. You should be able to get away with an npm/yarn upgrade FYI. As we didn't break any APIs.

**Comment by IsaacSomething** [comment]
Updating npm doesn't work, i still get the same issue.

**Comment by jakehockey10** [comment]
@jamesdaniels One exception to "didn't break any APIs" that I've run into so far is that `docData` observable now has a different type for the data (now is `DocumentData | { id: any } | undefined`).  I think the type didn't used to include `undefined`.

In the releases page of this github page, I only see 16 listed.  Is there a list of other changes since 7 that I can review?

**Comment by jakehockey10** [comment]
It looks like the type slightly changed for `customClaims` from `'@angular/fire/auth-guard'` as well...
