### ISSUE TITLE
Update angular version 17.0.2 and ng add @angular/fire

### ISSUE THREAD

**Issue by Shemo01** [angular/angularfire#3467]
Buenos dias,

Estoy haciendo unas pruebas con Ionic 7.1.5, la informacion de instalacion es:

Ionic:

   Ionic CLI                     : 7.1.5 (C:\Users\admin\AppData\Roaming\nvm\v20.9.0\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 7.5.6
   @angular-devkit/build-angular : 17.0.3
   @angular-devkit/schematics    : 17.0.3
   @angular/cli                  : 17.0.3
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.5.1
   @capacitor/android : not installed
   @capacitor/core    : 5.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.4

System:

   NodeJS : v20.9.0 (C:\Program Files\nodejs\node.exe)
   npm    : 10.1.0
   OS     : Windows 10

la version de Angular es 

Angular CLI: 17.0.3
Node: 20.9.0
Package Manager: npm 10.1.0
OS: win32 x64

Angular: 17.0.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.3
@angular-devkit/build-angular   17.0.3
@angular-devkit/core            17.0.3
@angular-devkit/schematics      17.0.3
@angular/cli                    17.0.3
@angular/fire                   0.0.0
@schematics/angular             17.0.3
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2

Hice la actualizacion de angular y quedo en la ultima version (17.0.3), al instalar el sdk para Firebase en la aplicacion teninedo en cuenta la documentacion (ng add @angular/fire) se presentan errores de integracion 

demo\ArgExpress>ng add @angular/fire
? Would you like to share pseudonymous usage data about this project with the Angular Team
at Google under Google's Privacy Policy at https://policies.google.com/privacy. For more
details and how to change this setting, see https://angular.io/analytics. Yes

Thank you for sharing pseudonymous usage data. Should you change your mind, the following
command will disable this feature entirely:

    ng analytics disable

Global setting: enabled
Local setting: enabled
Effective status: enabled
ℹ Using package manager: npm
✔ Found compatible package version: @angular/fire@0.0.0.
✔ Package information loaded.

The package @angular/fire@0.0.0 will be installed and executed.
Would you like to proceed? Yes
✔ Packages successfully installed.
Error /> Package "@angular/fire" was found but does not support schematics.

![error fb](https://github.com/angular/angularfire/assets/29437981/8a338c3d-42ef-42ca-bfa4-70cf73f40f23)

Este error no permite realizar la configuracion de Firebase, como antes de que se actalizara la version de angular.

este error se puede reproducir de la siguiente forma 

1. realizar las actualizaciones de Ionic y Angular
2. ionic start nombreProyecto tabs
3. ng add @angular/fire => error install @angular/fire@0.0.0
4. se instala la version a fuerza (npm install @angular/fire@latest --force)

Al intentar instalar cualquier plugin o libreria auxiliar genera errores 

![image](https://github.com/angular/angularfire/assets/29437981/c1a05c88-69ca-465d-a919-cf6abda54ecb)

![image](https://github.com/angular/angularfire/assets/29437981/97847b96-c420-4edc-8925-11825084dd8e)

**Comment by brandomcombr** [comment]
@angular/fire@17.0.0-next.0

work for me

**Comment by simontol** [comment]
I got this when trying to install @angular/fire@17.0.0-next.0:

npm ERR! Found: rxjs@7.6.0
npm ERR! node_modules/rxjs
npm ERR!   rxjs@"~7.6.0" from the root project
npm ERR!   peer rxjs@"^6.5.3 || ^7.4.0" from @angular/common@17.0.5
npm ERR!   node_modules/@angular/common
npm ERR!     @angular/common@"^17.0.5" from the root project
npm ERR!     peer @angular/common@"^17.0.0-next.0" from @angular/fire@17.0.0-next.0
npm ERR!     node_modules/@angular/fire
npm ERR!       @angular/fire@"17.0.0-next.0" from the root project
npm ERR!     2 more (@angular/platform-browser, @angular/platform-browser-dynamic)
npm ERR!   1 more (@angular/core)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer rxjs@"~7.8.0" from @angular/fire@17.0.0-next.0
npm ERR! node_modules/@angular/fire
npm ERR!   @angular/fire@"17.0.0-next.0" from the root project

**Comment by jakehockey10** [comment]
17 was released about 18 hours ago, worth giving it a shot!  I'm having to comment out Analytics and Performance features in my app.config.ts at the moment, unfortunately, but everything seems to be working fine
