### ISSUE TITLE
Deprecate @angular/fire@0.0.0

### ISSUE THREAD

**Issue by mgechev** [angular/angularfire#3480]
### Version info

**Angular:**

N/A

**Firebase:**

N/A

**AngularFire:**

N/A

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

`ng add` with a new version of Angular which doesn't have a corresponding version of `@angular/fire` with matching peer dependencies succeeds with v0.0.0 of `@angular/fire`:

```
$ ng new foo-app
$ cd foo-app

$ ng add @angular/fire
ℹ Using package manager: npm
✔ Found compatible package version: @angular/fire@0.0.0.
✔ Package information loaded.

The package @angular/fire@0.0.0 will be installed and executed.
Would you like to proceed? Yes
✔ Packages successfully installed.
Package "@angular/fire" was found but does not support schematics.
```

### Expected behavior

`ng add` should fail

### Actual behavior

`ng add` does not fail due to `@angular/fire@0.0.0` satisfying the peer dependencies of the CLI.

**Comment by fredsa** [comment]
Note this issue reappears each time a newer version of Angular is released. The issue persists until a compatible version of AngularFire is made available. During the period of brokenness, users are unable to `ng add @angular/fire
` per the documentation (https://angular.dev/tools/cli/deployment).

A quick [search](https://github.com/angular/angularfire/issues?q=%27%40angular%2Ffire%400.0.0%27++%27does+not+support+schematics%27) through the issues reveals users have been regularly affected: #3321, #3467, #3290, #3235, #3162, #3105, #3044, #2832, #2830.

**Comment by jamesdaniels** [comment]
v0.0.0 has been deprecated
