### ISSUE TITLE
Unable to use order by desc

### ISSUE THREAD

**Issue by Dev-Mohit-1220** [angular/angularfire#3540]
How to achieve order by functionality with specific field in latest version

**Comment by Dev-Mohit-1220** [comment]
How can I use order by functionality, there is no documentation.
**Please provide proper documentation**

**Comment by jnizet** [comment]
@Dev-Mohit-1220 There is documentation: https://firebase.google.com/docs/firestore/query-data/order-limit-data

**Comment by Dev-Mohit-1220** [comment]
I have to follow firebase documentation in angular/fire, am I correct?

**Comment by jnizet** [comment]
You have to start at the documentation here: https://github.com/angular/angularfire/blob/master/docs/firestore.md

It says: 

> AngularFire wraps the Firebase JS SDK to ensure proper functionality in Angular, while providing the same API.

> Update the imports from import { ... } from 'firebase/firestore' to import { ... } from '@angular/fire/firestore' and follow the official documentation.

And the link to the official documentation follows. And that official documentation shows how to write queries.

**Comment by Dev-Mohit-1220** [comment]
Thanks @jnizet
