### ISSUE TITLE
Installing @angular/fire on IDX adds an unrecognized locationId

### ISSUE THREAD

**Issue by christhompsongoogle** [angular/angularfire#3556]
Related issue: https://github.com/angular/angularfire/issues/3452

When installing @angular/fire from `ng add` the firebase config is installed with a `locationId` field that isn't recognized. I installed firestore but I _think_ this also applies to storage, and likely some others.

Interestingly the firebase config in the console (https://console.firebase.google.com/u/3/project/myprojectid/settings/general/web) doesn't contain a locationId:

```
const firebaseConfig = {
  apiKey: "",
  authDomain: "",
  projectId: "",
  storageBucket: "",
  messagingSenderId: "",
  appId: "",
  measurementId: ""
};
```

This may be coming from firebase-tools but at first glance I don't know where exactly. Example: [src/init/features/project.ts](https://cs.opensource.google/firebase-sdk/firebase-tools/+/master:src/init/features/project.ts)

Versions:

**Angular:**
18.1.2

**Firebase:**
13.13.1

**AngularFire:**
18.0.1

### Expected behavior
Recognize the locationId in the config or if not supported we could strip it from the config.

![image](https://github.com/user-attachments/assets/6554114a-8e62-444d-9c6c-d672fbbc1445)

**Comment by donksper** [comment]
I have the same problem... has anyone solved it?

**Comment by christhompsongoogle** [comment]
The solution in the near-term is just to remove the locationId completely and it should work.
